### ISSUE TITLE
NetLogo Shell doesn't work

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#1001]
When running `netlogo/runMain org.nlogo.headless.Shell` in `./sbt`, I get (along with some warnings about missing credential files for bintray, which I understood to be fine):

```
[info] Running org.nlogo.headless.Shell 
[error] NetLogo 6.0-M2 (March 24, 2016)
[success] Total time: 2 s, completed Mar 30, 2016 7:34:33 PM
```

**Comment by mrerrormessage** [comment]
This is a quirk of how `sbt` runs processes. It can be worked around as follows:
```
$ ./sbt
//...
> set connectInput := true
//...
> netlogo/runMain org.nlogo.headless.Shell
//...
// netlogo shell available
```
The time it would take to write a command to wrap this is enough that I'm inclined to just say it doesn't matter. A PR adding a command (or a customized task) which did this would be accepted, but the above steps are quick, easy, and work without adding anything extra to the build.

**Comment by Idloj** [comment]
I still get the same behavior

**Comment by mrerrormessage** [comment]
Ah, I goofed the command, it needs to be `set connectInput in netlogo := true`
