### ISSUE TITLE
Preserve "caused by" parts of cause for ExtensionExceptions

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1002]
Currently, the "caused by" section of the stack trace that `ExtensionException` inherits from its cause gets lost. However, this information is often crucial.

Also, we may want to switch using the actual cause-support built into exceptions rather than tacking on the original stack ourselves.

**Comment by mrerrormessage** [comment]
@qiemem , would you have time to finish this change in the next two weeks?

**Comment by qiemem** [comment]
I'll give it a shot! I think I actually tried to fix it once and it turned to be trickier than I thought it would be. I know that simply switching to the built-in caused by mechanism does not work, which is extremely odd. There's another bug associated with `ExtensionException` that may be interfering.

**Comment by qiemem** [comment]
My confusion was due the `_extern`'s wrapping of `ExtensionException`: https://github.com/NetLogo/NetLogo/blob/4729c320ba7ecb6b4d0cb2e2c3d6090a2a179df0/netlogo-gui/src/main/prim/_extern.java#L50
This suffers the same problem that `ExtensionException`'s wrapping other exceptions has (via `setStackTrace`). `setStackTrace` doesn't preserve "caused by", I believe.

Switching to exception's built-in cause stuff should fix it, but that comment above the code referenced worries me.

**Comment by mrerrormessage** [comment]
It might be easiest to make the change and see if anything breaks. It isn't clear to me where the referenced handler is. I can't find any code that deals with a specific exception beginning with "Extension Exception", so I'm unsure whether it even exists anymore.

I agree that if we change this to use the `cause` mechanism, we also need to change `ExtensionException` to do the same.
