### ISSUE TITLE
Newlines are displayed as spaces in labels

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1007]
Came up in MAM meeting in response to a student's question. It's also worth noting that the student's question was about being able to offset the labels in general. There are a couple ways of doing this: spaces, invisible label turtle, etc.

**Comment by SethTisue** [comment]
so this is a feature request for multi-line labels?

**Comment by mrerrormessage** [comment]
Related: 

* #325 : links stamp labels, but turtles don't
* #237 : allow label size modification from code
* #823 : shape clipping is inconsistent

I'm tempted to combine all four of these issues into one "Label and turtle animation enhancement." I would like to say that this would probably be the easiest to fix as I imagine few (if any) models in the models library depend on newlines being displayed as spaces.

**Comment by SethTisue** [comment]
Uri writes, "The problem is that students in the course (and others) mentioned that they’d like to be able to offset labels. We have a workaround (sort of) for horizontal offsets with spaces, but not so much for vertical offsets"

**Comment by SethTisue** [comment]
as discussed on Gitter, it's not clear any of these little incremental extensions are worth doing one at a time — maybe better to find some way of giving access to the full power of SVG

**Comment by SethTisue** [comment]
> it's seems very doubtful that any of these little incremental extensions are worth doing one at a time

well, maybe this one :-)
