### ISSUE TITLE
Combine duplicate classes between the different NetLogo projects

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1008]
This is an umbrella issue to keep track of which packages are duplicated between projects.
- [x] `job` package (fixed in 427867a)
- [x] `lab` package (although only `netlogo-gui` should have the `lab.gui` package)
- [x] `generate`/`generator` package (fixed in 41c482734a04592863982c81b4cb56990fabf314)
- [ ] `plot` (post model format changes)
- [x] `nvm`

**Comment by mrerrormessage** [comment]
Planning to remove much of the duplication in `compile`/`compiler` as part of https://github.com/NetLogo/NetLogo/pull/1147

**Comment by mrerrormessage** [comment]
`TestAllSyntaxes` is also a problem.

**Comment by mrerrormessage** [comment]
Closing this since `plot` has other dependencies. This thread of work is continued on #1446
