### ISSUE TITLE
in applet, make output area, error dialogs, etc copyable into clipboard

### ISSUE THREAD

**Issue by stepheneb** [NetLogo/NetLogo#101]
It is easier to produce useful error reports when the text describing the error in detail can be copied into the clipboard.

When an error occurs while running NetLogo as an applet a dialog appears with some information. While the text of the error description is selectable the keyboard commands for copying the selected text into the clipboard do not work.

I can only report this occurring on Mac OS X 10.6.8 running NetLogoLite.jar as an applet. Don't have any other experience.

**Comment by SethTisue** [comment]
closing, since we are no longer making improvements to applets
