### ISSUE TITLE
`stop` doesn't just end `loop`

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1027]
According to [the docs](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#loop), a `stop` in a `loop` should exit the `loop`, but not the procedure.

However, as running this procedure demonstrates:

```
to foo
  let i 0
  loop [ print i set i i + 1 stop ]
  print "done"
end
```

`stop` just ends the procedure.

I tested in both m5 and 5.3.1 to the same result. I don't particularly want to install Java 6, so haven't tested in earlier versions.

**Comment by mrerrormessage** [comment]
Perhaps there is a documentation ambiguity that needs to be resolved here. The documentation reads:

>  loop [ commands ]
> Repeats the commands forever, or until the enclosing procedure exits through use of the stop or report commands. 
> ...
> In this example, stop exits not just the loop, but the entire procedure.

The way I read this suggests that `stop` exits the procedure entirely, which has the effect of ending the loop. I'm not sure how to make this clearer, but if you can think of a way I'd happily change the docs.

**Comment by qiemem** [comment]
Oh I totally misread that, I'm sorry.
