### ISSUE TITLE
M5: Having a view too big to fit in the window causes the window to get really small

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1030]
To reproduce:

1. Create a model with a view that doesn't fit in the window.
2. Save.
3. Quit NetLogo.
4. Double click on the model to open NetLogo. It does not happen when you open through open file dialogue (which is going to make this a pain to test).

The window collapses to the bottom left of my screen:

![image](https://cloud.githubusercontent.com/assets/28215/14863550/bbaaf124-0c7b-11e6-843d-2a1db82454a1.png)

Model maximized:

![image](https://cloud.githubusercontent.com/assets/28215/14863556/c92d2b32-0c7b-11e6-9028-f2b47930023a.png)

On OS X 10.11.4.

**Comment by mrerrormessage** [comment]
@qiemem , have you seen any reports of this on windows? I'm happy to test it myself, just curious whether you had already seen it.

**Comment by qiemem** [comment]
No. I only found it myself. No one has reported it.

**Comment by mrerrormessage** [comment]
I was unable to reproduce this bug except with NetLogo Launcher. I right clicked on the model and chose "Open With" trying multiple NetLogo versions, but didn't see it until I opened with the launcher. I'm not sure who's maintaining the NetLogo Launcher these days, but you can file a bug with them [on their Github project](https://github.com/qiemem/NetLogo-Launcher/issues) 😉. Note that at some point we're planning to finish #995 and make NetLogo Launcher obsolete. This will certainly be an important bug to test for then. Thanks for reporting!
