### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1036]
When I visited in FireFox version 43 (but not in Chrome)

https://ccl.northwestern.edu/netlogo/5.3.1/

I got

ccl.northwestern.edu uses an invalid security certificate.

The certificate is not trusted because the issuer certificate is unknown.
The server might not be sending the appropriate intermediate certificates.
An additional root certificate may need to be imported.

(Error code: sec_error_unknown_issuer)

**Comment by mrerrormessage** [comment]
Thanks for the heads-up, we're looking into it.

**Comment by mrerrormessage** [comment]
Just wanted to post an update: I've been able to reproduce this in Windows 10 and Ubuntu 14.04 Firefox, but not Windows 7 or OS X El Capitan. Our system administrator is continuing to investigate.

**Comment by mrerrormessage** [comment]
We think we've resolved the issue. Can you try again and see whether it works for you? If you're still having problems, knowing the operating system version that you're using will help us troubleshoot further.

**Comment by ToonTalk** [comment]
The problem came up on the instructor computer in a classroom here -- I'll try again on that one on Wednesday. No problem from my laptop. Both are Windows 7.

**Comment by ToonTalk** [comment]
While I haven't been back to the classroom where the problem occurred I'm now in another classroom managed by the same people and there is no certificate error now.

**Comment by mrerrormessage** [comment]
Great! I'm going to mark this as closed. Thanks for reporting!
