### ISSUE TITLE
M6: Error dialog on command input

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1044]
To reproduce:

Create a input box with type `String (commands)`. Enter `foo` (or some other procedure name that doesn't exist). Try to hit OK. You'll get an error.

This is quite related to #1028

**Comment by mrerrormessage** [comment]
Just to clarify, I'm assuming based on the "hit OK" this is only happening for multi-line input boxes?

**Comment by qiemem** [comment]
Ah, I'm glad you asked. I hadn't actually checked single-line.

With single line, there's no error dialog, but the input won't lose focus. When you try to click elsewhere, the full text of the input is selected.
