### ISSUE TITLE
The link to the Localization wiki-page in Interface Guide doesn't work

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#1049]
Go to Interface Guide in https://ccl.northwestern.edu/netlogo/docs/ and try to click "this wiki page" at the very bottom of the page.

In Chrome, nothing will happen and an error will be shown in the console:
```
Refused to display 'https://github.com/NetLogo/NetLogo/wiki/Localization' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

In Firefox, the right frame of the page will become blank and a similar error will be shown in the console:
```
Load denied by X-Frame-Options: https://github.com/NetLogo/NetLogo/wiki/Localization does not permit framing. <unknown>
```

**Comment by mrerrormessage** [comment]
This anchor tag should have `target="_blank"` added, as should most or all of the external links in the NetLogo manual. There's some larger issue out there involving converting the NetLogo manual to pages that aren't in frames, but that's too big for this particular issue.
