### ISSUE TITLE
Hexy model loading: master errors when loading file with empty input

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1055]
Breaks for every input type, single line or multi line. There is an input box in the model with empty input, you get:

![image](https://cloud.githubusercontent.com/assets/28215/15456862/6b8e3dec-2042-11e6-9f4b-b5613793caff.png)

**Comment by qiemem** [comment]
Highly related to #1054. If they should be considered the same bug, feel free to close one.

**Comment by mrerrormessage** [comment]
Fixed in https://github.com/NetLogo/NetLogo/commit/912667be391299963a77a5ff80d7ac17772361f5
