### ISSUE TITLE
M6: Copy view/export-view in NetLogo 3D gives weird zoomed in view

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1057]
For example, this:

![image](https://cloud.githubusercontent.com/assets/28215/15490897/6cc0e7e2-2131-11e6-9bbe-0c67e5449c7a.png)

when copied with the Copy View context menu item or exported with `export-view`, gives this:

![image](https://cloud.githubusercontent.com/assets/28215/15490890/651df584-2131-11e6-8443-31c0b801b1cb.png)

**Comment by mrerrormessage** [comment]
Would you mind re-testing this on the `wip-3d-view-resizable` branch? I fixed two 3D bugs on that branch and it may be enough to fix this as well.

**Comment by mrerrormessage** [comment]
OK, I think I have a fix for this. It only affect High DPI (Retina) displays and has to do with the fact that there 2x as many pixels in the canvas as the nominal canvas pixel size. Will be incorporated into https://github.com/NetLogo/NetLogo/pull/1056 shortly.
