### ISSUE TITLE
When a runtime exception is thrown, check if it is caused by OutOfMemoryError

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1069]
We've been getting frequent reports (like [this one](https://github.com/NetLogo/NetLogo/issues/1066)) from users who are seeing an exception which is ultimately caused by an OOM, but results in another exception being thrown. We should handle this case just like any other out of memory error.

**Comment by SethTisue** [comment]
related: #25

**Comment by mrerrormessage** [comment]
Here's what I've got right now. I'm happy to change the text if there's other relevant information we can provide. The "Open FAQ" button opens the FAQ to the "how big" section. 

![screen shot 2016-07-07 at 3 39 15 pm](https://cloud.githubusercontent.com/assets/143198/16669023/0398bbbe-4459-11e6-834d-bfc6622647d6.png)

**Comment by mrerrormessage** [comment]
Closed in #25
