### ISSUE TITLE
Autosuggestion tweaks

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1077]
This is for tweaks to the new autosuggestion popup outside of ordering (#1075) and expansion of source list (#1076).
- [ ] Add to command center.
- [ ] Make items on the box selectable with the mouse.

**Comment by Idloj** [comment]
Filer out command or reporters based on context. For example, after `create-turtles ` there should be only reporters in the list, and in the start of a row (directly within the procedure) only commands should be listed.

**Comment by Idloj** [comment]
Zebra-stripe the lines like in #1079

**Comment by Akarshit** [comment]
@Idloj I tried the zebra stripes but that was not looking good. The main reason being that user will move up/down in the suggestion list frequently as opposed to a simple click in `Show Usage`. The screenshots of the suggestion box are below with zebra strips.
![screenshot from 2016-06-29 15 16 02](https://cloud.githubusercontent.com/assets/7762605/16448025/f6255c64-3e0c-11e6-8d82-ad75d0e13b68.png)
![screenshot from 2016-06-29 15 16 28](https://cloud.githubusercontent.com/assets/7762605/16448024/f625ce60-3e0c-11e6-8301-b57863d993ad.png)

**Comment by mrerrormessage** [comment]
I agree that zebra-striping looks strange.

**Comment by Idloj** [comment]
Another idea: if there is only one item, don't show the box and just complete the text in the only way available

**Comment by mrerrormessage** [comment]
These issues look to have been resolved in 6.0

**Comment by Idloj** [comment]
@mrerrormessage, can you leave this issue open? I believe my context-based-completion suggestion is still valid. I see this (wrongly, it seems) as an umbrella issue for whatever suggestions people come up with.

**Comment by mrerrormessage** [comment]
I'd rather create a new issue. I would gladly copy-and-paste your comment into a new issue, or you're welcome to open one, whichever you would prefer.
