### ISSUE TITLE
nsum4 translation mishandles parentheses

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#109]
In NetLogo 4.1.2, if you try to open a file containing

  nsum4 (trader-position)

the code is altered to

  sum values-from neighbors4 [(]trader-position)

This has two problems: the mishandlng of parentheses (clearly a bug), and the presence of values-from (reasonably called a bug in 4.1.2, given that a code substitution was made by the program).

Not tested for 5.0, but probably the same there.

**Comment by mrerrormessage** [comment]
This is unfortunately a bug that will not get fixed at this point. 6.x will only support transitions from 5.x (as well as token substitution changes from earlier versions, but no rewriting changes).
