### ISSUE TITLE
export/import-world should save/restore default shapes

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#11]
export-world is supposed to save all state, but this is a piece of state that isn't being saved.

(included in docs/issues.html)

**Comment by Idloj** [comment]
This is resolved in https://github.com/NetLogo/NetLogo/commit/b54eb3106e02934b6c0f03a531d0a96a463b5a07

**Comment by mrerrormessage** [comment]
Indeed. Nice catch, @Idloj !
