### ISSUE TITLE
Mode on NetLogo Mac binary set to 744

### ISSUE THREAD

**Issue by vmiller** [NetLogo/NetLogo#1102]
I was working on updating software deployment for some of the labs I support, and was puzzled by when NetLogo 5.3.1 would refuse to launch.  After a little digging, I found the mode on the binary in the .app bundle was set to 744 instead of 755.  This means only the owner of the app can launch it (in the case of a using a deployment tool, that owner will be root).  This was also true of the binary in the NetLogo 3D app and the NetLogo Logging app.

I went back and checked NetLogo 5.2.1 and the mode was correctly set to 755 in that version.

**Comment by mrerrormessage** [comment]
Thanks for reporting. I'll ensure this is fixed in the next release.

**Comment by vmiller** [comment]
Perfect, thanks!
