### ISSUE TITLE
Update NetLogo Web Export in Next Version - When exported to NETLogo web numbers in plot does not dissapear on mouse-out

### ISSUE THREAD

**Issue by surfaslt** [NetLogo/NetLogo#1114]
I exported my model to NETLogo web.
I ran it and whenever I hover over the plot lines with my mouse it shows me the exact number of x and y axis of that place. - That is great.

The problem is: when I move my mouse away from the plot or even click somewhere, that additional information does not disappear and hides some parts of the plot. - Not so great.

I have checked the known-bugs database and could not find anything like that.
![netlogo bug](https://cloud.githubusercontent.com/assets/5831685/17138183/d5d53a80-5336-11e6-9395-f383ab1ff324.JPG)

**Comment by mrerrormessage** [comment]
Hi, thanks for reporting. We update "Export to NetLogo Web" with each release, but it doesn't match the latest version found at http://netlogoweb.org/. When using your model on netlogoweb.org, do you seem the same problem?

**Comment by surfaslt** [comment]
Issue seems to be tackled in netlogoweb.org. However, it has another issue with NaN that "Export to NetLogo Web" seems not to have. See the picture.

![netlogoweb error](https://cloud.githubusercontent.com/assets/5831685/17141363/ae522182-5343-11e6-8947-e828568eca11.png)

**Comment by mrerrormessage** [comment]
Would you mind to repost this to [NetLogo/Galapagos](https://github.com/NetLogo/Galapagos/issues) ? We try to track NetLogo Web bugs over there. I'm going to keep this ticket to track updating of NetLogo Web Export in the next version of NetLogo Desktop, thanks!

**Comment by mrerrormessage** [comment]
Fixed in 86f5efe1717d8602e9b29c4c7374941a25f9be74
