### ISSUE TITLE
Regression: 5.3.1 HubNet broadcast broken

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1115]
A user reports that HubNet broadcasting isn't working under 5.3.1 where it _was_ working under 5.2.1 (user is in Mac 10.11.1). Given there were no substantial code changes to the code between 5.2.1 and 5.3.1, this may be due to changes between the Java 6 and Java 8 networking stack, but I'll need to investigate this more thoroughly. We haven't yet received reports of this on Windows, to my knowledge.

**Comment by mrerrormessage** [comment]
Running the HubNet client from `sbt` shows that the hubnet Discovery Listener is crashing on Mac OS X. Adding `-Djava.net.preferIPv4Stack=true` (forcing java to use IP4) fixes the crash but the client still doesn't discover the server.

**Comment by SethTisue** [comment]
> shows that the hubnet Discovery Listener is crashing on Mac OS X

could a test (that just uses the loopback interface and not the actual network) have caught this?

**Comment by mrerrormessage** [comment]
Mac OS X 10.11 switched to IPv6 by default, which appears to be the cause of this problem. Setting `-Djava.net.preferIPv4Stack=true` for a NetLogo 6.0.2 HubNet Client causes discovery to work as it did prior to Mac OS X 10.11.

A one-liner to work around this:

```
awk -v patt="-Dapple.laf.useScreenMenuBar=true" '$0 ~ patt {gsub(patt, patt"\n-Djava.net.preferIPv4Stack=true")}1' /Applications/NetLogo\ 6.0.2/HubNet\ Client\ 6.0.2.app/Contents/Java/HubNet\ Client.cfg > tmp.cfg && cp tmp.cfg /Applications/NetLogo\ 6.0.2/HubNet\ Client\ 6.0.2.app/Contents/Java/HubNet\ Client.cfg  && rm tmp.cfg
```

Note that this fix is only necessary on Mac.
