### ISSUE TITLE
Implement `range`

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1121]
`range` is a common function in a number of programming languages that is used to generate sequences of numbers. It often has three forms:

```
range 10 => [0 1 2 3 4 5 6 7 8 9]
range 5 10 => [ 5 6 7 8 9 ]
range 5 10 2 => [ 5 7 9 ]
```

This came up today in a devel meeting. Currently, the way to implement `range` functionality is with `n-values`, which is essentially the first form of `range`, followed by a `map`. `n-values` works well for the basic case (with just a maximum: `n-values 10 [ ? ]`) but for more complicated cases, it gets trickier:

```
range start top => n-values (top - start) [ from + ? ]
range start top step => n-values ceiling ((top - start) / step) [ start + step * ? ]
```

To be honest, it took me an embarrassing amount of time to figure out how to correctly write the `n-values` version with `step`. A novice would likely have a very difficult time figuring out how to do this. This is fairly common task and should be simple to do.

As for what the range syntax should look like, the simplest is `range`, with one required argument and two optional. The three forms are then:

```
range top
(range start top)
(range start top step)
```

Note that `step` here can then be a decimal.

The problems with this are:
- Remembering whether `step` comes before or after `top` is always a pain. Different programming languages do this differently.
- The meaning of the arguments changes depending on how many there are.

I'm personally okay with these drawbacks.

This is definitely _not_ targeted for hexy.

**Comment by SethTisue** [comment]
are floating point ranges allowed, like `(range 0 1 0.1)`? If you want to support that, you'll need to be really really really careful about roundoff problems.

**Comment by qiemem** [comment]
> are floating point ranges allowed, like (range 0 1 0.1)? If you want to support that, you'll need to be really really really careful about roundoff problems.

I would definitely say yes. This implementation performs correctly I believe:

```
to-report range [ start top step ]
  report n-values ceiling ((top - start) / step) [ start + step * ? ]
end
```

Now if you want to avoid any floating point weirdness at all, we could correct for it on the fly. Something like this:

```
to-report range [ start top step ]
  let p 0
  if step != floor step [
    let w (word step)
    set p length w - position "." w
  ]
  report n-values ceiling ((top - start) / step) [ precision (start + step * ?) p ]
end
```

Though gross, that gives the exact expected result as far as I can tell:

```
observer> show range 0 1 .11
observer: [0 0.11 0.22 0.33 0.44 0.55 0.66 0.77 0.88 0.99]
observer> show range 0 1 .3
observer: [0 0.3 0.6 0.9]
observer> show range 0 5 1.1
observer: [0 1.1 2.2 3.3 4.4]
```

It also doesn't work on exponential notation.

**Comment by SethTisue** [comment]
> This implementation performs correctly I believe

What reason do you have to believe that? What's stopping `((top - start) / step)` from occasionally returning something like 9.0000000000001 instead of the 9 you expected, and then `ceiling` would return 10?

You said "performs correctly" but then you supply an alternative implementation. If you believe the first is correct why is the second needed at all?

**Comment by qiemem** [comment]
You're absolutely right. I was trying to avoid the accumulating error that occurs with the naive implementation (just incrementing by the step value), but didn't consider how round-off errors would interact with `ceiling`.

The obvious solution is to just use Scala's `until`, but I found inconsistencies that occur for common, fractional step sizes (e.g. `1.0/3.0 until (1, 1.0/3.0)` vs `0 until (1, 1.0/3.0)`).

I do not believe it's possible to be completely consistent. That said, we can do pretty well. This implementation seems to work quite well:

```
to-report range-*-iter [ start top step ]
  let res []
  let sign ifelse-value (step < 0) [ -1 ] [ 1 ]
  ; Calculate the level of precision specified by the `start` and `top`
  let prec-exp min (list (exponent top) (exponent start))
  ; `epsilon` will operate on the last two bits of the significand of a double
  ; at that level of precision.
  let epsilon (2 ^ -51 + 2 ^ -52) * 2 ^ prec-exp
  
  if (exponent step) + 50 < prec-exp [
    ; the low bits are important so disable epsilon. The 50 here may need to tweaked.
    set epsilon 0
  ]
  while [ sign * (length res * step + start) + epsilon < sign * top ] [
    set res lput (length res * step + start) res
  ]
  report res
end

; Calculate the exponent portion of doubles
to-report exponent [ x ]
  report ifelse-value (x = 0) [ 1023 ] [ floor log abs x 2 ]
end

```

It's pretty similar to the one I posted before (in that it uses multiplication to get the actual items), but it calculates the number of items based on when it exceeds the top (which is really the obvious way to do it), thus avoiding the problems with ceiling. But there's still a problem of, for instance, getting `0.9999999999999999` instead of `1`. To deal with this, an epsilon value is used to allow for rounding errors. The epsilon is determined from the precision level of the `start` and `top` values.

You can find the file I created to test this (and other solutions) here: https://gist.github.com/qiemem/17d4787bf0e3ccc2b5c5605aa76dc509

The test cases are probably the most important part:

```
  let tests (list
    (list (-1 + 1 / 3) 0 (1 / 3) 2) ; Shows approaching 0
    (list (2 ^ 52 - 100) (2 ^ 52) 1 100) ; tests maximal differences in exponent
    (list (2 ^ 52 - 100000) (2 ^ 52) 1000 100) ; tests maximal differences in exponent
    (list -1 (2 ^ 52) (2 ^ 52) 2)
    [ 0 1 0.1 10 ]
    [ 1e-4 1e-3 1e-4 9]
    [ 1.00001e-10 1e-9 1e-10 9]
    (list 0 1 (1 / 3) 3)
    (list (1 / 3) 1 (1 / 3) 2)
    (list 0 2 (2 / 3) 3)
    (list (2 / 3) 2 (2 / 3) 2)
    (list 0 1 (1 / 6) 6)
    (list (1 / 6) 1 (1 / 6) 5)
    (list 0 3333.333334 (1 / 3) 10001)
  )
```

Additional tests are also run by adding constants to the bounds as well as swapping the bounds and negating the step size.

Not really sure why I did this in NetLogo instead of Scala... Also, the actual implementation would have to do input verification to make sure the `step` is the right sign and such.

**Comment by SethTisue** [comment]
another possibility would be to not do floating point math at all, but do it all in decimal, and only convert to floating point on the way out. (this has been proposed for NumericRange as well in Scala, but nobody has gotten around to actually doing it)

**Comment by qiemem** [comment]
I thought about that as well. The problem is that rounding is desirable in the case of, for instance, common fractions. For instance:

```
scala> def range(start: Double, top: Double, step: Double) = {
     | val decTop = BigDecimal (top)
     | val decStep = BigDecimal (step)
     | Iterator.iterate(BigDecimal(start))(_ + decStep).takeWhile(_ < decTop).toList
     | }
range: (start: Double, top: Double, step: Double)List[scala.math.BigDecimal]

scala> range(0.0, 1.0, 1.0 / 3.0)
res7: List[scala.math.BigDecimal] = List(0.0, 0.3333333333333333, 0.6666666666666666, 0.9999999999999999)
```

You could argue that that's the correct answer, I suppose, but it almost certainly goes against what would be intended by the user. To do it properly, you'd need to be using an implementation of the rationals, and take input that was specified in the rationals as well.

**Comment by SethTisue** [comment]
That's what I'm proposing: compute in rationals. Parse "0.1" as "1/10" and compute from there.
