### ISSUE TITLE
`my-<breeds>` primitive should exist for both directed and undirected breeds, according to docs

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1132]
This is a consequence of #639

**Comment by Wolgo** [comment]
my-<breeds> works for both undirected and directed breeds in the current version 6.2.0. (See attached model for proof I guess.)

I think this issue can be closed. 

[Issue1132.zip](https://github.com/NetLogo/NetLogo/files/5939091/Issue1132.zip)

**Comment by brandesNW** [comment]
As illustrated by sample model above, issue is not reproducible.
