### ISSUE TITLE
"Show usage" popup on Linux not quite high enough

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#1141]
For example:

![untitled](https://cloud.githubusercontent.com/assets/908754/18086736/4184f88c-6ea9-11e6-8397-4215449774c2.png)

It's only missing a few pixels, but the letters in the second line are truncated and the scroll bar unnecessarily appears.

**Comment by mrerrormessage** [comment]
@Akarshit , would you be interested in working on this bug and have a chance to fix it in the next 2 weeks or so?

**Comment by Akarshit** [comment]
@mrerrormessage sorry I missed the notification for this one. Working on this now.

**Comment by mrerrormessage** [comment]
Thanks! Really appreciate the help!
