### ISSUE TITLE
Tab cycle through slider widget numeric settings

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1161]
Currently, if you hit tab while in `Minimum`, `Increment`, or `Maximum`, it inserts an actual tab character. It should cycle to the next field.

Other fields appear to cycle as expected. I haven't tested other widgets yet.

**Comment by Idloj** [comment]
You also can't use Enter instead of clicking "OK"

**Comment by mrerrormessage** [comment]
I suspect this will be relatively easy to fix, but given that each of those fields is an editor field, it may be tricky to intercept the tab character properly.

**Comment by qiemem** [comment]
Oh, this is a regression btw. It worked in 5.3.1.

**Comment by Idloj** [comment]
Wanted to mention that monitors work correctly, even though they have an editor area too, so however it is done there should be copyable to sliders

**Comment by SethTisue** [comment]
I assume it's because those fields allow code and have syntax highlighting
