### ISSUE TITLE
Keyboard save does not seem to work with BehaviorSpace dialogue open

### ISSUE THREAD

**Issue by BruceEdmonds** [NetLogo/NetLogo#1167]
ctrl+S (or in mac command+s) saves a model in most circumstances in the Netlogo interface but not when the BehaviorSpace dialogue is open. One has to quit the dialogue, save and open it again. As a result I often forget to save the experiments I have just entered before I run them (OK, I know duuuuh).  Is it possible to fix this?

**Comment by nicolaspayette** [comment]
I have experienced the same thing many times. Enabling <kbd>Ctrl</kbd>+<kbd>S</kbd> in the BehaviorSpace dialog would be one way to alleviate the problem. I think it might also be worth warning the user before starting an experiment on an unsaved model (and offering to save).

**Comment by SethTisue** [comment]
> I think it might also be worth warning the user before starting an experiment on an unsaved model (and offering to save)

+1
