### ISSUE TITLE
BehaviorSpace errors when running a non-resaved model from an earlier version

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1168]
To reproduce:
- Open a model from 5.3.1 (or earlier) in 6.0-Beta (must have behaviorSpace experiment)
- Run a BehaviorSpace experiment
- Will see a version mismatch error as behaviorspace headless attempts to open the model from file and encounters an error.

**Comment by SethTisue** [comment]
good catch — I imagine this is actually a very old bug
