### ISSUE TITLE
Fix link primitive consistency issues

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1169]
Relatively recently, we have discovered a number of consistency issues with the link primitives:
- #1130 - `my-in-links`/`my-out-links` inconsistent with each other and with docs; unresolved
- #739 - `link-neighbor?` wrong for directed, breeded links; resolved by changing `link-neighbor?` stricter in accordance with docs
- #740 - `*-link-neighbor?` primitives wrong for undirected link breeds; resolved by making `out-link-neighbor?` stricter in accordance with docs
- #639 - `my-links` documentation is wrong; resolved by keeping `my-links` flexible and changing docs

Despite resolution of some specific issues, consistency issues remain. Furthermore, it's not clear how the inconsistencies should be resolved. This is meant to be a mega-issue for all link primitive consistency problems.

Here is a table showing the current behavior of all relevant link primitives:

![image](https://cloud.githubusercontent.com/assets/28215/18798344/b153ed3e-8197-11e6-8c18-de74a0327546.png)

The column headers indicate the type of link or neighbor being tested: "un" is undirected, "out" is directed, outgoing, and "in" is directed, incoming. The "-breeded" variants indicate that a breeded link is being used. The breeded primitives are automatically adjusted to target the breed of the link being tested.

A few inconsistencies:
- `link-with` errors when using directed, non-breeded links, but returns directed, breeded links. This is both internally inconsistent and conflicts with `link-neighbors` and `link-neighbor?`
- `my-out-links`,  is similarly inconsistent between breeded and non-breeded.
- `my-out-links` and `my-in-links` handle undirected links differently.
- `out-link-to` and `in-link-from` handle undirected links differently.
- `my-links` return everything whereas, eg, `link-neighbors` does not.

Breeded variants of primitives are internally consistent with each other, and are almost consistent with unbreeded variants in unbreeded models, if we assume that unbreeded links should act like breeded links with respect to the unbreeded primitives.

Now, before discussing how to resolve these issues, keep in mind a few things about links in NetLogo:
- A model may only use breeded or non-breeded links, not both. (which type a model can use depends on what kind of link is created first, not on the declaration of breeds or anything)
- Non-breeded links may be directed or undirected, but all non-breeded links in a model must have the same directedness.
- Breeded links are declared undirected or directed.
- Mixed directedness is possible, but only through multiple link breeds.

I see a few possible ways of resolving these issues, with two being strict and one being flexible.
## Strict

This is likely what people had in mind when originally designing the link system, as this is the resolution the docs are most consistent with:

![image](https://cloud.githubusercontent.com/assets/28215/18930293/1b4d81e8-858d-11e6-9532-406a0728b15d.png)

The idea here is that:
- An unspecified `link` _always_ refers to an undirected link. (the except being `links` itself)
- `out-link` _always_ refers to a directed, outgoing link
- `in-link` _always_ refers to a directed, incoming link

I've removed any erroring behavior whatsoever: sometimes, you don't know the directedness of your links before you start making them (they could be determined by a switch, or imported from a file). Thus, being able to do things like `(link-set my-links my-out-links)` is crucial.
## Super strict

![image](https://cloud.githubusercontent.com/assets/28215/18798628/0332de16-8199-11e6-9f08-1196d423fbdd.png)

This one is even stricter in that, instead of returning `false`, it errors in the situations where a un-breeded primitive can never return anything. This makes it so that unbreeded primitives in unbreeded models behave like breeded primitives in breeded models.

I believe this is what was originally intended for link primitives in NetLogo, as it's the closest match to how they behave currently (with the biggest, perhaps justifiable exception being `my-links`).

I would strongly advise against this method, as it makes models where you don't know directedness beforehand basically impossible, as you can't do stuff like: `(turtle-set link-neighbors out-link-neighbors)`. 
## Flexible

This is a more pragmatic approach, rooted in what I think is more useful given my experiences in network analysis:

![image](https://cloud.githubusercontent.com/assets/28215/18798799/dafc6efc-8199-11e6-8b39-f12fca0ea5cc.png)

The idea here is that:
- An unspecified `link` refers to any type of link.
- `out-link` refers to a outgoing link, regardless of directedness; that is, any link that you can use to travel out from node A to node B.
- `in-link` refers to a incoming link, regardless of directedness; that is, any link that you can use to travel into node A from node B.

Practically, the times when this differs from other methods are in mixed-directed networks and in networks where you don't know the directedness beforehand.

I have a strong preference for the flexible approach.
- Generally, in network science and graph theory, undirected links are treated as both incoming and outgoing links. Virtually all graph algorithms treat undirected links as both incoming and outgoing links, to the point where in the most basic network analytics, each undirected link is like two directed links (thus, the `2 * L` in all the undirected forms of network analytics). Case-in-point: In the NW extension, the link and neighbor fetching functions that all the algorithms are based on use the flexible approach.
- For networks where you don't know the directedness beforehand, this allows you to write algorithms that naturally work with either. In the strict resolution, you have to use a lot of `(link-set ...)` and `(turtle-set ...)`.
- In mixed networks, you can achieve the strict results by either just using the breeded primitives themselves (which you would probably do anyway), or, worst case, doing things like `my-out-links with [ is-directed-link? self ]`.

While the flexible approach differs more with NetLogo's current behavior, the only models where results will actually change are multi-link-breed, mixed-directedness models where the un-breeded primitives are being used. Otherwise, it will only make what were error-causing situations into non-error-causing situations.

The strict resolutions, on the other hand, would change the behavior of even unbreeded models, given the differences to `my-links` and the `out-link` primitives.

We could also consider hybrid resolutions, where, say, the unspecified link primitives do any directedness, the `in-link` do specifically directed, incoming links, and the `out-link` primitives take either the flexible or strict approach.

**Comment by qiemem** [comment]
Here's the model I used to generate the first table: [Link Test.nlogo](https://gist.github.com/qiemem/ad5efb004bced4963acfc03d1ddb7d2f)

**Comment by nicolaspayette** [comment]
Impressive work on building these tables, @qiemem. It is by far the clearest statement I have seen of this problem so far.

I also have a strong preference for the flexible approach. In my experience, this is pretty much always what you'd want. (And easy to get around if you do need a stricter interpretation.)

**Comment by qiemem** [comment]
> Impressive work on building these tables, @qiemem. It is by far the clearest statement I have seen of this problem so far.

Thanks! It's been bugging me for a while.

After more thinking, I think the original approach conceived of link usage in two different situations:

- Unbreeded - Then, `links` is basically a breed. Since there's only one breed, we know we can error on certain primitives. I'll add the breeded prims to the table when I get a chance to check to see if unbreeded link prims in an unbreeded model act like breeded prims in a breeded model.
 - Breeded - Then, the unbreeded link prims act as generic, all link prims.

I find this pretty confusing, personally.

**Comment by SethTisue** [comment]
Seems like a sweeping, incompatible change like this would either have to happen very soon in NetLogo 6.0, or wait for 7.0?

**Comment by qiemem** [comment]
You're absolutely right, @SethTisue. I've been thinking 6.0, as long as another beta is planned. The changes should not be difficult, only somewhat tedious.

It's also worth noting that in the majority of situations, these changes would only make situations that previously produced an error not error. That is, it wouldn't change the behavior of many error-free models. The exceptions are models with multiple breeds of links of varying directedness.

The strict approach is somewhat harsher in that it changes `my-links` significantly. If we go with that approach, it is definitely worth considering keeping `my-links` as is.

**Comment by TheBizzle** [comment]
I'm all for consistency, especially with this link system, which is frustratingly inconsistent.

I support the "flexible" approach.  I think it's more intuitive, and, if you want the strict mechanics (for some unknown reason), you can achieve it with a little extra code.

**Comment by SethTisue** [comment]
I have little memory of this except that we probably figured strict was safer since it could always be made looser later.

**Comment by qiemem** [comment]
I have updated my original post with the breeded variants, as well as with a table that I think was the original intention behind link primitives, given current behavior and @SethTisue's comment.

**Comment by arthurhjorth** [comment]
I too have a **strong** preference for the flexible approach.

`links` in compound primitives ought to work in the same way as `turtles` do - a catch-all reporter that just gets everything. I think that the flexible approach best captures that. Using `with` or set-operations can give you what you want if you want to filter what they report. People who do networks stuff should not find that difficult, whereas people who are just learning netlogo or just learning netsci stuff will struggle with the strict or super strict approach. So I think that both for consistency of the language and for learning, the flexible approach is the the better one.

**Comment by bainco** [comment]
I think that the flexible approach is much more pragmatic.

The only concern I have in the flexible approach is undirected links are considered both out-links and in-links. However, @qiemem's point that this is the standard in network science is a good enough justification for me. This also meshes with _most_ graph theory algorithms that simply take undirected graphs and "replace" their edges with two directed edges.

My only request is that this is made explicit in the documentation (e.g. Undirected links are treated as both in-links and out-links). Hopefully, that would be enough to avoid the "0 is neither positive nor negative so an undirected link is neither a in or an out link" thought.

**Comment by qiemem** [comment]
> My only request is that this is made explicit in the documentation (e.g. Undirected links are treated as both in-links and out-links). Hopefully, that would be enough to avoid the "0 is neither positive nor negative so an undirected link is neither an in or an out link" thought.

Absolutely. The documentation most definitely needs to be completely clear, whatever our decision is.

**Comment by bainco** [comment]
@nicolaspayette, any models come to mind that this will effect? Maybe I should make a corresponding issue in NetLogo/models.

**Comment by nicolaspayette** [comment]
> @nicolaspayette, any models come to mind that this will affect?

None that come to mind, no, but that doesn't mean none we'll be affected. We'll have to check the library carefully.

> Maybe I should make a corresponding issue in NetLogo/models.

Yes, please do!

**Comment by qiemem** [comment]
We've decided to go ahead with the flexible approach for now. I'll probably talk to a few more network people about it first, though.

We're also targeting this for 6.0, and, given the significance of this change, it *must* be in a beta before release. Thus, we're targeting the next beta.

**Comment by qiemem** [comment]
As part of this, we should add a `directed?` primitive to make it easy to make the flexible primitives strict if desired.

**Comment by nicolaspayette** [comment]
> we should add a `directed?` primitive

I agree that `directed?` would be nicer, but we already have [`is-directed-link?`](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#is-of-type). I'm afraid that having both could be confusing.

**Comment by arthurhjorth** [comment]
I completely agree, but I can't come up with a good case for using (O)
`is-directed-link?` over (L) `is-directed-link`?

In fact, I think we should open an issue for all of the `is-x?` primitives
and move to rewrite them for running in -TPL contexts.

`is-turtle? turtle 0`

ought to be

`[is-turtle?] of turtle 0`

**Comment by nicolaspayette** [comment]
> all of the `is-x?` primitives and move to rewrite them for running in -TPL contexts.

That's an interesting idea, but it would break consistency with other <tt>is-<i>x</i>?</tt> prims like `is-string?` and `is-number?`.

**Comment by arthurhjorth** [comment]
Yes, but their current implementation seems inconsistent with all other
things that relate to reporting properties of turtles, patches, or links.
If a student had written a reporter that took a TPL as an argument and
reported a variable, we would tell them to rewrite it as a TPL context
reporter.

The cases in which we use this is also different. We sometime ask turtles
whether they are of a particular breed or type, but we would never ask a
boolean if it is it a boolean. Consequently, this

ask a-turtle [
   if is-boolean? my-var [
        ...
]
]

makese sense in a way that

ask a-turtle [
   if is-breed? self [
        ...
]
]

doesn't. At least to me.

**Comment by qiemem** [comment]
I can definitely understand where you guys are coming from, but note that `directed?` and `is-directed-link?` are actually different. `is-directed-link?` is checking what something *is*, whereas `directed?` is getting the value of a property that the thing *has*. It's difference between `is-<breed>?` and `breed = <breed>`. More concretely, `is-directed-link?` first makes sure the thing is a link and then makes sure that the thing is directed.

> Yes, but their current implementation seems inconsistent with all other
things that relate to reporting properties of turtles, patches, or links.

That's because these things aren't for testing properties, they're for testing type.

**Comment by arthurhjorth** [comment]
Of the things in the language that we've been talking about changing over
the last few months, this is by far the one I care the least about. But I
think this would be more conceptually (even if not semantically) consistent
with agent-centricism, which, again to me, is a core concept of NetLogo. If
people think we shouldn't change it "just" for that, then so be it.  :)

**Comment by wvermeer** [comment]
upon request a netsci perspective... :)
The flexible approach is indeed what is the standard in network analysis, in terms narrowing the divide between Netlogo and netsci I feel this is certainly an step forward. Also the consistency between links and turtles, in terms of both of them being a 'a catch-all' reporter that just gets everything is in my opinion a important improvement.

With regards to the discussion of `directed?` and `is-directed-link?`, I feel that curently a directed-link is created as a different type of object, so in my mind directedness is not a characteristic of a link, which would make calling for it using the `directed?` counter-intuative for me...
That being said, I feel the change to the flexible approach will result in a need for a procedure that checks if a link in the opposite direction is present, rather than using name such as `directed?` I would adopt a language consistent with other netsci packages, which refer to this as a mutual tie (or reciprocal tie). As this does not refers to the type of object (rather it checks if another object is present in the same location, but opposite direction) we could use `mutual?` or `reciprocal?` which would be along the lines of @qiemem's proposal, yet less confusing.

On a different note; I'd be a proponent of getting rid of undirected links all together, and force them into 2 directed links. While I see how this would not be backwards compatible, this would in my mind reduce complexity, create clarity in terms of how to use links, would make the documentation a lot simpler, and increase consistency across breeded and unbreeded links. As far as I can see there are no analytical objections to doing so.
An upside to doing this is that the `directed?` and `is-directed-link?` discussion becomes irrelevant, and also any issues related to all non-breeded links in a model having to have the same directedness would be prevented.

**Comment by qiemem** [comment]
Thanks for the perspective @wvermeer!

> With regards to the discussion of directed? and is-directed-link?, I feel that curently a directed-link is created as a different type of object, so in my mind directedness is not a characteristic of a link, which would make calling for it using the directed? counter-intuative for me...

Alright, there's been enough resistance to this that I think we should scrap it for now. In the docs, I'll write `with [ is-directed-link? self ]` as the recommended way to get strict results.

> As this does not refers to the type of object (rather it checks if another object is present in the same location, but opposite direction) we could use `mutual?` or `reciprocal?` which would be along the lines of @qiemem's proposal, yet less confusing.

Under the flexible proposal, this is implementable as `[ out-link-neighbor? [ end1 ] of myself ] of end2`... I guess that's a little awkward. I confess, however, I don't see how this would be that useful, though. It seems like a pretty specialized functionality to be included among the base primitives. That unless we implement your final suggestion:

 > On a different note; I'd be a proponent of getting rid of undirected links all together, and force them into 2 directed links.

This definitely has appeal. However, pretty much every major netsci package out there supports both, so for interop alone, it's therefore worth it to have both. Also, from a novice perspective, I think working with undirected links when all links are in fact mutual is conceptually simpler. Finally, I think it's too big of a change right now. While the changes proposed above shouldn't break too many models, removing undirected links would obviously break tons of models, even if we're really clever about converting them to directed-only.

**Comment by SethTisue** [comment]
> I think working with undirected links when all links are in fact mutual is conceptually simpler

+1

**Comment by nicolaspayette** [comment]
> I'd be a proponent of getting rid of undirected links all together, and force them into 2 directed links. [...] As far as I can see there are no analytical objections to doing so.

I think link attributes constitute an objection. For example:

```nlogo
undirected-link-breed [ friendships friendship ]
friendships-own [ strength ]
```

How would you manage the `strength` attribute with two directed links? You could always write code to keep the attribute value in sync in both directions, but it would be verbose and error prone.

**Comment by wvermeer** [comment]
@nicolaspayette: you have a valid point, although the example is somewhat awkward as as friendship is inherently directed... Just because I consider you a friend, that does not mean you will consider me a friend, let alone with equal strength. 
That being said, there are certainly instances where true undirected links are created such as when links represent something like co-occurrence, there is no way in which A can be at the same place as B without the opposite being also true, in which case the mutual link scenario would seem problematic...
