### ISSUE TITLE
Netlogo, Maps, Zones

### ISSUE THREAD

**Issue by nasrinir** [NetLogo/NetLogo#1179]
I have five zones on my map. 4 shapes show my four zones the rest is zone 5 in the file. I try to set our zone as set-zone_num [x-left y-down x-right  y-up num dist]. I do not know how I can find these info? what is x-left for our zones?!
[9_CountyLAyout_Zones.pdf](https://github.com/NetLogo/NetLogo/files/516514/9_CountyLAyout_Zones.pdf)

**Comment by mrerrormessage** [comment]
I'm not entirely sure from what you've posted, but it looks like you have a question about a particular model and/or a NetLogo Programming question. It doesn't look like this is a bug in NetLogo or a feature request.

In general, the best places to look for help with a pre-made NetLogo model is the person who supplied it to you. If you're trying to learn more about NetLogo or NetLogo Programming, the [NetLogo Resources page](https://ccl.northwestern.edu/netlogo/resources.shtml) can probably help you find what you need. If you're looking for modelling assistance in general, the [netlogo-users](https://groups.yahoo.com/neo/groups/netlogo-users/info) group can be a helpful place to post.
