### ISSUE TITLE
Changes in code not recognized

### ISSUE THREAD

**Issue by cstaelin** [NetLogo/NetLogo#1181]
This is related to issue #1180, but is more general so I thought I should open a new issue.  I am running v6.0.beta1 of NetLogo 3D,  In working on the code in an  `__includes` tab I get the following scenario.
1. open the model
2. press "go" - all works as coded.
3. delete a "show" command in the code.  Check button goes "on"
4. move to interface tab, then back to code.  Check button is "off"
5. move back to interface tab and press go.  Show command still displays.
6. repeat a few times just to make sure I'm not missing something.  Same behavior.
7. save the model
8. use `__reload` in the command center - model reloads
9. run the model - the show command now does not display.

It appears that when pressing the check button or moving to the interface tab, the changes in the code are not recognized or the newly compiled code is not saved over the old code.

Changing the code in the "Code" tab does not yield this problem, so I assume that it only occurs in "included" code tabs.    Of course `__includes` is still termed "experimental", but shouldn't be a regular part of the language after all these years?  It is heavily used.

Thanks,
Charles

**Comment by mrerrormessage** [comment]
Thanks for this report as well as the other one! While `__includes` is technically experimental, this definitely sounds like a major issue that we will want to look at.

**Comment by cstaelin** [comment]
Thank you Robert.  Since the beta1 version of 6.0 also doesn't really error
check in an __include tab, my workaround for the moment is to develop new
code in the main Code tab and to move it to an __include tab when I'm sure
it is working properly.  That, and saving and __reloading the model as
necessary.

I'm starting a new project that uses anonymous reporters pretty heavily,
both in the NetLogo code and in extensions, and I'd prefer not to work in
v5.3 and then have to translate the whole thing over when v6.0 becomes
official.  I hope my work in v6.0 can be useful to you.

Cordially,
Charles


-------------------------------
Charles P. Staelin
Professor of Economics
Smith College
Northampton, MA 01063
