### ISSUE TITLE
benches.scala is really out of date

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1184]
It doesn't work anymore.

**Comment by mrerrormessage** [comment]
Fixed in https://github.com/NetLogo/NetLogo/commit/a8c8b92cfc7e2636538983a412bd81a2e9562362. Requires `SCALA_HOME`, so if you've downloaded a scala binary from lightbend to `~/scala-2.11.7`, run like `SCALA_HOME=~/scala-2.11.7/ ./bin/benches.scala`.
