### ISSUE TITLE
Make NetLogo indentation faster

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1193]
NetLogo's SmartIndenter is *slow*. on large files (> 500) with a lot of indentation changes, it can take as long as a few seconds to re-indent the file. There's no reason it needs to be so slow: caching and doing basic (as opposed to compiler-level) tokenization could increase speed significantly.

**Comment by qiemem** [comment]
In NLW, we increase the indentation level after `to`, `to-report`, `[`, and `(`. We decrease it on `end`, `]`, `)`. This works quite well (much better than NetLogo's smart indent, in fact) and requires minimal parsing.

It probably is irrelevant, but here's the codemirror syntax mode definition (includes highlighting as well as indentation): https://github.com/NetLogo/Galapagos/blob/a4b1d8100daed5fc2fd086b9f4913c0323a040d1/app/assets/javascripts/codemirror/mode.coffee#L525-L549

The electric chars bit is "when you see this character, apply the current indent level to this line (as opposed to the indent level from the beginning of the line", making it so dedenting tokens apply to the line they appear on.

**Comment by qiemem** [comment]
Right now, the `SmartIndenter` does arbitrary look back look for a matching opener under certain circumstances. A really simple change that could both simplify the indenter and improve performance dramatically would be to have `Token`s store the most recent unmatched opener; essentially, that would store what context they were in. Opener's themselves would store the opener at the next level up.

**Comment by qiemem** [comment]
I came across a number of potential ways of improving indenter performance when working on #1231. @mrerrormessage do we have any models that particularly exemplify the performance problems for testing?

**Comment by mrerrormessage** [comment]
Reported again in #1290 .
