### ISSUE TITLE
Linux GUI: Editor stops responding to keyboard

### ISSUE THREAD

**Issue by erelsgl** [NetLogo/NetLogo#120]
I created a project, made a few edits to the code, saved once or twice, and all of a sudden, the program stopped responding to the keyboard. I closed NetLogo and restarted, and the same thing happened - after several edits and saves, it stopped responding. It did respond to the mouse, though.

OS:  Ubuntu: 2.6.32-37-generic #81-Ubuntu SMP Fri Dec 2 20:32:42 UTC 2011 x86_64 GNU/Linux

Java: version "1.6.0_26"
Java(TM) SE Runtime Environment (build 1.6.0_26-b03)
Java HotSpot(TM) 64-Bit Server VM (build 20.1-b02, mixed mode)

**Comment by mrerrormessage** [comment]
We've had no further reports of this in 4 years, even with 2 dedicated linux users here at the CCL. I'm closing this. It can be re-opened if the problem resurfaces.
