### ISSUE TITLE
Improve sort documentation

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1203]
The documentation for sort needs to be more clear about what happens in cases where the list includes two of a number, a string, and an agent.

Sort order needs to be clarified for links, since at the moment it documents sort order only for patches and turtles.

Another user writes:

> It would be helpful if the Dictionary entry for "sort" said exactly what 
> turtles and patches are sorted by. The example indicates that patches 
> are sorted by pxcor in ascending order and pycor in descending order. 
> Experimenting indicates that turtles are sorted by who number.

**Comment by SethTisue** [comment]
docs/programming.html has

```
    <p>
      If you use <a href="dictionary.html#sort"><code>sort</code></a> on an
      agentset of links, the result is a list of links, sorted in ascending
      order first by <a href="dictionary.html#end1"><code>end1</code></a> then
      by <a href="dictionary.html#end2"><code>end2</code></a> any remaining
      ties are resolved by breed in the order they are declared in the Code
      tab.
```
