### ISSUE TITLE
Corrupted file save in 6.0 Beta 1

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1211]
I saved a file and it seems to be fill with gibberish.
[Wolf Sheep Predation-b6.zip](https://github.com/NetLogo/NetLogo/files/582904/Wolf.Sheep.Predation-b6.zip)

**Comment by ToonTalk** [comment]
Windows 7

**Comment by ToonTalk** [comment]
Perhaps but probably not relevant is that I had these models open and Windows automatically rebooted while I was away. It happened to 3 files but today I tried various ways to reproduce the problem and couldn't.

**Comment by mrerrormessage** [comment]
Thanks for reporting. Were you using 32 or 64-bit Windows and 32 or 64-bit NetLogo? Also, is this happening to you with every model or just certain models?

**Comment by ToonTalk** [comment]
64-bit Windows and NetLogo 

All of the models had been originally been from NetLogo 6.0-CONSTRUCTIONISM-2016-PREVIEW and then saved in Beta 1. While this happened with 3 such models it didn't for a fourth one. It has never happened with 5.3.1 models that were saved in Beta 1. All trashed models were running LevelSpace but it doesn't happen for all LevelSpace models.

**Comment by mrerrormessage** [comment]
I've tried to reproduce this but haven't been able to do so. The file you posted above, also didn't yield any deeper information about the problem, unfortunately. I'm planning to look at auto-saving in NetLogo 6 very soon, which could also be connected to this (if tangentially). I'm planning to leave this issue open for a while in case others have this issue.

**Comment by mrerrormessage** [comment]
I haven't heard any further reports of this in the 6.0 Beta period or since the release of 6.0 2 months ago. I'm going to go ahead and close this, although if future users have problems with corrupted model files in the 6.x series, they should feel free to comment here and we can re-evaluate.
