### ISSUE TITLE
Repeated warning about saving in a new version

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1212]
If I save a file in a later version of NetLogo it sensibly puts up a warning dialog. But there is no need to do so on every save to the same file location since I've already saved it in the new version.

![image](https://cloud.githubusercontent.com/assets/2138696/20171148/47272812-a727-11e6-863d-74200bc0c9e3.png)

**Comment by mrerrormessage** [comment]
Fixed in #1237
