### ISSUE TITLE
Bugs in LevelSpace Beta 1 6.0 documentation

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1214]
From NetLogo%206.0-BETA1/app/docs/index2.html

(ls:create-models "My-Model.nlogo" [ set model-id ? ])

is missing the number of models and uses the old command so it should be

(ls:create-models 1 "My-Model.nlogo" [ [?] -> set model-id ? ])

The documentation doesn't mention that the parentheses are required otherwise it is a syntax error.

ls:create-models number path anonymous command

should be

ls:create-models number path anonymous-command

since it looks like it takes 4 arguments.

"You should use this primitive you plan" should be

"You should use this primitive if you plan"

repeat 30 [ ls:load-headless-model "Wolf Sheep Predation.nlogo" ]

should be

repeat 30 [ ls:create-models 1 "Wolf Sheep Predation.nlogo" ] or

 ls:create-models 30 "Wolf Sheep Predation.nlogo"

**Comment by qiemem** [comment]
Thank you for reporting! I'll make sure all these get fixed for the next beta.

**Comment by mrerrormessage** [comment]
@qiemem , I'm closing these as fixed. Please re-open if needed.
