### ISSUE TITLE
Choosers forget variable name

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#1226]
On the current head of `hexy` (fad2d7b0b59a1584947d66dd667f8e7246171d06), if you create a chooser on the interface, the name of the associated global variable doesn't get saved and doesn't appear on the interface either.

![screenshot from 2016-11-20 14-21-44](https://cloud.githubusercontent.com/assets/908754/20463515/b61acf96-af2c-11e6-8d48-50573b1d172e.png)

Results in:

![untitled](https://cloud.githubusercontent.com/assets/908754/20463519/d93d4bca-af2c-11e6-989a-68734e1d13bb.png)

Same happens when you load an existing model that has a chooser (that's how I noticed the bug in the first place).

**Comment by nicolaspayette** [comment]
Rolling back to 46dc42f fixes it for me.

**Comment by mrerrormessage** [comment]
I found and fixed this while testing the release. I'll push and post the SHA1 soon.

**Comment by mrerrormessage** [comment]
This is fixed in a96b5cc138eb56f686bad1570104b86703577531
