### ISSUE TITLE
NetLogo3D 6.0-Beta2 running headless

### ISSUE THREAD

**Issue by cstaelin** [NetLogo/NetLogo#1238]
I am running NetLogo3D v6.0Beta2 headless under Ubuntu.  It works, but I get a strange error related to the slider widget (or in other NetLogo3D programs whatever widgets are present) written to the stdout.  It seems to have something to do with expecting a 3D view widget?  I did use the java command modified for 3D as shown in the manual.

I've attached a zip of the simple test program I used along with the sh file used to run the model and the results.

Charles
[3DHeadlessTest.zip](https://github.com/NetLogo/NetLogo/files/629597/3DHeadlessTest.zip)

**Comment by mrerrormessage** [comment]
Thanks for the very thorough report and test case. This extra output is from some debugging code accidentally left in, which was removed in https://github.com/NetLogo/NetLogo/commit/fe7a1af36f847df5c64f46e5813262fa592be8b6. This change will be included in the next release of 6.0. Thanks again!
