### ISSUE TITLE
download page still says "6.0 beta"

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#1260]
https://ccl.northwestern.edu/netlogo/oldversions.shtml only has "NetLogo 6.0 (Beta) (September 2016)"

**Comment by SethTisue** [comment]
https://github.com/NetLogo/NetLogo/wiki/Hexy-Extension-Transition-Guide needs updating now that 6.0 is out, too

**Comment by mrerrormessage** [comment]
Thanks for reporting. These have now been resolved.
