### ISSUE TITLE
Blank frame from http://ccl.northwestern.edu/netlogo/docs/

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1261]
I clicked on Controlling then 'here' in go here and the frame is empty. The console contains:

Refused to display 'https://github.com/NetLogo/NetLogo/wiki/Controlling-API' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".

Work around is to open 'here' in a new tab.

By the way many consider anchor text such as 'here' as bad practice.

**Comment by mrerrormessage** [comment]
Thanks for reporting. The NetLogo documentation unfortunately doesn't make good use of best practices. We are hoping to improve it at some point.

**Comment by Idloj** [comment]
related: https://github.com/NetLogo/NetLogo/pull/1052

**Comment by mrerrormessage** [comment]
This is now addressed on the referenced page. Thanks for reporting!
