### ISSUE TITLE
Documentation recommends deprecated MaxPermSize

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1262]
https://github.com/NetLogo/NetLogo/wiki/Controlling-API suggests using MaxPermSize which is ignored in Java 8.

See for example http://stackoverflow.com/questions/18339707/permgen-elimination-in-jdk-8

**Comment by mrerrormessage** [comment]
Thanks for pointing this out. I've updated the page and removed that instruction.
