### ISSUE TITLE
import org.nlogo.api.CompilerException missing from netlogo-6.0.0.jar

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1263]
The import org.nlogo.api.CompilerException cannot be resolved	BC2NetLogo.java	/BC2NetLogo/src/uk/ac/ox/it/modelling4all/bc2netlogo	line 22	Java Problem

**Comment by mrerrormessage** [comment]
This is documented in [the extension transition guide](https://github.com/NetLogo/NetLogo/wiki/Hexy-Extension-Transition-Guide). How did you go about looking for information and how can we make the extension transition guide easier to find?

**Comment by ToonTalk** [comment]
Thanks - just what I needed.

I'm updating a controlling application so I didn't think to look for the extension transition guide -- perhaps it should be renamed to extensions and controlling transition guide and links to this guide should be easy to find for those working on controlling applications.

**Comment by mrerrormessage** [comment]
A link has been added to the Controlling API page and [the transition guide itself has been renamed](https://github.com/NetLogo/NetLogo/wiki/6.0-Extension-and-Controlling-API-Transition-Guide) to indicate that it's for both extension and controlling API authors.
