### ISSUE TITLE
http://ccl.northwestern.edu/netlogo/docs/scaladoc/ page title is NetLogo 5.3.1

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1264]

**Comment by mrerrormessage** [comment]
This will be fixed soon, in the meantime, the 6.0 scaladocs are available at http://ccl.northwestern.edu/netlogo/6.0/docs/scaladoc/org/nlogo/

**Comment by ToonTalk** [comment]
A similar problem is that clicking on "Extensions Guide" from http://ccl.northwestern.edu/netlogo/docs/

leads to http://ccl.northwestern.edu/netlogo/docs/extensions.html

which says it is NetLogo 5.3.1 User Manual

**Comment by Idloj** [comment]
http://ccl.northwestern.edu/netlogo/docs/ itself is 5.3.1

**Comment by mrerrormessage** [comment]
Thanks for reporting. This issue has been resolved, both for "/netlogo/docs" and "/netlogo/docs/scaladoc".
