### ISSUE TITLE
ModelSaver changed in 6.0 and yet not documented

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1265]
org.nlogo.app.ModelSaver used to take an App argument and now apparently expects ModelSections and ModelLoader arguments.

I could not find ModelSaver or ModelLoader documentation in http://ccl.northwestern.edu/netlogo/docs/scaladoc/

**Comment by mrerrormessage** [comment]
I'll be adding a wiki page on this at some point. `ModelSaver` no longer saves models (probably should have been renamed). To save a model, get a [`fileformat.basicLoader`](http://ccl.northwestern.edu/netlogo/6.0/docs/scaladoc/org/nlogo/fileformat/index.html) and then call [`save(model, uri)`](http://ccl.northwestern.edu/netlogo/6.0/docs/scaladoc/org/nlogo/api/ConfigurableModelLoader.html) on the returned loader. `ModelSaver` could probably be better named `ModelTracker`.

**Comment by ToonTalk** [comment]
Thanks.

I'm not saving the model but it used to be that

new ModelSaver(App.app()).save()

would return a string that corresponds to the contents of the file if the model was saved.

I see there is something called sourceString but not sure how to use or if there is now another way.

**Comment by mrerrormessage** [comment]
Yes, `sourceString` is the way to do it. Using `sourceString(model, "nlogo")` (or `"nlogo3d"` for 3D models) will return a `scala.util.Try[String]`. The `String` contained in the result will be the source of the ".nlogo" model.

**Comment by ToonTalk** [comment]
Thanks. But I'm finding writing a couple lines of Java based on Scala examples very confusing.

For example I found a test file that seems to do what I want: 

https://github.com/NetLogo/NetLogo/blob/febdb7ce6c884aa4f48f0bce834209c27b5a604a/netlogo-headless/src/test/headless/misc/TestCompileAll.scala

but I can't figure out how to do something similar in Java.  You suggested fileformat.basicLoader and yet when I type org.nlogo.fileformat. the completions that are offered do not include basicLoader (or standardLoader) so I don't know how in Java to create a loader.

In http://ccl.northwestern.edu/netlogo/6.0/docs/scaladoc/org/nlogo/fileformat/index.html I see basicLoader is a "Value Member" but again not clear how in Java to access it.

Previously I used  App.app().openFromSource but I'm guessing that now I should use loader.readModel(modelString, "nlogo") to get the model to pass to sourceString. But again I can't see how to get a loader. (I'm assuming that sourceString will return the up-to-date string if the user made any edits after loading the model.)

**Comment by mrerrormessage** [comment]
Good point, it's `fileformat.basicLoader` from Scala, but from Java it's `fileformat$.MODULE$.basicLoader()`. `sourceString` is also slightly more complex. It takes a `org.nlogo.core.Model`, which represents all of the saveable data in the model. To get the latest string for the latest model the user has of the model, you need to pass in the latest version of the model, which is where `ModelSaver` re-enters the picture. Calling `sourceString(new ModelSaver(App.app, null).currentModel, "nlogo")` should save the currently active model (although in Java, you may need to do `App$.MODULE$.app()` instead of `App.app`).

All of this is certainly a lot more work than before, but it does serve a purpose. These changes have been made as part of efforts to think about NetLogo as potentially having more than one model open at once (vis-a-vis LevelSpace) and to hopefully enable new file format(s) in the future (although we aren't sure exactly when).

**Comment by ToonTalk** [comment]
Thanks. Makes sense and I'm making progress. The following compiles

                    ModelSaver modelSaver = new ModelSaver(App.app(), null);
                    Model currentModel = modelSaver.currentModel();
                    String modelAsString = modelSaver.modelAsString(currentModel, "nlogo");

But the 3rd line causes a null pointer exception. Perhaps due to the null in new ModelSaver.

I tried fileformat$.MODULE$.basicLoader() but fileformat$ isn't defined. Perhaps I'm missing a JAR that wasn't needed in 5.3 -- I'm using netlogo-6.0.0.jar and pretty much every other JAR in NetLogo 6.0\app except perhaps missed something when upgrading to 6.0

**Comment by mrerrormessage** [comment]
Ah, my earlier post was mistaken. It's `org.nlogo.fileformat.package$`. The following compiles for me:

```
package org.nlogo.app;

import org.nlogo.fileformat.package$;

class TestJava {
  public void foo() {
    org.nlogo.api.ConfigurableModelLoader loader = package$.MODULE$.basicLoader();
    String source = loader.sourceString(new org.nlogo.app.ModelSaver(App$.MODULE$.app(), null).currentModel(), "nlogo").get();
  }
}
```

While you could probably get `modelSaver.modelAsString` to work by passing in an appropriate model loader to the `ModelSaver` initializer, we're very likely to remove that method in a future version of NetLogo, so I would recommend avoiding it if possible.

**Comment by ToonTalk** [comment]
Thanks. That compiles and runs fine now. But now I'm stuck due to #1268.
