### ISSUE TITLE
App.app().openFromSource behaves differently in 6.0

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1268]
It behaves as if it loads the contents of the file name that is its first argument and ignores the second argument. I see that it is defined in the headless work space - https://github.com/NetLogo/NetLogo/blob/7eb938f273ae6b30344d9bf6caa73063463be521/netlogo-gui/src/main/headless/HeadlessWorkspace.scala

I also tried

 ConfigurableModelLoader loader = package$.MODULE$.basicLoader();
 loader.readModel(modelString, extension);

but it didn't seem to do anything.

I'm doing this with the GUI not the headless work space.

**Comment by ToonTalk** [comment]
To clarify

loader.readModel(modelString, extension);

returned a Try<Model> and sourceString of that model returned a copy of the modelString but the model wasn't loaded into the current app.

**Comment by mrerrormessage** [comment]
This appears to be something we overlooked in the 6.0 API. The method behaves as you describe. Unfortunately, the best workaround at the moment is to save the file to a temporary location and pass the location of that file to `App.app().fileManager().openFromPath(temporaryFile.getPath(), ModelTypeJ.NORMAL())`. I'll update this ticket with more information on a potential fix.

**Comment by ToonTalk** [comment]
Thanks. The workaround is good enough.

Is 

`App.app().open(temporaryFile.getPath());`

equivalent to

`App.app().fileManager().openFromPath(temporaryFile.getPath(), ModelTypeJ.NORMAL())`

**Comment by mrerrormessage** [comment]
Yes, the two are equivalent, assuming they are called from the Swing event thread (`App.app().open(...)` checks that it is being called from the Swing event thread, `App.app().fileManager.openFromPath(...)` assumes that its caller has checked).
