### ISSUE TITLE
Bug in documents of v6.0

### ISSUE THREAD

**Issue by itsaquestion** [NetLogo/NetLogo#1278]
Entry "foreach" : 
 "-&;gt;" at the end of the first line should be "->" .

**Comment by mrerrormessage** [comment]
Thanks for reporting!

**Comment by Idloj** [comment]
I'll address this as part of #1259

**Comment by mrerrormessage** [comment]
I have a fix for this already on the `wip-documentation-fixes`. I'll go ahead and merge that into hexy so it gets into your branch as well.
