### ISSUE TITLE
add table:values and table:get-default (enhancement request)

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#1279]
It would be convenient if `table` included `values` and `get-default` primitives for reporting a list of values and for contingently reporting a default value when getting (rather than conditioning on `has-key?`).

**Comment by mrerrormessage** [comment]
These sound like good ideas. We've already had `get-default` proposed [here](https://github.com/NetLogo/Table-Extension/issues/2). 

Under your proposal, would `table:values` return a de-duplicated list of values or a list including duplicates?

**Comment by alan-isaac** [comment]
Duplicates should be included, imo.  (Compare http://reference.wolfram.com/language/ref/Values.html in Mma.)  So the effect should be equivalent to that of `[[?] -> map last (table:to-list ?)]`.

**Comment by mrerrormessage** [comment]
`table:values` was added in 2f3c334 . We had another issue [here](https://github.com/NetLogo/Table-Extension/issues/2) in the table extension regarding a get-with-default primitive. The names that have been proposed for this primitive include:

* `get-default`
* `get-or-default`
* `get-or-else`

At the moment, I lean towards `get-default` as it's the simplest. @qiemem , you opened the issue on the table extension, do you have a strong preference for `get-or-default` or `get-or-else` over `get-default`?

**Comment by qiemem** [comment]
I typically go with `getOrElse` when I write the equivalent function in other languages.

Another possibility is adding it as an optional argument to the regular `table:get` reporter.

That is:

`(table:get my-table "key" "I'm a default value!")`

**Comment by nicolaspayette** [comment]
2¢: I find `get-default` to be semantically misleading. It makes sound like you're going to get the default value no matter what.

**Comment by SethTisue** [comment]
> I find get-default to be semantically misleading

agree

**Comment by alan-isaac** [comment]
In haskell it is `findWithDefault`.  In Python it is just `get`. In Mma it is `Lookup`.  I would probably favor `default-get` over `get-or-default`, but the latter seems ok ...  

An alternative is to follow Ruby and allow specifying a default value for the table with a `set-default` primitive.  The result would resemble a `defaultdict` in Python, which I find myself using quite a bit in that language.  This alternatively should probably be considered?

**Comment by alan-isaac** [comment]
After some time has passed, I find that I have repeatedly been wishing for an equivalent to Python's `defaultdict`.  Is there any developer sympathy for the idea that one could say `table:setdefault mytable []` to change the behavior of `table:get mytable mykey` to return `[]` whenever `mytable` does not contain `mykey`?  If this is infeasible, I now like second best the overloading suggestion of @qiemem on Jan 23.

**Comment by qiemem** [comment]
Update: This was added to the table extension a little over two week ago: https://github.com/NetLogo/Table-Extension/commit/079bb1995b2fd3381c9ee18756a92e7b2461d4bc. Decided on `table:get-or-default`.
