### ISSUE TITLE
Netlogo-matlab extension in mac

### ISSUE THREAD

**Issue by Rbhui** [NetLogo/NetLogo#1281]
Hi,
I have created an ABM using NetLogo 3D 5.3.1 on Windows 10 (and Windows 7), 64 bit, and < 16gb RAM. It has Matlab extension in it. But when I tried it On OSX, the netlogo simulation never loads to the main interface also it would not automatically launch Matlab as it is supposed to. In a word, a model with netlogo-matlab extension is not opened in Mac. Please let me know how I can use this type of model in Mac.

Thank you,
Rita

**Comment by mrerrormessage** [comment]
Can you upload a copy of the model? Also, can you provide a link to the site where you downloaded the Matlab extension? Thanks!

**Comment by Rbhui** [comment]
Thank you for your reply. Please attached file. To download the extension, I used this link https://github.com/mbi2gs/netlogo-matlab-extension/wiki and below it there is download zip file. Please let me know if  you need anything else.

[https://avatars2.githubusercontent.com/u/3629777?v=3&s=400]<https://github.com/mbi2gs/netlogo-matlab-extension/wiki>

Home · mbi2gs/netlogo-matlab-extension Wiki · GitHub<https://github.com/mbi2gs/netlogo-matlab-extension/wiki>
github.com
netlogo-matlab-extension - An extension for NetLogo that gives access to Matlab functions from a Netlogo script and allows data-passsing between the two programs.


________________________________

**Comment by mrerrormessage** [comment]
The `matlab` extension is maintained by @mbi2gs . Can you post the issue on [their issue tracker](https://github.com/mbi2gs/netlogo-matlab-extension/issues?q=is%3Aissue+is%3Aclosed) and see if they can help you out? I'm happy to assist with errors in NetLogo, but on reading your issue more closely, this sounds more like a Matlab extension or configuration problem that the extension author would know how to handle better. If you work with the author and determine that there's a problem in NetLogo that needs to be addressed, please don't hesitate to comment here or re-open this issue.
