### ISSUE TITLE
foreach 100 times faster than equivalent while loop

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1291]
[lorenz-curve-fast.zip](https://github.com/NetLogo/NetLogo/files/725969/lorenz-curve-fast.zip)

In the attached
```

while [ agents-in-percent-of-population-remaining != [ ] ]
         [ let agent first agents-in-percent-of-population-remaining
          set wealth-of-percent-of-population
                wealth-of-percent-of-population + [ run-result a ] of agent
           set agents-in-percent-of-population-remaining but-first agents-in-percent-of-population-remaining
            ]
```
is 100 times slower than

```
 foreach agents-in-percent-of-population-remaining [[agent] ->
               set wealth-of-percent-of-population
                     wealth-of-percent-of-population + [ run-result a ] of agent
               ]
```

where `a` is just the name of a turtle variable. Replacing `run-result a` with `my-sugar` eliminates the problem.

The difference on my laptop is a difference between 2 seconds and .02 seconds.

I tried to make a simple example but the speeds were comparable. I also tried to use the profiler but it doesn't seem to notice anonymous functions.

**Comment by mrerrormessage** [comment]
Thank you for reporting! This looks like another instance of the slowness reported in [this bug](https://github.com/NetLogo/NetLogo/issues/1266). Having another example model is helpful for us to know that we're covering all the necessary cases. We are planning to address this slowness in the next release.

**Comment by mrerrormessage** [comment]
I'm going to close this as a duplicate for now, but I will link to it from #1266

**Comment by ToonTalk** [comment]
Thanks. Eliminating the innermost 'let' fixed the problem:

```
while [ agents-in-percent-of-population-remaining != [ ] ]
                                      [
                                        set wealth-of-percent-of-population
                                            wealth-of-percent-of-population + [ run-result a ] of first agents-in-percent-of-population-remaining
                                        set agents-in-percent-of-population-remaining but-first agents-in-percent-of-population-remaining
                                    ]
```
