### ISSUE TITLE
can't import world with an array containing strings with curly braces

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#13]
there are now commented-out tests for this in TestImportExport and TokenizerTests.
a string like this: `{{array: 0: "}}" "{{"}}`

confuses the tokenizer because it doesn't know the }} are part of the string rather than terminating the array

I'm not sure how fixable this even is without redesigning the export format

add to TokenizerTests:

``` scala
  test("array of strings containing doubled curly braces") {
    val tokens = tokenize("{{array: 0: \"}}\" \"{{\"}}")
    expect(1)(tokens.size)
    expect("Token({{array: 0: \"}}\" \"{{\"}},LITERAL,{{array: 0: \"}}\" \"{{\"}})")(
      tokens.mkString)
```

add to TestImportExport:

``` scala
  test("testImportingArrayContainingStringsWithBraces") {
    roundTripHelper("set a array:from-list [\"}}\" \"{{\"]",
                    "extensions [array] globals [a]")
  }
```

**Comment by brandesNW** [comment]
closed by https://github.com/NetLogo/NetLogo/pull/2296

**Comment by SethTisue** [comment]
cool to see a two-digit bug number getting closed 🚀
