### ISSUE TITLE
layout-radial link-set behavior

### ISSUE THREAD

**Issue by daimpi** [NetLogo/NetLogo#1301]
When distributing turtles via `layout-radial` the link-set input seems to work inconsistently depending on whether the link set is specified as a breed-set `(breed-set)` or as `links with [breed = breed-set] `

The behavior can be observed in the following example:

```
directed-link-breed [attacks attack]
undirected-link-breed [starters starter]

to setup [input]
  clear-all
  set-default-shape turtles "circle"
  crt 6
  ask turtle 0 [
    create-starter-with turtle 1
    create-starter-with turtle 2
    create-starter-with turtle 3
    if input [
      create-attack-to turtle 4
    ]
  ]
  ask turtle 1 [
    create-starter-with turtle 4
    create-starter-with turtle 5
  ]
  show (word "starters: " starters)
  show sort starters
  show (word "links with [breed = starters]: " links with [breed = starters])
  show sort links with [breed = starters]
end

to make-a-tree1
  layout-radial turtles (links with [breed = starters]) (turtle 0)
end

to make-a-tree2
  layout-radial turtles starters (turtle 0)
end
```

The output for the link sets is the same whether `setup` is called with the parameter `true` or `false` :

> observer: "starters: starters"
> observer: [(starter 0 1) (starter 0 2) (starter 0 3) (starter 1 4) (starter 1 5)]
> observer: "links with [breed = starters]: (agentset, 5 links)"
> observer: [(starter 0 1) (starter 0 2) (starter 0 3) (starter 1 4) (starter 1 5)]

The difference is that the former also creates a directed link (attack) from turtle 0 to turtle 4.

When this link exists (i.e. `setup true`) the two procedures make-a-tree1 and make-a-tree2 produce different layouts although the link-sets for `layout-radial` and everything else should be the same. This behavior seems to only appear in NetLogo 6.0 but not in 5.3.1. 

Strangely NetLogo 6 was also crashing (i.e. not responding and using a full cpu) twice during my experiments with this code, but unfortunately I wasn't able to reproduce this consistently to figure out what triggered the crashs.

**Comment by mrerrormessage** [comment]
Thanks for reporting! I'm attaching a screenshot of the divergent behavior below. The expected behavior (5.3.1 behavior) is on the right, the other behavior is on the left. I didn't run into any crashes while running the model, but I will be on the lookout for those in the future.

![screen shot 2017-01-30 at 9 23 03 am](https://cloud.githubusercontent.com/assets/143198/22428826/1ced009e-e6ce-11e6-9dfa-02b019493810.png)
