### ISSUE TITLE
Code Generation raises exception

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1310]
One of our users reports the following bug in NetLogo 6.0:

> NetLogo is unable to supply you with more details about this error.  Please report the problem
>  at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
> contents of this window into your report.
>
> java.lang.IllegalArgumentException
> at org.objectweb.asm.ByteVector.putUTF8(Unknown Source)
> at org.objectweb.asm.ClassWriter.newUTF8(Unknown Source)
> at org.objectweb.asm.ClassWriter.a(Unknown Source)
> at org.objectweb.asm.ClassWriter.newClass(Unknown Source)
> at org.objectweb.asm.ClassWriter.visit(Unknown Source)
> at org.nlogo.generate.Generator$InstructionGenerator.generate(Generator.scala:68)
> at org.nlogo.generate.Generator.org$nlogo$generate$Generator$$recurse(Generator.scala:28)
> at org.nlogo.generate.Generator.$anonfun$generate$1(Generator.scala:24)
> at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
> at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
> at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
> at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:193)
> at scala.collection.TraversableLike.map(TraversableLike.scala:234)
> at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
> at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:193)
> at org.nlogo.generate.Generator.generate(Generator.scala:24)
> at org.nlogo.compile.CompilerMain$.assembleProcedure(CompilerMain.scala:74)
> at org.nlogo.compile.CompilerMain$.$anonfun$compile$2(CompilerMain.scala:50)
> at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
> at scala.collection.immutable.List.foreach(List.scala:378)
> at scala.collection.TraversableLike.map(TraversableLike.scala:234)
> at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
> at scala.collection.immutable.List.map(List.scala:284)
> at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:50)
> at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:52)
> at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:203)
> at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:174)
> at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:138)
> at org.nlogo.window.Events$CompileAllEvent.beHandledBy(Events.java:185)
> at org.nlogo.window.Event.doRaise(Event.java:198)
> at org.nlogo.window.Event.raise(Event.java:122)
> at org.nlogo.app.codetab.CodeTab.compile(CodeTab.scala:134)
> at org.nlogo.app.codetab.CodeTab$CompileAction$.actionPerformed(CodeTab.scala:170)
> at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
> at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
> at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
> at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
> at java.awt.Component.processMouseEvent(Component.java:6533)
> at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
> at java.awt.Component.processEvent(Component.java:6298)
> at java.awt.Container.processEvent(Container.java:2236)
> at java.awt.Component.dispatchEventImpl(Component.java:4889)
> at java.awt.Container.dispatchEventImpl(Container.java:2294)
> at java.awt.Component.dispatchEvent(Component.java:4711)
> at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
> at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
> at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
> at java.awt.Container.dispatchEventImpl(Container.java:2280)
> at java.awt.Window.dispatchEventImpl(Window.java:2746)
> at java.awt.Component.dispatchEvent(Component.java:4711)
> at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
> at java.awt.EventQueue.access$500(EventQueue.java:97)
> at java.awt.EventQueue$3.run(EventQueue.java:709)
> at java.awt.EventQueue$3.run(EventQueue.java:703)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
> at java.awt.EventQueue$4.run(EventQueue.java:731)
> at java.awt.EventQueue$4.run(EventQueue.java:729)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
> at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
> at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
> at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
>
> NetLogo 6.0
> main: org.nlogo.app.AppFrame
> thread: AWT-EventQueue-0
> Java HotSpot(TM) 64-Bit Server VM 1.8.0_112 (Oracle Corporation; 1.8.0_112-b15)
> operating system: Windows 10 10.0 (amd64 processor)
>
> Scala version 2.12.1
> JOGL: (3D View not initialized)
> OpenGL Graphics: (3D View not initialized)
> model: PV+ California_v7
>
> 04:59:59.384 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
> 04:59:59.384 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
> 04:59:59.384 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
> 04:59:59.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
> 04:59:59.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
> 04:59:59.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
> 04:59:59.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
> 04:59:59.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
> 04:59:59.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
> 04:59:59.384 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

Some quick googling suggests that the problem here is a too-long classname. I need to investigate more, but I don't think we have any limit on the length of generated class names. It should be easy to just add that on. This wasn't an issue in 5.3.1 because our classes were named differently.

**Comment by marius89Zurich** [comment]
Hello,

I was able to solve that issue for my particular code. The problem was the following: 
For my I model need to read around 90 rows if input variables. The model reads the csv file and inserts all values into one variable (here: policy-mix-parameters-from-file). In a second step, I split this list into several list and give each of them a new name (see code). However, in NetLogo 6.0 this kin dof coding does not work as it does under 5.3.1. To make the model working again, I had to split the code into two parts, i.e., cut the foreach part into one from 1 - 40 and then from 41 - 90. Then it worked. It seems that there is some limit on words / commands that can be run under the foreach command. 

I think that is a major bug so far in NetLogo 6.0.

Best,
Marius


set line 0                                                                                     
  foreach policy-mix-parameters-from-file [ [x] -> 
    ifelse is-string? x [
      set line line + 1
      ][
        ifelse line = 1 [ set feed-in-remuneration-policy-off-scenario lput x feed-in-remuneration-policy-off-scenario ][
        ifelse line = 2 [ set feed-in-tariff-level-policy-off-scenario lput x feed-in-tariff-level-policy-off-scenario ][
....... (continue like this for further 80 rows)
