### ISSUE TITLE
Negative number of runs in BehaviorSpace

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1312]
If one naively creates way too many runs for an experiment it can show a negative number of runs:

![image](https://cloud.githubusercontent.com/assets/2138696/22853207/f96a2b3a-f08a-11e6-8b41-099412ef7279.png)

**Comment by mrerrormessage** [comment]
Thanks for reporting this. I think to fix this we will need to cap the number of runs at or below the range in which Java can use a `double` to represent an integer exactly.
