### ISSUE TITLE
6.0.1-M1 Regression: Bird breeders hubnet takes forever to open

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1325]
I believe the problem is that the modal dialog doesn't display while the widgets are loading (or perhaps just while they finish compilation). I'm not quite sure how to resolve this at the moment, but I think it was caused by changes to the UI loading code in 6.0. Also note that the HubNet control center should come up for Bird Breeders HubNet on open (but doesn't).

**Comment by TheBizzle** [comment]
This is a fun one.

Open a new model (can use "File => Recent Files" or `___`).  Even after the UI has finished loading for a model, there will sometimes be a delay before the UI can interacted with.  Sometimes, it's very brief; sometimes, it takes on the order of seconds for the UI to start responding to interactions.  There's absolutely no part of the UI that you can interact with during this—Command Center, widgets, the menu strip—all of them fail to react, until it eventually starts reacting, and then all of your actions play out at once, as if queued.

I've seen this happen with:

  * Wolf Sheep Predation
  * Slime
  * Bird Breeder
  * Fire
  * Flocking

I cannot, however, make it happen every single time, and, with some models, I can't get them to do it at all (e.g. Breed Procedures Example).  Bird Breeder is reliable is getting this to occur, and Bird Breeders HubNet seems to be the most egregious.  Opening that led to me having to wait a timed 34.xx seconds before the UI would respond.  I think there's a correlation with code length, but that's just a guess.

This behavior can't be reproduced in 5.3.1, but *is* reproducible in 6.0 and 6.0.1-M1.

My OS/desktop environment is Linux Mint 18 / Cinnamon 3.0.7 .

**Comment by mrerrormessage** [comment]
On further investigation, I have found I can get this to happen even on my mac book, but only when I open "Bird Breeders Hubnet" twice in a row! What seems to be happening is the following (for purposes of my description I'll assume that we're closing model A and opening model B). 

* Model B is read into NetLogo and the events in `ReconfigureWorkspaceUI` begin to fire
* The `LoadBeginEvent` reaches `WidgetPanel`, which causes it to `removeAllWidgets`
* Removing all widgets ends up calling `removeNotify` on each widget, which raises a `WidgetRemovedEvent`
* The `WidgetRemovedEvent`s are caught by `InterfacePanel`, which fires a `CompileAllEvent` (but delayed)
* Compilation finishes for the core of the model with the `LoadEndEvent`, which sets the `CompilerManager` to have `isLoading = false`
* The `CompileAllEvent`s triggered in step 4 are processed by Swing. Unfortunately, the`CompilerManager` doesn't skip full compilation due to loading because the model has finished loading
* Repeatedly running compilations in the foreground (in my tests, 10+ full compilations were being run on the second load of Bird Breeders HubNet) makes the UI unresponsive

Steps to solve this:

* Disentangle Swing UI concerns from NetLogo widget logic concerns. Widgets should have a well-defined lifecycle parallel to (but distinct from) the Swing component lifecyle. To this end, I propose removing all logic from the `removeNotify` and `addNotify` methods and creating the following methods on widgets which provide sensible hooks for behavior:
  * `create` - Called when a widget is explicitly created by the user
