### ISSUE TITLE
6.0.1-M1: Re-indenting moves cursor to end of line

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1328]
To reproduce:

Open a model. Place the cursor anywhere inside any line. Press "tab", "enter", or "]". The cursor will move to the end of the line (after inserting the corresponding character in the case of "enter" or "]").

**Comment by mrerrormessage** [comment]
The changes made to the indenter where indentation is now deletion + insertion probably caused this. Can/should be fixed alongside #1329 .
