### ISSUE TITLE
6.0.1-M1: Re-indenting adds the deletion of the current line to the undo history.

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1329]
To reproduce:

Open a model. Put the cursor in any line. Press "tab", "enter", or "]". Press the undo hotkey. The line will be deleted. Press the undo hotkey again to restore it.

**Comment by mrerrormessage** [comment]
The changes to the indenter delete the text and add in new text to replace it. This allows re-indentation to be done in a single operation. This operation should be packaged in such a way that Swing understands it as an atomic edit, even though it performs both a deletion and an insertion.
