### ISSUE TITLE
Globals not cleared from previous model in same instance

### ISSUE THREAD

**Issue by dougedmunds** [NetLogo/NetLogo#1334]
Version 6.0 on Windows 10 x64

I notice that the values of globals are not being set to 0 when a new model is opened
(before call in Setup to clear all).  For example,  create two models having one or more global variables names in common:

;identical files test1.nlogo and test2.nlogo
globals [g1 g2 g3]

to setup
  ca
  set g1 [ "dog" "cat" ]
  set g2 100
  set g3 true
end

to go
 set g1 lput "frog" g1
 set g2 g2 + 5
 set g3 not g3
end

a. Open test1.  Before running setup, use the observer, to "show g1".  It reports 0.
b. Run setup.  Use the observer to "show g1".  It reports ["dog" "cat"]
c.  In the same instance of NetLogo 6, using File>Open, open test2.
d. Before running setup, use the observer, to "show g1".  It reports ["dog" "cat"].
e. If 'go' is then run in test2, g1 will take on the value [ "dog" "cat" "frog"]

f. If you now reopen test1.nlogo, and use the observer to "show g1" it
will show a starting value of ["dog" "cat" "frog"]

Opening a new file should clear all values.  Version 6.0 does not. This worked properly in V 5.3.1.

**Comment by mrerrormessage** [comment]
Thanks for reporting! We've fixed this bug [here](https://github.com/NetLogo/NetLogo/issues/1284) and the fix will be included in the next release of NetLogo.
