### ISSUE TITLE
reduce documentation bug

### ISSUE THREAD

**Issue by dougedmunds** [NetLogo/NetLogo#1342]
Version 6.0 documentation for reduce has this example

     reduce [ [result-so-far next-item] -> fput result-so-far next-item ] (fput [] [1 2 3 4 5])
 
This generates a runtime error "FPUT expected input to be a list but got the number 1 instead." (referring to the first FPUT.

The corrected example should be: 

     reduce [ [result-so-far next-item] -> fput next-item result-so-far ] (fput [] [1 2 3 4 5])
     => [5 4 3 2 1]

Compare the code in version 5.3.1

      show reduce [fput ?2 ?1] (fput [] [1 2 3 4 5])
     => [5 4 3 2 1]

**Comment by mrerrormessage** [comment]
Thanks for reporting!
