### ISSUE TITLE
useless error report for dangling variables (enhancement request)

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#1354]
Consider the following broken code:

    to test
      let _x 2
      print "this" _x
    end

The syntax error reported is "Nothing named _x has been defined."

**Comment by mrerrormessage** [comment]
In 5.3.1 (and earlier), this error was reported as "Expected command". Due to the way NetLogo parses code, it's hard to get a more specific error than that. Do you consider that error sufficiently clear?

**Comment by alan-isaac** [comment]
Restoring that old behavior would be much better.  The current message is very confusing to students, who can see clearly that they defined the variable.  Thanks.
