### ISSUE TITLE
Offer option to start Behaviorspace run with "Update plots and monitors" disabled

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1359]

**Comment by nicolaspayette** [comment]
Maybe that was implicit in what @mrerrormessage already said, but I think the value of that property should be saved in the preferences like we already do for "spreadsheet" and "table" outputs in the same dialog:

https://github.com/NetLogo/NetLogo/blob/c56cffd5b12cf135efc4c3640b3cc0d5dc2acc3c/netlogo-gui/src/main/lab/gui/RunOptionsDialog.scala#L20
