### ISSUE TITLE
GoGo extension sometimes crashes on Mac OS X

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#136]
Corey Brady (@cbradyatinquire) writes:

>Our current state on 5.0 and 5.0.1 releases is that the GoGo monitor crashes on mac if you press Setup twice and it also crashes whenever you close the model or the software, if you have actually connected with a board.

**Comment by mrerrormessage** [comment]
@cbradyatinquire , is this still relevant given that we're now using gogo-hid?

**Comment by mrerrormessage** [comment]
I'm closing this as I'm pretty sure it isn't relevant to the gogo-hid extension.
