### ISSUE TITLE
netlogo-headless.sh references missing file NetLogo.jar

### ISSUE THREAD

**Issue by azric** [NetLogo/NetLogo#1361]
Fresh extract of tar file, NetLogo-6.0-64.tgz;
cd NetLogo\ 6.0
./netlogo-headless.sh
Error: Could not find or load main class org.nlogo.headless.Main

If I change the 
java -Xmx1024m -Dfile.encoding=UTF-8 -classpath app/NetLogo.jar org.nlogo.headless.Main "$@"
line in that script to
java -Xmx1024m -Dfile.encoding=UTF-8 -classpath app/netlogo-6.0.0.jar org.nlogo.headless.Main "$@"
then things work as expected.  Did I get a bad download?

**Comment by mrerrormessage** [comment]
Thanks for reporting! You did not get a bad download, this was a bug. Your change is correct and we will incorporate it into the next NetLogo release.
