### ISSUE TITLE
improve BehaviorSpace dialog location

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#1369]
The location of the BehaviorSpace dialog box is apparently not tied to the location of the NetLogo GUI.  It would be helpful if the dialog box were to initially open on top of the GUI.

**Comment by mrerrormessage** [comment]
Perfect fix for a new contributor. [This SO Post](https://stackoverflow.com/questions/1677318/java-swing-positioning-dialog-on-top-of-existing-window) covers how to do this in Swing. The fix should be able to be applied to [LabManager.show](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/lab/gui/LabManager.scala#L39).

**Comment by svr8** [comment]
I was trying to do the fix. I'm not noticing any significant GUI changes, am I choosing the right parent object ? I edited the line
https://github.com/NetLogo/NetLogo/blob/0f797196eadb86a27fd0f2f5b4c93b273cc73133/netlogo-gui/src/main/lab/gui/LabManager.scala#L39 to this:

def show() { 
dialog.update(); 
dialog.setVisible(true); 
dialog.setLocationRelativeTo(workspace.viewWidget)
}

**Comment by mrerrormessage** [comment]
The `LabManager` dialog is opened when choosing "Behaviorspace" from the "Tools" menu. The location should be set relative to the `Frame` contained in the workspace.

**Comment by Idloj** [comment]
We also have [this function](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/awt/Positioning.scala#L11) which is used in several locations.

**Comment by svr8** [comment]
Okay! I think adding one more statement should do the fix ?
Previous:
  ##https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/lab/gui/LabManager.scala#L39
New:
`def show() { 
     dialog.update(); 
     dialog.setVisible(true);
     dialog.setLocationRelativeTo(workspace.getFrame)
}`

**Comment by mrerrormessage** [comment]
If you have solved the problem, test your work and open a pull request for review.

**Comment by mrerrormessage** [comment]
Fixed in #1584
