### ISSUE TITLE
Should file selection dialogs on Linux use awt's FileDialog instead of swing's JFileChooser?

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#1375]
Currently, `org.nlogo.swing.FileDialog.show` uses JFileChooser in two cases: Linux and directory choosing.

Directory choosing uses JFileChooser because (as I understand it, anyway) then we can do `chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY)` to only show directories.

As for Linux, there is a [comment](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/swing/FileDialog.java#L61) about it:

    // On Linux:
    // 1) java.awt.FileDialog has a weird bug where it returns OK even
    //       if the user clicks the X on the dialog to cancel it.
    // 2) The AWT dialog looks unbelievably ugly, shows all the hidden files
    //  and folders in my HOME directory (and yes, there are a million),
    //  won't autocomplete names, won't let me start typing names to select files,
    //    and generally hates me as much as I hate it.
    // I suspect my Linux-specific code could replace all the Mac/Windows code below,
    // but that code already seems strangely more complicated than expected, so I decided
    // not to mess with it.  Probably it's just left-over cruft from a pre-JFileChooser era,
    // but I'm not sure.
    //  ~Forrest (6/8/2009)

1) If "returns OK" means that `getFile` returns a file and not `null` than that's no longer true.

2) (a) The GTK file dialog looks quite good, and is what used for all other non-Java applications
    (b) hidden files can be filtered out forcibly. Hidden directories can't be forcibly filtered out and their
         visibility is whatever the user decides, Ctrl+H for toggling in file dialog/manager, the default is to
         hide them.
    (c) It does autocomplete names (JFileChooser doesn't)
    (d) It does let you select files by starting typing

Here is a screenshot of awt FileDialog:

![screenshot from 2017-04-03 21-46-01](https://cloud.githubusercontent.com/assets/8083458/24625226/fe1c5c58-18b6-11e7-90ad-29e5c29f774f.png)

Here is a screenshot of swing JFileChooser with GTK l&f:

![screenshot from 2017-04-03 21-48-37](https://cloud.githubusercontent.com/assets/8083458/24625443/b39a2682-18b7-11e7-8eff-1c703d052e4a.png)

and with Nimbus l&f (that's what used by NetLogo on Linux, for me anyway) :
![screenshot from 2017-04-03 21-50-08](https://cloud.githubusercontent.com/assets/8083458/24625429/aafbd674-18b7-11e7-93dd-a5d2672787bb.png)

I want to change `org.nlogo.swing.FileDialog.show` to use native awt FileDialog for Linux too, and am opening this issue for discussion before making the change (there's going to be a PR anyway, because I converted the file to Scala and simplified the code - no behavior changes. I want to include this change in the PR if accepted)

Environment details:
Ubuntu 16.10 (I'm using LXDE and openbox as the de and wm, respectively)
No special configuration other than that, every Ubuntu uses gtk file dialog.

**Comment by mrerrormessage** [comment]
Do any of our linux users have strong preferences (or are you annoyed by the current status quo)? @TheBizzle @nicolaspayette ?

**Comment by TheBizzle** [comment]
I don't have a *strong* preference, but my weak preference is for my OS's provided file dialog to be used.

**Comment by nicolaspayette** [comment]
> I don't have a _strong_ preference, but my weak preference is for my OS's provided file dialog to be used.

Same for me.
