### ISSUE TITLE
Offer option to start Behaviorspace run with "Update plots and monitors" disabled

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1376]
For users with large models, it can be a pain to wait until a model loads to uncheck "update plots and monitors" in behaviorspace. We can add an option when starting a behaviorspace run to start with plots and monitors disabled.

This is an ideal fix for someone new to the project to make. Here are the steps involved:

* Add an additional boolean property in `RunOptionsDialog` which corresponds to "Disable view, plot and monitor updates"
* Add a property to `Supervisor.RunOptions` which corresponds to this.
* If the option is set, disable periodic updates and view updates in `Supervisor.start()` (see `ProgressDialog` for how this is done).

**Comment by nicolaspayette** [comment]
I think the value of that new property should be saved in the preferences like we already do for "spreadsheet" and "table" outputs in the same dialog:

https://github.com/NetLogo/NetLogo/blob/c56cffd5b12cf135efc4c3640b3cc0d5dc2acc3c/netlogo-gui/src/main/lab/gui/RunOptionsDialog.scala#L20

**Comment by LaCuneta** [comment]
This was competed in #1572 which went out with NetLogo 6.0.4.
