### ISSUE TITLE
updates documentation bug

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#1378]
In the section on <a href="https://ccl.northwestern.edu/netlogo/docs/programming.html#updates">View Updates</a>, the NetLogo <a href="https://ccl.northwestern.edu/netlogo/docs/programming.html">Programming Guide</a> states:

> Updating the view takes time, so if one update per tick is enough, 
> then enforcing there is only one update per tick will make your model faster. 

This is not generally true.  A good example is the Heroes and Cowards model in the NetLogo Models Library.

**Comment by SethTisue** [comment]
good point. it depends on how much computational work happens per tick. if a great deal of work happens per tick, then "one update per tick" will result in a speedup. if each tick does only a little work, requiring an update every tick may slow the model down, relative to so-called "continuous" updates.

**Comment by SethTisue** [comment]
related: #741. if that were implemented, you could have the best of both worlds: updates that only happen at tick time (and not at arbitrary times in between as with "continuous" updates), but more control over whether every tick must update or not.
