### ISSUE TITLE
link-neighbors are not cleared on `clear-links`

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1381]
In 6.0.1:

```
observer> crt 4
observer> ask turtle 0 [ create-link-with turtle 1 ] clear-links
observer> ask turtle 0 [ create-link-with turtle 2 ] clear-links
observer> ask turtle 0 [ create-link-with turtle 3 ] clear-links
observer> show [ link-neighbors ] of turtle 0
observer: (agentset, 3 turtles)
observer> show [ my-links ] of turtle 0
observer: (agentset, 0 links)
observer> ask links [ die ]
observer> show [ link-neighbors ] of turtle 0
observer: (agentset, 3 turtles)
```

Edit: Here's a one-liner to show it. Trying to fix now:

```
observer> crt 4 ask turtle 0 [ create-links-with other turtles ] clear-links show [ link-neighbors ] of turtle 0 show [ my-links ] of turtle 0
observer: (agentset, 3 turtles)
observer: (agentset, 0 links)
```

**Comment by SethTisue** [comment]
😱

**Comment by qiemem** [comment]
Yeup...

**Comment by qiemem** [comment]
Oh, the discrepancy between `link-neighbors` and `my-links` is due to the fact that the links are dead. Thus, `my-links` counts 0 living agents when determining its size.

Also, it's not quite as bad as I thought. The break is in `clear-links` specifically, not in link death in general. `clear-links` is wiping out the master link agentset before resetting the link manager. Woops. The link manager is what's responsible for getting the turtles to remove their links, but since the world's master linkset is already empty it doesn't do anything.
