### ISSUE TITLE
Benchmark mysteriously runs much too fast

### ISSUE THREAD

**Issue by mattsap** [NetLogo/NetLogo#1383]
I was able to get the benchmarking up and running due to Seth and Bryan's help. However, I wasn't able to get it to complete. I noticed the time to execute was getting larger, but my model's mean is staying the same.

See the bottom for my output. Essentially, the mean for running the model was .004 with a .001 std. What you'll notice is that the run number starts off with 2k runs being executed every 10 seconds, then dwindles down to 3 runs every 10 seconds. However, the mean and std are staying the same.

As seth pointed out, the logic is here: https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-headless/src/main/workspace/Benchmarker.scala

I don't know much Scala, but looked into the running time of some methods. According to [here](http://rnowling.github.io/software/engineering/2015/07/01/gotcha-scala-collections.html), size and appending to the end is expensive for list buffers. If you notice, these methods are called every iteration of the go once. I'm unsure, but I think the large amount of needed cycles with these expensive operations makes the benchmarking slow. 

This is my Execution Trace. For the record, the Fire benchmark is the one that is available online through http://ccl.northwestern.edu/netlogo/models/models/test/benchmarks/

> > headless/runMain org.nlogo.headless.HeadlessBenchmarker Fire
> [warn] Credentials file /Users/tnj/.bintray/.credentials does not exist
> [warn] Credentials file /Users/tnj/.bintray/.credentials does not exist
> [warn] Credentials file /Users/tnj/.bintray/.credentials does not exist
> [warn] compile:run::javaOptions will be ignored, compile:run::fork is set to false
> [info] Running org.nlogo.headless.HeadlessBenchmarker Fire
> @@@@@@ benchmarking NetLogo 6.0 (INTERIM DEVEL BUILD)
> @@@@@@ warmup 60 seconds, min 60 seconds, max 300 seconds
> (Fire Benchmark)
> 1/2 (mean=0.003, stddev=0.000)
> 2249/18199 (mean=0.004, stddev=0.001)
> 4602/17874 (mean=0.004, stddev=0.001)
> 6780/18524 (mean=0.004, stddev=0.001)
> 8928/17888 (mean=0.004, stddev=0.001)
> 11038/17819 (mean=0.004, stddev=0.001)
> 13114/17589 (mean=0.004, stddev=0.001)
> 15178/16949 (mean=0.004, stddev=0.001)
> 15963/16751 (mean=0.004, stddev=0.001)
> 15966/16755 (mean=0.004, stddev=0.001)
> 15969/16756 (mean=0.004, stddev=0.001)
> 15972/16753 (mean=0.004, stddev=0.001)
> 15975/16751 (mean=0.004, stddev=0.001)
> 15978/16752 (mean=0.004, stddev=0.001)
> 15981/16749 (mean=0.004, stddev=0.001)
> 15984/16758 (mean=0.004, stddev=0.001)
> 15987/16756 (mean=0.004, stddev=0.001)
> 15990/16783 (mean=0.004, stddev=0.001)
> 15993/16783 (mean=0.004, stddev=0.001)
> 15996/16792 (mean=0.004, stddev=0.001)
> 15999/16794 (mean=0.004, stddev=0.001)
> 16002/16867 (mean=0.004, stddev=0.001)
> 16005/16867 (mean=0.004, stddev=0.001)
> 16008/16864 (mean=0.004, stddev=0.001)
> 16011/16931 (mean=0.004, stddev=0.001)
> 16014/16939 (mean=0.004, stddev=0.001)
> 16017/16940 (mean=0.004, stddev=0.001)

**Comment by SethTisue** [comment]
here's a run I just did on my MacBook Pro, on the head of the hexy branch:

```
> headless/runMain org.nlogo.headless.HeadlessBenchmarker Fire
[warn] compile:run::javaOptions will be ignored, compile:run::fork is set to false
[info] Running org.nlogo.headless.HeadlessBenchmarker Fire
@@@@@@ benchmarking NetLogo 6.0 (INTERIM DEVEL BUILD)
@@@@@@ warmup 60 seconds, min 60 seconds, max 300 seconds
(Fire Benchmark)
1/2 (mean=0.167, stddev=0.000)
67/615 (mean=0.152, stddev=0.005)
132/630 (mean=0.152, stddev=0.005)
198/654 (mean=0.152, stddev=0.005)
264/686 (mean=0.152, stddev=0.005)
330/677 (mean=0.152, stddev=0.005)
396/698 (mean=0.152, stddev=0.005)
460/682 (mean=0.153, stddev=0.005)
523/679 (mean=0.153, stddev=0.005)
586/695 (mean=0.153, stddev=0.005)
648/671 (mean=0.153, stddev=0.005)
686/686 (mean=0.153, stddev=0.005)
@@@ Fire Benchmark: 0.153
```

if you're getting mean=0.004, something is wrong — your machine can't be 40 times faster than mine. I don't have a guess at what might be going wrong there.

**Comment by mattsap** [comment]
Oh, the the mean being so low is caused because I ramped down the number of repeats being executed in the model. But, this doesn't explain, why only 3 model runs are being executed in 10 seconds.  Maybe it's just because there were too many runs to iterate through because the scale was too small?

When I revert to the original Fire benchmark.nlogo, I go over my maximum limit, but the number of runs executed becomes more stable. Seems the standard deviation may be too high and the benchmarker want's more accurate results. I closed out all applications and shut the network off. I may just need to use another computer. 

```
(Fire2 Benchmark)
1/2 (mean=0.241, stddev=0.000)
47/7229 (mean=0.218, stddev=0.024)
92/11265 (mean=0.221, stddev=0.030)
135/16685 (mean=0.224, stddev=0.037)
169/38046 (mean=0.239, stddev=0.060)
211/32330 (mean=0.239, stddev=0.055)
248/32651 (mean=0.244, stddev=0.057)
295/30499 (mean=0.239, stddev=0.054)
340/33237 (mean=0.236, stddev=0.056)
390/32151 (mean=0.232, stddev=0.054)
443/32220 (mean=0.226, stddev=0.052)
496/31801 (mean=0.222, stddev=0.051)
548/30986 (mean=0.219, stddev=0.050)
600/30084 (mean=0.216, stddev=0.048)
651/29057 (mean=0.214, stddev=0.047)
702/28098 (mean=0.212, stddev=0.046)
752/27114 (mean=0.210, stddev=0.045)
802/26204 (mean=0.209, stddev=0.044)
851/25374 (mean=0.207, stddev=0.043)
899/24587 (mean=0.206, stddev=0.042)
946/23789 (mean=0.205, stddev=0.041)
992/23060 (mean=0.205, stddev=0.040)
1037/22372 (mean=0.204, stddev=0.039)
1081/21722 (mean=0.203, stddev=0.039)
1124/21156 (mean=0.203, stddev=0.038)
1166/20612 (mean=0.202, stddev=0.037)
1207/20125 (mean=0.202, stddev=0.037)
1246/19660 (mean=0.201, stddev=0.036)
1284/19214 (mean=0.201, stddev=0.036)
1319/18838 (mean=0.201, stddev=0.036)
1354/18461 (mean=0.200, stddev=0.035)
1389/18112 (mean=0.200, stddev=0.035)
1424/17758 (mean=0.200, stddev=0.034)
1457/17426 (mean=0.200, stddev=0.034)
1489/17132 (mean=0.199, stddev=0.034)
1506/16981 (mean=0.199, stddev=0.033)
@@@ Fire2 Benchmark: 0.199 (hit time limit)
[success] Total time: 418 s, completed Apr 12, 2017 11:55:06 AM
```

**Comment by SethTisue** [comment]
> Oh, the the mean being so low is caused because I ramped down the number of repeats being executed in the model

oh... the benchmark uses a millisecond-resolution timer (`System.currentTimeMillis`), so you can't do that. I guess it could be changed to use the nanosecond-resolution timer current JVMs offer, but I'd be hesitant to make that change because it might seem to promise something we can't really deliver without switching over to a JMH-based approach. if anything, I think it would be better for the benchmarked to print a warning anytime someone is trying to measure something that doesn't last at least a second or so, preferably in the neighborhood of 10 seconds. a lot of the iteration counts in the benchmarks were established a long time ago when machines were slower. they should be raised across the board, IMO

**Comment by SethTisue** [comment]
> Seems the standard deviation may be too high and the benchmarker want's more accurate results

agree. note the `max = 300`, which means it won't try again forever, it will stop after five minutes. at that point you could decide for yourself whether you think the standard deviation is low enough for your own purposes. `private val TOLERANCE = 0.003` is a very high bar; I set the bar that high at a time when I was trying to shave a percentage point here and a percentage point there off the model runtimes.

**Comment by mattsap** [comment]
I think it may be interesting/useful to have the threshold as an input to the bench marker if different people value different levels of precision. It could also be an optional argument. If it can wait, I can add it to the repository.

**Comment by SethTisue** [comment]
> it may be interesting/useful to have the threshold as an input to the bench marker

sure, there's no particular reason that isn't already configurable
