### ISSUE TITLE
Error when connection Netlogo 6.0.1 and R 3.3.3

### ISSUE THREAD

**Issue by elenanitodelbosque** [NetLogo/NetLogo#1388]
I am having problems using RNetlogo link

> Sys.setenv(NOAWT=1)     # to run RNetLogo in headless mode disable AWT before loading RNetlogo
> library(RNetLogo)
> setwd("/Applications/NetLogo 6.0.1/Java")
> nl.path <- getwd()
> NLStart(nl.path, gui=FALSE)
java.lang.NoClassDefFoundError: org/nlogo/workspace/Controllable
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
Caused by: java.lang.ClassNotFoundException
    at RJavaClassLoader.findClass(RJavaClassLoader.java:383)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    ... 2 more

> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.4

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RNetLogo_1.0-3 igraph_1.0.1   rJava_0.9-8   

loaded via a namespace (and not attached):
[1] magrittr_1.5 tools_3.3.3 

Can anyone help me solve the problem?

**Comment by mrerrormessage** [comment]
I don't know very much about rNetLogo, but have you tried setting `nl.path` to "/Applications/NetLogo 6.0.1/Java" and then `setwd(nl.path)`? Also, are you using NetLogo 6.0.1 32-bit or 64-bit?

**Comment by elenanitodelbosque** [comment]
Hi, I did try with setting working directory in the Java folder but I get the same error. Im using 64-bit.

**Comment by AseemAwad** [comment]
https://www.bountysource.com/issues/40837673-error-when-connecting-netlogo-6-0-and-r.

Check out the end of the thread. You have to tell R where to find a java component.

**Comment by mrerrormessage** [comment]
This has been inactive for several months and it seems that if it is a bug, it's an RNetLogo bug, not a NetLogo bug. Please contact the author of that library for further support or post on StackOverflow.
