### ISSUE TITLE
Clarify documentation regarding anonymous procedure optional syntax

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1391]
Bad example (illegal code) here: https://github.com/NetLogo/NetLogo/blob/hexy/autogen/docs/programming.html.mustache#L2874

It would be good to clarify which syntaxes are optional and when they are optional. I have made this table, which could serve as a template for such a clarification:
<img width="942" alt="screen shot 2017-05-01 at 8 43 42 am" src="https://cloud.githubusercontent.com/assets/143198/25580969/4aac65d8-2e4a-11e7-8ff5-fce1728cec84.png">

Further, it would be good to see if we can find a way to explain agentset context in blocks vs anonymous procedures. Blocks, of course, can and do change agentset context when run. Anonymous procedures do not. Explaining the concept of agentset context without scaring away beginners could prove a bit challenging, however.

**Comment by mrerrormessage** [comment]
@arthurhjorth @qiemem , do you have any feedback on whether the following table is helpful or confusing? Obviously this only needs to be understood by users who are comfortable with anonymous procedures, but more understandable is better. Appreciate any feedback you can offer either on style (my CSS game isn't great, and this has to go into the NetLogo User Manual) or substance (my writing tends toward the technical and esoteric).
<img width="1392" alt="screen shot 2017-05-24 at 4 12 58 pm" src="https://cloud.githubusercontent.com/assets/143198/26425863/f97daef6-409b-11e7-85dc-69121de24c0f.png">

**Comment by SethTisue** [comment]
we say "inputs" not "arguments"

**Comment by mrerrormessage** [comment]
Thanks Seth! I've updated:

<img width="1343" alt="screen shot 2017-05-25 at 8 04 50 am" src="https://cloud.githubusercontent.com/assets/143198/26451284/0b1223ec-4121-11e7-80b2-67998eab3b6a.png">
