### ISSUE TITLE
NetLogo 3D: Windows: turning off edge smoothing may cause crash

### ISSUE THREAD

**Issue by turtlemaniac** [NetLogo/NetLogo#140]
I opened netlogo 3d, turned off edge smoothing, right clicked view and netlogo closed itself. I can reproduce this.

NetLogo 3D 5.0.1 (April 12, 2012)
Extension API version: 5.0
Java HotSpot(TM) Server VM 1.6.0_30 (Sun Microsystems Inc.; 1.6.0_30-b12)
operating system: Windows XP 5.1 (x86 processor)
Scala version 2.9.1.final
Java heap: used = 16 MB, free = 22 MB, max = 494 MB

JOGL: 1.1.1
OpenGL graphics: Intel 945G
OpenGL version: 1.4.0 - Build 7.14.10.4926
OpenGL vendor: Intel

**Comment by mrerrormessage** [comment]
Closing due to age and JOGL upgrade. If you're still seeing this behavior, please comment and we'll reopen.
