### ISSUE TITLE
Numeric widgets can be made multiline when changed from String type

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#1402]
- Add a new String input, mark it Multi-Line and OK.
- Edit it and set the Type to Number.  "Multi-Line" goes grey but retains the check.  OK.
- The input now acts like a multi-line input, but still only accepts a single number value.  

I think the expected behavior would be that the numeric input continues to act as the "normal" single-line version even when the box is checked.  Or possibly that the multi-line value should auto-clear when type is changed to numeric (when saved and reloaded, the field is cleared for numerics).

**Comment by mrerrormessage** [comment]
Fixes for this will live in [InputBox.scala](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/window/InputBox.scala). Whether or not the `changeButton` is visible, which is controlled (in part) by whether the current `inputType` has `changeVisible`. The relevant lines are [multiline set](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/window/InputBox.scala#L91), [typeOptions set](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/window/InputBox.scala#L289) and overriding [`changeVisible`](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/window/InputBox.scala#L500) as appropriate.

**Comment by TheBizzle** [comment]
Fixed by [853af3a](https://github.com/NetLogo/NetLogo/pull/1724/commits/853af3a6f9700c2281d71a66f600251f6adbabd0)
