### ISSUE TITLE
missing dependencies from bintray

### ISSUE THREAD

**Issue by alee** [NetLogo/NetLogo#1406]
We are trying to run NetLogo programmatically using the instructions at https://github.com/NetLogo/NetLogo/wiki/Controlling-API - we are referencing the [bintray](https://bintray.com/netlogo/NetLogo-JVM/netlogo)  repository but ran into errors resolving dependencies for `org.jhotdraw` and `org.nlogo:parser:jar:0.1.1` - we found org.jhotdraw on SourceForge but are having trouble locating the parser package.

**Comment by mrerrormessage** [comment]
You need to depend intransitively on the netlogo jar, then add the dependencies separately:

In sbt, this looks like:

```scala
libraryDependencies ++= Seq(
"org.nlogo" % "netlogo" % "6.0.1" intransitive,
"org.picocontainer" % "picocontainer" % "2.13.6",
"org.ow2.asm" % "asm-all" % "5.0.3",
"org.scala-lang.modules" % "scala-parser-combinators_2.12" % "1.0.6",
"org.parboiled" %% "parboiled" % "2.1.4")
```

Syntax will differ, of course, depending on your build tool. If you want various other auxiliary features of NetLogo, you may need to add one or more of [these other libraries](https://github.com/NetLogo/NetLogo/blob/hexy/build.sbt#L129-L143).

If you run into further problems, please comment here and we can reopen the ticket if needed. 

See [here](https://github.com/NetLogo/NetLogo/issues/1398#issuecomment-302415322) for a related discussion.

**Comment by alee** [comment]
That worked. Thanks!
