### ISSUE TITLE
Using a `let` variable where a command is expected gives wrong error

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1447]
Example code:

```
to foo
  let bar 5
  bar
end
```

Gives the error `Nothing named BAR has been defined.` when it should be `Expected command.`

**Comment by Idloj** [comment]
Wasn't it fixed by https://github.com/NetLogo/NetLogo/commit/a479653e5312624655030ab0fd6f56e791cd0d33 ?

**Comment by qiemem** [comment]
Woops, didn't test in HEAD. Thanks @Idloj! Sorry about that!
