### ISSUE TITLE
Delete + Undo on plot widgets breaks them

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1450]
To reproduce:
* Create a plot widget (level of complexity unimportant)
* Delete it
* Undo the deletion
* Interact with the model in a way that would typically cause the plot to update itself, it will not respond.

This happens in 6.0 (where widget undo/redo was added) through HEAD (as of 7/10).

**Comment by LaCuneta** [comment]
We had [a duplicate issue](https://github.com/NetLogo/NetLogo/issues/1618) for this that was closed in the 6.1.0 release.
