### ISSUE TITLE
Save as NLW: Nothing named `RANGE` defined

### ISSUE THREAD

**Issue by bainco** [NetLogo/NetLogo#1470]
In 6.0.2-RC2, exporting a model that uses the `range` primitive using `Save as NetLogo Web...` and then opening the exported model results in an unknown primitive error:

![screen shot 2017-07-25 at 4 04 02 pm](https://user-images.githubusercontent.com/2212919/28594054-2f2f3f36-7154-11e7-8322-7a400dd21cf6.png)

Maybe an NLW version problem in the Save as functionality?

OS: MacOS 10.12.6

Attached: 
A zip of .nlogo and .html (NLW version) of a test model with range primitive
[range_test_NLW.zip](https://github.com/NetLogo/NetLogo/files/1174781/range_test_NLW.zip)

**Comment by LaCuneta** [comment]
I confirmed this was working in RC1, so it's likely that the NLW standalone page we updated in RC2 was actually an older version.

**Comment by mrerrormessage** [comment]
Thanks @LaCuneta . I can revert if needed.
