### ISSUE TITLE
 clear-all not clearing output area on Netlogo Web

### ISSUE THREAD

**Issue by klemensj** [NetLogo/NetLogo#1471]
Minor bug. "clear-all" function does not clear the output area on Netlogo web model, "clear-output" function has to be called independently in order to clear output area. 

Creating a model with code below shows the bug:

to setup
  clear-all
  ;clear-output
end 

to go
  output-print "test text"
end

Creating the netlogo web model with Netlogo 6.0.1 on OS X
The issue only occurs after the model is exported to Netlogo web
Error replicates on safari and chrome

**Comment by LaCuneta** [comment]
Hey @klemensj, thanks for reporting this and providing the details!  I've [created an issue](https://github.com/NetLogo/Tortoise/issues/195) to track it in the repository for the NetLogo Web code, where we'll put the fix.
