### ISSUE TITLE
Opening Agent Monitor Makes model "dirty"

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#1476]
To Reproduce:

* Open any NetLogo model
* Inspect an agent
* Attempt to quit or open a new model, NetLogo will act as though the model has changed even though no change has taken place

This isn't a major bug as it's fairly simple for a user to make a choice. However, it should be investigated and fixed. This isn't a regression (or at least not a recent one), I found the same behavior as far back as 5.2.

**Comment by Idloj** [comment]
Cause: AgentVarEditor (defined [in AgentMonitorEditor.scala](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/app/tools/AgentMonitorEditor.scala#L97)) extends `JobWidget`, which in turn extends `Widget`. `Widget` overrides `addNotify` (and similarly `removeNotify`) to, among other things, raise a `WidgetAddedEvent` which is caught by `DirtyMonitor` and marks our model as dirty. `addNotify` is a `JComponent` method which is called whenever the component (the widget in our case) is added to a container.
