### ISSUE TITLE
`export-world` has trailing comma in global variable names for some models

### ISSUE THREAD

**Issue by CamdenClark** [NetLogo/NetLogo#1479]
In the sample models, I can find that the following models
```
Hill Climbing Example
Simple Economy
Boiling
Tie System Example
Link Lattice Example
Link Breeds Example
```
are having the same bug, which is that there is an extra trailing comma in the global variable definition. For example, in Hill Climbing Example:

```
"GLOBALS"
"min-pxcor","max-pxcor","min-pycor","max-pycor","perspective","subject","nextIndex","directed-links","ticks",
"-40","40","-40","40","0","nobody","800","""NEITHER""","8"
```
Is the relevant section of what's returned when I call `export-world` in NetLogo Desktop. Note the trailing comma in the definition. Obviously a minor bug but might be worth checking out. I might try and bug squash this myself if I get a chance, but I don't understand why this is only happening for certain models, I don't know what these models have in common.

**Comment by mrerrormessage** [comment]
Thanks for reporting! This only happens in models with no global variables because [this line](https://github.com/NetLogo/NetLogo/blob/5.3.1/src/main/org/nlogo/agent/Exporter.scala#L114) should be conditional on whether there are any program globals.
