### ISSUE TITLE
Exporting different world

### ISSUE THREAD

**Issue by Rbhui** [NetLogo/NetLogo#1489]
Hi 

I have a model which was run for 7 months. Now in another same kind of model but added new rules, new variables, I imported the previous model (which was run for 7 months) and running the simulation. It is working fine but when I am exporting it, I can't. It is being partially exported I guess and showing me the error, I mentioned in the last issue. Please let me know what I should do.

Thank you.

**Comment by mrerrormessage** [comment]
Sorry, I meant to respond to your previous issue sooner. Since this is the same problem, we will handle it under that issue (https://github.com/NetLogo/NetLogo/issues/1486). Closing this one as duplicate.
