### ISSUE TITLE
Unable to run from Browser

### ISSUE THREAD

**Issue by Depue** [NetLogo/NetLogo#1494]
I've tried every browser but keep receiving "not working? read this" 
I have not seen anything that would lead me to a solution? 
Any incite would be much appreciated

**Comment by mrerrormessage** [comment]
Thanks for checking in about this. NetLogo doesn't support Java applets anymore. I've updated the pages on our site which used to have applets (and now display the warning "not working? read this") to reflect that. We recommend using [NetLogo web](https://netlogoweb.org/) instead. The vast majority of library models run on NetLogo Web and it supports all major browsers.
