### ISSUE TITLE
netlogo-headless.sh creates JAVA var, does not use

### ISSUE THREAD

**Issue by mtfurlan** [NetLogo/NetLogo#1501]
`netlogo-headless.sh` creates the `JAVA` variable, pointing to either the thing in `JAVA_HOME` or just `java`, but then the call uses `java` instead of `$JAVA`.
https://github.com/NetLogo/NetLogo/blob/hexy/dist/configuration/shared/linux/netlogo-headless.sh.mustache#L42

Doesn't affect me, just figured this was a typo.
Cheers

**Comment by mrerrormessage** [comment]
Nice catch. This should be fixed in the next release of NetLogo.
