### ISSUE TITLE
Input sliders reset to 0 if model is saved with coding errors

### ISSUE THREAD

**Issue by lscottmyers** [NetLogo/NetLogo#1502]
To replicate:
1. build a model with sliders or other numerical input devices on interface and set them to non-zero values
2. enter nonsense on code page like "start here" to remind yourself where to pick back up - hit the check arrow and you will get the error message indicating that phrase doesn't make sense.
3. save & close the model with the code error
4. re-open the model - all the numerical inputs on UI will be reset to 0

This seems to be new for 6.0 - I never got this on 5.x versions

**Comment by mrerrormessage** [comment]
I've confirmed this is an issue starting with NetLogo 6.0.2 (the behavior in 6.0, 6.0.1 appears to be the same as 5.3.1). Thanks for reporting!
