### ISSUE TITLE
Missing menu bar

### ISSUE THREAD

**Issue by Chriko2502** [NetLogo/NetLogo#1506]
Just downloaded NetLogo v6.0.2 for MacOS (High Sierra 10.13).
I noticed that the menu bar, which the documentation says should be existing (https://ccl.northwestern.edu/netlogo/docs/interface.html) is missing:
<img width="696" alt="menu bar missing" src="https://user-images.githubusercontent.com/16100090/31311268-f35bffaa-aba8-11e7-861c-dc43561b8cd8.png">

Did I do something wrong? Or is it a known issue?

**Comment by mrerrormessage** [comment]
Are you using the Sierra beta? One of our testers observed this problem in a beta version, but not in the released version of Sierra. A [similar bug](https://github.com/arduino/Arduino/issues/6548) indicates that this problem may appear if the system locale is set to something other than English. Is that the case for you?

**Comment by Chriko2502** [comment]
My system locale was/is German. Changing it to English fixed the problem. As a temporal workaround its ok, but it would be great if you could investigate/fix this problem so NetLogo is usable at any system with different default languages.

**Comment by mrerrormessage** [comment]
Thanks for checking. Obviously, we want NetLogo to work on all system locales. We will be investigating a fix for this problem. Stay tuned to this issue for further updates.

**Comment by nsteffens** [comment]
Hey there, you can fix it without changing your system language by executing this line in terminal:

`defaults write org.nlogo.NetLogo AppleLanguages '(en)'`

This should change the language specifically for this application to English.
Could fix this problem in High Sierra (publicly released version).

**Comment by rosuna72** [comment]
nsteffens...

Thank you SO MUCH!

**Comment by mrerrormessage** [comment]
Based on our testing, we *believe* that this issue has been corrected in 10.13.1 (final release, not in the beta releases). Please let us know if you have encountered in 10.13.1 and we'll investigate further.

**Comment by mrerrormessage** [comment]
This seems to have been fixed in 10.13.1. Closing.

**Comment by brunotamborero** [comment]
It's not fixed yet! I had to execute the command!
