### ISSUE TITLE
java.lang.NoClassDefFoundError: org/nlogo/generator/GeneratedCommand

### ISSUE THREAD

**Issue by romainreuillon** [NetLogo/NetLogo#1516]
Dear NetLogo devs,

in OpenMOLE we embed Netlogo headless. Since NetLogo version 6, we encounter "java.lang.NoClassDefFoundError: org/nlogo/generator/GeneratedCommand" exceptions. 

It seems that NetLogo 6 generates some bytecode. OpenMOLE is based on OSGi which implements its own classloaders. Is there some documentation on how NetLogo generates the bytecode and how I could tweek the netlogo headless workspace to make it generate a custom location (or to get the classloader where in which the classes is made available)?

cheers,
Romain

**Comment by romainreuillon** [comment]
Addenda: actually it happening with the NetLogo version 5.3

**Comment by mrerrormessage** [comment]
This is a great question. I don't know a lot about OSGi, so the information I'll offer here is general in nature. Please let me know if you need more specific information.

As a good troubleshooting step, NetLogo allows disabling the bytecode generator by setting the java system property `org.nlogo.noGenerator` to `true`. NetLogo runs with the same whether or not the bytecode generator is enabled (in fact, we run tests to ensure that the generated and non-generated versions give the same results). 

From a high level, NetLogo code generation works by using the ASM library to generate bytecode by effectively copying the methods on various primitives into a single large method which is then loaded and executed. The classes that are important to note here are [CustomClassLoader](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-core/src/main/generate/CustomClassLoader.scala) (which does the work of defining classes) and [Generator](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-core/src/main/generate/Generator.scala#L41). The linked line in Generator shows it being instantiated with `Thread.currentThread.getContextClassLoader` as its parent class loader. My understanding of the problem you are presenting suggests that the context class loader for the thread executing NetLogo is not the same classLoader used to load the various `org.nlogo` classes (the relevant class here being of course, `CustomCommand`). Note that while NetLogo does have a second thread (called "JobThread"), the generator will *usually* (but not always) run on whatever thread calls into the NetLogo workspace. It's likely that by setting the context class loader before compilation-triggering calls to NetLogo, it will be possible to compile and run the vast majority of NetLogo models correctly. Once the compilation-triggering calls to NetLogo are finished, you can set the context class loader back to whatever it was before.

So what about the cases where the generator *doesn't* run on the thread which calls into the NetLogo workspace? These are cases where `run` or `runresult` is called in the NetLogo model with a string as the argument and triggers compilation from the job thread. The job thread has a different `contextClassLoader` than the thread calling NetLogo. Specifically, the `contextClassLoader` of the NetLogo job thread will be the `contextClassLoader` of the thread which instantiated the `HeadlessWorkspace` at the time it instantiated `HeadlessWorkspace`. The easiest way to fix this is by setting the context class loader of the thread which creates `HeadlessWorkspace` to be the `ClassLoader` used to load the `org.nlogo` classes at the time that `HeadlessWorkspace` is created (it can be changed back afterwards).

Having typed all of this out, it's easy to see how this system would make it very difficult for people using OSGi or other tools which mess with the `ClassLoader` to successfully run NetLogo code. Please let us know whether you are able to get things working as I'm certainly open to improvements in this area if necessary.

**Comment by romainreuillon** [comment]
Thanks a lot, it was very help full. The bug seems to be fixed.

The here is how we create the workspace:
https://github.com/openmole/openmole/blob/dev/openmole/plugins/org.openmole.plugin.tool.netlogo5/src/main/java/org/openmole/plugin/tool/netlogo5/NetLogo5.java#L35

Here is how we execute the model:
https://github.com/openmole/openmole/blob/dev/openmole/plugins/org.openmole.plugin.task.netlogo/src/main/scala/org/openmole/plugin/task/netlogo/NetLogoTask.scala#L75

**Comment by mrerrormessage** [comment]
Glad to hear it's working! If you run into further problems, please don't hesitate to reach out.
