### ISSUE TITLE
Add Brazilian Portuguese Language

### ISSUE THREAD

**Issue by juliopw** [NetLogo/NetLogo#1519]
As an open educational platform, NetLogo must be accessible to most users. It would be great to have PT-BR among the supported languages. I translated most of the strings to Portuguese based on the Spanish strings file. This file is attached below. Thanks.
[GUI_Strings_pt.txt](https://github.com/NetLogo/NetLogo/files/1524082/GUI_Strings_pt.txt)

**Comment by mrerrormessage** [comment]
Thank you so much for contributing this! I'll look into integrating it next week and get back to you if I encounter any problems.

**Comment by juliopw** [comment]
Right now I'm fixing some incorrect translations and missing strings. I'll upload the final file here, along with the errors strings file.

I've noticed that the "*.properties" language files need to be formated in ANSI in order to be displayed by NetLogo. Is that correct?

Finally, thank you for your attention. Feel free to contact me at any time.

**Comment by mrerrormessage** [comment]
@juliopw , sorry, meant to get to this last week but didn't.

> I've noticed that the "*.properties" language files need to be formated in ANSI in order to be displayed by NetLogo. Is that correct?

That is correct. We have a special task in our build which does this, based on Oracle's [native2ascii](https://docs.oracle.com/javase/6/docs/technotes/tools/solaris/native2ascii.html).

Is the file in your previous comment in it's final form, or are you still working? Thanks again for looking at this.

**Comment by juliopw** [comment]
> sorry, meant to get to this last week but didn't.

Don't worry. I was translating the error file in the meantime.

> Is the file in your previous comment in it's final form

I think I've changed a few things in the file since I posted it earlier.

These are the final translation files for Portuguese.

[Errors_pt.txt](https://github.com/NetLogo/NetLogo/files/1553127/Errors_pt.txt)
[GUI_Strings_pt.txt](https://github.com/NetLogo/NetLogo/files/1553128/GUI_Strings_pt.txt)

I have noticed that at line 170 of the error file in English "Errors_en.txt" there is a = sign missing. I've fixed this in the translation. Is it supposed to be this way?

`170` `org.nlogo.prim._askconcurrent.onlyObserverCanAskAllTurtles only the observer can ASK the set of all turtles`

Thank you!

**Comment by mrerrormessage** [comment]
You're correct, the English version was a mistake. I'll try to integrate the translations and get back to you in a few days. Thanks again!

**Comment by mrerrormessage** [comment]
So, I've tried this out and it looks awesome! While I was going through and checking things out, I noticed a few keys which were not translated:

* common.messages.error.runtimeError
* edit.chooser.example
* edit.slider.minmax.message
* edit.monitor.precision
* edit.chooser.example
* error.dialog.outOfMemory.title
* tabs.run.widget.view.copy
* tabs.run.widget.view.export
* tabs.run.widget.view.inspectGlobals
* tools.agentMonitor.editor.noVariables
* tools.agentMonitor.window.globals
* tools.agentMonitor.view.watch
* tools.agentMonitor.view
* tools.agentMonitor.properties
* tools.previewPanel.runPreviewCommands

Many of these are for more obscure uses (like the title for the out-of-memory dialog) or cases where text may not be as important (the agent inspector and globals inspector). The existing translations are pretty much ready-to-go, so let me know whether or not you would like to add the above keys and we can move forward.

**Comment by juliopw** [comment]
You're right! those keys were missing. I have translated and included them. I've also compared it side by side with the [GUI_Strings_en.txt](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/project/autogen/i18n/GUI_Strings_en.txt) file and it looks like all keys are translated now. Here's the new file. 

Translated file: [GUI_Strings_pt.txt](https://github.com/NetLogo/NetLogo/files/1560574/GUI_Strings_pt.txt)

> Here is an exhaustive list of GUI keys that were missing.

Thanks for that. Made the job a lot easier! If there's anything else missing (including other files to translate) please let me know.

**Comment by mrerrormessage** [comment]
@juliopw , thanks for the update. Can you send me an email at robert _dot_ grider _at_ northwestern _dot_ edu and we'll discuss next steps in moving this forward? Thanks!

**Comment by juliopw** [comment]
@mrerrormessage ok, I've sent you an email. Thanks!
