### ISSUE TITLE
Find a bug in model : "File Input Example"

### ISSUE THREAD

**Issue by Jeremyymerej** [NetLogo/NetLogo#1520]
Found a bug in a model provided with NetLogo named "File Input Example". The author gives a skeleton of a procedure to write data inside a file. Unfortunatly, we have this error message when trying to execute the procedure "save-patch-data".

No file has been opened.
error while observer running FILE-WRITE
  called by procedure SAVE-PATCH-DATA
  called by Button 'save-patch-data'

I think it's a silly forget, a single line missing. You'll find a correction attach here.
I added "file-open file" and it work well.
[File Input Example.zip](https://github.com/NetLogo/NetLogo/files/1515632/File.Input.Example.zip)

Hope this helps futur Netlogo modeler :)

**Comment by bainco** [comment]
Thanks for reporting!

This has been fixed in NetLogo/models@815a0e9.

**Comment by mrerrormessage** [comment]
The updated model should be included in the next version of NetLogo. In the meantime, it can be accessed from the models repository. Closing.
