### ISSUE TITLE
NetLogo 3D Does Not Save System Dynamics Models to File

### ISSUE THREAD

**Issue by ptgrogan** [NetLogo/NetLogo#1523]
Greetings, I have unfortunately discovered that NetLogo 3D will not save System Dynamics components of a model to file. Steps to reproduce on 6.0.2:

1. Open NetLogo 3D
2. Open System Dynamics Modeler
3. Draw any model components (e.g. a stock named "test" with initial value 0)
4. Save to file
5. Close NetLogo 3D
6. Open saved file and System Dynamics Modeler -- there are no model components.

There appears to be no reference to the SD model components in the .nlogo3d file.

**Comment by mrerrormessage** [comment]
Thanks for reporting! This bug appears to have been introduced around 6.0. We're currently making some changes to the code that works with model saving / loading and we'll be sure to have a look at this.
