### ISSUE TITLE
System Dynamics Modeler Code Tab Does Not Fill Screen

### ISSUE THREAD

**Issue by ptgrogan** [NetLogo/NetLogo#1524]
The Code tab for the System Dynamics Modeler has a scroll pane to display generated code. However, it is set to a fixed height and width in the middle of the panel, causing difficulties reading long lines or long documents.

An improved display would be similar to the main NetLogo Code tab which stretches the scroll pane to fill the entire content area of the tab.

**Comment by mrerrormessage** [comment]
Thanks for reporting! We'll be looking into this.
