### ISSUE TITLE
Need a NLCommand that waits

### ISSUE THREAD

**Issue by jholderieath** [NetLogo/NetLogo#1538]
I have a model that has some commands that seem to take longer than `R` is willing to wait. I have resorted to inserting a `Sys.sleep` in `R`. Is there a better way? There are not any natural reporters to use a `dowhile`.

For example, I will call a command where my turtles go through a process of claiming territory and moving around. 
`RNetLogo::NLCommand("count_and_claim", nl.obj = nl_obj)`

This does not take a very long time, but is not quick either. When I ask for the territory held by one of the breeds 
`RNetLogo::NLGetPatches(sounderTerritoryStrength, patchset="patches", as.matrix=TRUE,
                                        as.data.frame=FALSE, patches.by.row=FALSE,
                                        as.vector=FALSE, nl.obj = nl_obj))`

The object will not be found if I do not insert a `Sys.sleep(2)` in R.
`Error in lapply(patch.var, function(x) { : 
  object 'sounderTerritoryStrength' not found `

**Comment by mrerrormessage** [comment]
Sorry, `RNetLogo` is not maintained by the CCL and we're unable to issue updates to that project. You may want to contact the author of that library and request their assistance.
