### ISSUE TITLE
The import org.nlogo cannot be resolved - Java Extension for NetLogo

### ISSUE THREAD

**Issue by SirAskALot31415** [NetLogo/NetLogo#1539]
Hello,

I have a little problem in Line 1-3 of the Java Code in Eclipse, trying to run this little example https://github.com/NetLogo/NetLogo/wiki/Extensions-API

Java Code:

1 import org.nlogo.api.*;
2 import org.nlogo.core.Syntax;
3 import org.nlogo.core.SyntaxJ;,

They all show the same error: "The import org.nlogo cannot be resolved"

I already found this issue (link below) but I still don't know what to do. What do I have to do to make the imports work? 
https://github.com/NetLogo/NetLogo/issues/1263

Thanks!

**Comment by mrerrormessage** [comment]
Add `netlogo-6.0.2.jar` (included with the NetLogo installation or [available for download on bintray](https://bintray.com/netlogo/NetLogo-JVM/netlogo/6.0.2)) to your classpath and you should see the errors resolve.

**Comment by SirAskALot31415** [comment]
Which classpath do you mean? To convert convert the .java files to .class files, I use this code from the example mentioned above:

"javac -classpath "C:\Program Files\NetLogo 6.0.2\app\netlogo-6.0.2.jar" -d classes src/IntegerList.java src/SampleExtension.java"

But that has nothing to do with the error in Eclipse, right?

**Comment by mrerrormessage** [comment]
I mean to ask whether you have added the netlogo jar to the "build path" (Eclipse's terminology, this is often called the compile classpath)? How to do this is detailed on [this page](https://www.techwalla.com/articles/how-to-set-the-classpath-in-eclipse) in the section about "Add JARs...".

**Comment by SirAskALot31415** [comment]
Yes, I just added the netlogo-6.0.2.jar to the the Projects Referenced Libraries but the errors are still there. Where is my fault?

**Comment by SirAskALot31415** [comment]
Well, i tried it with two different projects. One is working now with the .jar added to the Referenced Libraries, the other project still shows the same errors.

**Comment by SirAskALot31415** [comment]
Finally. Copied all the classes to a new project, where i added the netlogo-6.0.2.jar at first. Now its working, just in case someone has the same problem. Thanks for helping!!!
