### ISSUE TITLE
Install NetLogo in Linux from Terminal

### ISSUE THREAD

**Issue by plopezmp** [NetLogo/NetLogo#1548]
Hi,

I would like to know how I could download and install NetLogo using Linux Terminal only commands.

I have been doing a web search and found the wiki pages of this site but it seems there is only a procedure for Windows and for Mac OSX.

Thank you for your help

**Comment by mrerrormessage** [comment]
NetLogo for linux is distributed as a tar.gz. Installing it can be done with the following commands:

```
wget http://ccl.northwestern.edu/netlogo/6.0.2/NetLogo-6.0.2-64.tgz
tar -xzf NetLogo-6.0.2-64.tgz
```

The NetLogo installation will live in the newly created "NetLogo 6.0.2" directory.

**Comment by RuneKlarskovJensen** [comment]
Do you only start by using the script netlogo-headless.sh ?

when I unzip it I do not find any other shell script til start Netlogo with.

Best regards, Rune Klarskov Jensen
