### ISSUE TITLE
no error for set-current-directory "nonexistantFolder"

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#1554]
`set-current-directory` does not raise an error when given an invalid path.

**Comment by mrerrormessage** [comment]
> `set-current-directory` does not raise an error when given an invalid path.

I assume here "invalid" means a path to a directory that doesn't exist. I don't see a reason for `set-current-directory` to error when given a non-existent path for two reasons:

1. Raising an error if the directory doesn't exist provides no guarantees that the directory exists at the time it is actually used. That is, a user could set the directory and then delete the location where it points, meaning that file operations would error. In that scenario, the user will still need to check and respond to any errors when using `file-read` or `file-write` as `file-open` *itself* doesn't check whether the file exists (or even whether the directory in which the file is located exists).
2. The flip-side of (1) which precludes the possibility that the directory might be added between the time `set-current-directory` is created and file primitives are used. While we don't have documented functions which create directories, it's easy to imagine that an extension or some other tool might create a directory during the course of a model run. Forcing that to happen before `set-current-directory` seems unnecessary. 

From #1555:

> Finally, note that `set-current-directory` does not raise an error if given a bad path. This definitely should be considered a bug, as it implies that users may unintentional overwrite files, believing the current directory is different than actually it is.

It isn't clear to me what you mean by "a bad path" here. Do you mean a path that the user doesn't have write permissions to? At the moment, we don't even have `file-open` raise an error in this case. Even if we errored here, we have the same problems as with `set-current-directory` above.

We do permit users to overwrite files by using `file-delete` and `file-write`. These are fundamental primitives and I can't really see removing them from the language or substantially changing how they work. If there is concern about unintentionally overwriting files, NetLogo's current directory is set by opening a model, so a user can create an empty model in an empty directory, open that model, then experiment with file primitives in a known location (an approach suggested by Forrest on [this netlogo-devel thread](https://groups.google.com/forum/#!searchin/netlogo-devel/set-current-directory%7Csort:date/netlogo-devel/0olEflw3rWg/9IXe2aTC4isJ)).

As it is, I don't see a compelling reason to change the current behavior. If there's something I'm missing or haven't considered, please feel free to comment.

**Comment by alan-isaac** [comment]
Silent errors are a curse; please reconsider.
Consider a user with a current working directory, dir1.  The user enters `set-current-directory "./tmp"` to safely play around with writing and deleting files.  But if the subdirectory was really "temp" not "tmp", this will currently fail silently.  The user's experiments now endanger the files in dir1.
NetLogo is supposed to be student friendly.  This is unfriendly behavior.

**Comment by mrerrormessage** [comment]
I think there's some misunderstanding about how `set-current-directory` works. Assuming I have the following setup:

```
-+ Playground
   \
   + Test.nlogo
   + temp
```

When I open Test.nlogo and run the following commands:

```
set-current-directory "./tmp"
file-open "foo.txt"
file-write "abc"
```

I see the error "The file C:\Path\to\Playground\tmp\foo.txt cannot be found".

So at this point I see an error (the operation doesn't fail silently in it's entirety) and I'm not risking any other files in "Playground" because after `set-current-directory`, new files are located in "Playground/tmp". Is there a step I'm missing in this setup?

**Comment by alan-isaac** [comment]
No, you are correct; my example was bad.  Nevertheless, it is inevitable that allowing errors to pass silently will eventually produce some undesirable outcome, even if we do not see how now.  Here is another example, hopefully better constructed.  This time, the user uses the standard construction `carefully [file-delete "temp.txt"] []`.  (I teach this early in the semester.)  Now they are believe that there is no "temp.txt" in their target directory, but they are wrong.

Out of curiosity, what is an example of another application where a command that has a name suggesting that it actually sets the working directory has no OS-level consequences?  At the very least, the current behavior seems to involve a misnomer: maybe `set-working-directory-path` would be more descriptive.  I certainly did not deduce its behavior from the documentation.

**Comment by mrerrormessage** [comment]
Due to the complexity of the discussion, I'd like to take this off GitHub at this point. I'll email you and CC some other folks as well. Once we've determined an outcome, I can post here for posterity.

**Comment by alan-isaac** [comment]
Could you please point to the discussion of the costs and benefits of not informing students of their error in this case? Thanks!
