### ISSUE TITLE
`import-world` clears all current variable values

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/NetLogo#156]
This problem is unnoticeable in the normal `import-world` scenario, where data is imported for the same model from which the data was exported.  However, if you try to export variables from one model and import them into another, this will result in clearing even the variables for which no value is being imported (which certainly seems undesirable).

The source of this problem is the call to `clearAll` in `AbstractWorkspace.importWorld`.  However, the solution isn't as simple as just removing that method call.  Esther has commented that line of code with:

```
we need to clearAll before we import in case
extensions are hanging on to old data. ev 4/10/09
```

So we'll need to work something out there.

Reported by: Y.Chaouche (http://groups.yahoo.com/group/netlogo-users/message/14568)

**Comment by TheBizzle** [comment]
Looking back on this, I really don't believe it's a good idea to allow importing world states from different models.  There's just way too much complexity there.

TheBizzle giveth and TheBizzle taketh away.

**Comment by ychaouche** [comment]
Hi there,

I suggest that documentation should include at least a line about this behavior (the principal of least surprise).
