### ISSUE TITLE
standardize on "good first issue" and "help wanted" labels?

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#1563]
right now I see you have "quickfix", but "good first issue" (despite not having exactly the same range of connotations, of course...) is a GitHub standard these days, so is "help wanted"

(GitHub allows renaming existing labels)

(we're (gradually) standardizing on these in scala/* repos)

references: https://github.com/collections/choosing-projects, https://help.github.com/articles/helping-new-contributors-find-your-project-with-labels/

**Comment by mrerrormessage** [comment]
Thanks Seth! We've updated our labels!
