### ISSUE TITLE
Request simple compile-time type declaration and checking

### ISSUE THREAD

**Issue by RussAbbott** [NetLogo/NetLogo#1595]
As I said in issue #1590 I'm very impressed with the how far NetLogo has come. There are a number of improvements I'd like to see that I think would make it even better and more attractive.

By far the one I think would have the most impact would be a simple static type system. I've spent much too much time tracking down type errors that a simple type checker could identify instantly. (This happens, at least to me, when modifying code much more than when initially composing it.)

Currently NetLogo has 4 basic class-like types (Inspector, Turtle, Patch, and Link) and a number of subtypes, such as breeds and directed links. In addition, NetLogo supports lists. And it has some primitive types such as Number and String. All-in-all it's not a very complex type system. I would like two things.

- An ability to declare the types of variables and procedure parameters and return values and to have NetLogo check to see that they are used consistently with their types. 

- A means to declare list types in terms of the types of the elements a list may contain and for NetLogo to check to see that lists are used consistently with their declared types. 

The addition of these two features would make writing and debugging NetLogo code far easier and more enjoyable.

**Comment by SethTisue** [comment]
fwiw, I find it difficult to imagine this ever happening. (Somewhat sadly, since I'm in the static-typing camp myself these days.)

You can make the types optional in the hopes of making everyone happy, but making something optional splits the language in two and the community in two. I think it's very important for the goals of NetLogo to be a single language that everyone writes basically the same way, and the accumulated weight of both Logo tradition and NetLogo tradition is not to have types at all (aka "dynamic typing").

**Comment by mrerrormessage** [comment]
I agree with Seth.

Unfortunately, the philosophy of the NetLogo language and it's common use make static typing a major break from the language as it stands today. The implementation of these features would likely be both controversial (major differences of opinion about whether types should/must be declared, whether the type system should prevent all possible errors or only certain errors, etc) and technically difficult (requiring major compiler changes from the ground up). None of this is to say that the current NetLogo type-checker couldn't be improved in certain regards, but implementing this proposal is a major change that would mark something fundamentally different from the current NetLogo language.

**Comment by RussAbbott** [comment]
I am very disappointed that this and the square-brackets suggestion were dismissed. As I said, when I came back to NetLogo 6 and found it so much improved over NetLogo 4 I was greatly impressed. I thought that NetLogo was becoming a real programming environment. The work that went into NetLogo 6 established a very powerful foundation. But it didn't finish the job. As it stands NetLogo is still too painful to use for anything of any size and complexity. When I think of writing something new, I cringe. My students simply don't want to write NetLogo code because it is so painful. 

The NetLogo community could take the plunge and decide to make NetLogo a platform that supports real development. It already has so much to offer. But as it stands it just doesn't provide the support needed to encourage people who know how to write software to use it.

I hate to see it reach this point and go no further. Look how much progress has been made in the Web client-side world with Angular, React, and others. They are a break with the past. But sometime that's necessary. Our world is one of change. We can't resist it and stay relevant. Or to take an example relevant to Seth, look at Scala. If Martin Odersky has said we can't change Java that much, where would we be?

I believe changes such as I suggested can be made in a way that would not offend current users. WRT backward compatibility, the NetLogo community already bit that bullet and was willing to forgo backward compatibility at least once. Doing so was the right thing to do because otherwise the language would have been trapped by its history. 

So for the sake of NetLogo's future, I urge you to reconsider. Let people know that major positive changes are under way. They will appear in, say, version 7 (or even version 8), but they are coming. Allow people to prepare and get used to the changes. But let them know that the result will be a far more attractive and enjoyable development experience.

**Comment by mrerrormessage** [comment]
We do appreciate and try to consider user feedback. GitHub is great for discussing measurable, solvable issues and enhancements which fit neatly within the framework of the existing NetLogo language. For a number of reasons, we prefer to receive suggestions about larger language changes or philosophy via email (feedback@ccl.northwestern.edu). I have responded to this issue and the bracket issue openly based primarily on whether I think it feasible to implement them in NetLogo at the present time, not on their merits as ideas about language philosophy. I would encourage you to summarize this issue in an email and send it to the feedback address above as food-for-thought about the future direction of NetLogo.
