### ISSUE TITLE
Replace "[" and "]" in some uses to make NetLogo code easier to read and understand

### ISSUE THREAD

**Issue by RussAbbott** [NetLogo/NetLogo#1596]
Currently NetLogo uses square brackets for both lists and code blocks. Furthermore, code blocks are either command blocks or reporter blocks. So square brackets are used in three very distinct ways. I would like to request that each of these three uses of square brackets be given its own symbol. Here is how I would do it.

- Use square brackets `[ ... ]` for lists. This is very widespread and would be easily understood. In addition, this would presumably preclude the need for the explicit `(list ... )` notation. (I find it very irritating that I can write, for example, `[1 2 3]` but not `[a b c]` where `a` `b` and `c` are variables.)

- Uses braces `{ ... }` for command blocks. This is also consistent with widespread use and would be easily understood.

- Use angle brackets `< ... >` for reporter blocks. NetLogo is insistent on distinguishing command blocks from reporter blocks. Since this difference is so deeply embedded in the language, let's have different notations for each. Angle brackets come to mind since their pointedness might suggest a return value. But I'd be happy with anything that works and that distinguishes reporter blocks visually from lists and command blocks. As long as I'm talking about reporter blocks, I would like anything that would be valid code in a reporter to be valid in a reporter block. In particular, I'd like to be able to begin a reporter block with a `let`.  I would also like the ability to indicate reported values by using the reserved word `report`. That way reporter blocks could have multiple points of termination, each one of which reports a value.

**Comment by mrerrormessage** [comment]
While it's easy to see how this change would make it easier to disambiguate between the different types of nested structures in NetLogo models, this is simply too large of a change to make to the language. This change would affect virtually every NetLogo model and is both backwards incompatible (old models won't work in a new program) and forwards incompatible (new models won't work in an old program). The `task`-to-`->` shift was also quite major, but it actually affected a relatively limited set of models (those that used `task`) while leaving others untouched. Thanks for the suggestion, but I do not believe implementing this is feasible.

**Comment by SethTisue** [comment]
fwiw, I agree — somewhat sadly, since I'm in the static-typing camp these days.

**Comment by SethTisue** [comment]
fwiw, I agree, this ship sailed years ago. if we were starting over it would be good to consider making a radical break like this, a break with both Logo and NetLogo tradition, but we aren't starting over.
