### ISSUE TITLE
NetLogo 6.0.3 "no mountable files systems" installing from dmg file in MacOS 10.11.6

### ISSUE THREAD

**Issue by mars0i** [NetLogo/NetLogo#1599]
When I download the current 6.0.3 dmg file from the downloads page, MacOS El Capitan 10.11.6 reports that "The following disk images couldn't be opened" because the file contains "no mountable file systems".  I tried downloading it a second time, in case there was some sort of corruption the first time, but I got the same error.

**Comment by LaCuneta** [comment]
Thanks for reporting the error!  It looks like it may be an issue with the new file system Apple introduced on High Sierra where we built the release causing our packages to not be backwards compatible.  We'll try to get a fix released as soon as we are able.

Are you able to install [NetLogo 6.0.2](https://ccl.northwestern.edu/netlogo/6.0.2/) without any problems?

**Comment by mars0i** [comment]
I have installed 6.0.2 on my other MacOS 10.11.6 machine, so it should work on the one where I experienced the error.  I'll try it when I get back to that machine.

**Comment by mars0i** [comment]
I can confirm that I can install 6.0.2 but not 6.0.3 on both of my 10.11.6 machines.  Same error on both with 6.0.3.  
Thanks!

**Comment by LaCuneta** [comment]
@mars0i If you have a chance, can you try out [this package of 6.0.3](https://ccl.northwestern.edu/netlogo/6.0.3/NetLogo-6.0.3_EC.dmg)?  It worked on a regular-Sierra (non-High), but we don't have an El Capitan install to test it against.

**Comment by mars0i** [comment]
@LaCuneta, it worked perfectly.  Thank you.

**Comment by LaCuneta** [comment]
The updated El Capitan-friendly `dmg` is posted, so future downloads should not have this issue.

**Comment by mars0i** [comment]
Great--thanks.
