### ISSUE TITLE
NetLogo 6.0.3 fails to open on Windows 10

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#1603]
On certain version of Windows 10, NetLogo 6.0.3 fails to open, giving an error that it failed to find the library `C:\Program Files\NetLogo 6.0.3\runtime\bin\server\jvm.dll`.  This is very likely [this issue with Java 8](https://bugs.java.com/view_bug.do?bug_id=JDK-8191176).  It looks like it affects more versions of Windows 10 than just those listed in that issue.  I confirmed it on Windows 10 Pro 64 bit.  Our possible solutions are limited, but the best is to wait for 8u172 which should resolve this completely.  

I'm working on building NetLogo for Windows 10 on the pre-release of 8u172 so we can verify the fix will work.  Until 8u172 is in general release, our best workaround is to use the prior version of NetLogo, 6.0.2, on Windows 10 computers that encounter the problem.

**Comment by daimpi** [comment]
On my Windows 10 Pro 64-bit everything seems fine:
Windows Version: 1709
Windows Build: 16299.309

NetLogo 6.0.3 (March 19, 2018)
Extension API version: 6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_152 (Oracle Corporation; 1.8.0_152-b16)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.4
Java heap: used = 15 MB, free = 152 MB, max = 910 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

Hope this helps :)

**Comment by LaCuneta** [comment]
@daimpi That is helpful to know, thank you!  Oracle's docs aren't clear about the exact versions that are affected, or why.  I'm trying to get more info about the other known failing systems.

**Comment by daimpi** [comment]
Ok I got an update:

today I tried to install NetLogo 6.0.3 on a new Windows (Windows 10 Pro 64-bit) Laptop and the error you described above occurred. So I Installed NetLogo 6.0.2 to see whether this would work, and it did. Next I tried starting NetLogo 6.0.3 again, just in case and to my surprise it now also works. No Idea why that is, but as soon as I uninstall 6.0.2 the error resurfaces and when I re-install 6.0.2 the error is goes away and I can use 6.0.3 as normal.

**Comment by LaCuneta** [comment]
Thanks for the extra information, that's very helpful!  I'll take a look and see if that means we can correct this problem.

**Comment by LaCuneta** [comment]
I confirmed this behavior on the Windows 10 Pro VM that previously had the failure.  Installing 6.0.2 made 6.0.3 work, even after uninstalling 6.0.2 completely.  6.0.3 was using the correct bundled version of the JRE (8u152).  I've added this as a possible workaround to the Known Issues listing and will continue to investigate.

**Comment by pcoquill** [comment]
Same thing on my desktop with Windows 7 pro (64 bits) : failed to find jvm.dll. (netlogo 6.0.3).
But 6.0.4 works perfectly on my laptop Windows 10 pro (64 bits)

**Comment by LaCuneta** [comment]
@pcoquill Awesome, it's good to get confirmation the issue is resolved in 6.0.4!
