### ISSUE TITLE
release notes page hasn't been updated since 6.0

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#1605]
http://ccl.northwestern.edu/netlogo/oldversions.shtml says "see release notes for details on version differences" and links to https://github.com/NetLogo/NetLogo/wiki/Release-notes which hasn't been updated since December 2016

**Comment by LaCuneta** [comment]
I swapped the link on `oldversions.shtml` to go to http://ccl.northwestern.edu/netlogo/docs/versions.html, which is probably more appropriate for people visiting that page.  I'll work on updating the NetLogo Github wiki release notes updated with items after 6.0.

**Comment by LaCuneta** [comment]
I added dates, release notes links, and a link to the Github closed issues for each `6.0.x` release.
