### ISSUE TITLE
add `clear-globals` to the language

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#161]
all of the other components of `clear-all` have their own individual `clear-*` primitives

a typical use case is that you almost want to do `clear-all`, but you want to preserve some things, e.g. the contents of plots, so you have to do the `clear-*` dance one step at a time

requested by @toontalk

**Comment by SethTisue** [comment]
@mrerrormessage you might like to port this to hexy

**Comment by mrerrormessage** [comment]
targeting for hexy. This is a perfect ticket for any new contributors as it's well-defined and the code should be basically entirely the same.

**Comment by mrerrormessage** [comment]
This is already done on Hexy. Closing.
