### ISSUE TITLE
6.0.3 : `link a b` fails to look up some directed links with at least three link breeds and three turtles

### ISSUE THREAD

**Issue by asjadnaqvi** [NetLogo/NetLogo#1611]
Dear Netlogo team,

NetLogo 6.0.3 and 6.0.2 reporters are not finding directed links even though they exist and can be viewed on screen and inspected. The same code works perfectly well in 6.0.1.

The code breaks down all the time when 3 or more directed links are used. With 2 directed breads it sometimes works.

A sample code file is attached.

[example_report_directednetwork_error.zip](https://github.com/NetLogo/NetLogo/files/1924097/example_report_directednetwork_error.zip)

**Comment by qiemem** [comment]
Which reporters are not finding all the correct links? As far as I can tell, the model is behaving as expected in 6.0.3, and testing various link primitives, everything appears to be working, but I could be missing something.

Also, in this procedure:

```
to-report report-list2 [a]
  let templist []
  foreach a [ ?1 -> set templist lput [link-length] of link1 who ?1 templist ]
  report templist
end
```

Should the `foreach` line refer to `link2` rather than `link1`?

**Comment by asjadnaqvi** [comment]
E.g. in the above code, if i generate a random network with   "random-seed 180418"

and i write 
ask node 0 [show [link-length] of link who 1] i get the the Runtime Error window "OF expected input to be an agent or agentset but got NOBODY instead."

**Comment by qiemem** [comment]
Thanks for clarying! I've narrowed down the problem. I'll post minimal conditions soon. Happens pretty inconsistently (in the sense that I can detect any patterns yet).

FWIW, generally, I recommend avoiding using `who` numbers directly. Instead, to get a link from one turtle to another, you can do `[ out-link1-to another-turtle ] of some-turtle`.

**Comment by qiemem** [comment]
As far as I can tell, you need at least 3 link breeds and 3 turtles for this to happen. With 3 link breeds, it always happens with the link breed declared first. With 4 link breeds, it happens with the first and last declared link breeds. With 5 link breeds, it happens with the first and last 2 breeds. It seems to happen more frequently with the last 2.

Here's the code I've been testing with:

```
directed-link-breed [links1 link1]
directed-link-breed [links2 link2]
directed-link-breed [links3 link3]
directed-link-breed [links4 link4]
directed-link-breed [links5 link5]

to test [ n ]
  let seed new-seed
  random-seed seed
  ca
  crt n [
    create-links1-to other turtles
    create-links2-to other turtles
    create-links3-to other turtles
  ]
  let i 0
  foreach range count turtles [ a ->
    foreach range count turtles [ b ->
      foreach ["link1" "link2" "link3" "link4" "link5"] [ l ->
        if a != b [
          test-nobody seed (word l " " a " " b)
        ]
      ]
    ]
  ]
end

to test-nobody [ seed code ]
  if runresult code = nobody [
    print (word seed ": " code)
  ]
end
```

**Comment by qiemem** [comment]
Turned out the problem was that our link breed order comparison was broken for our link lookup. It can only occur when you have a bunch of different link breeds between the same turtles, so not too surprising it hadn't been caught till now.

**Comment by asjadnaqvi** [comment]
thanks for patching it up and pointing out to the new syntax!
