### ISSUE TITLE
section dividers vs terminators (documentation bug?)

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#1616]
https://github.com/NetLogo/NetLogo/wiki/File-(.nlogo)-and-Widget-Format  documents 12 sections, each terminated by `@#$#@#$#@`.  But in version 6, saved files have 11 sections, each terminated by `@#$#@#$#@`.  Presumably these are 11 "separators" and the final section is empty (as suggested by the docs).  Bottom line: the docs appear to erroneously include an extra `@#$#@#$#@`.

**Comment by LaCuneta** [comment]
Thank you for reporting that!  I've corrected the wiki page, it is 12 sections, but 11 dividers - there is no divider at the end of the last (empty) section.
