### ISSUE TITLE
__reload does not correctly reload included files

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#1617]
In NetLogo 6.0.3, if a syntax error is detected in a .nls file, I have to run `__reload` twice to correctly reload the source file.  The first time, I can see the changes I made (in an external editor), but the old error message still reappears.  If I immediately reload the model (a second time), then all is well.  (Very odd!)

**Comment by alan-isaac** [comment]
This is still present in 6.1.

**Comment by alan-isaac** [comment]
This is still present in 6.1.1.

**Comment by alan-isaac** [comment]
This is still present in 6.2, and now even worse. Reloading the model (say, `model1`) multiple time did not recompile its `.nls` source file. More bizarrely, if opened in the Code tab, the correct code displayed but was different (!!) than the compiled code used when running. Even more bizarrely, trying to force a full reload by opening an new NetLogo model and then reopening `model1` *still* did not force a recompile of the .nls file! Experimentation suggests that to force a recompile of the .nls file one must touch the file in NetLogo (by opening the code tab) and *then* reload the model.  This wasted 30 minutes today during a bug hunt. Please make fixing this a priority.

**Comment by brandesNW** [comment]
Related: #[1832](https://github.com/NetLogo/NetLogo/issues/1832)

**Comment by brandesNW** [comment]
The zip file has a model with instructions for reproducing 6 distinct bugs related to this problem.
[nls-save-models.zip](https://github.com/NetLogo/NetLogo/files/8383506/nls-save-models.zip)

**Comment by alan-isaac** [comment]
This problem is still present in NetLogo 6.4. If a .nls file with an error is fixed with an external editor, I have to use __reload twice for NetLogo to recognize that it has been fixed.

**Comment by brandesNW** [comment]
Fixed by https://github.com/NetLogo/NetLogo/pull/2286
