### ISSUE TITLE
SHA-256 changed for NetLogo 6.0.3

### ISSUE THREAD

**Issue by gtmgianni** [NetLogo/NetLogo#1625]
Hi guys,

The SHA-256 hash for version 6.0.3 of NetLogo's installer has changed. (the .dmg file you can download from https://ccl.northwestern.edu/netlogo/6.0.3/NetLogo-6.0.3.dmg)

[For the purpose of this pull request](https://github.com/caskroom/homebrew-cask/pull/47082), would a developer be able to confirm that this change was legitimate?

(confirmation is necessary due to [these Homebrew-Cask guidelines](https://github.com/caskroom/homebrew-cask/blob/077309dd91b7a8aaeab8661572429b42cef774da/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256))

Thanks in advance.

**Comment by LaCuneta** [comment]
@gtmgianni I can confirm the change is legit.  We had to re-package the macOS version of 6.0.3 to fix [this issue](https://github.com/NetLogo/NetLogo/issues/1599).  Thanks for checking.

**Comment by gtmgianni** [comment]
Thank you @LaCuneta.
