### ISSUE TITLE
extensions API: some extensions written in Scala may not compile against lite jar (missing ScalaSig attributes)

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#163]
to save space, we use ProGuard to strip ScalaSig attributes from NetLogo.jar. this may strip information needed by the Scala compiler to compile some kinds of Scala code.

for example, @nicolaspayette discovered in his network extension that the parts of code where he uses the implicit conversions in `api.ScalaConversions` don't compile against NetLogoLite.jar, while against NetLogo.jar net it works. that's because the ScalaSig attributes contain the information about which methods are implicit. you can see this by comparing the output of `scalap -classpath NetLogoLite.jar org.nlogo.api.ScalaConversions` to the output of `scalap -classpath NetLogo.jar org.nlogo.api.ScalaConversions` — the `implicit`s are gone.

Now, just because something is _compiled_ against NetLogo.jar doesn't necessarily mean it won't _run_ fine against NetLogoLite.jar, so this isn't a terrible problem, but it's nicer to get warned about problems at compile time then discover them later at runtime.

If you consider the compile time checking sufficiently important in your extension, you can always call the offending methods explicitly instead of having them filled in by the compiler, at the expense of some ugliness, or you can tweak the ProGuard config and build yourself an alternate lite jar that has ScalaSig stuff.

**Comment by Idloj** [comment]
Proguard is gone, isn't it?

**Comment by SethTisue** [comment]
yup, this is wontfix now that applets are going away
