### ISSUE TITLE
A workaround of "dpi / scaling / ui too small" problem of NetLogo in Linux system with hidpi monitor 

### ISSUE THREAD

**Issue by itsaquestion** [NetLogo/NetLogo#1638]
1. install jdk9 (I'm using Oracle JDK)
2. run NetLogo like this: 
`
bash -c 'export GDK_SCALE=2 && java -jar /PATH_OF_NETLOGO/netlogo-6.0.4.jar' &
`
3. enjoy!

**Comment by daimpi** [comment]
This might also be interesting for everyone following the original issue #1295

**Comment by SethTisue** [comment]
I've commented on #1295 with a link to here. closing this one. thanks @itsaquestion
