### ISSUE TITLE
movie primitives generate unreasonably large files

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#166]
on the MASON list, Sean Luke writes:

> JMF is an abandoned Sun project for generating and viewing media of all kinds, but primarily video.  Rather than produce Java versions of various video codecs, Sun decided to go the cheapo route and rely on "performance packs" -- their term for wrappers over native operating-system-specific codecs.  This was a dumb decision, since it wasn't portable in any way, and you had to rely on JMF being installed system-wide on your computer.
> 
> So anyway.  The jmf.jar file that MASON uses by default (see the libraries on the MASON website) has no "performance packs" at all.  It's pure Java, which means it can only write out with a single codec: Motion JPEG.  Motion JPEG is little more than a stream of JPEG images, and as you might imagine, it generates gigantic video files.
> 
> This is easily fixed though: just generate the movie, then load it into a decent video program (Quicktime or iMovie will do on the Mac, I can't speak to Windows) and save it out again under a good codec.  I suggest H.264, though Apple Animation makes better files in some situations.
> 
> [...] Because JMF is abandonware, you should never expect these to get fixed.  And there is no Java library I am aware of which can replace JMF realistically.  MASON, NetLogo, Processing, and Repast all have this issue.  But these are minor bugs that are easily worked around -- pump out the movie, then resave it as a different codec.

see also #165

**Comment by SethTisue** [comment]
note that not only are the files large, but they take an unreasonably long time to generate, too.

**Comment by Idloj** [comment]
Is https://github.com/artclarke/humble-video a good alternative to JMF?

**Comment by Idloj** [comment]
I believe this issue is not relevant now that the vid extension is used, is it?

**Comment by mrerrormessage** [comment]
@Idloj , correct, this issue is no longer relevant.
