### ISSUE TITLE
Comment in `__includes` prim causes strange behavior

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#1666]
If you have a model with code:

```
__includes ; here is a comment
[ 
  "foo.nls"
]
```

Add a corresponding `foo.nls` file, you'll see some odd behavior.  The `foo.nls` file will not show in the Included Files dropdown.  If you have multiple file names in the list, none will show in the dropdown.  This occurs on all platforms.

That's bad enough, but on Windows 10 (not on macOS, not sure on Linux) things get weirder, where if you open the `foo.nls` via the "Open Source File..." option, it'll be given the full path as its name, and changes to it will not be correctly detected or error-checked.  Once the main model is error-checked, if it finds a problem in the included file, it will popup a new `foo.nls` window (not the full path), so you'll have duplicate windows for the same file open.  

The workaround is to not have a comment between the `__includes` prim and the opening `[` for the file names list, so at least it's an easy fix.

**Comment by charlesres** [comment]
Bug has been fixed with latest commit.
