### ISSUE TITLE
DropBox of Documentation Section is messy

### ISSUE THREAD

**Issue by shivam3746** [NetLogo/NetLogo#1667]
The dropbox of documentation section looks messy in the netlogo main application  it can be enhanced in order to make it more user-friendly

**Comment by LaCuneta** [comment]
@shivam3746 Thanks for reporting this issue.  Do you have more information on which documentation section you're talking about?  How does it look messy?  Which version of NetLogo are you using and on which operating system?

**Comment by SethTisue** [comment]
a screen shot might be useful here

**Comment by shivam3746** [comment]
When user clicks on Documentation in the website of netlogo Dropbox appears in which a list appears which is looking messy because of no proper space b/w the list items . I think a proper bulleted list will solve the issue and will increase the UI unity of the website.

**Comment by LaCuneta** [comment]
@shivam3746 Can you send a link to the page that has the messy dropdown?  Or a screenshot would be great, too.

**Comment by shivam3746** [comment]
![dropbox](https://user-images.githubusercontent.com/25079911/45106336-07247880-b154-11e8-89b3-13e8e120e29f.png)

Talking about this dropdown

**Comment by LaCuneta** [comment]
I understand now!  That's the NetLogo Web software, this repository is for the NetLogo desktop software.  I'll make a note to add some spacing between those items in the [Galapagos repository](https://github.com/NetLogo/Galapagos).
