### ISSUE TITLE
Saving all tabs simultaneously

### ISSUE THREAD

**Issue by JusteRaimbault** [NetLogo/NetLogo#1669]
When doing a ctrl+S in the gui, only the current tab is currently saved (contrary to NetLogo 5 which saved all tabs) ; would it be possible to add this feature in NetLogo6 ?

**Comment by LaCuneta** [comment]
Thanks for pointing this out, I think it'd be a great feature to support.

**Comment by LaCuneta** [comment]
Found some related info in [a prior PR](https://github.com/NetLogo/NetLogo/pull/1215#issuecomment-268013684): 

> I would really prefer that we not show the "Save All" option unless __includes is active. It gives the perception that "Save" doesn't save some part of the model, which is only true when there are __includes files.
