### ISSUE TITLE
Slider data loss when opening models with errors

### ISSUE THREAD

**Issue by facorread** [NetLogo/NetLogo#1676]
**How to reproduce:**
New model
Create a slider with default values. As an example, name it `fifty` because its value is 50.
In the code tab, enter just one erroneous line, such as `grgrgr`
Save & close
Reopen
The error `keyword expected` is reported by NetLogo

**Expected behavior:**
Slider `fifty` should have the value 50.

**Actual behavior:**
Slider `Fifty` is never set to its value 50; it is set to 0. This error is silently ignored by NetLogo.

This error actually leads to data loss because the saved value of sliders is never recovered from the file; if the user saves the model, the invalid slider values "0" are saved to disk.

**Comment by LaCuneta** [comment]
@facorread Thanks for reporting this issue, we appreciate it.  It was [reported before](https://github.com/NetLogo/NetLogo/issues/1502), so I'm going to close this one as a duplicate.  It's on our radar to get fixed soon.
