### ISSUE TITLE
Plot Pen Case Sensitivity Auto-Conversion Too Sensitive

### ISSUE THREAD

**Issue by bainco** [NetLogo/NetLogo#1679]
In #1576 the auto-converter was updated to prevent plot & pen case sensitivity by implementing a renaming scheme for pens that were identical up to case insensitivity. However, it appears the auto-converter is _too_ sensitive as it will auto-convert pen names that are identical (up to case insensitivity) _*across*_ plots. 

This means that if you create a model (see attached) with two plots where:

1. Plot 1 has a single pen named `default`
2. Plot 2 has a single pen named `DEFAULT`

The model will save and run just fine, but when the model is reopened in NetLogo post 3ae13aa the auto-converter, following the rules from #1576, will rename the `DEFAULT` pen to `DEFAULT_1`. While this is not a breaking change, it is unnecessary.
 
[plot_pen_demo.nlogo.zip](https://github.com/NetLogo/NetLogo/files/2480316/plot_pen_demo.nlogo.zip)

**Comment by LaCuneta** [comment]
Attaching a different sample model:

[Duplicate pen names.nlogo.zip](https://github.com/NetLogo/NetLogo/files/2672465/Duplicate.pen.names.nlogo.zip)
