### ISSUE TITLE
Documentation: replace table:group-by with table:group-items in the example code.

### ISSUE THREAD

**Issue by mariopaolucci** [NetLogo/NetLogo#1682]
See https://ccl.northwestern.edu/netlogo/docs/table.html#table:group-items. 

```
observer> show table:group-by range 10 [ num -> num mod 3 ]
observer: {{table: [[0 [0 3 6 9]] [1 [1 4 7]] [2 [2 5 8]]]}}
```
should instead be 

```
observer> show table:group-items range 10 [ num -> num mod 3 ]
observer: {{table: [[0 [0 3 6 9]] [1 [1 4 7]] [2 [2 5 8]]]}}
````

**Comment by LaCuneta** [comment]
Thanks for reporting that, we'll get it fixed up.

**Comment by nicolaspayette** [comment]
Isn't it already fixed? :-)

https://github.com/NetLogo/Table-Extension/pull/10/files

--
Nicolas
(mobile)

**Comment by LaCuneta** [comment]
Forgot about that, nice!  Thanks again, Nicolas!
