### ISSUE TITLE
How to ask a  patch-set, which is called from a chooser (a string), to do something, say change pcolor?

### ISSUE THREAD

**Issue by Gorgali** [NetLogo/NetLogo#1687]
Hi everyone,
I want to ask a patch-set, which is called from a chooser (a string), to do something, say change pcolor.
In other words, I want to convert a string to a patch-set name.
I receive this error:
"PATCH-SET expected to be a patch agentset or patch but got the string "LCB" instead."
Could you please tell me how can I call a patch-set by a string?

Cheers,
Gorgali

**Comment by charlesres** [comment]
Hi Gorgali,

Thank you your question, unfortunately, the NetLogo issues section does not take modeling questions. There is a "netlogo-users" google group, which is a quick and easy way to ask modeling questions, if you need assistance with modeling in netlogo.
Link to the google-group : https://groups.google.com/forum/#!forum/netlogo-users
