### ISSUE TITLE
NetLogo not running on HPC cluster

### ISSUE THREAD

**Issue by samfux84** [NetLogo/NetLogo#1690]
Hi,

I tried to install NetLogo on our HPC cluster using the following instructions:

```
git clone https://github.com/NetLogo/NetLogo.git
mv NetLogo 6.0.4
cd 6.0.4
git checkout tags/6.0.4
git submodule update --init
./sbt all
```

I tried to run the resulting installation with the command sbt netlogo/run, which failed:

```
[sfux@eu-login-17-ng ~]$ module load new gcc/4.8.2 java/1.8.0_91 netlogo/6.0.4
[sfux@eu-login-17-ng ~]$ sbt netlogo/run
Picked up _JAVA_OPTIONS: -XX:ParallelGCThreads=1
[info] Loading project definition from /cluster/home/sfux/project
[info] Set current project to sfux (in build file:/cluster/home/sfux/)
[error] Expected ID character
[error] Not a valid command: netlogo
[error] Expected project ID
[error] Expected configuration
[error] Expected ':'
[error] Expected key
[error] Not a valid key: netlogo
[error] netlogo/run
[error]        ^
[sfux@eu-login-17-ng ~]$
```

Information about our HPC cluster:

```
[sfux@eu-login-17-ng ~]$ cat /etc/redhat-release 
CentOS Linux release 7.5.1804 (Core) 
[sfux@eu-login-17-ng ~]$ uname -a
Linux eu-login-17-ng 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Any idea why this is not working ?

Any help is appreciated.

Best regards

Sam

**Comment by LaCuneta** [comment]
Hey Sam, 

Thanks for reaching out about the issue you're having, and posting the detailed notes.  

My initial guess is that you're not running `sbt` with a working directory of the NetLogo repository.  `sbt` needs to run there to read the `build.sbt` and other configuration files.  Something like `cd netlogo/6.0.4; sbt netlogo/run` might work, depending on your filesystem layout.  Let me know if that helps or if you run into other issues.  

Can I ask where you got the HPC cluster instructions you followed?  Thanks!

**Comment by samfux84** [comment]
Hi LaCuneta,

Thank you for your reply.

I am managing the applications on our HPC cluster (ETH Zurich) and I got a request from some of our users to install NetLogo.

For installing the software, I was following the instructions on

https://github.com/NetLogo/NetLogo/wiki/Building

I adapted them a little bit, as I prefer to install releases (in this case a tag) rather than the master branch of a software because in the end, I create modules that the cluster users load.

**netlogo/6.0.4** is much more intuitive than **netlogo/8b3583ee1119016496eff9ee98237088a26261a2** (using a git commit tag). It is also easier for the users to compare different versions and to refer to a version when they publish some of their results if the versions are numbered.

> My initial guess is that you're not running sbt with a working directory of the NetLogo repository. sbt needs to run there to read the build.sbt and other configuration files.

This is correct. I tried to run it from my $HOME on the cluster. Is there any possibility to run it from anywhere and to specify some additional information like the path to the installation directory ?

After discussing the installation with the users that requested it, they proposed to use pyNetLogo as an interface to NetLogo. Using this, I could specify the installation directory of NetLogo:

netlogo = pyNetLogo.NetLogoLink(gui=False, netlogo_home="/cluster/apps/netlogo/6.0.4", netlogo_version="6")

I will ask our users to test if using pyNetLogo works for them.

Best regards

Sam

**Comment by SethTisue** [comment]
> Is there a reason you didn't go with a pre-compiled JAR file to run things?

seconded, normally there's really no reason to build NetLogo yourself

**Comment by samfux84** [comment]
We usually compile all software on the cluster to optimize them for our hardware in the cluster.

I got some feedback from our users that requested the installation of NetLogo. They can successfully use it through pyNetLogo. I think that for HPC clusters this is the preferred solution as it does not require to run within the installation directory.

**Comment by LaCuneta** [comment]
Thank you for the explanation!  Glad you got a solution that works on your cluster.

**Comment by SethTisue** [comment]
for the record (in case anyone else happens on this ticket), because NetLogo is JVM-based, there isn’t any benefit to compiling it on the same hardware it will run on, since no native code is produced, only platform-independent bytecode

**Comment by samfux84** [comment]
@SethTisue Thank you for your comment. I am also aware that compiling java code does not give any benefits. I was just not aware that NetLogo is pure java.
