### ISSUE TITLE
RNetLogo, JavaObject issue

### ISSUE THREAD

**Issue by plondonolarrea** [NetLogo/NetLogo#1694]
Hi, I'm new using RNetLogo. I was trying to apply a procedure from 

> Facilitating Parameter Estimation and Sensitivity Analysis of Agent-Based Models: A Cookbook Using NetLogo and R, Thiele 2014

In the code for Morris sensitivity analysis I have this:         
sim.results.morris <- apply(mo$X, 1, function(x) {simulate(param.set=x,                            
                              no.repeated.sim=no.repeated.sim, 
                              nl.obj=nl.sm13, trace.progress=trace.progress,
                              parameter.names=input.names, iter.length=iter.length,
                              function.name="Morris")}
                           )
That calls the function <simulate>, that is a R file in which it has:

    lapply(seq(1:length(parameter.names)), function(x) {NLCommand("set", parameter.names[x], param.set[x], nl.obj=nl.obj)})

But, when I run the code in Morris it says this error message:

[1] "Java-Object{This non-standard character is not allowed. at position 50 in }"
Error in NLCommand("set", parameter.names[x], param.set[x], nl.obj = nl.obj) : 

Does someone knows how it can be solved?

Thank you.

**Comment by charlesres** [comment]
@plondonolarrea Thanks for reporting this issue. The first thing that comes to mind is looking through your data and looking for non-standard characters, like tabs (\t) or \r. This often comes up with individuals using csv files or other file formats in RNetLogo. In the meantime, which version of RNetLogo and NetLogo are you using? Also, did you install RNetLogo for Windows or Mac? Any other information you can provide would be helpful. Thanks!

**Comment by plondonolarrea** [comment]
Hi @charlesres, thank you for your response. I'm using a NetLogo 6.0.4 and RNetLogo 1.0.4. My computer is Windows. I have my Java and JRE updated with the lastest  versions. 
I'm not using any .csv exports in the simulation. 
Actually, my code is based on the published, only minimal changes have been done:

require(RNetLogo)
set.seed(-402223867)
nl.path <- "C:\\Program Files\\NetLogo 6.0.4\\app
model.path  <- "C:\\Users\\Visitor\\Desktop\\SupplementalMaterial\\scripts\\SM2_Hoopoes2.nlogo"
simfun.path <- "C:\\Users\\Visitor\\Desktop\\SupplementalMaterial\\scripts\\simulation_function1.R"
input.values <- list(
               'scout-prob' = list(min = 0.0, max = 0.5),
               'survival-prob' = list(min = 0.95, max = 1.0),
               'scouting-survival' = list(min = 0.5, max = 1.0)
              )
morris.design <- list(type = "oat", levels = 5, grid.jump = 3)
no.repitions <- 10
output.names <- c("abundance","variation","vacancy")
no.repeated.sim <- 10
plot.on.screen <- TRUE
plot.3d <- FALSE
trace.progress = TRUE
nl.sm13 <- "nl.sm13"
nl.jarname <- "netlogo-6.0.4.jar"
NLStart(nl.path, nl.jarname=nl.jarname, gui=TRUE, nl.obj=nl.sm13)
NLLoadModel(model.path,nl.obj=nl.sm13)
source(file=simfun.path)
require(sensitivity)
already.processed <- 0  
input.names = names(input.values)
iter.length <- no.repitions * (length(input.values)+1)
mins <- sapply(seq(1,length(input.values)), function(i) {
		input.values[[i]]$min})
maxs <- sapply(seq(1,length(input.values)), function(i) {
		input.values[[i]]$max})
mo <- morris(model = NULL, factors = input.names, r = no.repitions, design = morris.design,
            binf = mins, bsup = maxs, scale=TRUE)
                                               
sim.results.morris <- apply(mo$X, 1, function(x) {simulate(param.set=x,                            
                              no.repeated.sim=no.repeated.sim, 
                              nl.obj=nl.sm13, trace.progress=trace.progress,
                              parameter.names=input.names, iter.length=iter.length,
                              function.name="Morris")}
                           )
if (plot.3d == TRUE) {
  require(rgl)
}
for (i in (1:length(sim.results.morris[,1])))
{
  tell(mo, sim.results.morris[i,])
  if (plot.on.screen == TRUE) {
    par(ask=TRUE)
  }
  if (plot.3d == TRUE) {
    plot3d.morris(mo)
  }
  else {
    plot(mo)
    title(main=output.names[i])
  }
}
for (i in (1:length(sim.results.morris[,1])))
{
  tell(mo, sim.results.morris[i,])
  mu <- apply(mo$ee, 2, mean)
  mu.star <- apply(mo$ee, 2, function(x) mean(abs(x)))
  sigma <- apply(mo$ee, 2, sd)
  
  if (plot.on.screen == TRUE) {
    par(ask=TRUE)
  }
  plot(mu.star, mu)
  if (plot.on.screen == TRUE) {
    par(ask=TRUE)
  }
  plot(mu.star, sigma)
}

And the function "simulate" is as follows:

simulate <- function(param.set, parameter.names, no.repeated.sim, nl.obj, trace.progress, iter.length, function.name) {
  # some security checks
  if (length(param.set) != length(parameter.names))
  { stop("Wrong length of param.set!") }
  if (no.repeated.sim <= 0)
  { stop("Number of repetitions must be > 0!") }
  if (length(parameter.names) <= 0)
  { stop("Length of parameter.names must be > 0!") }

  # an empty list to save the simulation results
  eval.values <- NULL

  # repeated simulations (to control stochasticity)
  for (i in 1:no.repeated.sim)
  {
    # create a random-seed for NetLogo from R, based on min/max of NetLogo's random seed
    # for NetLogo 4:
    #NLCommand("random-seed",runif(1,-9007199254740992,9007199254740992), nl.obj=nl.obj)
    # since NetLogo 5:
    NLCommand("random-seed",runif(1,-2147483648,2147483647), nl.obj=nl.obj)
    
    # TODO: adapt the following to your simulation model
    # This is the stuff for one simulation
    NLCommand("setup", nl.obj=nl.obj)

    # set NetLogo parameters to current parameter values
    lapply(seq(1:length(parameter.names)), function(x) {NLCommand("set ",parameter.names[x], param.set[x], nl.obj=nl.obj)})

    # run simulation
    # TODO: adapt to your simulation process
    # two warm-up years (12 months each)
    NLDoCommand(2,"repeat 12 [go]", nl.obj=nl.obj)
    # here: run 20 x 1 year (=12 months) and get results from month 11 (november) as calibration criterion
    cal.crit <- NLDoReport(20,"repeat 12 [go]",c("year","month-11-count","month-11-alpha"), as.data.frame=T, df.col.names=c("year","abund","alpha"), nl.obj=nl.obj)

    # TODO: adapt to your calibration criteria
    # number of patches (for calculation of percentage)
    patches.count <- NLReport("count patches", nl.obj=nl.obj)

    # calculate calibration criteria
    # mean abundance criterion
    abundance.criterion <- mean(cal.crit$abund)
    # variation criterion
    variation.criterion <- sd(cal.crit$abund)
    # vacancy criterion
    vacancy.criterion <- mean(cal.crit$alpha/patches.count)

    # merge calibration criteria
    calibration.criteria <- c(abundance.criterion,variation.criterion,vacancy.criterion)

    # append to former results
    eval.values <- rbind(eval.values,calibration.criteria)
  }

  # print the progress if requested
  if (trace.progress == TRUE)
  {
    already.processed <- get("already.processed",env=globalenv()) + 1
    assign("already.processed", already.processed, env=globalenv())
    print(paste("processed (",function.name,"): ", already.processed / iter.length * 100, "%", sep = ""))
  }

  # return the mean of the repeated simulation results
  if (no.repeated.sim > 1)
  {
    return(colMeans(eval.values))
  }
  else {
    return(eval.values)
  }
}

Thanks for your help

**Comment by charlesres** [comment]
Awesome! I was able to reproduce the error.

    [1] "Java-Object{This non-standard character is not allowed. at position 51 in }"
    Error in NLCommand("set ", parameter.names[x], param.set[x], nl.obj = nl.obj) :

For now, I'll look through it.

**Comment by plondonolarrea** [comment]
@charlesres It helps me a lot!... Awesome!. Thank you so much
