### ISSUE TITLE
NetLogo 6.0.4 wont start up on ubuntu 18.04

### ISSUE THREAD

**Issue by foufa89** [NetLogo/NetLogo#1695]
hi! 
I had installed NetLogo 6.0.4 (64 bits) on a machine with ubuntu 18.04 server system (64 bits) 
when I try to start it with a double click it doesn't start 
I tried to start it from a terminal and this message appears :

"The format of this file is the same as for the corresponding file of the X Window System, which normally can be found in /usr/lib/X11/locale/libpackager.so not found."

**Comment by foufa89** [comment]
Hi, 
thank you @charlesres  for your reply, 
I am a beginner user of Linux; I have tried to change `JRE_HOME` and` JAVA_HOME` variables in `.bashrc` file 
`JAVA_HOME=/usr/lib/java/jdk1.8.0_191`
`JRE_HOME=/usr/lib/java/jdk1.8.0_191/jre`
`export PATH= $JAVA_HOME/bin:$PATH`
`export PATH=$JRE_HOME/bin:$PATH`

**Comment by charlesres** [comment]
Hi,
For the JAVA_HOME and JRE_HOME paths, how did you install the JDK, (tar.gz or apt-get) and are you using the downloaded NetLogo version on the NetLogo website? There might be an issue with the paths in the JDK and NetLogo.

One more thing, could you post your output for
`    $ sudo update-alternatives --get-selections | grep ^java `

**Comment by foufa89** [comment]
Hi, I had installed it using tar.gz 
But, I have removed the installed java and reinstall it using these commands :
`sudo add-apt-repository ppa:webupd8team/java`
`sudo apt-get update`
`sudo apt-get install oracle-java8-installer`
`sudo apt install oracle-java8-set-default`

Now it works :) 
Thank you @charlesres
