### ISSUE TITLE
Error: java program that starts the full NetLogo application

### ISSUE THREAD

**Issue by gabyjoehn** [NetLogo/NetLogo#1700]
Hello,

I am trying to compile and run the very first Example (with GUI) on the following link: https://github.com/NetLogo/NetLogo/wiki/Controlling-API#example-with-gui 

I am doing the following on terminal in Mac OS X: 
**javac -cp Java/netlogo-6.0.2.jar Example1.java
java -cp Java/netlogo-6.0.2.jar Example1

Error: Could not find or load main class Example1
Caused by: java.lang.ClassNotFoundException: Example1**

Please advise!

**Comment by gabyjoehn** [comment]
#

**Comment by SethTisue** [comment]
when you don't give the `java` command an explicit classpath, it includes the current directory by default

if you *do* give an explicit classpath, you must include `.` if you want it. so try this: `java -cp .:Java/netlogo-6.0.2.jar Example1`

**Comment by SethTisue** [comment]
note that questions like this are better on https://groups.google.com/forum/#!forum/netlogo-devel than here in the issue tracker

**Comment by gabyjoehn** [comment]
Thank you!
