### ISSUE TITLE
"Expected nlogo file to have 12 sections, this had 10." Error

### ISSUE THREAD

**Issue by betheltarekegne** [NetLogo/NetLogo#1705]
I downloaded the Babster model from NetLogo Modeling Commons, but the download keeps generating an error and whey I try to run the model in NetLogo I keep receiving the following: 
"NetLogo can't open the model"
"Expected nlogo file to have 12 sections, this had 10."

I have previously downloaded the model on my Mac and it works fine. This is an error on a Windows 10 desktop computer. 

Would anyone be able to help in what might be causing this error?

Thank you!

**Comment by charlesres** [comment]
Hi @betheltarekegne. Thanks for reporting this issue. Could you provide the NetLogo version you are using for the model, along with the source code you have so far? Since the model was written in NetLogo 5.2, this may be an issue with different NetLogo versions being used to save and load the model.

**Comment by charlesres** [comment]
Since you are having some issues with downloading the model, I've provided a gist of the Babster model source code. This should contain 12 sections, so let me know if NetLogo still recognizes 10 sections on Windows 10.

**Comment by betheltarekegne** [comment]
@charlesres thank you for your help. It says it has 11 now. Thanks in advance for all your help on this!

**Comment by charlesres** [comment]
@betheltarekegne After trying out Babster.nlogo on Windows 10, it seems like it could be an issue with the way NetLogo files are represented in Windows 10. Here is a gist with an updated version of babster with newlines at the end of the file.
https://gist.github.com/charlesres/df71ad0b1d920223c42903c3b1e28b38
It seems like adding the newlines at the end of the document help with reading the final section.
