### ISSUE TITLE
netlogobuild has expired certificate

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#1708]
over at #1707 when I tried to view the CI results I got:

<img width="591" alt="screen shot 2019-02-04 at 11 20 52 am" src="https://user-images.githubusercontent.com/161079/52231548-1b89b000-286f-11e9-9ccb-c62b05e2bd9a.png">

**Comment by LaCuneta** [comment]
Updated the cert to be valid and current, should be good to go now.
