### ISSUE TITLE
Primitive for reporting output

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/NetLogo#1717]
The output area often functions as a convenient buffer that you write stuff to that happens as your model runs, or while students interact with it. Currently it is only possible to save it by using the 'export-output' primitive. It would be pretty great if there was a way to get the output text as a string so it would be possible to save it to a variable.

My use case is that students do stuff in a model that is reflected as text (so they more easily remember what they said or did) and I want to show them what they said and did later on. Currently I have to write the output contents to a file, then open and read that file, and close it. Given how easy I imagine it would be to just report it rather than write it to a file, this feels like low hanging fruit. Though maybe my use case is so unusual that it isn't worth it... :)

**Comment by TheBizzle** [comment]
This was actually something that had already been on my list.

So... users of NetLogo 6.1.0-RC1 and later can now find [the Export-The extension](https://github.com/NetLogo/ExportThe-Extension#readme) listed in the Extensions Manager.  It includes the primitive `export-the:output`, which does exactly what was requested here.

I'm not sure that that precludes adding it as a standard language primitive or not, but at least there now is/soon will be a workaround for this, by way of the Export-The extension.

**Comment by arthurhjorth** [comment]
That's awesome, @TheBizzle ! Thanks so much! I'm happy to close this (or to let you do that) since I'm in favor of letting a primitive like this live in an extension rather than in the core.
