### ISSUE TITLE
Bug (or bugs) in documentation for layout-tutte

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#1725]
http://ccl.northwestern.edu/netlogo/docs/dictionary.html#layout-tutte says

```
to make-a-tree
  set-default-shape turtles "circle"
  crt 6
  ask turtle 0 [
    create-link-with turtle 1
    create-link-with turtle 2
    create-link-with turtle 3
  ]
  ask turtle 1 [
    create-link-with turtle 4
    create-link-with turtle 5
  ]
  ; place all the turtles with just one
  ; neighbor on the perimeter of a circle
  ; and then place the remaining turtles inside
  ; this circle, spread between their neighbors.
  repeat 10 [ layout-tutte (turtles with [link-neighbors = 1]) links 12 ]
end
```

But clearly `link-neighbors = 1` is always false. I assume it should be `count link-neighbors = 1`

But all I see then are 3 nodes on top of each other forming a line with 3 other nodes on top of each other.

Also a radius of 12 for the default world size causes the link to wrap around which isn't wrong but is confusing.

**Comment by LaCuneta** [comment]
Confirmed, I'll get this cleaned up.
