### ISSUE TITLE
The jump to procedure menu sometimes doesn't properly erase items/resize

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#1732]
Found on 6.1.0-RC1 in Linux.

![Screenshot from 2019-04-03 08-52-49](https://user-images.githubusercontent.com/28215/55493568-08385e00-55ee-11e9-92dc-a2067a52486a.png)

**Comment by charlesres** [comment]
Thanks for submitting a report, @qiemem. Perhaps this behavior has something to do with how procedures are stored and filtered with jump. It's odd that the other procedures, also, appear.

**Comment by qiemem** [comment]
I'm pretty sure it's actually a redraw issue. The items aren't actually highlightable or clickable. There's also a related issue where sometimes when you delete characters, the menu doesn't re-extend properly. That is, when you have this:

![Screenshot from 2019-04-03 09-08-27](https://user-images.githubusercontent.com/28215/55494694-1dae8780-55f0-11e9-9b09-b620cb3d23b4.png)

And then you delete the character:

![Screenshot from 2019-04-03 09-08-35](https://user-images.githubusercontent.com/28215/55494713-269f5900-55f0-11e9-8bc5-b27a6568f27d.png)

My guess is that swing is redrawing a smaller rect than it actually needs to redraw.

**Comment by LaCuneta** [comment]
I've been unable to reproduce on macOS, so that does point towards this being some sort of Swing repainting issue on Linux

**Comment by qiemem** [comment]
Confirmed not to happen on macos. So I'm guessing the problem is here: https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/app/codetab/ProceduresMenu.scala#L52-L55

This SO answer might be worth playing around with: https://stackoverflow.com/questions/1097366/java-swing-revalidate-vs-repaint. I had it issuing a validate and then resize, but probably need a repaint in there too.
