### ISSUE TITLE
__includes with full path fails on Mac

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#1734]
I do not have access to a Mac, so I will do my best to report a problem encountered by my students, who use 6.0.4.  This only affected Mac users.  My students store some .nls files I give them in a specific location.  If they try to use `__includes` with a full path, starting with a tilde for their home directory, NetLogo fails to find the files.  (I checked that the paths they were using were correct.)  Is this a known issue?

**Comment by charlesres** [comment]
@alan-isaac, thanks for submitting a report. With paths to .nls files, paths that are accepted are absolute paths ("/home/user/netlogo.nls") or relative paths ("./netlogo.nls"). I don't believe NetLogo expands tildas to the home directory, unlike bash and other terminals, which could be the issue you are having. A workaround would be to provide the path as mentioned above.

**Comment by SethTisue** [comment]
that sounds plausible. `~` is Unix shell syntax, it doesn't exist at either the JVM level or the OS level

**Comment by qiemem** [comment]
@charlesres you are correct; this is a common issue in Java path handling. Given the ubiquity of using `~` in *nix, it might be worth handling.

Here's a variety of possible solutions: https://stackoverflow.com/questions/7163364/how-to-handle-in-file-paths

**Comment by brandesNW** [comment]
fixed by https://github.com/NetLogo/NetLogo/pull/2282
