### ISSUE TITLE
Don´t find extensions Netlogo.jar when I run a file from Eclipse.. HEELP!! 

### ISSUE THREAD

**Issue by juanchodiazg10** [NetLogo/NetLogo#1748]
Hi
I have created a netlogo file and I am using Eclipse to run it from this application using the netlogo-6.0.4.jar library in the build path. The problem is that the netlogo file uses extensions, so when it is opened directly from the netlogo-6.0.4.jar file it is perfect, but when it is opened from Eclipse, it does not find the extensions and does not allow executing.

The extensions are csv and array.

Please, I need help fastly!!

**Comment by LaCuneta** [comment]
Thanks for your interest in NetLogo.  The GItHub issues are for reporting problems with the NetLogo software.  For help with developing new programs using NetLogo, we have [the NetLogo developers mailing list](https://groups.google.com/forum/#!forum/netlogo-devel).  

The first thing I'd check is that you have the extension jar files in a directory NetLogo can find them in.  [Here is a list of where it looks, by default](http://ccl.northwestern.edu/netlogo/docs/extensions.html#where-extensions-are-located).  The second option is relative to the NetLogo jar file itself, so it will depend on where you've placed it for your project.
