### ISSUE TITLE
netlogo-headless.sh not dealing correctly with spaces in java path on mac 

### ISSUE THREAD

**Issue by mariopaolucci** [NetLogo/NetLogo#1753]
The error:

````
/Applications/NetLogo 6.1.0/netlogo-headless.sh: line 43: /Library/Internet: No such file or directory
````

Fix: If I add quotes as in https://github.com/CompEvol/beast2/issues/799, it works for me. That amounts to changing 

https://github.com/NetLogo/NetLogo/blob/69b7d4175504165ba502736e915eb51562af17bb/dist/configuration/shared/macosx/netlogo-headless.sh.mustache#L41

into 
```
"$JAVA" "${JVM_OPTS[@]}" -Dnetlogo.extensions.dir="${BASE_DIR}/extensions" -classpath "$CLASSPATH" org.nlogo.headless.Main "${ARGS[@]}"
```

My context:

```
>echo $JAVA_HOME
/Library/Internet Plug-ins/JavaAppletPlugin.plugin/Contents/Home
>java -version
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
````

```
  System Version:	macOS 10.13.6 (17G6030)
  Kernel Version:	Darwin 17.7.0
```

**Comment by nwijermans** [comment]
I do not know whether my issue is related or not but I cannot run my model headless on my mac. It throws the following error:

`Exception in thread "main" java.lang.IllegalStateException: unknown NetLogo version: NetLogo 6.1.0 at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:31)
	at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:535)
	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:502)
	at org.nlogo.headless.Main$.newWorkspace$1(Main.scala:18)
	at org.nlogo.headless.Main$.runExperiment(Main.scala:21)
	at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:12)
	at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:12)
	at scala.Option.foreach(Option.scala:257)
	at org.nlogo.headless.Main$.main(Main.scala:12)
	at org.nlogo.headless.Main.main(Main.scala)`

To include my context too:

>  echo $JAVA_HOME
> /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home
>  java -version
> java version "1.8.0_111"
> Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
> 
> System Version: macOS 10.14.5 (18F132)
> Kernel Version: Darwin 18.6.0

Any advice to solve this?

**Comment by mariopaolucci** [comment]
Hello Nanda,

it does not look related to me - it sounds if it's trying to use Netlogo libraries from an older version. Can you give the full path to your netlogo-headless.sh, to begin with?

I can reproduce your behavior like this:

```
/Applications/NetLogo\ 6.0.4/netlogo-headless.sh --model PROTON-OC-1.0.nlogo --setup-file experiments-xml/run-at-1000/exp-OC-baseEduEco.xml  --table table2-output.csv 

Exception in thread "main" java.lang.IllegalStateException: unknown NetLogo version: NetLogo 6.1.4
```

(no, I don't have a version 6.1.4, I just edited the version number in the file) - so it's probably just a version mismatch. Try saving the model under 6.0.4, for example, and see if the behavior persists

**Comment by nwijermans** [comment]
Hi Mario,

You are so right! Thanks so much for your input, I solved it now. Should properly adapt my .sh files ;).

Hope there is a solution for your problem soon!

**Comment by LaCuneta** [comment]
@mariopaolucci Thanks for the report and for your workaround!  I've got this fixed up for the next release.  

@nwijermans Glad you got your versioning issue resolved as well!
