### ISSUE TITLE
Nothing named error for out-commented variables

### ISSUE THREAD

**Issue by nwijermans** [NetLogo/NetLogo#1762]
Hi,

I get the following error when running an experiment using BehaviourSpace:

> Nothing named OPT-TIMEOUT-A has been defined. at position 38 

the curious thing is that I just cleaned up my code of all the variables I am not using anymore - and exactly these variables it seems to need. Can anyone explain why this is happening and how I can resolve this without reintroducing variables that have no use?

Below the full error message. Thanks in advance!

Best wishes, Nanda

> Nothing named OPT-TIMEOUT-A has been defined. at position 38 in 
>  at org.nlogo.core.Fail$.exception(Fail.scala:27)
>  at org.nlogo.core.Fail$.exception(Fail.scala:25)
>  at org.nlogo.core.Fail$.exception(Fail.scala:23)
>  at org.nlogo.parse.ExpressionParser$.$anonfun$parseExpressionInternal$4(ExpressionParser.scala:391)
>  at scala.Option.getOrElse(Option.scala:138)
>  at org.nlogo.parse.ExpressionParser$.parseExpressionInternal(ExpressionParser.scala:391)
>  at org.nlogo.parse.ExpressionParser$.parseArgExpression(ExpressionParser.scala:230)
>  at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1(ExpressionParser.scala:166)
>  at org.nlogo.parse.ExpressionParser$.$anonfun$parseArguments$1$adapted(ExpressionParser.scala:165)
>  at scala.collection.immutable.Range.foreach(Range.scala:158)
>  at org.nlogo.parse.ExpressionParser$.parseArguments(ExpressionParser.scala:165)
>  at org.nlogo.parse.ExpressionParser$.parsePotentiallyVariadicArgumentList(ExpressionParser.scala:88)
>  at org.nlogo.parse.ExpressionParser$.parseStatement(ExpressionParser.scala:69)
>  at org.nlogo.parse.ExpressionParser$.$anonfun$apply$1(ExpressionParser.scala:30)
>  at org.nlogo.parse.ExpressionParser$.parseStatements(ExpressionParser.scala:42)
>  at org.nlogo.parse.ExpressionParser$.apply(ExpressionParser.scala:30)
>  at org.nlogo.parse.NetLogoParser.parseProcedure(NetLogoParser.scala:45)
>  at org.nlogo.parse.NetLogoParser.parseProcedure$(NetLogoParser.scala:29)
>  at org.nlogo.parse.FrontEnd$.parseProcedure(FrontEnd.scala:10)
>  at org.nlogo.parse.NetLogoParser.$anonfun$basicParse$1(NetLogoParser.scala:25)
>  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
>  at scala.collection.Iterator.foreach(Iterator.scala:941)
>  at scala.collection.Iterator.foreach$(Iterator.scala:941)
>  at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
>  at scala.collection.MapLike$DefaultValuesIterable.foreach(MapLike.scala:213)
>  at scala.collection.TraversableLike.map(TraversableLike.scala:237)
>  at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
>  at scala.collection.AbstractTraversable.map(Traversable.scala:108)
>  at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:25)
>  at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
>  at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
>  at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
>  at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
>  at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
>  at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:43)
>  at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:86)
>  at org.nlogo.compile.Compiler.compileMoreCode(Compiler.scala:100)
>  at org.nlogo.workspace.Evaluator.invokeCompiler(Evaluator.scala:159)
>  at org.nlogo.workspace.Evaluator.makeCommandThunk(Evaluator.scala:110)
>  at org.nlogo.workspace.Evaluating.makeCommandThunk(Evaluating.scala:25)
>  at org.nlogo.workspace.Evaluating.makeCommandThunk$(Evaluating.scala:23)
>  at org.nlogo.workspace.AbstractWorkspaceScala.makeCommandThunk(AbstractWorkspaceScala.scala:26)
>  at org.nlogo.plot.PlotManager.compile$1(PlotManager.scala:92)
>  at org.nlogo.plot.PlotManager.$anonfun$compilePlot$4(PlotManager.scala:108)
>  at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:742)
>  at scala.collection.immutable.List.foreach(List.scala:392)
>  at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:741)
>  at org.nlogo.plot.PlotManager.compilePlot(PlotManager.scala:106)
>  at org.nlogo.plot.PlotManager.$anonfun$compileAllPlots$1(PlotManager.scala:87)
>  at scala.collection.immutable.List.flatMap(List.scala:338)
>  at org.nlogo.plot.PlotManager.compileAllPlots(PlotManager.scala:87)
>  at org.nlogo.headless.HeadlessModelOpener.finish(HeadlessModelOpener.scala:90)
>  at org.nlogo.headless.HeadlessModelOpener.openFromModel(HeadlessModelOpener.scala:74)
>  at org.nlogo.headless.HeadlessWorkspace.openModel(HeadlessWorkspace.scala:539)
>  at org.nlogo.app.App$$anon$1.openCurrentModelIn(App.scala:133)
>  at org.nlogo.lab.gui.Supervisor.$anonfun$start$1(Supervisor.scala:98)
>  at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
>  at org.nlogo.lab.gui.Supervisor.start(Supervisor.scala:96)
>  at org.nlogo.lab.gui.ManagerDialog.run(ManagerDialog.scala:103)
>  at org.nlogo.lab.gui.ManagerDialog.$anonfun$runAction$1(ManagerDialog.scala:30)
>  at org.nlogo.lab.gui.ManagerDialog$$anon$1.actionPerformed(ManagerDialog.scala:24)
>  at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
>  at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
>  at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
>  at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
>  at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
>  at java.awt.Component.processMouseEvent(Component.java:6539)
>  at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
>  at java.awt.Component.processEvent(Component.java:6304)
>  at java.awt.Container.processEvent(Container.java:2239)
>  at java.awt.Component.dispatchEventImpl(Component.java:4889)
>  at java.awt.Container.dispatchEventImpl(Container.java:2297)
>  at java.awt.Component.dispatchEvent(Component.java:4711)
>  at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
>  at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
>  at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
>  at java.awt.Container.dispatchEventImpl(Container.java:2283)
>  at java.awt.Window.dispatchEventImpl(Window.java:2746)
>  at java.awt.Component.dispatchEvent(Component.java:4711)
>  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
>  at java.awt.EventQueue.access$500(EventQueue.java:97)
>  at java.awt.EventQueue$3.run(EventQueue.java:709)
>  at java.awt.EventQueue$3.run(EventQueue.java:703)
>  at java.security.AccessController.doPrivileged(Native Method)
>  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
>  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
>  at java.awt.EventQueue$4.run(EventQueue.java:733)
>  at java.awt.EventQueue$4.run(EventQueue.java:731)
>  at java.security.AccessController.doPrivileged(Native Method)
>  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
>  at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
>  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
>  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
>  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
>  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
>  at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> NetLogo 6.1.0
> main: org.nlogo.app.AppFrame
> thread: AWT-EventQueue-0
> Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
> operating system: Mac OS X 10.14.5 (x86_64 processor)
> Scala version 2.12.8
> JOGL: (3D View not initialized)
> OpenGL Graphics: (3D View not initialized)
> model: FIBE
> 
> 11:40:51.106 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
> 11:40:51.106 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
> 11:40:51.106 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
> 11:40:51.106 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
> 11:40:51.106 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
> 11:40:51.106 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
> 11:40:51.106 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
> 11:40:51.106 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
> 11:40:51.106 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
> 11:40:51.106 JobRemovedEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread

**Comment by LaCuneta** [comment]
Nanda, thank you for reporting this error and sorry you ran into it!  

It looks like one of those old variables might be used in a plot somewhere?  It's when the plot compiler is running that the failure occurs, so there might be a leftover reference in a plot pen definition.  

If you look through the plots and cannot find an out-of-date variable name, would you be able to post your model here or to to send it in to bugs@ccl.northwestern.edu for us to take a look at it?

**Comment by LaCuneta** [comment]
I'm closing this for now, but if it's still a problem feel free to leave a comment with more information as per the previous comments and we'll look back into it.
