### ISSUE TITLE
Documentation: improve consistency of boolean arguments naming

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#1770]
Here are the syntax descriptions of the various `if`-like primitives [in the dictionnary](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#if):

- **if ***condition*** [ ***commands*** ]**
- **ifelse ***reporter1*** [ ***commands1*** ] [ ***elsecommands*** ]**
  **(ifelse ***reporter1*** [ ***commands1*** ] ***reporter2*** [ ***commands2*** ] ... [ ***elsecommands*** ])**
- **ifelse-value ***tfreporter1*** [ ***reporter1*** ] [ ***elsereporter*** ]**
  **(ifelse-value ***tfreporter1*** [ ***reporter1*** ] ***tfreporter2*** [ ***reporter2*** ] ... [ ***elsereporter*** ])**

The boolean arguments are variously referred to as **condition**, **reporter** and **tfreporter**.

The [`or`](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#or) and [`and`](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#and) primitives are also inconsistent:

- *****boolean1*** or ***boolean2*****
- *****condition1*** and ***condition2*****

Heck, `or` is even inconsistent within its own documentation:

>  Reports true if either *boolean1* or *boolean2*, or both, is true.
>
> Note that if *condition1* is true, then *condition2* will not be run (since it can't affect the result). 

I did not do a systematic search, but I wouldn't be surprised if other examples could be found in the dictionary.

What should they all be changed to?

My personal preference is ***boolean***, but maybe ***condition*** is more friendly (though arguably less clear). I think ***reporter*** and ***tfreporter*** are misleading, since the prims expect values in those slots, not reporters. I also find the Hungarian-notation style of ***tfreporter*** to be very unnetlogoish.

**Comment by LaCuneta** [comment]
I browsed the dictionary pretty quickly, and for the most part primitives seem to use the type of the parameter as the stand-in name, so **_boolean_** would fit in with that.  The cases where descriptive names are used instead mostly are around disambiguating, like `towards x y` where `towards number1 number2` would be less descriptive. 

Given that, I'd agree to go with **_boolean_**.

**Comment by alan-isaac** [comment]
Thank you for paying attention to this situation, which is very confusing for students.  The inconsistency is also in `if`, which begins the documentation by referring to "Reporter" rather than to the `condition` used to present the syntax.
