### ISSUE TITLE
Model created in Netlogo 6.1 and running it in Netlogo 6.0.4 

### ISSUE THREAD

**Issue by pankaj113** [NetLogo/NetLogo#1779]
error (NonLocalExit)
 while observer running ASK
  called by procedure INITIATE-BACTERIA
  called by procedure GO
  called by Button 'go'

NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

org.nlogo.nvm.NonLocalExit

NetLogo 6.0.4
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_172 (Oracle Corporation; 1.8.0_172-b11)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.4
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: Microbiome dynamics

06:23:09.900 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
06:23:09.878 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
06:23:09.878 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:23:09.878 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:23:09.878 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:23:09.878 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:23:09.878 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:23:09.878 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:23:09.878 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
06:23:09.878 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0

**Comment by LaCuneta** [comment]
@pankaj113 Thanks for reporting this issue, sorry you ran into it.  

To confirm, does the issue happen each time you run your model?  And you do not see this error in NetLogo 6.1.0?  If you're able to send your model, that would be helpful.  You can either post it here, or send it in to bugs@ccl.northwestern.edu if you need to keep it private.

**Comment by pankaj113** [comment]
Hi,

Background-
The model is not created by me - I received it for evaluation. We are part of an online course, learning about Agent Based Models and Netlogo. Until now I was using Netlogo 6.0.4. I installed Netlogo 6.1.0 today morning.

Response to your Query-
Yes, the issue happens each time the model is run in Netlogo 6.0.4. For different runs, the issue happened at different ticks - 554, 854, 535, 853, 851, 843.

The original model created in Netlogo 6.1.0 did not use cf extension with ifelse command. I changed the code to run the model in my Netlogo 6.0.4 version. I just ran the model, with and without cf extension in Netlogo 6.1.0 - no error is seen for multiple runs.

I will send the model to the email ID given. I look forward to learning more about the issue. Thanks.

**Comment by LaCuneta** [comment]
It turns out this is an issue with using the `stop` command inside a `cf` command block in 6.0.4: 

```
extensions [ cf ]

to test
  repeat 100 [ go ]
end

to go
  let x random 30
  (cf:ifelse 
    x < 10 [ ]
    x < 20 [ stop ]
    [ show "big number" ]
  )
end
```

The best option is to convert to 6.1.0+ if possible and to use the build-in `ifelse` since it doesn't have this issue.  Other workarounds include either doing nothing instead of using `stop` if possible, or to use a local variable like `should-stop` if you need more control to recreate the `stop` behavior.

Because `cf` is deprecated and this issue doesn't happen with the built-in `ifelse` prim in 6.1.0+, there probably isn't much else to be done in terms of a code fix.

**Comment by UriCCL** [comment]
Jeremy,
Please make sure all bug messages are also sent to the bugs list.

Thanks,

—Uri


Uri Wilensky
Lorraine H. Morton Professor of Learning Sciences, Computer Science and Complex Systems
Director, Center for Connected Learning  and Computer-Based Modeling (CCL)
Co-director, Computer Science/Learning Sciences PHD program (CSLS)
Governing Board, Northwestern Institute on Complex Systems (NICO)
Faculty member, program in Cognitive Science 
Faculty member, program in Technology and Social Behavior
Co-Investigator, Center for Prevention Implementation  Methodology (Ce-PIM)
Northwestern University
