### ISSUE TITLE
Extensions guide error?

### ISSUE THREAD

**Issue by SulisEm** [NetLogo/NetLogo#1785]
In the Scala tutorial extension part, probably the name of the file IntegerList.java is not correct:
$ scalac -classpath NetLogo.jar -d classes src/main/scala/IntegerList.java

The command has to be:
$ scalac -classpath NetLogo.jar -d classes src/main/scala/IntegerList.scala

Similarly, the name of the Scala folder has to be "example" instead of "example-scala"

**Comment by LaCuneta** [comment]
@SulisEm Thanks for the report!  I assume you were referring to [this wiki page](https://github.com/NetLogo/NetLogo/wiki/Extensions-API)?

I corrected the `IntegerList.scala` command line there.  I believe the Scala folder should be fine as `example-scala`, as that's just the root project folder - it shouldn't affect much in writing out the example.  What problem did you notice when trying to use it?
