### ISSUE TITLE
Empty input box crashes NetLogo

### ISSUE THREAD

**Issue by myildi** [NetLogo/NetLogo#1786]
Hello,
I have been observing this problem from time to time in many version of NetLogo on OSX.
When I create input boxes in the interface and do not immediately give a value to them, at one point the cursor starts to blink and NL just crashes, without any possibility of saving the file. Clicking Halt does not solve the crash and one has to kill NL and loose the unsaved code. 

I have just suffered this problem in NL 6.1 on OSX 10.14.6, but it is definitely not limited to these versions. My students meet this problem quite frequently too during the workshops I give on ABMs with NL. If I can help you to locate this bug in anyway, please do not hesitate to contact me, because it is quite painful.

**Comment by myildi** [comment]
Just a complement: when I have killed NL, and reopened my program, I see that NL has been able to save the code and even the empty input boxes (which show a value of 0 now). That is a relief!

**Comment by LaCuneta** [comment]
Murat, thanks for report, and sorry you ran into it.  Can I clarify, when you say NetLogo crashes, you mean that it stops responding to input?  But you're able to open the Tools menu and hit Halt?  Does NetLogo give you an error message of any kind?  I'm guessing it does not, but just want to be sure.

I played around creating a bunch of different input widgets on MacOS 10.14.6 without filling in values, but I haven't been able to reproduce the issue yet.  

Does this problem occur when creating any particular type of input widget (string/multi-line string/number/color/reporter/commands)?  Can you think of any other steps you take that cause the problem to happen every time?  Such as clicking in a different part of the UI or running the model for a while?

**Comment by myildi** [comment]
Hi Jeremy,
Yes, I am able to access to menus but they do not trigger any effective action. The cursor just blinks in the input boxes (they are of type number in this case). I was creating three of them in a row by right-clicking, choosing input box in the contextual menu. I have created two of them, it just hang just after the creation of the third. The model has not been running because it is not yet in a runnable state, I was creating utility commands before go. 
This problem seems really random, this is why I get caught. :-( 
I hope this helps.

**Comment by LaCuneta** [comment]
Murat, thanks for the extra information, it is very helpful.

I haven' been able to reproduce the exact issue, but trying again with number type input widgets gives me some strange behavior I believe would be related.  Here are the steps to reproduce:

- Create one input widget with a number type, do not give it a value, but click into after creation so the cursor is blinking in the input box.
- Create a second input widget with a number type, do not give it a value, but click into after creation. 
- You should see the cursor starts blinking rapidly between the two input widgets and you've somewhat lost control of the UI - typing will give weird results and you cannot click into the command center.

It's not quite unresponsive enough to require me to stop the NetLogo app, as I am able to click into the code tab and back to restore functionality.  It does point to the number type input widgets being too "aggressive" in validating their input and stealing focus in a way that could cause the unresponsiveness, though.

**Comment by myildi** [comment]
This really looks like the issue I get, except that in my case the interface becomes unresponsive and I cannot switch to the code tab. I need to kill NL, I cannot quit it neither.

**Comment by LaCuneta** [comment]
Good to know we're on the right track.  The workaround, obviously, is to enter numbers into the widgets as they are created, even just 0's.  It's not ideal to have to remember that, and we will definitely look into a proper fix in a future release.

**Comment by ERSUCC** [comment]
I have a potential fix. See pull request #2254.
