### ISSUE TITLE
Stop button not working

### ISSUE THREAD

**Issue by joeglessner1** [NetLogo/NetLogo#1792]
Checking the globals monitor, continue remains true upon clicking the Stop/Halt button and the model continues to run with the only option being Tools->Halt.

```
globals [
continue
]
to Go
  set continue true
  loop[
    ifelse continue and count people > 0[
      ask people [
      ...
      ]
      ]
      [
      stop
      ]
     ]
end
;;--------
to Halt
    set continue false
end
```

**Comment by SethTisue** [comment]
this is working as designed. buttons take turns; they don't interleave execution with each other. (otherwise all sorts of havoc might ensue if the user pressed multiple buttons)

here `Go` just keeps looping and therefore no other buttons will ever get a turn.

**Comment by LaCuneta** [comment]
Seth is correct, and this behavior is expected.  The `loop` prim is going to take control and not give it up.

If I'm reading your code correctly, I believe you can get the effect you want by making the button that calls your `Go` procedure [a forever button](https://ccl.northwestern.edu/netlogo/docs/programming.html#buttons), then removing the `loop`.   Then you wouldn't need a `Halt` button or the `continue` global, you can just re-click your running `Go`  button to stop it.

```
to Go
  if count people <= 0 [ stop ]
  ask people [
    ...
  ]
end
```

If you need more help with your model, I'd recommend posting to [the NetLogo users group](https://groups.google.com/forum/#!forum/netlogo-users).
