### ISSUE TITLE
There is no way for extensions from the manager to link to examples

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#1798]
This has been reported/rediscovered a couple times be people working on extensions and submitting them to [the library](https://github.com/NetLogo/NetLogo-Libraries).  

At the moment, example models can be included with the extension, but they get dropped into the user and system dependent NetLogo data folder, which is hidden by default.  It's hard to point users to that folder to open them.  

I think we should add some way for a contributed extension to easily show the user some example models to try out.

One option is to use a convention for a sub-folder of the extension archive file, like `examples`, and add a GUI button in the extension manager to start the open model dialog in that folder.

**Comment by Idloj** [comment]
Or maybe (I believe this idea has been brought up once) we can have the example models integrated in the Models Library. `Code Examples > Extension Examples` already provides example models for bundled extensions, and it seems natural to have other extension example models there once they're installed.
