### ISSUE TITLE
Trouble with Agent Breeds

### ISSUE THREAD

**Issue by jamesmrollins** [NetLogo/NetLogo#1804]
I am new to this agent programming language; thus, I am unsure if this is a "bug" or if it is a programmer issue. Nevertheless, when I run the setup procedure shown below, the "create-leaders 2" routine does not create 2 leaders effectively (see code screen capture below).  However, when you look at world on the interface screen, you can see both leaders.  By virtue of the order of execution, the leader breed should be turtles 1 and 2.  I can get 1 to display in the turtle monitor, but not 2. When I put in "2" it displays a agent from the next breed.  I can advance through all the breeds using the turtle monitor, but the other leader agent is not present.

This routine used to work, but not now for some reason.  Your help is appreciated - Thank you.

**Code Screen Capture**

![image](https://user-images.githubusercontent.com/30132017/71210767-7dbe8a00-2262-11ea-8966-26e3bdec0696.png)

**Interface Screen Capture**

![image](https://user-images.githubusercontent.com/30132017/71210719-61225200-2262-11ea-980e-64828e25de6c.png)

**Comment by SethTisue** [comment]
turtle numbers start at 0, not 1

**Comment by LaCuneta** [comment]
@jamesmrollins In addition to what Seth said, you can also right click on an agent in the view and a popup will come up with the agents listed at the bottom by breed and `who` number.  You can `inspect` the turtle directly from that menu, or it can just help you ID a turtle when you don't know the number it was assigned.

**Comment by jamesmrollins** [comment]
@SethTisue @LaCuneta Thank you for your help.  I will use these tools to continue my troubleshooting.  ~ James
