### ISSUE TITLE
Global variables not updating in anonymous functions

### ISSUE THREAD

**Issue by vityavv** [NetLogo/NetLogo#1809]
Basically, with this code:

```
to test
  repeat 10 [
    (run [ _ ->
      show word "Value of stop? " stop?
      wait 1
    ] 1)
  ]
end
```

If I run it in the console, and set stop? to true halfway through, here's what I get:

```
observer> set stop? false
observer> test
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer> set stop? true
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
```

What's even more interesting is it still doesn't work if I do something like this

```
; replace stop? in original function with stop?-reporter
to-report stop?-reporter
  report stop?
end
```

it has the same result!

**Comment by SethTisue** [comment]
The NetLogo language is single-threaded. It doesn't have any kind of support for multi-threading, concurrency, or parallelism (except parallel runs in BehaviorSpace). The first command must finish before the next command begins executing.

**Comment by LaCuneta** [comment]
@vityavv You can maybe better visualize what Seth is saying by changing out your `set stop? true` command center command to another `show` primitive:  `set stop? false test show "hello there!"`

Outputs:

```
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "Value of stop? false"
observer: "hello there!"
```

**Comment by vityavv** [comment]
@SethTisue @LaCuneta the problem is that this works properly if the code is *not* in an anonymous function. I'm not expecting the language to be multi-threaded

**Comment by qiemem** [comment]
I think what's happening here is that, normally, `wait` allows for job switching for concurrently executing jobs:

```
observer> wait 5 print "done"
observer> print "hi"
hi
done
```

(NetLogo does have some concurrency despite it's lack of parallelism)

However, anonymous functions [are executed exclusively to completion](https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-core/src/main/nvm/AnonymousProcedure.scala#L175):

```
observer> run [ -> wait 5 print "done" ]
observer> print "hi"
done
hi
```

I don't think this isn't really a bug, per se, as the concurrency features of NetLogo are more there to support stuff like monitors and for historical reasons (leftover from the pre-tick-all-the-things days and `ask-concurrent` and such; @SethTisue can almost certainly provide the actual context), afaik.

@vityavv is this interfering with something you're trying to do?

**Comment by SethTisue** [comment]
agree that it's merely historical/vestigial that it behaves differently outside of a lambda

**Comment by vityavv** [comment]
Hi all. Thank you for your responses. This wasn't really interfering with
anything I was writing. Is the difference in behavior documented somewhere?

**Comment by SethTisue** [comment]
There is some doc on `ask-concurrent` at http://ccl.northwestern.edu/netlogo/docs/programming.html#ask-concurrent which may give you some partial insight, but it's specific to the `ask-concurrent` primitive. I don't think it's documented anywhere that similar behavior is occasionally observable elsewhere.
