### ISSUE TITLE
"patches with" optimization bug in NetLogo 3D

### ISSUE THREAD

**Issue by fstonedahl** [NetLogo/NetLogo#1810]
In NetLogo 3D 6.1.1, type:

`ask patches with [ pxcor = 16 ] [ set color red ]`

Note that only those patches that also have `pzcor = 0` actually change color. 

This is almost certainly a bug caused by optimized code for patches-with primitives, which works in NetLogo 2D, but does not work correctly in NetLogo 3D.

**Comment by LaCuneta** [comment]
@fstonedahl Thanks for the report, Forrest!

I'm sure you're aware, but for anyone else who does happen on this bug, you can workaround by adding a pz-coordinate condition that would always be true:

```
ask patches with [ pxcor = 16 and pzcor <= max-pzcor ] [ set pcolor red ]
```

**Comment by UriCCL** [comment]
yes, we should fix this bug.


On Tue, Jan 14, 2020 at 9:26 PM Forrest Stonedahl <notifications@github.com>
wrote:

> In NetLogo 3D 6.1.1, type:
>
> ask patches with [ pxcor = 16 ] [ set color red ]
>
> Note that only those patches that also have pzcor = 0 actually change
> color.
>
> This is almost certainly a bug caused by optimized code for patches-with
> primitives, which works in NetLogo 2D, but does not work correctly in
> NetLogo 3D.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_NetLogo_NetLogo_issues_1810-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DABRSBQPZDI3EQWZASZ2NFBTQ5YGXNA5CNFSM4KGYI3XKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IGE2G4A&d=DwMCaQ&c=yHlS04HhBraes5BQ9ueu5zKhE7rtNXt_d012z2PA6ws&r=3MqBF7qr0NcLDqkRmbayrNl8ngBdhnLx94XK9q7mwRU&m=0-kb9xF3KDtyamC7J-biSceWsT1ntTu4IUDfd4W8ZoY&s=T2lUYBtLOQSsIDoa0gZNxFVycfu1P3r5eV4S_4-dd_Y&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ABRSBQLWNQKKYCL76LIV5TLQ5YGXNANCNFSM4KGYI3XA&d=DwMCaQ&c=yHlS04HhBraes5BQ9ueu5zKhE7rtNXt_d012z2PA6ws&r=3MqBF7qr0NcLDqkRmbayrNl8ngBdhnLx94XK9q7mwRU&m=0-kb9xF3KDtyamC7J-biSceWsT1ntTu4IUDfd4W8ZoY&s=_B4JN4jYQkrV_-vwkyPlMVK27ml5FOMeoRrHFO5ayHo&e=>
> .
>


-- 
-- Uri
uri.wilensky@gmail.com
