### ISSUE TITLE
Font value not being read from .nlogo3d file

### ISSUE THREAD

**Issue by cstaelin** [NetLogo/NetLogo#1811]
When I change the font in the Settings of my model, in this case from the default 10 to 36, and then save the model, I see that the new value is reflected in the GRAPHICS-WINDOW portion of the .nlogo3d file.
```
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
@#$#@#$#@
GRAPHICS-WINDOW
0
0
489
490
-1
-1
13.0
1
36
1
1
1
0
1
1
1
-18
18
-18
18
-20
20
1
1
1
ticks
30.0
```
However, when I open the file again, the new value seems not to be read and the settings window shows a font size of 10 (screen shot attached).  Seems like a bug?  I can send the whole .nlogo3d file if it would be useful.

Charles

![Settings](https://user-images.githubusercontent.com/1297495/72441940-92b30e00-3779-11ea-81af-538d121d03bc.jpg)

**Comment by brandesNW** [comment]
Hi Charles,
Thank you for submitting this bug. I have verified that it occurs in NetLogo3D but not in NetLogo2D.   

I have noticed that the bug occurs if you quit NetLogo, but not if you open another model, and then re-open the model with the changed font. So if you are working on a model on-and-off for a short period of time you could try keeping NetLogo open with a New model when you are not actively working.

- Aaron
