### ISSUE TITLE
primitive autoplot? is documented but does not exist

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#1815]
entering "autoplot?" in the observer context results in an error message in the command center
ERROR: Nothing named autoplot? has been defined. 

[Documentation](https://ccl.northwestern.edu/netlogo/docs/dictionary.html#autoplot)

**Comment by ERSUCC** [comment]
Hi @brandesNW, turns out it was just missing from the file that converts etc primitives to other primitives. I fixed it, see pull request #2279.
