### ISSUE TITLE
Model works in desktop, but not NetLogo Web - type error in simulation engine

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#1831]
The user created related three models. I have verified that they run in the NetLogo desktop application.
However if they are exported to NetLogo Web, they produce an error.
Press the setup button, turtles are generated.
Press the go button, an error message pops up.

--------
Error
A type error has occurred in the simulation engine. More information about these sorts of errors can be found [here](https://netlogoweb.org/docs/faq#type-errors).

Advanced users might find the generated error helpful, which is as follows:

turtle2.projectionBy is not a function
----------------

Note: the last line varies depending on the model. the message above is for biased_trust.html.
Note: If the web model is exported as a NetLogo model, the resulting model works in desktop NetLogo.

I reproduced the problem using NetLogo 6.1.1.

The system details for the user are:

NetLogo 6.0.4 (June 4, 2018)
Extension API version: 6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_172 (Oracle Corporation; 1.8.0_172-b11)
operating system: Linux 4.15.0-91-generic (amd64 processor)
Scala version 2.12.4
Java heap: used = 31 MB, free = 420 MB, max = 910 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

[netlogo-web-only.zip](https://github.com/NetLogo/NetLogo/files/4439421/netlogo-web-only.zip)

**Comment by TheBizzle** [comment]
This is a Tortoise issue and was resolved in NetLogo/Tortoise@4de6758c985a90625f4e4bfeb188ddcc44689e00 .
