### ISSUE TITLE
Evacuation model

### ISSUE THREAD

**Issue by ricarddiagos** [NetLogo/NetLogo#1845]
Hey, I am quiet new in netlogo environment. Currerntly, I would like to make a evacuation model that the walking speed is affected by gaining elevation. I know how to input these environments dataset, such as: DEM, road network, population density, etc. i do not know how to eloborate the code to make the walking speed is affeted by elevation (gaining elevation, walking speed is slower and etc.)

Do you have any idea, what should i do with this issue? or Do you have any kind of references or sample code, etc that might help me with this proble?

Thank you for your support
Best regards

**Comment by SethTisue** [comment]
https://ccl.northwestern.edu/netlogo/resources.shtml has links on where to ask for NetLogo help — https://groups.google.com/d/forum/netlogo-users would be appropriate in this case

**Comment by brandesNW** [comment]
As Seth said, while I was typing -An issue in NetLogo/NetLogo should either be a bug in NetLogo - that is NetLogo fails to perform as documented/designed, or less frequently, a request for an enhancement in NetLogo's current capabilities.  
I second his recommendations and am closing this issue.
