### ISSUE TITLE
example code missing from website

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#1850]
The "Code Examples" are missing from the website's listing of the [Models Library](http://ccl.northwestern.edu/netlogo/models/). The models have pages (e.g., [Neighborhoods Example](http://ccl.northwestern.edu/netlogo/models/NeighborhoodsExample)), but the main page lacks links to the model pages.

**Comment by LaCuneta** [comment]
Thanks for the heads up, they should show up there now.
