### ISSUE TITLE
How to install NetLogo in Linux?

### ISSUE THREAD

**Issue by Mojahid-Ahmad** [NetLogo/NetLogo#1854]
How to install NetLogo in Linux?

**Comment by LaCuneta** [comment]
These steps should get NetLogo running on typical Linux distributions:

- Go the the NetLogo download page: http://ccl.northwestern.edu/netlogo/download.shtml
- Download the Linux version, probably 64 bit unless you are certain you need 32 bit.
- Extract the contents of the NetLogo-6.1.1-64.tgz file wherever you like.  If you're not sure which directory to use, you could just use a folder in your home directory.
- Once extracted you can run the `NetLogo` executable from the directory, which should work if you're running through a graphical user interface.  http://ccl.northwestern.edu/netlogo/docs/requirements.html#linux

If you need further assistance, I recommend asking in the NetLogo users Google Group:  https://groups.google.com/g/netlogo-users
