### ISSUE TITLE
Non-constant time to look up agent by id when using breed keyword

### ISSUE THREAD

**Issue by jlambvo** [NetLogo/NetLogo#1856]
I ran into a unexpected performance issue in NetLogo 6.1.1 when attempting to get a variable value from a turtle by its "who" index, and found that there may be an issue related to breeds. 

When looking up an agent with `turtle i`, lookup time is constant as expected. However, if referencing by breed name, e.g. `tuna i` then lookup time increases roughly linearly with `i`. That is, the lookup time for `[variable] of tuna 0` is similar to `[variable] of turtle 0` but `[variable] of tuna 10000` is very slow. 

Below is a simple test model that demonstrates the issue along with screenshots of output. The code assumes UI inputs for "N," "turtleToQuery," and "breed?". I am curious if this can be reproduced. 

```
breed [tunas tuna]
turtles-own [someVariable]
globals [maxWho]

to spawn-turtles
  create-tunas N [
    setxy random-xcor random-ycor
    set someVariable 1
  ]
end

to setup
  clear-all
  spawn-turtles
  set turtleToQuery 0
  set maxWho max [who] of turtles
  reset-ticks
end

to go
  reset-timer
  ask turtles [
    ifelse (breed?) [
      let j [someVariable] of tuna turtleToQuery
    ]
    [
      let j [someVariable] of turtle turtleToQuery
    ]
  ]
  set turtleToQuery turtleToQuery + 1
  if (turtleToQuery > maxWho) [set turtleToQuery maxWho]
  show timer
  tick
end
```
![BreedBug1](https://user-images.githubusercontent.com/7811016/93410376-c2a53a80-f84d-11ea-9df6-008c7b320b0c.png)
![BreedBug2](https://user-images.githubusercontent.com/7811016/93410382-c3d66780-f84d-11ea-8553-295105dbed87.png)

**Comment by SethTisue** [comment]
This seems worthy of devel attention to me.

**Comment by qiemem** [comment]
Good catch! Just opened a PR with a fix.
