### ISSUE TITLE
Request: higher quality export-view export-interface

### ISSUE THREAD

**Issue by cdwren** [NetLogo/NetLogo#1890]
Would it be possible to add functionality for a higher quality export-view and export-interface PNGs? Typically I increase the patch size of the view and then export, but the pen-down lines in particular are still of quite low quality. This method also doesn't work for export-interface. Perhaps a way to specify export image size/resolution?

**Comment by brandesNW** [comment]
Hi Colin,
Thanks for letting us know about the issue you encountered.

I have looked at the underlying code and it seems to capture all the pixels in the world view, which is the resolution limit.
I also did a test and the pen lines seem as clear in the png as they are in NetLogo.
This is using the default settings (x, y from -16 to 16, patch size 13) in a new model.
See code below and attached png file.

Can you share an example that demonstrates your problem?

to setup
  clear-all
  random-seed 2021
  crt 3 [ pd fd 6]
end

To share a .nlogo model file please include it in a zip file or change the extension because github accepts only the following attachment formats:
PNG (.png)
GIF (.gif)
JPEG (.jpg)
Log files (.log)
Microsoft Word (.docx), Powerpoint (.pptx), and Excel (.xlsx) documents.
Text files (.txt)
PDFs (.pdf)
ZIP (.zip, .gz)

Thanks,
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling

**Comment by cdwren** [comment]
Thanks Aaron. Your MWE works just fine to illustrate the problem though perhaps I should have specified that I'm looking for print quality level images for an academic book we're working on. See the zoomed in version of the export-view using your example code pasted above. Academic publications often require 600 dpi quality images.
![view](https://user-images.githubusercontent.com/11464945/105216620-0bc50e00-5b10-11eb-964d-6329927c3f4f.png)

By increasing the patch-size a lot (to 50 with your code), I am able to force NetLogo to export a higher resolution image with export-view but it still isn't great (see below). In addition, increasing the patch-size too much will cause a memory limit error (and yes I know how to increase the available memory).
![view_big](https://user-images.githubusercontent.com/11464945/105216989-87bf5600-5b10-11eb-86e9-c1effd9d622a.png)

So what I was hoping for would be a way to add a parameter to export-view to specify the export of a higher quality image. export-view filename dpi would be an easy way for example. I'm not sure how the agent graphics and path graphics are stored though, I imagine if the default turtle icon is originally a 32x32 raster image it would be harder to scale it to higher res than if it was stored as vector for example. 

I hope that clarifies what I was hoping for. It isn't that it doesn't look fine on the screen within NetLogo, but it isn't exactly professional print quality. For now I've taken to using export-view, then digitizing it in Inkscape to create a print quality version (thankfully the current figure is fairly simple).

**Comment by SethTisue** [comment]
The drawing layer (which is what `pen-down` affects) is a bitmap. Turtle shapes are vector graphics.

Related: https://stackoverflow.com/questions/34116889/how-to-export-view-to-a-vector-image-format-in-netlogo, and https://github.com/aesmaeili/vectorview which appears abandoned

**Comment by brandesNW** [comment]
Hi Colin,
As Seth has noted the results of pen-down are bitmaps. If you want better resolution, you should use smaller patches. As you noted the size of the model will be memory limited.  So unfortunately I don’t think a simple change to NetLogo to meet your request is possible.
However, many papers have been published that use NetLogo images, so perhaps your publisher will accept the images as they are.
You can find CCL publications here<http://ccl.northwestern.edu/papers.shtml>

Here is an example of settings that give you a resolution of 600 pixels per inch.

to setup
  ca
  let width 380
  let height 367
  resize-world 0 width - 1 0 height - 1
  set-patch-size 1
  crt 1 [ set heading 0 set color red pd repeat 360 [ fd 1 rt 1 ] ]
  crt 1 [ set heading 30 set color cyan pd repeat 720 [ fd .5 rt .5 ] ]
  crt 1 [ set heading 60 set color violet pd repeat 14440 [ fd .25 rt .25 ] ]
end

BTW I got the size of the model by using the bitmap extension to upload a 600 bw dpi jpg file.
I used
https://www.researchgate.net/figure/Relevant-portion-of-the-cephalometric-image-scanned-at-600-dpi-in-black-and-white_fig3_11994344

and the following code.


extensions[bitmap]

to setup
  ca
  let image-file user-file
  let image bitmap:import image-file
  let height bitmap:height image
  let width bitmap:width image
  show height
  show width
  resize-world 0 width - 1 0 height - 1
  set-patch-size 1
  import-pcolors-rgb image-file
end

I hope that is helpful.

  *   Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling

**Comment by cdwren** [comment]
Thank you for working through the details with me here, I guess we can close this for now though the abandoned vectorview extension seems like it would have been great. I have published a few papers with NetLogo figures already, but was hoping for some extra crisp figures for our book.
