### ISSUE TITLE
Custom 2D shapes in NetLogo 3D not appearing until restart

### ISSUE THREAD

**Issue by fstonedahl** [NetLogo/NetLogo#1896]
Several of my students encountered this bug this year -- if they created a new shape (with the turtle shapes editor) in NetLogo 3D, their turtles would still appear as the "default" turtle shape even after setting the shape, until after they closed NetLogo and restarted it.

**Comment by brandesNW** [comment]
I have verified this. There are similar bugs for the 3D view in NetLogo and in the View 2.5 extension.
This bug does not happen when if you go to Full Screen in NetLogo3D
