### ISSUE TITLE
Changing the breed of a link without any variable to a breed with a variable, causes an error.

### ISSUE THREAD

**Issue by Wolgo** [NetLogo/NetLogo#1899]
### The bug:

When I try to change the breed of a link w without any variables defined in breed-own, to a breed2 with a variable defined in breed2-own. I get the attached error message. 

When the breed does have *any* variable defined, changing to the breed2 does not give an error.
The attached zip file contains a NetLogo project with comments that showcases the bug. There are some pieces commented that I investigated. Please be aware that the error caused by this bug might not be gone after pressing setup (which uses clear-all), and that you might have to reload the model.

This bug is especially nasty because removing the offending code and rerunning still gives the error-message. The model even completely stops reacting to my buttons in some instances.

### The attached files:
[error-message.txt](https://github.com/NetLogo/NetLogo/files/5920515/error-message.txt)
[bugged_link_breed_change.zip](https://github.com/NetLogo/NetLogo/files/5920697/bugged_link_breed_change.zip)

### My diagnosis

When we look at the error I see it happening on:
`at org.nlogo.agent.Link.realloc(Link.java:175)
`
https://github.com/NetLogo/NetLogo/blob/341263d8fcd659505573a17827f2eefdd3f96fc2/netlogo-core/src/main/agent/Link.java#L167-L178

For each variable, we check the old position if it existed in the previous breed, so that we retain data.
Line 175 should only be reached when there was an old position for this variable. 
The variable we are changing to did not exist in the previous breed, thus we should never have reached line 175.
This means we got a wrong result for `oldpos`.

This means the error exists in the function `oldBreedsOwnIndexOf` 
https://github.com/NetLogo/NetLogo/blob/341263d8fcd659505573a17827f2eefdd3f96fc2/netlogo-core/src/main/agent/Link.java#L187-L197

Here is where my knowledge of the NetLogo is too lacking to exactly know where to look further. Because if we define any variable at all for the first breed, I suspect that `found.isEmpty()` does not return true when there are no "breed-own" defined variables. This is probably because the link does have variables such color defined. (I don't know what the intended behaviour is)

If the `found.isEmpty()` functions correctly, then `found.get().owns().indexOf(name)` is most likely not returning -1 when the variable does not exist.

Similar code is used for turtle, which does not suffer the same problem! 
https://github.com/NetLogo/NetLogo/blob/341263d8fcd659505573a17827f2eefdd3f96fc2/netlogo-core/src/main/agent/Turtle.java#L205-L236

Thank you for reviewing my report. I hope that it can be fixed soon.

### The workaround
Just give your links without breed-own variables some breed-own variable that you do nothing with.

**Comment by Wolgo** [comment]
I found the real problem, oldBreed in turtle was passed along in the setBreed function. In Link oldBreed was set to the new breed. Which meant the new breed was finding "old" position in itself. I am making a pull request to change this to work just as turtle works and actually pass along the oldbreed.

**Comment by brandesNW** [comment]
Closed by pull request #1900
Tests for this and related breed changes were added separately
