### ISSUE TITLE
Using bundled Java runtime for netlogo headless

### ISSUE THREAD

**Issue by bevsxyz** [NetLogo/NetLogo#1909]
Hello,
I am wondering if it would be possible to use the netlogo bundled version of java instead of the default one in my linux machine. I wonder why it is even required to use the one provided by the OS. Anyway, is it possible to set JAVA_HOME to the bundled version. I would appreciate pointers in this direction.

**Comment by LaCuneta** [comment]
I think there is a way.  In your NetLogo 6.2.0 application folder:

- In the root of the folder, copy the `NetLogo` executable file to `NetLogoHeadless` (make sure it's still executable)
- In the `app/` folder, copy the `NetLogo.cfg` file to `NetLogoHeadless.cfg`
- Edit the `NetLogoHeadless.cfg` file, change the line `app.mainclass=org/nlogo/app/App` to  `app.mainclass=org/nlogo/headless/Main`
- Try to run the `NetLogoHeadless` executable, it should prompt for a `--model` just as the `netlogo-headless.sh` script does.

Let us know if that works for you.

**Comment by LaCuneta** [comment]
Closing this, but please do leave a comment if the above steps worked for you or not.  Thanks.

**Comment by bevsxyz** [comment]
I'm gonna try to implement this now.

**Comment by LaCuneta** [comment]
@bevsxyz You are most welcome to give it a try!  

I believe one of the issues you might run into would be in macOS support.  Generating the command-line application bundles for Linux and Windows should be fine, but I don't think macOS lets apps be "command line only" in the same way.  I haven't done any research on that, and I'm happy to be proven wrong, but I don't know if we'd want to include a feature that wasn't supported on macOS.

**Comment by bevsxyz** [comment]
I don't see why it should not. Of course I am not a Mac user, but Mac does support terminal apps right? I'm taking the zsh hype and Darwin as proxies here, but could be a scala thing. Anyway thanks for the heads-up.

**Comment by LaCuneta** [comment]
> yes Mac supports running stuff from the terminal. Darwin is a fully fledged Unix

Of course!  To be clear on what I meant, you cannot run something like `/Applications/NetLogo 6.3.3/NetLogo Headless.app` directly at the terminal, you have to know the "trick" to do `/Applications/NetLogo 6.3.3/NetLogo Headless.app/Contents/MacOS/netlogo` (or whatever the binary path is).  It's just odd compared to Linux and Windows which created stand-alone executables.

**Comment by LaCuneta** [comment]
Between [this commit](https://github.com/NetLogo/NetLogo/commit/3bb7ce81a9acc7acbea26138d0ca79d0568db522) and [this commit](https://github.com/NetLogo/NetLogo/commit/3054e2ef65192038bbe847a8845aee29aba728a1) we now have a common `NetLogo_Console` entry point to easily run NetLogo headlessly on any platform using the bundled Java.  This will be included in the next NetLogo release.
