### ISSUE TITLE
R extension for NetLogo 6.2

### ISSUE THREAD

**Issue by Rafaela-Lorena** [NetLogo/NetLogo#1911]

**Comment by SethTisue** [comment]
also asked at https://stackoverflow.com/questions/66969629/how-to-install-r-extension-in-netlogo-6-2-windows-10

**Comment by Rafaela-Lorena** [comment]
I resolve the problem! Thanks

**Comment by SethTisue** [comment]
What was the resolution? If you can tell us, the information might be helpful to others in the future.

**Comment by Rafaela-Lorena** [comment]
The problem was in 2 places:
First is the extension of the user file that when making changes to the file and saving it was in .txt and it is to be .properties
And second, correctly edit the System Environment Variable “Path”

**Comment by SethTisue** [comment]
Thank you!
