### ISSUE TITLE
Error reports in 6.2.0 not taking me to the code that triggered the error.

### ISSUE THREAD

**Issue by innovative-simulator** [NetLogo/NetLogo#1917]
I've just switched to 6.2.0 from 6.1.1. Running Windows 10.

When my code triggers errors during execution, as well as putting up a message box with the error, NetLogo should switch to the Code tab (from the User tab) and highlight the bit of code that triggered the error.

This isn't happening in 6.2.0! I get the error message, but I then stay on the User tab and nothing is highlighted in the Code tab. (This makes debugging my code *really* tricky - where to start looking for the bug?!)

Running the same code in 6.1.1 triggers the error message, tab swtich, and code highlighting as normal.

For an example, paste this program into NetLogo 6.2.0 and call test1 from a button or the command center. It attempts to use "of" with a global variable that hasn't been set yet. Once the error is triggered, the word "of" should be highlighted, but it isn't!

```
globals [
  fred
]

to test1
  ; Should cause an error, due to global variable not being set to a turtle.
  ; Should then highlight the word "of" as the position in the code that raised the error.
  ; Does this in 6.1.1 but not in 6.2.0!

  clear-all
  crt 1

;  set fred turtle 0 ; Commented out, so that next line triggers error message.

  user-message [color] of fred
  ; Did NetLogo switch to Code tab and highlight the word "of" for you?
end
```

**Comment by brandesNW** [comment]
Confirmed on MacOS
