### ISSUE TITLE
Error opening .nls file in non-English locale

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#1920]
To reproduce the bug 
Do step 1 only if you are using English as your _User Interface Language_.

1. Set Spanish as the _User Interface Language_ 
    1. Open NetLogo
    2. Open the File->Preferences Dialogue and select Spanish for the _User Interface Language_ (Probably any non-English language will do.)
    3. Click the OK button
    4. Exit NetLogo, there is no need to save the model
    5. Note: After the test you will probably want to use these steps to set your language back to English.

2. Try to open an .nls file
    1. Open NetLogo
    2. Go to the Código (code) tab
    3. Insert the line `__includes[]` at the top of the file
    4. Click the check to compile.
    5. Click on the "Included Files" pulldown, and select "New Source File"

The following error message should appear:
 

> NetLogo is unable to supply you with more details about this error.  Please report the problem 
>  at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
> contents of this window into your report. 
> 
> 
> java.security.PrivilegedActionException: java.security.PrivilegedActionException: java.lang.Exception: No menu named Tabsexists
>  at java.security.AccessController.doPrivileged(Native Method)
>  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
>  at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
>  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
>  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
>  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
>  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
>  at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> Caused by: java.security.PrivilegedActionException: java.lang.Exception: No menu named Tabsexists
>  at java.security.AccessController.doPrivileged(Native Method)
>  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
>  at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
>  at java.awt.EventQueue$4.run(EventQueue.java:733)
>  at java.awt.EventQueue$4.run(EventQueue.java:731)
>  ... 9 more
> Caused by: java.lang.Exception: No menu named Tabsexists
>  at org.nlogo.app.AppTabManager.copyMenuAcceleratorsByName(AppTabManager.scala:323)
>  at org.nlogo.app.Tabs.addMenuItem(Tabs.scala:348)
>  at org.nlogo.app.AppTabManager.addNewTab(AppTabManager.scala:436)
>  at org.nlogo.app.Tabs.addNewExternalFileTab(Tabs.scala:301)
>  at org.nlogo.app.Tabs.openExternalFile(Tabs.scala:293)
>  at org.nlogo.app.codetab.IncludedFilesMenu.$anonfun$populate$4(IncludedFilesMenu.scala:45)
>  at org.nlogo.swing.RichJMenuItem$$anon$13$$anon$14.actionPerformed(Implicits.scala:82)
>  at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
>  at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
>  at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
>  at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
>  at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
>  at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
>  at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
>  at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
>  at java.awt.Component.processMouseEvent(Component.java:6539)
>  at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
>  at java.awt.Component.processEvent(Component.java:6304)
>  at java.awt.Container.processEvent(Container.java:2239)
>  at java.awt.Component.dispatchEventImpl(Component.java:4889)
>  at java.awt.Container.dispatchEventImpl(Container.java:2297)
>  at java.awt.Component.dispatchEvent(Component.java:4711)
>  at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
>  at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
>  at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
>  at java.awt.Container.dispatchEventImpl(Container.java:2283)
>  at java.awt.Window.dispatchEventImpl(Window.java:2746)
>  at java.awt.Component.dispatchEvent(Component.java:4711)
>  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
>  at java.awt.EventQueue.access$500(EventQueue.java:97)
>  at java.awt.EventQueue$3.run(EventQueue.java:709)
>  at java.awt.EventQueue$3.run(EventQueue.java:703)
>  ... 14 more
> 
> NetLogo 6.2.0
> main: org.nlogo.app.AppFrame
> thread: AWT-EventQueue-0
> OpenJDK 64-Bit Server VM 1.8.0_275 (BellSoft; 1.8.0_275-b01)
> operating system: Mac OS X 10.14.6 (x86_64 processor)
> Scala version 2.12.12
> JOGL: (3D View not initialized)
> OpenGL Graphics: (3D View not initialized)
> model: SaveTest
> 
> 05:20:35.472 DirtyEvent (org.nlogo.app.codetab.TemporaryCodeTab) AWT-EventQueue-0
> 05:20:35.470 DirtyEvent (org.nlogo.app.codetab.TemporaryCodeTab) AWT-EventQueue-0
> 05:20:35.300 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
> 05:20:35.300 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
> 05:20:35.097 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
> 05:20:35.097 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
> 05:20:34.891 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
> 05:20:34.891 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
> 05:20:34.690 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
> 05:20:34.690 PeriodicUpdateEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by LaCuneta** [comment]
A little more info:  I ran through the steps to reproduce in NetLogo 6.1.1 and no error occurred, so that indicates that this is a regression in NetLogo 6.2.0.
