### ISSUE TITLE
minimum working example of a Netlogo-headless.sh run.

### ISSUE THREAD

**Issue by mdkeehan** [NetLogo/NetLogo#1923]
I am trying to help a colleague run NetLogo on a HPC cluster. He has some large models that take too long to run on a laptop.
I cannot find a minimal working example of the files needed to run in `headless`  mode.
A small working example in the documentation so that people can test their installation and setup would be very useful to your users.

**Comment by LaCuneta** [comment]
Hey @mdkeehan, thanks for your interest in NetLogo.

There are [some Examples in the BehaviorSpace documentation, in the command line section](http://ccl.northwestern.edu/netlogo/docs/behaviorspace.html#running-from-the-command-line).  The only other item that is necessary is to have a version of Java 8 installed and `JAVA_HOME` environment variable set to point to it.  I do see that those examples mostly use the Fire model, which doesn't actually come with those listed experiments, meaning you cannot run them "as is".

For your purposes, you could add experiments to Fire.nlogo with the matching experiment names to the example commmands and they should run.  Another option is to run the commands with a model that does already have experiments setup.  Here is an example using the Red Queen model from the models library.  This should run "as is" from the NetLogo folder on Linux if everything is setup correctly and you have write access to the home folder on the system (`~`).

```sh
➜  NetLogo 6.2.0 readlink -f `which java`
/usr/lib/jvm/bellsoft-java8-full-amd64/bin/java
➜  NetLogo 6.2.0 export JAVA_HOME=/usr/lib/jvm/bellsoft-java8-full-amd64/
➜  NetLogo 6.2.0 echo $JAVA_HOME
/usr/lib/jvm/bellsoft-java8-full-amd64/
➜  NetLogo 6.2.0 ./netlogo-headless.sh --model "app/models/Curricular Models/BEAGLE Evolution/Red Queen.nlogo" --experiment "Final Counts" --spreadsheet ~/red-queen-output.csv
```

I hope that helps.  I think the examples would be better if they referenced models that had experiments ready to go, and with paths correctly set to the models library.

**Comment by SethTisue** [comment]
> I think the examples would be better if they referenced models that had experiments ready to go, and with paths correctly set to the models library

It would be neat to have a GitHub repo with this all set up, including a GitHub Actions workflow that actually runs it and sees that the results are as expected.

**Comment by Add-mac** [comment]
Hey @LaCuneta 

Thank you for your prompt help

I used the previous example, but, still have the following issues

Exception in thread "main" java.lang.Exception: Unable to open model with current format: /Applications/NetLogo 6.2.0/app/Applications/NetLogo 6.2.0/models/Curricular Models/BEAGLE Evolution/Red Queen.nlogo
	at org.nlogo.api.ModelLoader.readModel(ModelLoader.scala:65)
	at org.nlogo.api.ModelLoader.readModel$(ModelLoader.scala:60)
	at org.nlogo.api.ConfigurableModelLoader.readModel(ModelLoader.scala:106)
	at org.nlogo.headless.HeadlessWorkspace.open(HeadlessWorkspace.scala:502)
	at org.nlogo.headless.Main$.newWorkspace$1(Main.scala:18)
	at org.nlogo.headless.Main$.runExperiment(Main.scala:21)
	at org.nlogo.headless.Main$.$anonfun$main$1(Main.scala:12)
	at org.nlogo.headless.Main$.$anonfun$main$1$adapted(Main.scala:12)
	at scala.Option.foreach(Option.scala:407)
	at org.nlogo.headless.Main$.main(Main.scala:12)
	at org.nlogo.headless.Main.main(Main.scala)

**Comment by LaCuneta** [comment]
@Add-mac That error is the one you'd get for a model file not found ([there is an open issue to improve that error message](https://github.com/NetLogo/NetLogo/issues/1862)).  This path `/Applications/NetLogo 6.2.0/app/Applications/NetLogo 6.2.0/models/Curricular Models/BEAGLE Evolution/Red Queen.nlogo` does not look right.  

Assuming NetLogo is installed to `/Applications/`, then it should be `/Applications/NetLogo 6.2.0/app/models/Curricular Models/BEAGLE Evolution/Red Queen.nlogo`.  Is that what you're passing as the `--model` parameter?

**Comment by Add-mac** [comment]
I also saved the fire model form Netlogo library by following "https://ccl.northwestern.edu/netlogo/docs/behaviorspace.html" and enabled to run it. The problem I had was I closed the program before affecting the change I have made. So, once the experiment setup finished, the change should be saved.

**Comment by Add-mac** [comment]
Hey @LaCuneta 

Thanks for your help!

it works as follow:

add@add-air add %  ./netlogo-headless.sh --model "/Applications/NetLogo 6.2.0/models/Curricular Models/BEAGLE Evolution/Red Queen.nlogo" --experiment "Final Counts" --table -

**Comment by mdkeehan** [comment]
Hi Guys,

Thanks for your help. After trying for an hour or so to figure out the documentation, I posted my grumble to github and then off course it all came clear. Perhaps if the documentation just has the two commands lines as suggested above added as exampels that would have been sufficient. They both worked for me when ran from the installation directory i.e.
```bash
./netlogo-headless.sh --model "app/models/Curricular Models/BEAGLE Evolution/Red Queen.nlogo" --experiment "Beta2" --table -
./netlogo-headless.sh --model "app/models/Curricular Models/BEAGLE Evolution/Red Queen.nlogo" --experiment "Final Counts" --table -
```
Looking at the ``Red Queen.nlogo`` file  shows an example of the embedded xml to specify the experiments.
The Fire.nlogo also works with a separate experiment.xml file as I eventually understood from the documentation:
```bash
someone@somemachine:~/somedir$ cat experiments.xml 
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE experiments SYSTEM "behaviorspace.dtd">
<experiments>
  <experiment name="experiment" repetitions="10" runMetricsEveryStep="true">
    <setup>setup</setup>
    <go>go</go>
    <exitCondition>not any? fires</exitCondition>
    <metric>burned-trees</metric>
    <enumeratedValueSet variable="density">
      <value value="40"/>
      <value value="0.1"/>
      <value value="70"/>
    </enumeratedValueSet>
  </experiment>
</experiments>
someone@somemachine:~/somedir$ ./netlogo-headless.sh --model "app/models/Sample Models/Earth Science/Fire.nlogo" --setup-file experiments.xml --table fire.out.txt
```
So my problem has been solved. Thank you all.
