### ISSUE TITLE
Save with detached code tab moves code tab behind

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#1955]
•	Open a new model or existing model
•	Detach the code tab
•	Move code tab to partially overlap main app window
•	Make a change in the code tab: e.g. add or change a procedure
•	Go to the code tab and hit save hot key (CMD+S in MacOS) [Provide name if saving new file.]
•	The code tab will move behind the main window.

**Comment by LaCuneta** [comment]
This behavior happens in macOS but not in Windows 11 in my testing.  It has also been present since NetLogo 6.2.0.
