### ISSUE TITLE
Pop-out code tab unusable when popped out from maximized window

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#1956]
This behavior might be particular to Windows (and Linux?).  I confirmed the issue does not happen in 6.2.0.

- Open NetLogo 6.2.1-beta1. 
- Maximize the NetLogo window.
- Switch to the code tab, press the **Code tab in separate window** checkbox.
- The code tab window pops out, but then is immediately hidden.  You can see it in the task switcher (Alt-Tab) or in the taskbar by clicking on the NetLogo icon, but selecting the window in either view just brings up the main NetLogo window, not the code tab window.

I suspected the problem was the code tab window was offscreen, and that turned out to be the case.

- After following the above steps, click the NetLogo icon in the taskbar, then click the code tab window.  It did not appear.
- Press Alt-Space to bring up the window controls, and they did appear on the right side of the screen.
- Select Move and then left-arrow until the code tab window was in view.

**Comment by brandesNW** [comment]
![MaxNetLogoWithDetachedCodeTabMac](https://user-images.githubusercontent.com/56969066/136076320-f5194baa-6790-4b43-80aa-0eb88b44b3b8.png)
