### ISSUE TITLE
require (and bundle) Oracle Java for Mac OS X users

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#197]
this may require some care about whether there are any behavior or look & feel regressions on Java 7. I don't think any of us have done any testing (yet, as of April 2013 — ST)

our sbt script should probably be updated to use Java 7 by default, instead of 6

not sure, but it might be better to postpone this until 5.1, so that if there are any regressions, they are associated with a big release rather than a bugfix release?

also I suggest we start _requiring_ Java 7 at the same time we start bundling it, to cut down our overall support burden, and that would definitely be a 5.1 change. requiring Java 7 would mean dropping support for OS X 10.6. (the minimum OS version for Java 7 is 10.7.3)

there are three kinds of associated support burden:

 * supporting different styles of building and packing (since if we don't require Java 7, we'll need to have two NetLogo downloads for Mac, one for Java 6 and another for Java 7, with ongoing costs for offering and maintaining both)
 * supporting users across a broader variety of setups
 * Java 7 has many nice API improvements. in general, staying on older Java versions means we as developers can't have nice things. and there's a cognitive burden with remembering what we can and can't use in our code

**Comment by SethTisue** [comment]
these days it'd be Java 8, of course

**Comment by SethTisue** [comment]
I'm pleased to see that http://www.randelshofer.ch/quaqua/ is still maintained. at least, there was a release in 2014. that release claims to support Java 8

**Comment by mrerrormessage** [comment]
Per your comment from Feb, 2014 - I have upgraded the version of jogl on the `java8-packaging` branch (cut from 5.x) and it has worked just find for me so far. I don't know whether it would be alright to go in the app store or not, but I haven't yet run into any problems running it locally.

**Comment by mrerrormessage** [comment]
5.2.2 will upgrade quaqua as well as bundling java 8.
