### ISSUE TITLE
Migrate to Scala.js v1

### ISSUE THREAD

**Issue by EwoutH** [NetLogo/NetLogo#1976]
A lot of dependency updates, including Scala 2.12.15 and ScalaCheck 1.15.4, require a newer version of [scala-js](https://github.com/scala-js/scala-js). We're currently on [v0.6.33](https://github.com/scala-js/scala-js/releases/tag/v0.6.33), and need to update to the v1 series of releases. I have a test [branch](https://github.com/EwoutH/NetLogo/tree/update/sbt-scalajs-1.7.1) and [PR](https://github.com/EwoutH/NetLogo/pull/20) here, and the CI is currently [stuck here](https://github.com/EwoutH/NetLogo/runs/4105959044?check_suite_focus=true#step:6:200).

```
/home/runner/work/NetLogo/NetLogo/build.sbt:306: error: value toScalaJSGroupID is not a member of object org.scalajs.sbtplugin.ScalaJSPlugin.autoImport
      import org.scalajs.sbtplugin.ScalaJSPlugin.autoImport.toScalaJSGroupID
             ^
Error:  sbt.compiler.EvalException: Type error in expression
Error:  Use 'last' for the full log.
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
Error: Process completed with exit code 1.
```

Scala.js has a migration guide here: [Announcing Scala.js 1.0.0](http://www.scala-js.org/news/2020/02/25/announcing-scalajs-1.0.0/).

Part of: #1968

**Comment by SethTisue** [comment]
what happens if you simply remove that import?

**Comment by EwoutH** [comment]
Tried it [here](https://github.com/EwoutH/NetLogo/actions/runs/1421813764), by changing `toScalaJSGroupID` to `_`, and it got a lot further.

Now we [are stuck](https://github.com/EwoutH/NetLogo/runs/4106529997?check_suite_focus=true#step:5:455) on the fact that the maven repository [doesn't have](https://repo1.maven.org/maven2/org/scalatest/scalatest_sjs1_2.12/) a scalatest 3.0.5 build for Scala.js 1 on Scala 2.12. That means #1974 needs to be fixed first.
```
[warn] 	Note: Unresolved dependencies path:
Error:  sbt.librarymanagement.ResolveException: Error downloading org.scalatest:scalatest_sjs1_2.12:3.0.5
Error:    Not found
Error:    Not found
Error:    not found: /home/runner/.ivy2/local/org.scalatest/scalatest_sjs1_2.12/3.0.5/ivys/ivy.xml
Error:    not found: https://repo1.maven.org/maven2/org/scalatest/scalatest_sjs1_2.12/3.0.5/scalatest_sjs1_2.12-3.0.5.pom
Error:    not found: https://oss.sonatype.org/content/repositories/releases/org/scalatest/scalatest_sjs1_2.12/3.0.5/scalatest_sjs1_2.12-3.0.5.pom
Error:  Error downloading org.scalacheck:scalacheck_sjs1_2.12:1.13.5
Error:    Not found
Error:    Not found
Error:    not found: /home/runner/.ivy2/local/org.scalacheck/scalacheck_sjs1_2.12/1.13.5/ivys/ivy.xml
Error:    not found: https://repo1.maven.org/maven2/org/scalacheck/scalacheck_sjs1_2.12/1.13.5/scalacheck_sjs1_2.12-1.13.5.pom
Error:    not found: https://oss.sonatype.org/content/repositories/releases/org/scalacheck/scalacheck_sjs1_2.12/1.13.5/scalacheck_sjs1_2.12-1.13.5.pom
```
