### ISSUE TITLE
Compilation error in JFlexRunner.scala when building with JFlex 1.5+

### ISSUE THREAD

**Issue by EwoutH** [NetLogo/NetLogo#1984]
When building with JFlex 1.5 or newer, it suddenly can't seem to find JFlex anymore, and the [following error](https://github.com/EwoutH/NetLogo/runs/4164358300?check_suite_focus=true#step:6:197) presents itself on compilation. The error is identical for JFlex 1.5.1, 1.6.1 and 1.8.2.
```
Error:  /home/runner/work/NetLogo/NetLogo/project/JFlexRunner.scala:30:5: not found: value JFlex
Error:      JFlex.Main.main(Array("--quiet", "-d", cacheDirectory.getPath, (autogenFolder / "flex" / (kind + ".flex")).asFile.getAbsolutePath.toString))
Error:      ^
Error:  one error found
Error:  (Compile / compileIncremental) Compilation failed
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
Error: Process completed with exit code 1.
```
The error is located in [project/JFlexRunner.scala](https://github.com/NetLogo/NetLogo/blob/6.2.1/project/JFlexRunner.scala#L30). JFlex can be updated in [project/plugins.sbt](https://github.com/NetLogo/NetLogo/blob/6.2.1/project/plugins.sbt#L28).

Part of #1968.

**Comment by SethTisue** [comment]
PR: #2004
