### ISSUE TITLE
Models library fails to open on some systems

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#2008]
In NetLogo 6.2.2, when the system language/locale is a set to something other than English/US, the models library window can fail to open; clicking the menu option or using the hotkeys causes a short loading screen to popup, but it vanishes and you're back at the main NetLogo interface.

The root cause is an uncaught exception when trying to get a language file in the default system language.  If the default system language is English, all works fine, but if not the library can fail to load.  The fix is coming shortly.

There are two workarounds for this issue:

1. Switch the UI language for NetLogo to English in its preferences (**Tools** > **Perferences...**).  This is the simplest method, but if you prefer to keep NetLogo's interface in a different language, see option 2.
2. Edit the `NetLogo.cfg` file and add the two lines below to the `[JVMOptions]` section.  The [file's location depends on your operating system](http://ccl.northwestern.edu/netlogo/docs/faq.html#where-is-cfg-file): in the `NetLogo 6.2.2/app/` folder on Windows/Linux and inside the `NetLogo 6.2.2.app` container on macOS at `NetLogo 6.2.2.app/Contents/Java/` (right-click the app and **Show Package Contents** to access the folders inside).

```
-Duser.language=en
-Duser.country=US
```

When done the `[JVMOptions]` section should look like this:

```
[JVMOptions]
-Xmx1024m
-XX:+UseParallelGC
-Dfile.encoding=UTF-8
-Duser.language=en
-Duser.country=US
```

After this is done you can select a different interface language in the NetLogo preferences, and it will change to that on restart.

**Comment by LaCuneta** [comment]
Fixed here:  https://github.com/NetLogo/NetLogo/commit/331adea38b3ea83a24ede3e0eda10c07b402b1be

**Comment by eccstartup** [comment]
Where do I locate this file on MacOS?

**Comment by LaCuneta** [comment]
From [the NetLogo FAQ](http://ccl.northwestern.edu/netlogo/docs/faq.html#how-big-can-my-model-be-how-many-turtles-patches-procedures-buttons-and-so-on-can-my-model-contain): 

> Mac OS X: The file for NetLogo will be located at: /Applications/NetLogo 6.2.2/NetLogo 6.2.2.app/Contents/Java/NetLogo.cfg For NetLogo 3D and the other applications, you will find the file in the corresponding location for each application package. You can reach the cfg file by control-clicking the application in the Finder and choosing “Show Package Contents” from the popup menu.

**Comment by eccstartup** [comment]
@LaCuneta Thanks! I now understand that a quick fix is to modify the `NetLogo.cfg` file.
