### ISSUE TITLE
Unknown option -C when building netlogo

### ISSUE THREAD

**Issue by AgnesResto** [NetLogo/NetLogo#2015]
I'm following the build instructions (https://github.com/NetLogo/NetLogo/wiki/Building), and I get the error in the attached image.
The ./sbt all continues after the error appears and finishes doing everything, but I can't find the NetLogo6.0.4.app. 

<img width="854" alt="image" src="https://user-images.githubusercontent.com/43544010/154567387-600e2216-514e-46e1-b7e7-daa27f97130b.png">

I'm working on a Linux system (centOS) with Liberica OpenJDK 8

**Comment by LaCuneta** [comment]
Thanks for your interest in NetLogo development.

What version of `git` is on your system?  `git --version`?  NetLogo is [trying to use `git -C <path>` to set the working directory for the extension builds](https://github.com/NetLogo/NetLogo/blob/hexy/project/Extensions.scala#L76), which is supported [per the git docs](https://git-scm.com/docs/git).  I've got git 2.25.1 running on my system and it works fine with the NetLogo build.

**Comment by AgnesResto** [comment]
Oh, I see. I checked and I have version 1.8.3.1. I'll update it and hopefully it will work. Thanks!
