### ISSUE TITLE
During a slider Edit, the value is constrained by original range.

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#2025]
If you edit a slider, changing the range, and if you also change the Current Value to a number that is outside the original range but valid in the new range, the edit on Current Value will fail.  That is, the OLD range is taken as the valid limits, and the new Current Value is “clamped” to that old range.

Identified by Corey Brady and verified by Aaron Brandes

**Comment by brandesNW** [comment]
Reproducible in NetLogo 5.3.1

**Comment by LaCuneta** [comment]
Fixed by #2040
