### ISSUE TITLE
NetLogo 6.2.2 fail to launch in Ubuntu 20.04

### ISSUE THREAD

**Issue by lionel68** [NetLogo/NetLogo#2042]
Dear All,

I downloaded and installed NetLogo6.2.2-64 on my Ubuntu 20.04 machine. When I go to the folder with all untarred files and run

./NetLogo 

I get

NetLogo Error invoking method.
NetLogo Failed to launch JVM

Could you help me?

**Comment by brandesNW** [comment]
Hi,
Sorry you ran into this problem.
Try running ./netlogo-gui.sh
The script sets the correct environment variables and runs the app using the java command.
Using a file manager and double-clicking on the NetLogo icon should also work.
Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: lionel68 ***@***.***>
Reply-To: NetLogo/NetLogo ***@***.***>
Date: Wednesday, July 27, 2022 at 8:18 AM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] NetLogo 6.2.2 fail to launch in Ubuntu 20.04 (Issue #2042)


Dear All,

I downloaded and installed NetLogo6.2.2-64 on my Ubuntu 20.04 machine. When I go to the folder with all untarred files and run

./NetLogo

I get

NetLogo Error invoking method.
NetLogo Failed to launch JVM

Could you help me?

**Comment by lionel68** [comment]
Thanks for your reply. I am however starting my NetLogo models from a server without a GUI. I had a go with netlogo-headless and it worked for me.

**Comment by LaCuneta** [comment]
Glad to hear the headless script worked for you!  Thanks for following up.
