### ISSUE TITLE
Models library is not shown if NetLogo is in a different language than English

### ISSUE THREAD

**Issue by cienciascontic** [NetLogo/NetLogo#2043]
Hi,
I reported this issue in the past but couldn't find the thread now, so I'm opening a new issue. I'm using NetLogo with Spanish interface and the library models is not opening. I'm using Mac OS Monterrey with M1 processor. Thanks for your support.

**Comment by LaCuneta** [comment]
See [this issue](https://github.com/NetLogo/NetLogo/issues/2008), which contains a couple of workarounds to get it working again.  Feel free to leave a comment there if you have questions getting it resolved.
