### ISSUE TITLE
<breed>-at reporter drops dz offset in 3D?

### ISSUE THREAD

**Issue by DOSull** [NetLogo/NetLogo#2046]
The following code:
```
breed [bugs bug]

to setup 
  clear-all
  ask patch 0 0 0 [
    sprout-bugs 1  ;; who 0
    ask neighbors6 [sprout-bugs 1]
  ]
  ask patch 3 3 3 [
    sprout 1  ;; who 7
    ask neighbors6 [sprout 1]
  ]
  ask bug 0 [
    show sort bugs-at 0 0 1
    show sort bugs-at 0 0 -1
  ]
  ask turtle 7 [
    show sort turtles-at 0 0 1
    show sort turtles-at 0 0 -1
  ]
end
```

Produces the following erroneous output

```
(bug 0): [(bug 0)]          ;; itself not the bug at 0 0 1
(bug 0): [(bug 0)]          ;; itself not the bug at 0 0 -1
(turtle 7): [(turtle 12)]
(turtle 7): [(turtle 13)]
```
I.e., `<breed>-at 0 0 1` or `breed-at 0 0 -1` seems to be interpreted as `<breed>-at 0 0`

**Comment by LaCuneta** [comment]
Thank you for the detailed report with the nice example code.  And sorry you ran into this issue.  I've confirmed the bug and we'll look into getting it fixed.

There is fortunately a simple workaround (which you may have already discovered), just use `turtles-at x y z with [breed = my-breed]`:

```
  ask bug 0 [
    show sort (turtles-at 0 0 1) with [breed = bugs]
    show sort (turtles-at 0 0 -1) with [breed = bugs]
  ]
```

If you use this kind of code a lot in your model it might be worth making a reporter procedure:

```
; necessary due to bug in `<breed>-at`
to-report breed-at [b x y z]
  report (turtles-at x y z) with [breed = b]
end

; used like so...
  ask bug 0 [
    show sort breed-at bugs 0 0 1 
    show sort breed-at bugs 0 0 -1 
  ]
```

**Comment by DOSull** [comment]
No problem - easy workaround - in my case I only have one breed at any given location so I can get away with turtles-at, but thanks for the suggestion!

**Comment by SethTisue** [comment]
Great catch, much appreciated.
