### ISSUE TITLE
Incorrect display of Close Command Center and Open Command Center in Tools Menu

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#2051]
**The problem is that the Tools menu is not updated when a closed command center is opened by `Jump to Command Center` or opening a new model**

*To reproduce: Version 1*

1. Open NetLogo (or just have the command center open, and `Close Command Center `  visible in the Tools menu)
2. Close command center via `Tools-> Close Command Center ` or hotkey (`ctrl-\` or `cmd-\`)
3. Jump to command center via `Tools-> Jump to Command Center` or hotkey (`ctrl-shift-C` or `cmd-shift-C`)

The Command Center will now be open, but the Tools menu choice is Open Command Center 

*To reproduce: Version 2*

1. Open  NetLogo
2. Close command center via `Tools-> Close Command Center ` or hotkey (`ctrl-\` or `cmd-\`)
3. Open a new model

The Command Center will now be open, but the Tools menu choice is Open Command Center

**Comment by ERSUCC** [comment]
@brandesNW See pull request #2268 for a fix. I was able to confirm that the issue you reported was still present in 6.4, and I also found that the same inconsistency occurred when using the JSplitPane controls, like dragging the bar or clicking the arrows. This fix should apply to all such places, but let me know if there is still a situation where it doesn't work, and I can fix it.
