### ISSUE TITLE
The preference "Reload the last used model on startup" does not take account of whether that model is appropriate (2D or 3D).

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#2054]
To reproduce:

1. Open NetLogo
2. Open a model
3. In the NetLogo->Preferences window ensure that the "Reload the last used model on startup" option is selected.
4. Open NetLogo 3D

It will open the previous NetLogo model, and then pop up a Dialog that says "You are attempting to open a 2D model in NetLogo 3D 6.3.0. You might need to make changes before it will work in 3D." You have the option to Cancel or Continue.

A similar problem arises if you open a 3D model in NetLogo 3D and then open NetLogo.

The appropriate behavior is for NetLogo to open the most recent .nlogo file and for NetLogo 3D to open the most recent .nlogo3d file.

**Comment by LaCuneta** [comment]
Fixed in #2255
