### ISSUE TITLE
Add about panel for netlogo desktop

### ISSUE THREAD

**Issue by dongxuwang** [NetLogo/NetLogo#2075]
Currently it's a default panel without any information display.

**Comment by brandesNW** [comment]
Hi,
We are sorry you have encountered this problem. Checking that the About NetLogo panel has correct information is something we do on Windows, MacOS and linux before every release. I just checked again on my MacOS system running NetLogo 6.3.0.  Could you please share the NetLogo version you are running, as well as your OS.
If you are not running NetLogo 6.3.0 I suggest you download and install it from https://ccl.northwestern.edu/netlogo/download.shtml.
If you are running NetLogo 6.3.0 uninstalling it and reinstalling it from a new download might help.

  *   Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Dongxu Wang ***@***.***>
Date: Monday, January 16, 2023 at 6:32 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetLogo/NetLogo] Add about panel for netlogo desktop (Issue #2075)

Currently it's a default panel without any information display.

**Comment by dongxuwang** [comment]
Oh yes, I built&run it from source in which there is nothing but version. I checked the downloaded version and sure the about panel looks good. 

So we can close this, thank you.
