### ISSUE TITLE
NetLogo 6.3.0 not running on Ubuntu 20.04

### ISSUE THREAD

**Issue by jpearl-003** [NetLogo/NetLogo#2079]
Hello,
I am having running the executable file on my Ubuntu vm. 

My steps taken were:
Download the 64bit version of NetLogo 6.3.0 from https://ccl.northwestern.edu/netlogo/download.shtml

I then extract the file into  ~/ NetLogo 6.3.0
$ tar -xf ~/Downloads/NetLogo-6.3.0-64.tgz

In the folder I then try to run NetLogo
$ ./NetLogo

I then am presented with this prompt
$ ./NetLogo: 2: ./bin/NetLogo: Exec format error

Architecture: aarch64
Java: openjdk 11.0.17

**Comment by LaCuneta** [comment]
It may be that it's having trouble locating the basic shell (the file in the root of the NetLogo install is just a shell script).  You can either change that shell script to reference a shell you know will work on your system (maybe `#!/bin/bash`?), or you can run `./bin/NetLogo` to run the actual binary.

Let me know if neither of those work for you.

**Comment by LaCuneta** [comment]
Ah, shoot, I missed the `aarch64`.  So.  That'll be a bit different.  You'll need to make sure you have the correct Java set, then use `./netlogo-gui.sh` to run NetLogo with your path Java.  If you have a `JAVA_HOME` set the script will try to look there first.  We have not tested NetLogo with Java 11 or on ARM on Linux, so I'm definitely interested to hear if that works for you.

**Comment by jpearl-003** [comment]
Setting the JAVA_HOME path works. I had no issue with my architecture or with Java 11. Thanks for the help.

**Comment by LaCuneta** [comment]
Glad it worked for you.  Thanks for letting us know!
