### ISSUE TITLE
Widgets can use primitive names for variables, causing a Behavior Space issue

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#2084]
The compiler will not allow a global in the code to have the same name as a primitive. However this is not true for a widget. If the code invokes a primitive that shares a name with a widget variable it will fail in a BehaviorSpace experiment when more than one thread is used. Some sort of overwriting probably occurs.
The resulting error message is obscure. For the attached model it is

`SET expected 2 inputs. at position 33 in ...`
[BS-random-seed-error.nlogo.zip](https://github.com/NetLogo/NetLogo/files/10770032/BS-random-seed-error.nlogo.zip)

**Comment by SethTisue** [comment]
nice catch!

**Comment by LaCuneta** [comment]
I think this is a duplicate of #1604, unless you want to consider how BehaviorSpace obscures that error message as a separate issue.

**Comment by brandesNW** [comment]
Closed as duplicate. Added info to #1604
