### ISSUE TITLE
BehaviorSpace (NetLogo 6.3.0) Experiment specification: "Invalid Settings" alert issues

### ISSUE THREAD

**Issue by balanco** [NetLogo/NetLogo#2094]
In BehaviorSpace for NetLogo 6.3.0 (September 29, 2022) (macOS),
the _Invalid Settings_ alert reporting of invalid variable value settings has the following issues:

_Use case:_

For the bad entry in the section **Vary variables as follows (note brackets and quotation marks):**
`["bla" [1 2 3 4 5]]`

upon clicking the **OK** button of the **Experiment** dialog, the following alert is displayed:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/2210852/224993799-a93e6587-7796-4995-a2a4-b6fa4a0e84d8.png">

_Issues in the **Invalid Settings** alert:_
1. In the "Variable: …" line, the _name_ of the variable in question is not displayed
2. In the "Variable: …" line, there is a typo: "Invaid" should read "Invalid"  _(i.e., missing lower-case "L")_

&lt;EOT&gt;

**Comment by LaCuneta** [comment]
@balanco Thank you so much for the detailed error report!  I've fixed the two issues you described and the changes will be included in the next release of NetLogo.
