### ISSUE TITLE
incorrect multi-line input bracket and parenthesis highlight

### ISSUE THREAD

**Issue by turtlemaniac** [NetLogo/NetLogo#210]
Sometimes bracket and parenthesis highlighting works incorrectly in multi-line input field while changing it.
Opening a new model, making a multi-line input containing a line brake before [] always visualizes the glitch for me. For unknown reasons the glitch disappears sometimes.

System:
NetLogo 5.0.2 (July 27, 2012)
Extension API version: 5.0
Java HotSpot(TM) Server VM 1.6.0_33 (Sun Microsystems Inc.; 1.6.0_33-b03)
operating system: Windows XP 5.1 (x86 processor)
Scala version 2.9.2
Java heap: used = 8 MB, free = 11 MB, max = 494 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

**Comment by Idloj** [comment]
It works fine for me(or I don't completely understand how you reproduce it)

**Comment by Idloj** [comment]
Seems to work fine on NetLogo 6.0.1

**Comment by mrerrormessage** [comment]
Agreed, this seems to work fine in 6.0.1.
