### ISSUE TITLE
Disable error-checking on tab switching

### ISSUE THREAD

**Issue by arcpaolo** [NetLogo/NetLogo#2111]
Whenever the user switches tabs (e.g., from code to info, or when there are include files), NetLogo automatically tries to do error-checking, and moves the focus where errors are found. 

This is extremely annoying when writing code with include files, or when adding interface elements. It is also dangerous because it highlights allegedly incorrect code, which can lead to accidental deletion. Also the insertion point can be quite far from the spot being edited (for instance a long block without a closing bracket will move the focus all the way to the opening bracket).

This feature should be removed or at least create an option to disable it. Checking for errors with the manual checkbox, when trying to run, and when saving should be more than adequate.

Note that a discussion was started on this topic on the NetLogo community mailing list, and several people agreed this is really annoying.

Thanks.

**Comment by SethTisue** [comment]
> a discussion was started on this topic on the NetLogo community mailing list,

link?

**Comment by arcpaolo** [comment]
https://groups.google.com/g/netlogo-users/c/FljzTaDXKNs/m/NxLIFg7NBAAJ

**Comment by arcpaolo** [comment]
And a further related request: error-checking should also be disabled (or at least optional) on save.

I am in the middle of making some substantial changes to my code, where I know that I may have to write dozens of lines of code before it will work (meaning before it will become error-free). Sometimes I want to save the stuff I have typed as I go along. When I do this, it invariably takes me away from where I was typing to some other random place where the error is occurring, often in a different tab altogether.

But even with a single-file program this is super-annoying. For example, I am in the process of making several changes to variable names in a <breeds>-own block: creating some new variables, removing some old ones, renaming some, moving things around to make it more coherent.

If I am in the middle of this and I hit "command-save" (which I am prone to do frequently out of habit), the error checker will immediately drag me to some random part of the code where one (I am guessing the first instance) of the removed/renamed variables happens to be. Now I have no idea where I am, I have to navigate back to the <breeds>own statement and figure out where I was and what I was doing. Even with a single file (which I often have hundreds of lines of code), this is really really really annoying. Enough so that I am taking time in the middle of a gnarly coding project to write these comments here.

PLEASE TURN OFF AUTOMATIC ERROR CHECKING OR AT LEAST MAKE IT CONFIGURABLE!

**Comment by ERSUCC** [comment]
@arcpaolo I think automatic error checking is pretty important, and making it manual instead of automatic would be a breaking change and probably confuse some people. As a compromise, I made a preference option that when unchecked would prevent the text or tab that produced the error from stealing focus from your current position. Hopefully this is a satisfactory solution!

**Comment by brandesNW** [comment]
@arcpaolo I think that NetLogo 6.4.0 has fixed the problem of compilation happening if you switch windows from the code tab to a different application and then back back to the code tab.

**Comment by brandesNW** [comment]
This issue will be closed by  https://github.com/NetLogo/NetLogo/pull/2261 so "deleting a widget while there is a parse error in the code tab will also trigger the auto error checking and switch back to the code tab to highlight the error." should become new issue.

**Comment by brandesNW** [comment]
fixed by 2261
