### ISSUE TITLE
Unable to save included file being edited in separate window 

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#2113]
To reproduce:

1. Open a model with an `__includes` file
2. In the code tab, click the "Included Files" drop down and click on one of the files to open up the nls file for editing.
3. Check "Code Tab in separate window" in the code tab
4. Edit the nls file in the now separated window
5. Hit the save hotkey

Expected:

The nls file to save and to recompile.

Actual:

The editor window weirdly changes its title to the main model file instead of the nls file. The nls file neither saves nor recompiles. I'm guessing that the model file is, in fact, being saved and recompiled instead.

Workaround:

After editing the nls file, re-attach the editor tabs to the main window, select the nls file tab, and then hit save.

**Comment by brandesNW** [comment]
I have verified that this is a bug.
The model file is being saved when you hit the save hotkey, as can be seen by changing something in the Interface, Info or Code tab and then performing the steps above. Next quit or reopen the model. You will be asked to save the nls file, but not the model file.

Another workaround is to click the _close_ button in the nls file tab. You will be offered a chance to save the file, and that will work. Reopen the nls file if desired.

**Comment by brandesNW** [comment]
Fixed by https://github.com/NetLogo/NetLogo/pull/2270
