### ISSUE TITLE
stopped netlogo window content visualization

### ISSUE THREAD

**Issue by turtlemaniac** [NetLogo/NetLogo#212]
Sometimes the whole netlogo window content visualization stops. Minimizing and maximizing the netlogo window instantly resolves the glitch. It seems that everything still works normally apart from visualization.

This glitch happens randomly and i am unable to reproduce it.

System:
NetLogo 5.0.2 (July 27, 2012)
Extension API version: 5.0
Java HotSpot(TM) Server VM 1.6.0_33 (Sun Microsystems Inc.; 1.6.0_33-b03)
operating system: Windows XP 5.1 (x86 processor)
Scala version 2.9.2
Java heap: used = 9 MB, free = 12 MB, max = 494 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

**Comment by mrerrormessage** [comment]
Closing due to age. If this issue is observed again under NetLogo 5.3, please comment and we can reopen.
