### ISSUE TITLE
Why does a statistical code change the calculation result of the procedure？

### ISSUE THREAD

**Issue by oscarbi** [NetLogo/NetLogo#2128]
I've got a problem in running the codes below in Netlogo 6.6.2.  the procedure "go" and "go-test" are almost the same. I only add "show sum [b] of turtles " in "go" procedure.  The problem is that the monitor reports variable "sum-b" in the interface reports different numbers after the second ticks under the two procedures.  

I wonder if the codes of computing will change the running process.
```
turtles-own [b]
to setup
  ca
  random-seed 123
  create-turtles 10 [set b 0]

end

to go
  ask turtles [set b b + random-float 1]
  show sum [b] of turtles
end

to go-test
 ask turtles [set b b + random-float 1]
end

to-report sum-b
  report sum [b] of turtles
end
```

**Comment by SethTisue** [comment]
Sounds like you're looking for [with-local-randomness](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#with-local-randomness)

**Comment by oscarbi** [comment]
Thanks SethTIsue! Very valuable suggestion. it works well when I include "with-local-randomness" in the previous procedure. it has been troubling me for weeks. Thanks again.
