### ISSUE TITLE
Using a constant as a global variable name gives unclear closing bracket error

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#2131]
This is similar to #1604 , but different enough that I'd expect the fix to be different, too.

You can create a declaration like `globals [ a b c d e f g ]` in a NetLogo model, and the compiler error you will see is "closing bracket expected" with the `e` highlighted.  This, of course, doesn't make any sense and it takes some thinking to realize what's going on.  This only affects constants, so I believe just `e` and `pi`.  Actual reporters like `max-pxcor` give a more reasonable "There is already a primitive called..." error.

**Comment by ERSUCC** [comment]
@LaCuneta See pull request #2259, I made some changes to fix this and some related issues. #1604 still seems to be an issue, so I'll check that out next.
