### ISSUE TITLE
How to use the command with-local-randomness correctly?

### ISSUE THREAD

**Issue by oscarbi** [NetLogo/NetLogo#2178]
I'v got confused by the command with-local-randomness in Netlogo version 6.2.2. In the codes below, I build one setup and two "go" procedures--go and go-test. 

The codes go like this:
```
to setup
  ca
  random-seed 123
  create-turtles 10 [ set color white  ]
end

to go
  ask n-of 3 turtles [ set color red ]
  show [who] of turtles with [color = red]
end

to go-test
  ask n-of 3 turtles [ set color red   ]
  with-local-randomness [
    show [who] of turtles with [color = red]
  ]
end
```
The results running 5 times are below:
```
observer> setup repeat 5 [go]
observer: [6 3 1]
observer: [6 3 1 0 5]
observer: [0 8 6 2 5 1 7 3]
observer: [6 5 4 8 0 3 9 7 1 2]
observer: [4 8 1 9 7 5 0 3 2 6]

observer> setup repeat 5 [go-test]
observer: [6 3 1]
observer: [7 3 1 0 6]
observer: [6 0 3 1 7]
observer: [4 3 1 0 5 7 6]
observer: [0 1 4 5 6 7 3]
```
I thought that with-local-randomness only applies to its own codes in [ ]. But it seems to change the codes outside [ ]. 
In this case, should I include with-local-randomness in my codes?  In more general situations, in what situations I should consider to employ this command? Thanks

**Comment by SethTisue** [comment]
`with-local-randomness` is behaving as designed here; there's no bug.

In your original `go` procedure, `show [who] of turtles with [color = red]` alters the state of the random number generator, since the agentset is iterated in random order. Surrounding it with `with-local-randomness` prevents it from doing so, changing the outcome.

`with-local-randomness` allows you to insert debug output without changing the overall outcome. But that isn't what you did here; your comparison point (the original `go`) has the debugging output already in it.

**Comment by oscarbi** [comment]
Big thanks to you SeThTisue! Honestly, this command has been troubling me for months. 

Why I consider this command is just because I notice the difference between the results shown in the interface and the results exported in the form of txt. I quite often use the command "set" or "let" to generate new variables related to some turtles, like "set variable sum [ ] of turtles". 

To reproduce the same simulation result, I usually set random-seed in the beginning. Thus, if I am to obtain the correct data during simulation, shall I include "with-local-randomness" wherever "set"\"let" \"show" appear in the codes? Or, in general, what commands will lead to the changes of random number generator and we should thus bring in with-local-randomness? 

Looking forward to your response. Thanks in advance!

**Comment by oscarbi** [comment]
Big thanks to you SeThTisue! Honestly, this command has been troubling me for months. 

Why I consider this command is just because I notice the difference between the results shown in the interface and the results exported in the form of txt. I quite often use the command "set" or "let" to generate new variables related to some turtles, like "set variable sum [ ] of turtles". 

To reproduce the same simulation result, I usually set random-seed in the beginning. Thus, if I am to obtain the correct data during simulation, shall I include "with-local-randomness" wherever "set"\"let" \"show" appear in the codes? Or, in general, what commands will lead to the changes of random number generator and we should thus bring in with-local-randomness? 

Look forward to your response. Thanks in advance!

**Comment by SethTisue** [comment]
Well, perhaps someone else will answer. There isn’t a NetLogo bug here. I usually limit myself to responding about bugs.

**Comment by oscarbi** [comment]
Thanks again for your reply.

**Comment by SethTisue** [comment]
Perhaps you've read it already, but https://ccl.northwestern.edu/netlogo/docs/programming.html#random-numbers may be of assistance

**Comment by oscarbi** [comment]
Thanks for this valuable information. I had not read it before. It is very helpful to understand the random numbers in Netlogo.
