### ISSUE TITLE
decimal

### ISSUE THREAD

**Issue by CYXcyxxycCYX** [NetLogo/NetLogo#2220]
![image](https://github.com/NetLogo/NetLogo/assets/152272511/73f608f0-79a3-4dea-ab46-8879fe9de37f)
The dictionary says the monitor can change the decimal digits but I didn't find a way to change the decimal digits on the view like changing the monitor. The only way is to change the precision through the program. However, this means the change of data when downloading the excel. I suppose if we can adjust the decimal digits of the turtle's variable shown in the figure, then it would be much more convenient than changing the program through precision.

**Comment by LaCuneta** [comment]
Thanks for your interest in NetLogo.

Okay, if I'm reading you right you want the display to have a limited number of decimals, but you want the core data to be unchanged.  Here is how I would do it:

```netlogo
turtles-own [ 
  my-var 
]

to setup
  create-turtles 10 [ 
    set shape "person" 
    setxy random-xcor random-ycor 
    update-my-var (random-float 10)
  ]
end

to go
  ask turtles [
    forward 1
    if random 10 < 2 [
      update-my-var (random-float 10)
    ] 
  ]
end

to update-my-var [new-val]
  set my-var new-val
  set label (precision my-var 2)
end
```

You add a turtle variable that tracks the real data, and that variable would be used to export the data for use in outside programs like excel.  The `label` of each turtle, then is just for display and wouldn't need to be exported.  We add a procedure `update-my-var` that does the update of both at the same time to make sure we don't forget to set the label when we set the variable.  Let me know if I misunderstood what you were asking, or if this doesn't work somehow.
