### ISSUE TITLE
NetLogo 3D 6.4 fails to open model that worked in 6.3; shows no menus

### ISSUE THREAD

**Issue by DOSull** [NetLogo/NetLogo#2226]
NetLogo 6.4 fails to open a 3D model that worked fine in previous versions. 

If opened from the desktop icon then it fails to show any menus other than the main **NetLogo** one, so that it is impossible to do anything except to start writing a new model. I have checked and I can write a model which runs. 

After a bit more experimentation, I found that I could get the menubar to appear by switching the **Code** tab to open in a separate window, clicking in it, then clicking back in the main interface window. However, if I then do **File - Open** and navigated to an existing model to open it, I get the spinning beachball of doom and the model never opens.

If I paste more complicated model code into the code window and make the needed interface elements to enable the model to run, then it will run, so it doesn't seem to be a problem with the core of the code, more something to do with startup.

If I attempt to open a model by double-clicking on it, then I get the spinning beachball and the model fails to open. This happens with models in the supplied model library, not just my models.

Once I get the spinning beachball all I can do is Force Quit to get out of it.

NetLogo 2D works fine.

This is on an Apple M2 Macbook Air, Sonoma  14.2.

The models I've been trying to open are found in this repo (but as noted above, I don't think this is anything to do with my models):

https://github.com/DOSull/spacetime-cartogram

**Comment by DOSull** [comment]
OK... so... checked this on another Mac at Sonoma 14.3 and that apparently works fine. I am now enduring the pain of updating to the latest Sonoma (always nerve wracking) so see if this fixes the problem.

**Comment by DOSull** [comment]
Can confirm the problem is gone on Sonoma 14.4. Perhaps this issue may offer clues to some of the other MacOS issues you've been having?

**Comment by brandesNW** [comment]
Thanks for reporting and investigating this.
I am on Sonoma 14.3.1 and don’t plan to go back to 14.2 to investigate, but I will take a look at your models.
Thanks,
Aaron
--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: DOSull ***@***.***>
Date: Sunday, March 10, 2024 at 7:11 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [NetLogo/NetLogo] NetLogo 3D 6.4 fails to open model that worked in 6.3; shows no menus (Issue #2226)

Closed #2226<https://urldefense.com/v3/__https:/github.com/NetLogo/NetLogo/issues/2226__;!!Dq0X2DkFhyF93HkjWTBQKhk!RbiUyW1YYZCLmnL93IC8jIqbMAczQ4_AQJgMnMtCbSJ9CDkO4jrLKPP7UrLEcWnwy8gqSh_isKIJ1x9CLMVbvPiTy1XmLs4ILQ$> as completed.

**Comment by DOSull** [comment]
It's nothing to do with my models - the model library 3D models had the same issue. Like you I am not going back to 14.2 to check!

**Comment by brandesNW** [comment]
Hi,
As expected stretched-lattice.nlogo3d worked fine on Sonoma 14.3.1.
The model is interesting. Thanks again for your interest in NetLogo.

  *   Aaron

--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: Aaron Andre Brandes ***@***.***>
Date: Tuesday, March 12, 2024 at 1:54 PM
To: NetLogo/NetLogo ***@***.***>, NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [NetLogo/NetLogo] NetLogo 3D 6.4 fails to open model that worked in 6.3; shows no menus (Issue #2226)
Thanks for reporting and investigating this.
I am on Sonoma 14.3.1 and don’t plan to go back to 14.2 to investigate, but I will take a look at your models.
Thanks,
Aaron
--
Aaron Brandes, Software Developer
Center for Connected Learning and Computer-Based Modeling


From: DOSull ***@***.***>
Date: Sunday, March 10, 2024 at 7:11 PM
To: NetLogo/NetLogo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [NetLogo/NetLogo] NetLogo 3D 6.4 fails to open model that worked in 6.3; shows no menus (Issue #2226)

Closed #2226<https://urldefense.com/v3/__https:/github.com/NetLogo/NetLogo/issues/2226__;!!Dq0X2DkFhyF93HkjWTBQKhk!RbiUyW1YYZCLmnL93IC8jIqbMAczQ4_AQJgMnMtCbSJ9CDkO4jrLKPP7UrLEcWnwy8gqSh_isKIJ1x9CLMVbvPiTy1XmLs4ILQ$> as completed.
