### ISSUE TITLE
The **Indent Automatically** checkbox should have a preference setting for default

### ISSUE THREAD

**Issue by LaCuneta** [NetLogo/NetLogo#2242]
Submitted by a user via email:  Currently the **Indent Automatically** checkbox on the code tab defaults to checked (enabled) on each start of NetLogo.  There is no way for a user who prefers not using it to leave it disabled unless checked.  It should have a matching value in the NetLogo Preferences to set the default to use on startup.

**Comment by ERSUCC** [comment]
See pull request #2262. It works now for the main code tab, but I'm not sure if there is anywhere else that requires a similar change. If there is, I can add it there too as part of the same pull request.
