### ISSUE TITLE
regression: curved links are invisible on OS X 10.8 (works on 10.7)

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#225]
so e.g. `cro 2 [ fd 5 create-links-with other turtles ]`. you will see a link. then go into Tools —> Link Shapes Editor and change the curviness of the default link shape from 0 to 1. the link disappears.

it's rather baffling that changing the curviness back to 0 doesn't make the link reappear.

reported by @mberland

**Comment by mrerrormessage** [comment]
Now that we're on 10.10, closing
