### ISSUE TITLE
String values are not rejected in numeric input widgets

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#2271]
To reproduce: Create a numeric input widget and give it a string value
Expect an error because value is wrong type, but none occurs.
If you print the value in the command center or create a monitor widget for the variable it will show the value 0.

**Comment by ERSUCC** [comment]
This sounds like it was caused by the changes I made to stop the infinite focusing on numeric input widgets. I'll see if I can fix it.

**Comment by ERSUCC** [comment]
Turns out it is also an issue in the released version of NetLogo, there has never been a way to disallow putting in the wrong value. What behavior would you want if the user puts an invalid value in an input box? (eg. error printed, error dialog box, replace value with a correct one, etc.)

**Comment by ERSUCC** [comment]
@brandesNW See pull request #2281, I decided to just have it revert to the old value if you try to enter a new one. That seemed the most logical and easiest fix for now.

**Comment by brandesNW** [comment]
fixed by PR #2281
