### ISSUE TITLE
multiple selected widgets: delete icon deletes them all, but right-click delete only deletes one

### ISSUE THREAD

**Issue by brandesNW** [NetLogo/NetLogo#2294]
This is documented behavior, although I think it's not what I would have expected.
Should we have a right-click "delete all" option? That would allow the behavior that goes with the icon, and also make it clearer that "delete" does not delete all the selected items.

[The interface tab documentation](https://ccl.northwestern.edu/netlogo/docs/interfacetab.html)  explains here that only one of multiple selected items is deleted

**Selecting multiple items:** You can select multiple interface elements at the same time by including them in the rectangle you drag. If multiple elements are selected, one of them is the “key” item, which means that if you use the “Edit” or “Delete” buttons on the Interface Toolbar, only the key item is affected. The key item’s border is darker gray.

Here it indicates that the delete icon deletes all, and does not re-iterate what happens if multiple items are selected.

**Deleting**: Select the element or elements you want to delete, then press the “Delete” button on the Interface toolbar. You may also delete an element by right-clicking it and choosing “Delete” from the popup menu. If you use this latter method, it is not necessary to select the element first.

I think we should perhaps repeat what happens when multiple items are selected and delete is used with a right-click.

**Comment by brandesNW** [comment]
I'm also wondering whether it makes sense to leave the other widgets selected. If you want to delete the next "key" item I think you have to right-click it, which doesn't require selection. It seems to me that the only thing the multiple selection does is to allow you to click on one of the selected items and move them all simultaneously.

**Comment by ERSUCC** [comment]
I believe this has been resolved in PR #2291.
