### ISSUE TITLE
Excess closing parentheses yield a nonsensical error

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/NetLogo#2309]
### Steps to reproduce

  * Compile the code `if true) [ show 0 ]`

### What should happen

> No opening parenthesis for closing parenthesis

### What actually happens

> IF expected 2 inputs, a TRUE/FALSE and a command block.

### Notes

In the context of a fuller model and a longer line of code, this error kept me and Uri baffled for more than 5 minutes as we tried to figure out what the heck was causing the error.  So that's bad.

Interestingly, we actually have the correct error message for the opposite situation.

`let x (true`:

> No closing parenthesis for this open parenthesis

`if (true [ show 0 ]`:

> Expected a closing parenthesis here.

**Comment by brandesNW** [comment]
closed by #2331
