### ISSUE TITLE
Info tab aesthetics: unordered list bullets are big and ugly

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#236]
they're like cannonballs. can they be made smaller somehow?

screen shot showing their vastness and darkness:
![screen shot](http://f.cl.ly/items/40263t0W1X3Q103v1H2N/Screen%20Shot%202012-11-05%20at%2011.01.34%20AM.png)

**Comment by mrerrormessage** [comment]
This should be adjustable via `info.css`.

**Comment by SethTisue** [comment]
these giant inky black holes always bugged me. thanks @Idloj!
