### ISSUE TITLE
2D view in app displays in wrong colorspace in Java 6 on Mac OS X 10.7 and 10.8

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#251]
Teletortoise shows the right shade of green. it's the same in Safari, Firefox, and Chrome, and I've triple checked that the right RGB values are being used.

as further confirmation that the colors in the NetLogo app are wrong, I get the right colors if I run the app bundle in Java 7 instead of Java 6

Jason says on Linux, the app colors match the Teletortoise colors

Jason also says OS X 10.7 behaves like 10.8.

(we don't know what 10.6 does)

NetLogo versions going at least as far back as NetLogo 3.1 are also affected

the 3D view is not affected, presumably because it uses a completely different rendering pipeline

![Screen Shot 2012-12-12 at 12 25 45 PM](https://f.cloud.github.com/assets/161079/8697/034efd20-4481-11e2-8889-761ee00b9712.png)

**Comment by SethTisue** [comment]
@mrerrormessage fixed in hexy, I think

**Comment by mrerrormessage** [comment]
This was fixed in 5.3, and by extension in hexy.

**Comment by SethTisue** [comment]
whites whiter, colors brighter!
