### ISSUE TITLE
CCL-authored extension download links have disappeared

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#253]
GitHub has removed its downloads feature. the URLs for existing uploads still work though (and will "for the foreseeable future"). so for all of the extensions we provide downloads for, we need to add links to the README.

for example, here's the change I made for the Shell extension: https://github.com/NetLogo/Shell-Extension/commit/46fe750a8e256b614449ce42d0b749f29a88273d

any other non-bundled extensions hosted under https://github.com/NetLogo need a corresponding change

**Comment by nicolaspayette** [comment]
All extensions listed in the wiki currently have working download links (even if they don't all use Releases). Closing this.
