### ISSUE TITLE
publish NetLogo jars on a Maven repository

### ISSUE THREAD

**Issue by HughDevlin** [NetLogo/NetLogo#256]
push releases and release candidate jars to a maven repository such as http://mvnrepository.com/ ;greatly simplify development environment set-up for extension development; note for example java, scala and java and scala testing resources are already on maven; thanks!

**Comment by digitaldust** [comment]
I am trying to manually install the jar in my maven project in Netbeans, but I am having problems because, despite Netbeans sees my manually installed artifact, it does not see its dependencies, and I don't know how to specify this to the POM file...

**Comment by SethTisue** [comment]
@digitaldust I expect you'll need to add all the JARs in the lib directory individually.

**Comment by mrerrormessage** [comment]
This *will* be in the next release and with any luck we'll be publishing snapshot artifacts within the next few weeks.

**Comment by reyman** [comment]
Hi, is netlogo artifact repository now accessible ?

**Comment by mrerrormessage** [comment]
This has now been added to the NetLogo build. Jars will be available [on bintray](https://bintray.com/netlogo/NetLogo-JVM/netlogo/view). Please note that the plan is to support this for NetLogo versions 6.0 and higher. Jars for 5.3 and 5.3.1 are attached to their releases [here](https://github.com/NetLogo/NetLogo/releases/tag/5.3.1) and [here](https://github.com/NetLogo/NetLogo/releases/tag/5.3.0). snapshot jars on bintray will be tagged with the first several characters of their git sha1. non-snapshot jars will be tagged as versioned with NetLogo.
