### ISSUE TITLE
sliders cropped under gtk native laf

### ISSUE THREAD

**Issue by memeplex** [NetLogo/NetLogo#257]
This only happens for the applet. LAF is configured in CLI with:

-Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel

Look at the attached screenshot.
![2013-01-03-123701_550x66_scrot](https://f.cloud.github.com/assets/2845433/41331/0eff1708-55d5-11e2-9006-e82ac26ed438.png)

**Comment by SethTisue** [comment]
closing since we don't do applets anymore
