### ISSUE TITLE
upgrade to latest pegdown & parboiled

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#261]
currently this is blocked by #260. the version of pegdown we're using depends on ASM 3.3, and so do does the bytecode generator, so we'd need to upgrade pegdown, parboiled, and ASM all at the same time. upgrading ASM is nontrivial because the API is different.

the good news is, it might not be terrible to just leave this alone. eventually, bugs or compatibility issues might bite us.

**Comment by mrerrormessage** [comment]
We're now on the latest ASM and we're on pegdown 1.5. We should be able to upgrade to 1.6 without issue.

**Comment by mrerrormessage** [comment]
Fixed in https://github.com/NetLogo/NetLogo/commit/461529c4200c9076f364d308c5dc358bc4c76f1a
