### ISSUE TITLE
headless NetLogo should complain about models from old NetLogo versions

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#27]
maybe ideally it would do the same auto-conversions that the app does, but in practice it's unlikely to happen. so it at least ought to notice the NetLogo version doesn't match and print a warning.

for now, we advise users to resave their old models in the GUI before running them headless in a new version

**Comment by mrerrormessage** [comment]
I believe this happens in hexy (Autoconversion if possible, warning if not). This should be a verify-and-close.

**Comment by qiemem** [comment]
LS relies on this behavior. This test (I believe) confirms that it's working as expected: https://github.com/NetLogo/LevelSpace/blob/25eef301ab54f455e262e47c947ccb177f0cb2ee/tests.txt#L141

**Comment by mrerrormessage** [comment]
Thanks @qiemem ! Closing.
