### ISSUE TITLE
code running in netlogo affects __random-state differently compared to the same code running in an applet

### ISSUE THREAD

**Issue by turtlemaniac** [NetLogo/NetLogo#276]
Code:
to startup
  ca random-seed 0
  output-print __random-state
  __ignore (one-of patches with[true])
  output-print __random-state
end

Resulting output from code:
netlogo:
0 0 -1727483681 624 0.0 false 0 1 1812433255 1900727105 ...
0 0 -1727483681 2 0.0 false -1851716334 1093594115 1878467924 -1585606278 ...
applet:
0 0 -1727483681 624 0.0 false 0 1 1812433255 1900727105 ...
0 0 -1727483681 1 0.0 false -1851716334 1093594115 1878467924 -1585606278

System:
NetLogo 5.0.3 (October 25, 2012)
Extension API version: 5.0
Java HotSpot(TM) Server VM 1.6.0_33 (Sun Microsystems Inc.; 1.6.0_33-b03)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
Java heap: used = 8 MB, free = 58 MB, max = 910 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

**Comment by SethTisue** [comment]
closing since we don't do applets anymore
