### ISSUE TITLE
on Linux, the exp primitive may not always return consistent answers

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#28]
We have discovered a problem on at least some versions of Linux where the `exp` primitive sometimes returns a slightly different answer (differing only in the last decimal place) for the same input. According to an engineer at Sun, this should only happen on Linux kernel versions 2.4.19 and earlier, but we have observed the problem on more recent kernel versions. We imagine the problem is Linux-specific and does not happen on other Unix-based systems. We are not sure if the problem ever occurs in practice during actual NetLogo model runs, or only occurs in the context of our automated test regimen. The bug is in Sun's Java VM, and not in NetLogo itself. We hope that only the `exp` is affected, but we can't be entirely sure.

Users are encouraged to visit http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=5023712 (free registration required) and vote for Sun to fix this bug.

**Comment by mrerrormessage** [comment]
This bug has been closed for some time. Given that it involved Java 5 and we're now on Java 8, as well as linux kernel version 2 and we're now on 4.7, I'm closing this.
