### ISSUE TITLE
Compiler should catch duplicate singular breed names

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#307]
For example:

    breed [ as a ]
    breed [ bs a ]

compiles, even though `a` is used twice.

This only affects 5.0.x and has been fixed in 5.1 by Seth's rewrite of `StructureParser` (378776800b221f22aa8a6355f2b11a7bfc4b3de0).

**Comment by SethTisue** [comment]
@mrerrormessage perhaps check if hexy gets the fix?

**Comment by mrerrormessage** [comment]
yep, will verify
