### ISSUE TITLE
gogo-serial extension should be dropped or upgraded to scala 2.11, java 8

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#310]
though I haven't tested it, it seems unlikely to me that the Scala code in the extension still actually works with NetLogo on master

**Comment by SethTisue** [comment]
@mrerrormessage what's the status for hexy?

**Comment by mrerrormessage** [comment]
We're considering dropping support in favor of the new gogo-hid extension. If not, we'll need to migrate from scala-actors to akka. This will definitely be addressed in hexy one way or another, so I'm changing the milestone.

**Comment by mrerrormessage** [comment]
This extension has been dropped from hexy and barring some unforeseen reversal of course will not be re-added.
