### ISSUE TITLE
bug: no (or poor) error message if task variable used as name

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#348]
so e.g. the error for `to ?1 end` is `Cannot use ?1 as a procedure name. Conflicts with: _taskvariable:1`, where the "taskvariable" stuff is compiler internals leaking out

and e.g. `turtles-own [?1]` doesn't cause a compile-time error at all

nor does `foreach [1 2 3] [ let ? 4 ]`

**Comment by SethTisue** [comment]
@mrerrormessage your compiler backport might fix this for hexy?

**Comment by mrerrormessage** [comment]
I'm pretty sure it will.
