### ISSUE TITLE
feature: support referring to variables from outer tasks

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#351]
`?`, `?1`, `?2` etc always refer  to the innermost enclosing task, so you can't access the inputs of an outer task. 

In a command task, you can work around it use `let` in the outer task to  give the task input a name.  But it's awkward. And in the reporter case there's no reporter equivalent of `let`,  so with reporter tasks, you get stuck. 

This is *the* biggest missing feature in tasks. (@joshcough and I were well aware of it all along.  We just didn't have time to do anything about it for 5.0.)

consider e.g. this program:

```netlogo
to-report tabulate [counts values]
  report reduce sentence (map ditto counts values)
end

to-report ditto [n value]
  report n-values n [value]
end
```

currently it's impossible to write this in one procedure. if you try:

```netlogo
to-report tabulate [counts values]
  report reduce sentence (map [n-values ?1 [?2]] counts values)
end
```

it doesn't work because the `?2` in the body of the `n-values` refers to the nonexistent second input to the n-values task, rather than the intended meaning where `?2` refers to the second input to the enclosing `map` task.  (and trying to do `let ditto task ...` first doesn't help.)

attempting to write the Y combinator in NetLogo runs afoul of the same issue.

also, Uri received this feature request:

 > Make tasks more general so that tasks can take tasks as input and 
 > produce tasks as output. This would involved control over the task 
 > variables. 

and he confirms that it refers to this issue.

so, we have a hole in the language.

there are several possible ways we could address it. in increasing order of how difficult they would be to implement:

the easiest way would be to add `letreport` to the language:

```netlogo
to-report tabulate [counts values]
  let ditto task [ letreport x ?2 n-values ?1 [x] ]
  report reduce sentence (map ditto counts values)
end
```

here the use of `let` is just for clarity; cramming it all into one command would work too

@toontalk has said: "To use let inside a reporter is something I often want. If possible would be nice if it was also called 'let' rather than 'letreport' but maybe that's not feasible."

the next easiest way would be to add some kind of syntax for giving names to task inputs, instead of just numbers. something like `let ditto task [n x => n-values n [x]]`

the hardest way would be to support commands inside the bodies of reporter tasks, something like:

```netlogo
let ditto task [ let x ?2 report n-values ?1 [x] ]
```

**Comment by mrerrormessage** [comment]
Fixed in hexy with the addition of `->`-anonymous procedures.

**Comment by SethTisue** [comment]
> we'll need to make sure you're always closing over a fresh binding

@mrerrormessage did this happen?

**Comment by mrerrormessage** [comment]
@SethTisue , that didn't happen.

So I suppose we have javascript-style loop variables at the moment. Just to confirm, we're talking about the behavior displayed in the following language test:

```
globals [glob1]
O> repeat 5 [ let bar 0 run [ [] -> set bar bar + 1 set glob1 bar ] ]
; with fresh bindings
glob1 => 1
; without fresh bindings
glob1 => 5
```

I haven't actually run this test, but I'm pretty sure it would be the second case. I don't think it should be terribly difficult to get it to be the first case - all the work should be in `LocalsVisitor`.

**Comment by SethTisue** [comment]
> Just to confirm, we're talking about the behavior displayed in the following language test

yes

and reporter tasks too, so e.g. `print map runresult n-values 5 [[x] -> [[] -> x]]` should be `[0 1 2 3 4]` (and is in hexy when I tried it just now, but I suggest making sure that fact is covered by tests)

> the example above actually is possible in NetLogo 5 using tasks

ha. well, that's a bug in NetLogo 5. not a known bug afaicr. good catch!

**Comment by SethTisue** [comment]
> it was even more awkward than I expected in NetLogo since you can't introduce a let in a reporter lambda

yes, this is covered already here on this ticket, see above about `letreport`
