### ISSUE TITLE
Compiler should error message when breed primitive used as procedure name

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#352]
for example:

```netlogo
breed [kittens kitten]
to kittens-at end
```

gives the error "Cannot use KITTENS-AT as a procedure name. Conflicts with: _breedat:KITTENS" where that last bit is internal compiler stuff leaking out

**Comment by mrerrormessage** [comment]
This is fixed in 6.0-M1, will add tests in #920 .
