### ISSUE TITLE
Allow programmatic closing of agent monitors

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#354]
Uri writes:

> We have programmatic control of opening inspectors, but there is no way to close them programmaticaly. It'd be nice if there was.

That would be the complement to [`inspect`](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#inspect). Not sure what a good name would be. `stop-inspecting`? `close-inspector`? `close-monitor`?

**Comment by nicolaspayette** [comment]
`uninspect`?

**Comment by nicolaspayette** [comment]
Update `src/test/org/nlogo/compiler/TestAllSyntaxes.scala`?

**Comment by SethTisue** [comment]
I was also going to suggest `uninspect`

**Comment by frankduncan** [comment]
I have put the question to uri.  @TheBizzle suggested stop-inspecting, and I didn't care enough to create an opinion of my own.
