### ISSUE TITLE
resolve status of Mathematica link (unbundle it?)

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#358]
the NetLogo-Mathematica Link currently lacks a maintainer. I don't think we even know if it works with NetLogo 5, or with recent versions of Mathematica. none of us own a copy of Mathematica.

under the circumstances, does it make sense to keep bundling the link?

**Comment by mrerrormessage** [comment]
NetLogo 5.2.2 will not bundle Mathematica Link, due to Java Version changes and the lack of an active maintainer. If a maintainer steps up in the future, I would be open to bundling it again.

**Comment by mrerrormessage** [comment]
Unbundled at the moment, still open to re-bundling if there is someone who can step up and help, especially with testing.
