### ISSUE TITLE
pen-down in certain conditions makes netlogo unresponsive

### ISSUE THREAD

**Issue by turtlemaniac** [NetLogo/NetLogo#361]
Code for default settings:
to t
  ca
  crt 1
    [;set ycor ycor + 7.7
    pen-down
    repeat 20
      [set xcor xcor + .0008;xcor needs to change
      set ycor ycor + 1.1
      print ycor
      wait .02]
  show "done"]
end

...results in:
*netlogo behaving as if it were stuck in an endless loop
*halted code not halting and making netlogo completely unresponsive

Max ycor is 16.5, ycor change:
foreach [0 6.6 7.7][let a ? repeat 20[set a a + 1.1 print a] print "#"]

System:
NetLogo 5.0.4 (March 19, 2013)
Extension API version: 5.0
Java HotSpot(TM) Server VM 1.6.0_41 (Sun Microsystems Inc.; 1.6.0_41-b02)
operating system: Windows 7 6.1 (x86 processor)
Scala version 2.9.2
Java heap: used = 8 MB, free = 52 MB, max = 910 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

**Comment by mrerrormessage** [comment]
So, I've found a way to fix it, but I'm concerned that it might break other things. I have basically just made [these](https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/render/TrailDrawer.java#L349) [two](https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/render/TrailDrawer.java#L360) lines look like [their](https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/render/TrailDrawer.java#L372) [counterparts](https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/render/TrailDrawer.java#L383) further down in `TrailDrawer`. While this fixes the bug, I'm concerned about why the lines were different to begin with. The difference goes back to NetLogo 3.0 (at least). I'm unsure what the subtlety of the different choices here means and whether changing it is likely to break anything else.

**Comment by SethTisue** [comment]
I've got no memories or insight on this.

the model checksums include the pixels of the drawing layer, so I'm not sure you need to be toooooooooo super scared to break something.

**Comment by mrerrormessage** [comment]
Fixed on 5.x
