### ISSUE TITLE
5.0.x and/or master builds could be less demanding about QTJava.zip

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#392]
maybe if QTJava.zip isn't found, just prompt the user whether they just want to continue the build without the qtj extension? it's a barrier to entry for people just wanting to build NetLogo

reported by https://github.iu.edu/sasasidh

**Comment by mrerrormessage** [comment]
We're planning to unbundle the QTJ extension in Hexy Honeycomb, which will mean no more searching for it :smile: .

**Comment by mrerrormessage** [comment]
This is covered by #780 in hexy. It would be nice to get it on 5.x as well, for anyone who wants to build that. Conditional compilation is possible.

**Comment by mrerrormessage** [comment]
This issue dies with the 5.x branch.
