### ISSUE TITLE
wishlist: Keyboard accelerators for menu items

### ISSUE THREAD

**Issue by sajith** [NetLogo/NetLogo#394]
It would be nice to summon menu dropdown items, like so (with a PC keyboard):

Alt + F = **F**ile
Alt + E = **E**dit
Alt + T = **T**ools
Alt + Z = **Z**oom
Alt + A = T **a** bs
Alt + H = **H**elp

At present one has to use the mouse to activate the pull down menus.  As a keyboard warrior, I find this rather aggravating. :-)

**Comment by Idloj** [comment]
Should I make a PR again for 5.3?

**Comment by mrerrormessage** [comment]
This has been resolved on the hexy and 6.x branches, so I'm closing this issue
