### ISSUE TITLE
NetLogo shouldn't rely on current working directory to find its own files

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#415]
(I'm just going to discuss the headless case, but it might be nice to have this fixed for GUI NetLogo as well)

`netlogo-headless.sh` begins with:

    cd "`dirname "$0"`"

so that NetLogo can find the `extensions` and `lib` directories. but this can be awkward for users for a variety of reasons:

 * they may be constructing their own launch script and not realize they need to copy what `netlogo-headless.sh` does
 * environment such as cluster computing environments may have their own ideas about what the current working directory ought to be
 * if NetLogo insists on having the working directory set for its own purposes, users can't set it to something else in order for their own model to be able to find its own files

an example recent thread on this is https://groups.google.com/d/msg/netlogo-devel/ppmG2yn7m_I/6eNVnuuoIx4J , but it's something that has come up repeatedly over the years

what form might a solution take? maybe an environment variable like NETLOGO_HOME that you'd set before launching

note that the `lib` directory might require special thought. the classpath in NetLogo.jar references jars in `lib` via relative paths. users can work around this by constructing their own classpath and not relying on the classpath line in the manifest in our jar, but it would be nice if they didn't have to do that.

**Comment by Idloj** [comment]
This is solved on 5.3, isn't it?
There is no script anymore, just an executable.
I made a symbolic link to that executable from a different directory and it worked fine.

**Comment by mrerrormessage** [comment]
5.3 addresses the issue of locating jars, etc. System variables are now provided for the following

* extensions - `netlogo.extensions.dir`
* models - `netlogo.models.dir`
* dics - `netlogo.docs.dir`

**Comment by fstonedahl** [comment]
Cheer!
