### ISSUE TITLE
support for running NetLogo in a 64-bit JVM on 64-bit Windows

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#423]
http://ccl.northwestern.edu/netlogo/docs/faq.html#windowsmemory says: "Upgrading to a newer version of Windows may help. Running Windows in 64-bit mode instead of 32-bit mode may also 
help."  These statements are rather vague; that's because we on the NetLogo development team don't have experience ourselves with trying to run really big models on Windows.  If there's anyone reading this who  could help us make these statements more specific, please comment below.

see e.g.:

 * http://netlogo-users.18673.x6.nabble.com/weird-parallel-runs-problem-td5002528.html
 * http://netlogo-users.18673.x6.nabble.com/Pointing-NetLogo-to-64-bit-JVM-td5002961.html
 * http://netlogo-users.18673.x6.nabble.com/Can-NetLogo-itself-be-run-in-64-bits-on-Windows-If-so-how-td5002970.html
 * http://netlogo-users.18673.x6.nabble.com/Java-OutofMemory-errors-for-large-NetLogo-worlds-suggestions-requested-td5002799.html

and probably other threads on netlogo-users in recent years

we could really use some community help on this

at minimum, it would be good to have an FAQ entry stating whatever is known or not known.

another relevant FAQ question is http://ccl.northwestern.edu/netlogo/docs/faq.html#howbig ; this is where someone trying to run a really big model is likely to start. (http://ccl.northwestern.edu/netlogo/docs/faq.html#windowsmemory is more about coping on machines with small memories.)

**Comment by jbadham** [comment]
This ended up being my problem with the R extension (and probably why I have never got RNetLogo to work either). See http://stackoverflow.com/questions/33345640/cannot-make-r-extension-work-in-netlogo/33393983#33393983 for details.

**Comment by AAinsleyAA** [comment]
Soooo where can I find the command for launching GUI NetLogo from the cmd line in Windows?  I've looked for it through the community and the User Manual...

**Comment by mrerrormessage** [comment]
In NetLogo 5.3, a 64-bit version of NetLogo opens a 64-bit JVM.
