### ISSUE TITLE
`report` should be allowed inside `ask`

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#424]
currently if you try e.g.:

```
to-report foo
  ask patches [ report 0 ]
end
```

you get "REPORT must be immediately inside a TO-REPORT"

any implementation difficulty shouldn't be too terribly hard to solve, I think, although it certainly might be tricky to get right

**Comment by mrerrormessage** [comment]
The current implementation in NetLogoWeb forbids `report` inside of `ask` as well. If we fix it, we'll need it done in both places. @SethTisue, @TheBizzle , @qiemem do you think `report` should be allowed inside of `ask` or other command blocks?

**Comment by TheBizzle** [comment]
I don't think it's a _necessary_ feature, and I wouldn't encourage people to use it if it were supported, and I also imagine that there's a (probably technical) reason why it _isn't_ supported right now.  However, I think it's inconsistent and surprising to users that `report` cannot be used inside certain kinds of blocks.

In short, I don't have strong feelings on this, and I don't see any urgency in adding this feature, but, idealistically speaking, I think it ought to be allowed.

**Comment by SethTisue** [comment]
I agree with @TheBizzle

**Comment by mrerrormessage** [comment]
related: #322

**Comment by mrerrormessage** [comment]
See #1071 for future developments on this issue.
