### ISSUE TITLE
Linux: shell script to run app can't be run from a symlink

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#43]
the problem line is:

```
cd "`dirname "$0"`"
```

it's there to ensure that when NetLogo starts, the NetLogo installation directory is the current working directory, since the app expects that. but if there's a symlink to the script, `$0` points to the symlink, rather than to the target, so we end up in the wrong directory

reported by Fred Drueck

**Comment by Idloj** [comment]
I know this isn't exactly a solution, but maybe providing a `.desktop` file can help, so the user doesn't even care about the `.sh` file. And it's just nice to provide a `.desktop` file!

**Comment by SethTisue** [comment]
I assume a PR adding a `.desktop` file would be accepted.

**Comment by Idloj** [comment]
BTW, this one will be nicer if #213 is resolved

**Comment by mrerrormessage** [comment]
As of 5.3, we no longer distribute shell scripts for NetLogo applications on Linux. This is related to #979 which should bring back only the netlogo-headless script and should take symlink resolution into consideration.
