### ISSUE TITLE
Show the "Include" menu even when there are errors

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/NetLogo#437]
Charles Staelin writes:

> I'm not sure if this is a bug or an enhancement request.  When a NetLogo file that contains __include  is opened, and if there are errors in one or more of the include (.nls) files, the code tab is opened along with the .nls file in which the first error was found.  However, under those circumstances, the code tab does not have the "include" menu and so one can not open any other .nls file within NetLogo without fixing the error that is presented.  
> 
> The problem is that the fix of that error may well be in one of the other .nls files.  The only way that I know to fix that is to open the other .nls file(s) in a text editor, fix them, close and reopen NetLogo, and keep going through the process until all the errors have been fixed.
> 
> Could the include menu be available even when the model opens with errors?

**Comment by mrerrormessage** [comment]
This bug no longer occurs in NetLogo 6.0. Thanks @Idloj for the hard work on the includes menu!
