### ISSUE TITLE
Linux: shell script to run app handles relative paths incorrectly

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#44]
because this happens:

```
cd "`dirname "$0"`
```

before the line that starts NetLogo runs, any relative pathnames passed on the command line will no longer point to the right place

it's not clear to me if this is even fixable as long as the app expects that the NetLogo directory must be the current working directory when NetLogo starts

reported by Fred Drueck

**Comment by Idloj** [comment]
What about using absolute paths, i.e. store this `dirname "$0"` in a variable instead of `cd`-ing to it.

**Comment by SethTisue** [comment]
the app expects that the NetLogo directory must be the current working directory when NetLogo starts. changing that is certainly doable, but it is not easy, since the assumption isn't only in one place in the code, and because http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4045688

**Comment by Idloj** [comment]
so this issue will be very straight-forward if #415 is solved, right?

**Comment by SethTisue** [comment]
yes, that is the root cause. good to have the two tickets linked.

**Comment by mrerrormessage** [comment]
Addressed in 5.3, via the fix for #415 .
