### ISSUE TITLE
CI solution for 5.0.x and master branches (fix Jenkins or replace it)

### ISSUE THREAD

**Issue by frankduncan** [NetLogo/NetLogo#473]
From Seth:

>I've been maintaining Jenkins myself on monk2 for some years now and I've kept doing it until now in part because it hasn't been very much work.  But now Jenkins won't start, I don't know why, and I don't want to spend time fixing it.  Who knows, maybe it's something trivial, I don't know.  I had just upgraded Jenkins to the latest version, as historically have done from time to time, but then also at the same time our sysadmin upgraded a bunch of stuff on monk2 (I don't know exactly what), so either of those could be the cause.

>Travis is not a full replacement for Jenkins, because Travis doesn't support Oracle Java 6 last time I checked, and the 5.0.x and master branches require it in order to build.

>If we only had the headless and tortoise branches (and branches that derive from them) to worry about, then just Travis would be fine (in fact I like it better than Jenkins).  And those are the branches I now mainly work on, so personally all I need is Travis, hence my decreasing enthusiasm for maintaining Jenkins myself.

>But y'all who are now in charge of the 5.0.x and master lines of development might decide resurrecting Jenkins is worth your while.

>Or, you might decide running nightly.sh yourself manually is fine.  You might even go and on and conclude that we don't even need monk2 anymore, and then we could stop paying a sysadmin to maintain it for us.  (Note that monk2 runs RHEL, which is annoying; simple things like getting the latest version of git installed, which would be so easy on Ubuntu, are hard, at least for me.)

>Jenkins is documented at:
>https://github.com/NetLogo/NetLogo/wiki/Continuous-integration
>I'm happy to answer any questions about it.

**Comment by Idloj** [comment]
AFAIK there are no 5.0.x or master branches any more...

**Comment by mrerrormessage** [comment]
Closing. I would really like to have CI working for 5.x, but setting up Jenkins is a pretty substantial task and I don't think the gain quite matches the effort at this point. Additionally, this ticket references an environment that (to the best of my knowledge) no longer exists.

**Comment by SethTisue** [comment]
Does hexy have Travis? (https://github.com/NetLogo/NetLogo/wiki/Continuous-integration says it doesn't.)

**Comment by mrerrormessage** [comment]
Hexy does have Travis. I'll update that wiki page.
