### ISSUE TITLE
Movie creation fails in NetLogo 5.0.4 on OS X 10.9

### ISSUE THREAD

**Issue by micrology** [NetLogo/NetLogo#499]
Usually, after the movie has been created, and movie-close called, a grey alert box appears in the middle of the interface, with no text in it, and NetLogo hangs (a force quit is the only way to exit).

Sometimes, a movie is created, but when I attempt to view it using Quicktime Player, QTP first attempts to 'convert' it and then reports that it has no suitable codec.  With VLC, the movie cannot be viewed because VLC reports that there is a bad channel count and that it requires a codec for format "twos".

The version is:

```
NetLogo 3D 5.0.4 (March 19, 2013)
Extension API version: 5.0
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65 (Apple Inc.; 1.6.0_65-b14-462-11M4609)
operating system: Mac OS X 10.9 (x86_64 processor)
Scala version 2.9.2
Java heap: used = 18 MB, free = 63 MB, max = 1015 MB

JOGL: 1.1.1
OpenGL graphics: ATI Radeon HD 6770M OpenGL Engine
OpenGL version: 2.1 ATI-1.14.21
OpenGL vendor: ATI Technologies Inc.
```

Here is a test program to try:

```
to setup
  crt 1 
  movie-start "test.mov"
end
to go
  repeat 100 [
    ask turtles [
      fd 1
    ]
    movie-grab-view
  ]
  movie-close
end
```

**Comment by applekrahe** [comment]
I think I found an end-run. At least it works for me. Don't close the movie file within your program. Open it there, but don't close it. Then after the program finishes its run, close it in the Command Center on the Interface page. I was having it get stuck on closing too and had to force quit. But this worked. Also nothing would open the movie file neither VLC or Quicktime, but MS Powerpoint imported it fine (which is where I needed it).
