### ISSUE TITLE
Mac OS X: in fullscreen mode, zooming messes up the window size

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#52]
...making it no longer fullscreen

steps to reproduce:

1. open a model with a small enough interface (e.g. Fire) on a big enough monitor
2. switch to fullscreen mode (click the two-arrows icon in the upper right corner, in the title bar)
3. zoom in or out (with the Zoom menu)

although NetLogo remains in fullscreen mode, the window doesn't actually fill the screen anymore

reported by Nathan Holbert

**Comment by mrerrormessage** [comment]
I tested this and didn't see it in the latest development builds or in 5.2.1. I suspect either Java or Mac OS X has fixed whatever the underlying problem was and/or this was fixed by #485.
