### ISSUE TITLE
Maximizing main frame causes cursor listener error (Linux Mate Desktop 1.4.2)

### ISSUE THREAD

**Issue by java99** [NetLogo/NetLogo#529]
After startup "java -jar NetLogo.jar", when resizing the window to full screen, the menu and all ui components do not correctly respond to clicking events.

When clicking on a menu-button and moving over the menu items in the list, no selection color is visible and event click or release listener for menu items fails.
Same behaviour for all other ui components.

After putting window size of Netlogo back to start-up size, it does take input from the cursor again.

The issue seems to be related to the Mate Desktop, because switching over to Cinnamon solves it.

Linux Mint 14 system - Mate Desktop 1.4.2 

NetLogo 5.0.5 (December 19, 2013)
Extension API version: 5.0
OpenJDK 64-Bit Server VM 1.7.0_25 (Oracle Corporation; 1.7.0_25-b30)
operating system: Linux 3.5.0-17-generic (amd64 processor)
Scala version 2.9.2
Java heap: used = 109 MB, free = 60 MB, max = 858 MB

JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)

**Comment by mrerrormessage** [comment]
@java99 , I'm closing this issue as it's now gone two years without any activity and all the versions involved are quite old. Please comment if you're still seeing this problem in 5.3.1 or the next release of NetLogo and we'll re-open the issue to investigate.

**Comment by SethTisue** [comment]
for the record, note that `java -jar NetLogo.jar` is not a correct way to start NetLogo and may result in an incorrectly behaving application; you should always use the provided shell script to launch NetLogo on Linux
