### ISSUE TITLE
NetLogo 3D sometimes crashes upon opening a model

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/NetLogo#538]
Maureen Clores writes:

> I intend to use Netlogo 3D for a project. I tried to run a model
 from the Models library and it rendered with no problems. The
 next time I opened the program it crashed (I mean, after running
 another model). From then on it crashes. I'm currently using
 Windows 7 Home Basic. I actually switched from Ultimate to a
 lower version just to see whether the OS is the problem.

**Comment by mrerrormessage** [comment]
JOGL has been upgraded in 5.3. I'm closing this for now, but we can obviously re-open if we see this continue to happen.
