### ISSUE TITLE
Add ability to run a task with a list of arguments

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#539]
Basically, add lisps `apply` to NetLogo.
Example:
`apply task foo [ "one" "two" "three"]`

One potential criticism of this is that it doesn't allow as much compile-time checking as normal `run`, but I'm not sure that even counts as a criticism.

Inspired by: http://stackoverflow.com/questions/21541133/run-a-task-with-a-variable-number-of-arguments-in-netlogo

**Comment by qiemem** [comment]
I came across this problem again, and actually figured out a workaround!

    to-report listify-task [ tsk num-args ]
      let args (reduce word n-values num-args [ (word " (item " ? " ?)") ])
      report runresult (word "task [ (runresult tsk " args ") ]")
    end

This converts a reporter task from something that takes a number of arguments to one that takes a list. You use it like so:

    observer> show (runresult (listify-task task [?1 + ?2] 2) [4 5])
    observer: 9

`apply` could be implemented on top of this like:

    to-report apply [ tsk args ]
      report (runresult (listify-task tsk length args) args)
    end

though it would be somewhat inefficient. Better to store the result of `listify-task` and the run that whenever you need to.

It essentially creates a task of the following form: `task [ (runresult tsk item 0 ? item 1 ? ...)]`.

**Comment by SethTisue** [comment]
nice. very clever

**Comment by SethTisue** [comment]
see also discussion at https://groups.google.com/d/msg/netlogo-devel/9o87_jxNvvo/nLVoLAnhEQAJ

**Comment by SethTisue** [comment]
recently requested again at https://groups.google.com/d/msg/netlogo-devel/b1c-mtScapQ/Hc3bXGq8BgAJ
