### ISSUE TITLE
set-plot-pen-color doesn't support rgb lists

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#540]
Doing `set-plot-pen-color [ 255 128 0 ]` fails to compile saying it wanted a number, not a list.

**Comment by SethTisue** [comment]
my intuition is that this would be relatively easy to fix.

**Comment by mrerrormessage** [comment]
Should just be a matter of modifying the syntax object to accept a list as well as a number, then dispatching on the type of the argument, just like all the other procedures which take colors.

**Comment by mrerrormessage** [comment]
Resolved in #984
