### ISSUE TITLE
feature: "Jump to Definition" in Code tab

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#544]
we're tantalizing close to already having this in that we already have code for:
- the Procedures menu, which lets you jump to any procedure definition that you choose by name
- the F1 key, which finds the token next to the cursor and takes an action depending on what it is

so this would be an easy starter project for someone (inside or outside the CCL) looking to improve the NetLogo editor/IDE

probably the F1 key ought to be reused for "Jump to definition"? if you F1 a primitive you get the User Manual, if you F1 your own procedure, it jumps to the definition.

**Comment by mrerrormessage** [comment]
This was closed in #653 .
