### ISSUE TITLE
enhancement: improve anemic `api.Task` API

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#554]
Extension authors wanting to use tasks will want additional methods (and better documentation).

For example, currently `perform` and `report` assume that the caller has already checked the task's arity. This fact ought to be stated in the Scaladoc. But then also currently the arity checking requires a downcast to `nvm.Task` because the `api` version doesn't provide a way to inspect the arity. (I suggest this be fixed with care to not unnecessarily expose implementation details, e.g. that that the underlying data structure in which formals are stored is `Array`.)

Note: I haven't targeted this for 5.0.x because of concern over binary compatibility for extensions.

**Comment by mrerrormessage** [comment]
Will be addressed as part of #948.
