### ISSUE TITLE
behaviorspace not running

### ISSUE THREAD

**Issue by hannah27** [NetLogo/NetLogo#570]
Hi there,

I'm pretty unfamiliar with NetLogo but I managed to run BehaviorSpace before several times. I have no idea why I get this message now. Can anybody help?

Cheers, Hannah

"NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.IllegalArgumentException
 at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:587)
 at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:478)
 at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:57)
 at org.nlogo.lab.Worker.run(Worker.scala:31)
 at org.nlogo.lab.gui.Supervisor$$anon$2.run(Supervisor.scala:47)
 at java.lang.Thread.run(Thread.java:695)

NetLogo 5.0.5
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65 (Apple Inc.; 1.6.0_65-b14-462-11M4609)
operating system: Mac OS X 10.8.5 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: ovation_baseline_sigma-beta

11:24:52.019 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
11:24:52.019 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:24:52.018 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:24:52.018 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:24:51.818 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
11:24:51.817 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:24:51.817 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
11:24:51.817 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:24:51.615 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
11:24:51.615 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0"

**Comment by SethTisue** [comment]
in the absence of any further details on this, closing the issue. if it is reproducible in NetLogo 5.2, let us know.
