### ISSUE TITLE
`ifelse-value` parses arguments differently than `if` and `ifelse`

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#588]
`ifelse-value` doesn't deal with infix operator in the first argument correctly.

`ifelse-value 0 < 1 [ "foo" ] [ "bar" ]` should return `"foo"`, but it fails to compile with

> ERROR: IFELSE-VALUE expected 3 inputs, a TRUE/FALSE, a reporter block and a reporter block. 

Note that this is different that `ifelse` and `if`, which handle infix operators as expected.

**Comment by qiemem** [comment]
The tricky case for this is when you're using `ifelse-value` as the argument to another infix operator. For instance:

```netlogo
ifelse-value true [ 5 ] [ 6 ] + ifelse-value false [ 7 ] [ 8 ]
```

Currently, that returns 13. Making that continue to work while also making:

```netlogo
ifelse-value 1 + 2 = 3 [ 5 ] [ 6 ]
```

work may not be possible.

**Comment by SethTisue** [comment]
🎉🎉🎉
