### ISSUE TITLE
EngineException should have a constructor that takes a cause

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#599]
in tons of places, we have code like this example: from `_run.scala`:

```
    try ...
    catch {
      case error: CompilerException =>
        throw new EngineException(context, this, error.getMessage)
    }
```

we're preserving only the message from the original exception, but not preserving the stack trace. this information would be very valuable to have when diagnosing bugs.

the API for `Throwable.getCause` (and the Exception constructor to fill it in) wasn't added to Java until 1.4, but EngineException goes all the way back to Java 1.1 days, and unfortunately never got upgraded to take advantage of the new API

probably ExtensionException has the same issue? I haven't looked.

**Comment by mrerrormessage** [comment]
Fixed in [https://github.com/NetLogo/NetLogo/commit/84564f2f70e27b68d1d8b62679502daca40ddbfc]
