### ISSUE TITLE
include version info in NetLogo Dictionary

### ISSUE THREAD

**Issue by alan-isaac** [NetLogo/NetLogo#614]
In the NetLogo Dictionary, please include version information stating when a command was added (or changed).  Thanks!

**Comment by Idloj** [comment]
What is the use case for this?

**Comment by alan-isaac** [comment]
None if you assume everyone always has the most recent version of NetLogo.  Otherwise, it seems a rather standard and necessary piece of documentation.  It gives a quick answer to the question, can I use primitive `x` when writing code for project Y.  (See for example the [Python docs](https://docs.python.org/2/library/functions.html).)  Example: can I use `behaviorspace-run-number` on a project with people still using version 5.0?  This would not replace the Transition Guide.  It would simply say e.g., *New in 5.2* or *Changed in 5.1*, and the transition guide would provide the details.

**Comment by Idloj** [comment]
You can just open the NetLogo dictionary from NetLogo, that way you get the dictionary for your version which comes with NetLogo.

**Comment by alan-isaac** [comment]
That would still be true if this information were added.  
Is it seen as a maintenance headache of some sort?

By the way, this would also offset current lacunae in the Transition Guide.

**Comment by SethTisue** [comment]
I imagine a pull request for this would be accepted? New primitives are being added at a glacial pace these days, so there would be negligible maintenance burden going forward.

**Comment by Idloj** [comment]
How would you get the version info? "History" on the files at Github?

**Comment by SethTisue** [comment]
the GitHub history doesn't go back past 2011, so somebody would have to download all the old JARs, extract the `tokens.txt` files from them, and diff them.

**Comment by Idloj** [comment]
someone from CCL I guess

**Comment by SethTisue** [comment]
why?

**Comment by Idloj** [comment]
ah, oops

**Comment by Idloj** [comment]
How would removed prims/keywords be documented?
Example: `locals` was available on NetLogo 1.0 but is no longer available.

**Comment by SethTisue** [comment]
In the Transition Guide. Let's not add NetLogo Dictionary entries for keywords and primitives that no longer exist.

**Comment by Idloj** [comment]
I'm intending to work on that now. Should I fork java8-packaging or hexy?

**Comment by mrerrormessage** [comment]
@Idloj , fork hexy.

**Comment by Idloj** [comment]
Should I wait with this until 5.3 changes are backported to hexy?

**Comment by mrerrormessage** [comment]
Yes, that would be best. I will plan to merge those changes in Monday or Tuesday of next week.

**Comment by mrerrormessage** [comment]
This has been merged into hexy with https://github.com/NetLogo/NetLogo/commit/7744178570c95b6095810238b73c7a4848bd7882
