### ISSUE TITLE
GIS Point shapefile - internal error 

### ISSUE THREAD

**Issue by gac55** [NetLogo/NetLogo#632]
Hi all,

I got the following internal error. I am trying to load a point shapefile as turtles. There are around 19,000 points, perhaps this is the source of the error?

Any help would be much appreciated

G

java.lang.NoClassDefFoundError: Could not initialize class org.nlogo.nvm.NonLocalExit$
 at org.nlogo.prim.etc._foreach.perform(_foreach.scala:29)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.0.5
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.6.0_65 (Apple Inc.; 1.6.0_65-b14-462-11M4609)
operating system: Mac OS X 10.9.3 (x86_64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: MSOA_V1

04:39:21.347 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:39:21.347 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:39:21.347 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:39:21.347 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:39:21.347 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:39:21.347 InterfaceGlobalEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
04:39:21.347 PeriodicUpdateEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:39:21.286 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
04:39:21.276 TickStateChangeEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) JobThread
04:39:21.271 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0

**Comment by mrerrormessage** [comment]
I ran into this bug (and fixed it, I believe) when fixing #1174 . The problem, if I may clumsily try to describe it, was that the following Scala idiom doesn't behave as you might hope when in low-memory situations:

```scala
// ...
  } catch {
    case NonLocalExit => //...
  }
```

In this case, the generated code attempts to allocate and initialize the class `NonLocalExit` (which of course results in a failure and causes a `NoClassDefFoundError`. I fixed the situation by turning `NonLocalExit` into a `class` instead of an `object` and catching based on the runtime type of the exception, which doesn't allocate or initialize anything.
