### ISSUE TITLE
Compiling failed due to wrong class name used in RecentFilesMenu.scala

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#633]
In the declaration of the `RecentFilesMenu` class, wrong class names are used `ModelSavedEvent.Handler` and `BeforeLoadEvent.Handler`. Should be changed to `ModelSavedEventHandler` and `BeforeLoadEventHandler`.

**Comment by frankduncan** [comment]
Considering everything is compiling, I'm going to mark this as closed
