### ISSUE TITLE
Bug or doc bug in `mean` primitive?

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#637]
according to Kory at http://stackoverflow.com/q/24619891/86485:

> I am having an issue with calculating the mean of a list of numbers and strings in netlogo. The user manual states that mean takes the average of a list while ignoring non-numeric values, but it errors out when there is a non-numeric value in my list.

**Comment by mrerrormessage** [comment]
fixed in b6e2c70
