### ISSUE TITLE
`my-links` documentation is wrong

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#639]
The documentation states

> Reports an agentset of all undirected links connected to the caller. 

However, `my-links` reports all links connected to the caller, regardless of directedness. Supposing you have a directed and undirected link breed, behold:

```
observer> crt 4
observer> ask turtle 0 [ create-undirected-link-with turtle 1 ]
observer> ask turtle 0 [ create-directed-link-to turtle 2 ]
observer> ask turtle 0 [ create-directed-link-from turtle 3 ]
observer> ask turtle 0 [ show my-links ]
(turtle 0): (agentset, 3 links)
```

I suppose an obvious question would be: is this even the intended behavior of `my-links`?

**Comment by nicolaspayette** [comment]
Assigning the 5.2.1 milestone on this one: we should at least update the doc to reflect the current behavior of the primitive (doing so wouldn't preclude reassessing this behavior later).
