### ISSUE TITLE
Check the `report` instruction is used only in `to-report` on compile time

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#641]
When your code is compiled, Netlogo checks that all your procedure body is made of commands(rather than reporters), but it doesn't check you don't use `report` in a `to` procedure(opposed to `to-report` procedure). Netlogo detects the problem only at runtime, and would be nice if it would check this on compilation.

**Comment by mrerrormessage** [comment]
This has been implemented in hexy.
