### ISSUE TITLE
Broken on OS X Yosemite?

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/NetLogo#659]
Víctor Cruz writes:

> I can't use net logo with OS X Yosemite
> Pleas, update netlogo to OS X Yosemite

The issue is likely related to [this](http://9to5mac.com/2014/08/04/apple-changing-gatekeeper-app-signing-rules-in-os-x-10-9-5-yosemite-could-break-some-apps/).

**Comment by mrn-aglic** [comment]
has there been any improvement regarding this issue, I want to install NetLogo, but I also want it to run under Java 8... any suggestions?

**Comment by digitaldust** [comment]
I think you can run NetLogo from Terminal, like:

    cd /Applications/NetLogo\ 5.1.0/
    java -jar NetLogo.jar

at this point, it should then use Java 8 (or whatever you have installed from Oracle), right?

**Comment by mrn-aglic** [comment]
Yes, you are right. However, some of the features are not working apparently. For instance, I get an exception when I try to look up something in dictionary. 
However, this is the only thing that I found not working.

**Comment by digitaldust** [comment]
it might depend on what java the table extension expects to find... I don't think you can do anything for that except trying to recompile the table extension...

**Comment by mrn-aglic** [comment]
ok, thanks.

I was just wondering, when can we expect Java 8 to be fully supported? Any idea?

**Comment by SethTisue** [comment]
The `java -jar` method is not fully correct and not all features will work. You need something more like the netlogo.sh script that ships with the Linux version of NetLogo. As a short term measure until we have an app bundle that works with 8, we might consider including an (appropriately tweaked) version of that script in the Mac download.

**Comment by mrn-aglic** [comment]
+1 for the script, that would be great.

**Comment by SethTisue** [comment]
"I get an exception when I try to look up something in dictionary" is now #758
