### ISSUE TITLE
NetLogo/GogoBoard

### ISSUE THREAD

**Issue by zachikibuta** [NetLogo/NetLogo#664]
Hi,

I'm teaching teachers to use Netlogo and robotics. 
I'm trying to connect the gogoboard to netlogo but I'm getting this error when I type gogo:ports into the observer>:

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
 at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1738)
 at java.lang.Runtime.loadLibrary0(Runtime.java:823)
 at java.lang.System.loadLibrary(System.java:1028)
 at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:123)
 at org.nlogo.extensions.gogo.GoGoController.listPorts(GoGoController.java:135)
 at org.nlogo.extensions.gogo.GoGoController.availablePorts(GoGoController.java:123)
 at org.nlogo.extensions.gogo.GoGoExtension$GoGoListPorts.report(GoGoExtension.java:167)
 at org.nlogo.prim._externreport.report(_externreport.java:50)
 at org.nlogo.prim.etc._show.perform(_show.scala:13)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.1.0
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06)
operating system: Windows 8 6.2 (x86 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: bifocalfinalsensor

10:18:15.604 AddJobEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
10:18:15.603 OutputEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
10:18:15.602 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
10:18:15.592 CompileMoreSourceEvent (org.nlogo.app.CommandLine) AWT-EventQueue-0
10:18:15.557 RemoveJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0
10:18:15.557 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
10:18:15.557 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
10:18:15.557 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
10:18:15.557 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
10:18:15.557 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0

_______________________________________

I'm trying to run this code that I wrote 1 year ago and it was working, see link http://www.youtube.com/watch?v=vkpOl6-5XoA

;; instructions: go to the 'Interface' tab, and on the command line at the bottom where it says 'observer>', type in the following:
;; gogo:ports    <-- this should bring up a ports that the gogoboard can connect to, such as "COM4".
;; then write:
;; gogo:open "COM4" (or whatever port was listed earlier)
;; the gogoboard should now be working. To test it, type:
;; gogo:ping
;; and it should return 'true' if it returns 'false' then something went wrong.

extensions [gogo]

breed [squareturtles squareturtle]
breed [sensorturtles sensorturtle]

to setup
  clear-all
  makesquares
  makesensorturtle
  reset-ticks
end

to go
  if gogo:sensor 1 < Sensitivity1  [ask sensorturtle 7 [set ycor -12]]
  if gogo:sensor 2 < Sensitivity2 [ask sensorturtle 7 [set ycor -8]]
  if gogo:sensor 3 < Sensitivity3  [ask sensorturtle 7 [set ycor -4]]
  if gogo:sensor 4 < Sensitivity4  [ask sensorturtle 7 [set ycor 0]]
  if gogo:sensor 5 < Sensitivity5  [ask sensorturtle 7 [set ycor 4]]
  if gogo:sensor 6 < Sensitivity6  [ask sensorturtle 7 [set ycor 8]]
  if gogo:sensor 7 < Sensitivity7  [ask sensorturtle 7 [set ycor 12]]
  tick
end

to drawline
  crt 1 [
    set xcor 0
    set ycor 0
    set heading 90
    set color blue
    pendown
    fd 200
    penup
    die
  ]
end

to makesquares
  create-squareturtles 7 [
    set shape "square"
    set color white
    set size 3
    setxy (100)(-12 + (who * 4))
  ]
end

to makesensorturtle
  create-sensorturtles 1 [
    set shape "circle"
    set color red
    set size 3
    setxy (100) (0)
  ]
end

to-report readsensor [number]
  if (gogoread = true) [report gogo:sensor number]
end

Thanks a lot!

Nancy

**Comment by frankduncan** [comment]
@cbradyatinquire I strongly suspect that this error is related to system setup, but do you know the specifics?  I don't mind closing it if it's just a system configuration problem, but having the solution here will be helpful for people searching for this stack trace on google.

**Comment by cbradyatinquire** [comment]
i have only gotten the rxtx-not-in-path when the usb-serial libraries are wrong in some way (either not there, compiled for the wrong architecture (32 vs 64 bit) etc.  For the last case (32/64) on MAC it may fix the problem to run NetLogo in 32 bit mode.  To do this, open the app "get info" window, and choose to "open in 32-bit mode".  if supported on the mac in question, this will be a checkbox.
