### ISSUE TITLE
`hsb` primitive strangely expects each argument to be between 0 and 255

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#678]
a user reports:

>I’m not sure if this is a bug in the doc, the code, or my understanding.
>according to this web page
>http://rgb.to/color/358/aqua-blue
>the HSB color 193, 70, 53 is equivalent to the RGB color 40, 113, 134
>as i understand it the hsb primitive should convert the former to the latter. But it reports  [46 38 53].

seems wrong to me too. I tried it in NetLogo 4.0, so I bet it's always been broken and nobody ever noticed.

**Comment by frankduncan** [comment]
Do we do the same for approximate-hsb and extract-hsb?

**Comment by qiemem** [comment]
Seems pretty silly not to...

**Comment by frankduncan** [comment]
I mean, creating an old for each one of these as well

**Comment by TheBizzle** [comment]
It seems to me like it would be sensible to create a migration primitive for each primitive that has significantly changed in its behavior.

**Comment by nicolaspayette** [comment]
@frankduncan, maybe I missed it, but it doesn't seem that https://github.com/NetLogo/NetLogo/blob/5.x/docs/dictionary.html has been updated for this. Reopening for now; feel free to close if I'm wrong...

**Comment by frankduncan** [comment]
Ah, good catch!  Fixed in 39eec0b
