### ISSUE TITLE
International windows installation bug

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#680]
We've had two users write to CCL-Bugs about a problem encountered by some users when installing 5.1.0 on international versions of windows. They see install4j start up, and while it is in the process of loading it displays an error "Not Enough Disk Space". Lantern has encountered a similar error [here](https://github.com/getlantern/lantern/issues/1469), and they seem to have fixed it by updating install4j. Our install4j was last updated in February, so simply changing that (if our license allows) may be enough to correct the problem.

**Comment by mrerrormessage** [comment]
For at least one of these users, 5.0.5 installed, but 5.1.0 didn't. I'm unclear why that worked, but it is another bit of data about the problem.

**Comment by SethTisue** [comment]
see https://groups.google.com/d/msg/netlogo-devel/ewnODIf0_BU/RZkkJMe2GzEJ for details, discussion, workarounds

**Comment by mrerrormessage** [comment]
5.3 redoes the Windows installer. Hopefully there are no more issues. If there are, they go under a new ticket.
