### ISSUE TITLE
Add way to dispose of GUIWorkspace

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#684]
Currently, there's no way to cleanly dispose of a `GUIWorkspace`. Other `Workspace`s have a [`dispose()`](https://github.com/NetLogo/NetLogo/blob/59e6bf6965844662db6b8a33faea31290ba87757/src/main/org/nlogo/workspace/AbstractWorkspace.java#L138) method that does it, but `GUIWorkspace` doesn't support it. In addition to calling `super.dispose()` (to close the job thread and extensions), `GUIWorkspace.dispose()` should also

- Kill its [`LifeGuard` thread](https://github.com/NetLogo/NetLogo/blob/59e6bf6965844662db6b8a33faea31290ba87757/src/main/org/nlogo/window/GUIWorkspace.java#L100)
- Stop its [`PeriodicUpdater`](https://github.com/NetLogo/NetLogo/blob/59e6bf6965844662db6b8a33faea31290ba87757/src/main/org/nlogo/window/GUIWorkspace.java#L85)
- Stop its [repaint `Timer`](https://github.com/NetLogo/NetLogo/blob/59e6bf6965844662db6b8a33faea31290ba87757/src/main/org/nlogo/window/GUIWorkspace.java#L98)

There may be other things, but this is what I've managed to discover so far.

**Comment by arthurhjorth** [comment]
@frankduncan & @qiemem was this fixed? Will this not be an issue for LevelSpace in 5.2?

**Comment by qiemem** [comment]
Mostly. There's still lingering issues, but I think that's on the ls end.

**Comment by arthurhjorth** [comment]
OK, just wanted to hear if I should close the issue in the LevelSpace repo. But nevermind. Thanks!
