### ISSUE TITLE
Sliders should not show more precision than increment

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#701]
I was running DaisyWorld and with ramp-up-ramp-down the slider displayed a value of 1.5874999999999877 while the increment was 0.0010. Shouldn't it display a value consistent with the increment -- in this case 1.587?

Alternatively, the properties of a slider should include a precision option.

**Comment by Idloj** [comment]
I guess a precision property would be the right choice, since you can put any value to a slider variable from code regardless of min/increment/max.

**Comment by mrerrormessage** [comment]
It looks like the daisy-world code increments/decrements this in values of `0.005` and `0.0025`, which would lead to values getting out of sync with the increment. @nicolaspayette is in charge of the model's library, I'll let him speak to whether changing the model to keep it consistent with the slider (or changing the slider to keep it consistent with the model) would be worthwhile.

As for the fact that the number ends in `...877`, this is unfortunately a consequence of the limited-precision double representation used in NetLogo. I'm not sure there's a lot that could be done about that without slowing down NetLogo substantially.

**Comment by nicolaspayette** [comment]
All right. I'll see what I can do in the model.

**Comment by nicolaspayette** [comment]
> Shouldn't it display a value consistent with the increment -- in this case 1.587?

I think that the Daisyworld case shows why it shouldn't: it's quite legitimate for a model to set the value of a slider variable to something more precise than the slider's increment.

> Alternatively, the properties of a slider should include a precision option.

That would make sense, but I'm not sure it's necessary:

- If you're setting values through the slider itself, NetLogo already handles precision issues for you.
- If you're setting values though code, you can always add a call to `precision` yourself (like I did in https://github.com/NetLogo/models/commit/0b8e7fd00c7c9f79999d63c74c45243920770a7c).

**Comment by Idloj** [comment]
So this can be closed?

**Comment by nicolaspayette** [comment]
Unless someone has a good argument to make for a precision property in sliders, yes.
