### ISSUE TITLE
.nls improvements catchall bug

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/NetLogo#710]
This ticket refers to multiple different problems that probably ought to be fixed, so it would not be unreasonable to break it up into multiple smaller issues—perhaps one issue for each circle 1-6?

[Here](https://groups.google.com/forum/#!topic/netlogo-devel/AJY9Y3b_-ow), Alan Isaac pointed out a couple of usability problems with NetLogo's support for `.nls` files.  His complaints (and several of mine) can be summarized as follows:
1. The "Includes" dropdown is hidden until an `__includes []` directive (with at least one string inside the list) is entered
2. Even if you have the tab selected for the `.nls` file you wish to save, choosing "Save as" after creating a new `.nls` file will not provide you with the option to save the `.nls` file; "Save as" only ever seems to save the `.nlogo` file
3. Even if you have the tab selected for the `.nls` file you wish to save, choosing "Save" on your fresh, new tab for the `.nls` file forces you to first "Save as" changes to the `.nlogo` file (if you got it from the Models Library)
4. An `.nls` file cannot be saved in NetLogo until something has been entered into the editor
5. Code tabs do not indicate when they have unsaved content
6. Rather than NetLogo being smart when you try to save an `.nls` file without having ".nls" in the path, it instead just complains to you, "You must choose a name ending with: .nls"

I think that the excuse till now has been that the `__includes` stuff is "experimental".  However, I can find references to it dating back to the manual for NetLogo 4.0 (back in the glorious September of 2007).  That's... pretty old.

As far as I'm concerned, the experiment's over—who's still gathering results on this experiment and doing anything with them?—and Alan's report is certainly not the first with significant complaints about the `__includes` support.  I think that it's about time that we either get serious about the functionality or remove it (and I really think that we shouldn't remove it, because I think it solves a serious problem for model authors).  The point is, though, that claiming it to still be experimental does not strike me as reasonable.

Regarding (1), I think the current behavior is pretty bogus.  Alan suggests that `__includes []` (without supplying any file name—real or fake) should show the dropdown.  Personally, I don't see what is really gained by hiding that dropdown at all ever.  It just serves to make things annoying for someone who wants to introduce a first `.nls` file.  It would actually be a very simple fix to [this file](https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/app/IncludesMenu.scala) to remove all of the references to `isEmpty` and make the dropdown always appear.

Regarding (2), surely this can't be the intended behavior....

Regarding (3), this is nothing short of annoying.  "Save" is acting as a "Save all", and we provide no means through which to selectively save an `.nls` file.

Regarding (4), that's phenomenal!  When coupled with (3), it's actually reasonable to think that you're saving the new `.nls` file that you just created, when, in fact, you simply resaved the `.nlogo` file that you had to edit in order to get a chance to open the `.nls` pane.  (I say that it's reasonable to think that because I seriously just did it a few minutes ago when I was tinkering with the functionality.)  It's not even that NetLogo has an opposition to saving an empty `.nls` file, because you can open a new `.nls` pane, type a character, hit backspace, and _then_ save the new file; it's just that you can't save a 100% fresh `.nls` file.

Regarding (5), that's quite user unfriendly.  IntelliJ shows you when a tab contains unsaved changes simply by putting an asterisk at the end of the tab's title.  Even an indication as simple as that is a sufficient fix—just so people know approximately what changed.

Regarding (6), this is kind of baffling.  It knows exactly what the problem is.  Just add the missing extension to the filename!

**Comment by TheBizzle** [comment]
Alan has suggested the following:

> Wouldn't it be trivial to activate the "Includes" button in the presence of `__includes []` instead of requiring `__includes ["arbitrary string"]`?  This change alone would be worth something.

As stated above, I would be in favor of always just showing the menu, but if I'm decided against on this matter, I strongly feel that we should, ***at the very least***, make the change that Alan is suggesting.  The relevant code for that change can be found [here](https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/compiler/StructureParser.scala#L561-L591).

**Comment by frankduncan** [comment]
Changing to 5.x since #717 is targeting just the small issue we want to fix for this release.
