### ISSUE TITLE
Should file save and open dialogs re-use last directory?

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#720]
(On Linux, at least:) **File / Open**, **File / Save** and **File / Save As...** always start from the user's home directory. This is inconvenient when, e.g., successively opening multiple models from a deeply buried folder.

Perhaps we could use the Java preference store (like we did for **Recent Files**) to save the last used directory?

**Comment by frankduncan** [comment]
I can definitely see how this would improve the user experience.
