### ISSUE TITLE
Add `netlogo-web?` primitive

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/NetLogo#721]
It seems likely that there won't be another release of JVM NetLogo before NetLogo Web sees its public release.  Consequently, Uri and I would like to see a `netlogo-web?` primitive introduced in 5.2, so that people can use it in much the same way that the existing `netlogo-applet?` primitive is used.

As for the behavior of this primitive, it is very simple.  As one would expect, `netlogo-web?` always returns `false` in JVM NetLogo.

**Comment by frankduncan** [comment]
Given that language divergence has already started, and that we have tentative plans to change the model file format in netlogo web, would it be better to go the 3d route and differentiate the models at a higher level than runtime?

Foo.nlogoweb or some such?  I'm thinking that in the future of netlogo, the netlogo-web? primitive will become quickly deprecated.  More likely a model will need to go through a conversion process that dumps out a web version.

**Comment by TheBizzle** [comment]
> Given that language divergence has already started

The current language divergence is very minute.  The only things that I'm aware of having changed are that certain age-old corner cases that were kept around for compatibility were not persisted in the latest iteration of the Headless compiler.

> that we have tentative plans to change the model file format in netlogo web

These is something far down the line, and proper authoring for NetLogo Web is, as well.  For the time being, all models are coming from JVM NetLogo.

> would it be better to go the 3d route and differentiate the models at a higher level than runtime? Foo.nlogoweb or some such?

I don't believe so.

> I'm thinking that in the future of netlogo, the netlogo-web? primitive will become quickly deprecated.

I don't see why that would be the case.  JVM NetLogo will live on for years.  It would be very helpful of us to allow modelers to tell which environment their model is running in.

> More likely a model will need to go through a conversion process that dumps out a web version.

Like... a manual one?  That basically runs contrary to the goals of the NetLogo Web project, and we already have models being automatically spit out to run in NetLogo Web.  NetLogo Web might possibly evolve beyond JVM NetLogo at some point, but being able to use JVM NetLogo models in NetLogo Web will invariably remain a requirement of the project.
