### ISSUE TITLE
Makefile and bin/sbt shouldn't hardcode Java path on Linux

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#73]
How about relying on `JAVA_HOME` environment variable instead of hard-coded `/usr/lib/jvm/java-6-sun`?

(reported by Ivan Sopov)

**Comment by Idloj** [comment]
@SethTisue, sbt is upgraded now, any news on this? What's the best solution now?

**Comment by mrerrormessage** [comment]
Closing this since we check a default path, then default to `$JAVA_HOME`.
