### ISSUE TITLE
Problem in AIDS model

### ISSUE THREAD

**Issue by ToonTalk** [NetLogo/NetLogo#730]
The infect command is

to infect  ;; turtle procedure
  if coupled? and infected? and not known?
    [ if random-float 11 > condom-use or
         random-float 11 > ([condom-use] of partner)
        [ if random-float 100 < infection-chance
            [ ask partner [ set infected? true ] ] ] ]
end

those calls should be to random-float 10 not 11. Perhaps the author intended to include 10 as a possible output but then 10.0000001 should have been appropriate. If somehow 11 is really the intent then the info tab should be updated.

Also it is odd that condom-use is a probability that ranges from 0 to 10 instead of being expressed as a percentage like infection-chance.

**Comment by nicolaspayette** [comment]
Thanks for the report, Ken! I've migrated the issue to our model repository: https://github.com/NetLogo/models/issues/18.
