### ISSUE TITLE
On branch 6.x calling to Jump to Definition results in a runtime error

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#742]
The most relevant part of the stack trace(the rest is just key binding, abstaractButton etc.):
java.lang.ClassCastException: org.nlogo.window.EditorColorizer cannot be cast to java.awt.Component
 at org.nlogo.window.Event.findTop(Event.java:235)
 at org.nlogo.window.Event.doRaise(Event.java:171)
 at org.nlogo.window.Event.raise(Event.java:113)
 at org.nlogo.window.EditorColorizer.jumpToDefinition(EditorColorizer.scala:117)
 at org.nlogo.editor.Actions$$anonfun$jumpToDefinitionAction$1.apply(Actions.scala:48)
 at org.nlogo.editor.Actions$$anonfun$jumpToDefinitionAction$1.apply(Actions.scala:48)
 at org.nlogo.editor.Actions$MyTextAction.actionPerformed(Actions.scala:55)

**Comment by SethTisue** [comment]
two ways to fix this: either set the EditorColorizer's Event.LinkParent, or use something else as the event raiser

**Comment by Idloj** [comment]
Didn't quite understand, could you add more details?

**Comment by SethTisue** [comment]
see the "Events" section of https://github.com/NetLogo/NetLogo/wiki/Architecture . the exception happens because the event couldn't be raised because the raiser isn't in the AWT hierarchy, and EventLinkComponent wasn't used to connect it something that is in that hierarchy

**Comment by frankduncan** [comment]
I will fix this next week, but if you want to take a shot at it, you will have to make the jumpToDefinition called by Actions.scala be called something liek "raiseJumpToDefinitionEvent" take in the EditorArea as an argument, using that to raise the event.

And, if you wrote a test of some sort that failed which you then fix, you would be my hero.  I have no idea how to do that.

**Comment by SethTisue** [comment]
curious what the status is on this?

**Comment by SethTisue** [comment]
closing since the 6.x branch is abandoned
