### ISSUE TITLE
Can't build 6.x branch

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#748]
Many "cannot find symbol" errors on using the MouseMode enum. for example:
```
WidgetWrapper.java:360: error: cannot find symbol
[error]   private MouseMode mouseMode = MouseMode.IDLE;
[error]                                          ^
[error]   symbol:   variable IDLE
[error]   location: class MouseMode
```

**Comment by frankduncan** [comment]
Not sure what's going on here, but travis disagrees.  Try running nightly.sh?

https://travis-ci.org/NetLogo/NetLogo/builds/55857504

**Comment by frankduncan** [comment]
Incidentally, for these kinds of build problems, you should jump on gitter!  Probably better than opening bugs.

**Comment by SethTisue** [comment]
there isn't an accessible gitter room for this, is there? and https://github.com/NetLogo/NetLogo/wiki still directs folks to IRC

**Comment by frankduncan** [comment]
Is our gitter not public?

**Comment by SethTisue** [comment]
Bryan has now made a public room at http://gitter.com/NetLogo/NetLogo

**Comment by Idloj** [comment]
So the docs(i.e. wiki and README) should be updated
