### ISSUE TITLE
Make model preview commands accessible from the GUI?

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#760]
It would make model library management easier for us, but could also be useful in other places (e.g., Modeling Commons? Community Models?)

**Comment by nicolaspayette** [comment]
It would also be nice, in the case of custom preview commands, to compile them like we do for the plot/widget code. It's not uncommon to see custom commands that don't work anymore because the model has changed.

**Comment by SethTisue** [comment]
if the custom preview commands aren't being compiled by TestCompileAll, I'd consider that a straight up bug.

**Comment by nicolaspayette** [comment]
They're not. And you're right that they should be. I'll open a separate issue.
