### ISSUE TITLE
TestCompileAll should test compiling custom preview commands

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#762]
(see #760)

**Comment by nicolaspayette** [comment]
I suspect that models with `need-to-manually-make-preview-for-this-model` won't compile. We'll need to handle that somehow, probably by just skipping them.

**Comment by SethTisue** [comment]
there's already two occurrences of `previewCommands.containsSlice("need-to-manually-make-preview-for-this-model")` in the codebase. so elegant.

**Comment by nicolaspayette** [comment]
> there's already two occurrences of `previewCommands.containsSlice("need-to-manually-make-preview-for-this-model")` in the codebase. so elegant.

Still far from ideal, but https://github.com/NetLogo/NetLogo/commit/6f7d6a957ed117e00e3ab4c762b2469e7bbed969 should help a little. :-)

**Comment by nicolaspayette** [comment]
This was resolved by merging  #766.
