### ISSUE TITLE
BehaviorSpace spreadsheet vs. table output: remember user preference?

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#768]
Regardless of the relative merits of each format, we could remember the user's previous selection and propose that by default in the **Run options** dialog. This would alleviate some of the pain for users needing "Table output"; forgetting to check it before starting a long running experiment can be frustrating, to say the least.

**Comment by SethTisue** [comment]
I'm not sure if we ever considered simply making it part of the experiment definition.

**Comment by nicolaspayette** [comment]
> I'm not sure if we ever considered simply making it part of the experiment definition.

@SethTisue, I went ahead with https://github.com/NetLogo/NetLogo/pull/769, as it was a much simpler change, but I referenced your comment in https://github.com/NetLogo/NetLogo/issues/576#issuecomment-97614145 so we don't loose track of that possibility in the future.
