### ISSUE TITLE
is-<breed>?

### ISSUE THREAD

**Issue by arthurhjorth** [NetLogo/NetLogo#770]
Currently we have to do `if [breed] of a-turtle = <breed> [ ... ]`. It would be really nice (and seemingly consistent with the language) to have a `is-<breed>?`

**Comment by mrerrormessage** [comment]
[Like this?](http://ccl.northwestern.edu/netlogo/docs/dictionary.html#is-breed)

**Comment by arthurhjorth** [comment]
Exactly like that! (i was expecting it to be the breed name, but it makes sense since `is-turtle?` is also the singular.
