### ISSUE TITLE
Allow tasks to have named arguments

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#773]
Discussion of this started at #771, but I thought it deserved its own issue.

@frankduncan mentioned that he found the current task definition behavior to be somewhat magical. The main practical benefits I see to allow named arguments are:

1. clarity of code: `?2` gives no indication of what the variable actually is.
2. nesting tasks: currently, because all task variables are named the same, you can't refer to an outer tasks variables from an inner task. For instance, a naive implementation of a simple histogram function would be:

```
n-values 100 [ length filter [ ? = ? ] lst ]
```

Obviously, this doesn't work. The `? = ?` is meant to compare the inner task-argument to the outer task-argument. Furthermore, since reporter-tasks must be single expressions, you can't declare local variables in them and resolve it that way. The only way to do this is create a full-fledged procedure.

---

My opinion: I confess, at first I really disliked NetLogo's task syntax, but I've come to really like it. It's concise (since you can often omit the `task` primitive) and simple. Reason 1 for adding named arguments is almost rendered moot by reason too: there is a fairly strict limit on how complex tasks can be. As for reason 2, although I've been bitten by this many times, the fact that it forces you to break things down into named procedures is probably ultimately better for readability. I would personally prioritize unifying tasks and blocks over this.

Then again, this would be damn useful. Some possible syntaxes:

Arrow notation:
```
foreach xs [ x ] -> [
  ask turtles [ fd x ]
]

n-values 100 [ bucket ] -> [ length filter [ x ] -> [ x = bucket ] ]
```

Lambda:
```
foreach xs lambda [ x ] [
  ask turtles [ fd x ]
]

n-values 100 lambda [ bucket ] [ length filter lambda [ x ] [ x = bucket ] ]
```

Obviously, these don't distinguish between reporter and command tasks, though that's determinable from context.

**Comment by SethTisue** [comment]
see discussion at #351

**Comment by qiemem** [comment]
I was looking for that issue! Thanks!

**Comment by qiemem** [comment]
Here is the cartesian product with all the various syntaxes we've discussed. Currently, this requires two separate procedures:

```
to-report cartesian-produce [ xs ys ]
  report reduce sentence map [ pair-with-all ? ys ] xs
end

to-report pair-with-all [ x ys ]
  report map [ list x ? ] ys
end
```

#### Berkeley syntax:

```
to-report cartesian-product [ xs ys ]
  report reduce sentence map [[x]
    map [[y] list x y ]
  ]
end
```

Note that Berkeley syntax produces some syntactic ambiguities for us. We can't tell if `[[]]` is command task that takes 0 arguments or is a reporter task that returns an empty list.

#### `->`:
```
to-report cartesian-product [ xs ys ]
  report reduce sentence map [x] -> [
    map [y] -> [ list x y ] ys
  ]
end
```

#### Hybrid Berkeley/`->`

```
to-report cartesian-product [ xs ys ]
  report reduce sentence map [[x] ->
    map [[y] -> list x y ] ys
  ]
end
```

This should remove any syntactic ambiguities introduced by either syntaxes.

#### `task-let`:
```
to-report cartesian-product [ xs ys ]
  report reduce sentence map task-let [x] [
    map task-let [y] [ list x y ] ys
  ]
end
```

#### `fun`:
```
to-report cartesian-product [ xs ys ]
  report reduce sentence map fun [x] [
    map fun [y] [ list x y ] ys
  ]
end
```

**Comment by qiemem** [comment]
Here's what the syntax look like for `foreach`. In this case, we have a list of x-coordinates and a list of y-coordinates and we want to create a turtle at all combinations of `x` and `y`:

#### Berkeley

```
foreach xs [[x]
  foreach ys [[y]
    crt 1 [ setxy x y ]
  ]
]
```

#### `->`

```
foreach xs [x] -> [
  foreach ys [y] -> [
    crt 1 [ setxy x y ]
  ]
]
```


#### Hybrid Berkeley/`->`

```
foreach xs [[x] ->
  foreach ys [[y] ->
    crt 1 [ setxy x y ]
  ]
]
```

####  Hybrid Berkeley/`->`, dropped `[]`

```
foreach xs [x ->
  foreach ys [y ->
    crt 1 [ setxy x y ]
  ]
]
```

#### `task-let`:
```
foreach xs task-let [x] [
  foreach ys task-let [y] [
    crt 1 [ setxy x y ]
  ]
]
```

#### `fun`:
```
foreach xs fun [x] [
  foreach ys fun [y] [
    crt 1 [ setxy x y ]
  ]
]
```

**Comment by mrerrormessage** [comment]
A few more examples, taken from the NetLogo dictionary examples:
```NetLogo
;current syntax
(foreach [ 1 2 3 ] [ 4 5 6 ] [ show (word "the sum is: " ?1 + ?2) ])
;current syntax - explicit tasks
(foreach [ 1 2 3 ] [ 4 5 6 ] task [ show (word "the sum is: " ?1 + ?2) ])
;berkley logo syntax
(foreach [ 1 2 3 ] [ 4 5 6 ] [ [x y] show (word "the sum is: " x + y) ])
;"arrow" syntax
(foreach [ 1 2 3 ] [ 4 5 6 ] [ x y ] -> [ show (word "the sum is: " x + y) ])
;modified "arrow" syntax
(foreach [ 1 2 3 ] [ 4 5 6 ] [ x y -> show (word "the sum is: " x + y) ])
; "fun" syntax
(foreach [ 1 2 3 ] [ 4 5 6 ] fun [x y] [ show (word "the sum is: " x + y) ])

; current syntax
filter [first ? != "t"] ["hi" "there" "everyone"]
; current syntax - explicit task
filter task [first ? != "t"] ["hi" "there" "everyone"]
; berkley logo syntax
filter [[s] first s != "t"] ["hi" "there" "everyone"]
;"arrow" syntax
filter [s] -> [first s != "t"] ["hi" "there" "everyone"]
; modified "arrow" syntax
filter [s -> first s != "t"] ["hi" "there" "everyone"]
; "fun" syntax
filter fun [s] [first s != "t"] ["hi" "there" "everyone"]

;current syntax
reduce [fput ?2 ?1] [[] 1 2 3 4 5]
; current syntax - explicit tasks
reduce task [fput ?2 ?1] [[] 1 2 3 4 5]
; berkley logo syntax
reduce [[acc el] fput el acc] [[] 1 2 3 4 5]
; "arrow" syntax
reduce [acc el] -> [fput el acc] [[] 1 2 3 4 5]
; modified "arrow" syntax
reduce [acc el -> fput el acc] [[] 1 2 3 4 5]
; "fun" syntax
reduce fun [acc el] [fput acc el] [[] 1 2 3 4 5]
```

**Comment by qiemem** [comment]
We discussed in the developer meeting today. The top contenders are `[ x y -> x + y ]` and `fun [x y] [ x + y ]`.

Pros of `[ x y -> x + y ]`:

- Matches other languages (Java, Scala, Haskell, Javascript, Coffeescript, ...)
- Groups together the arguments and body into a single unit. The advantage of this is are most obvious with something like `filter [s -> first s != "t"] ["hi" "there" "everyone"]`, where having separate blocks for arguments and body make it difficult to tell at a glance what the argument list is, what the filtering predicate is, and what the list to be filtered is.
- Very concise.

Cons of `[ x y -> x + y ]`:

- Adds a weird symbol to the language. While `->` is arguably meaningful, symbols are in general scary for novices.

Pros of `fun [x y] [ x + y ]`:

- Fits in with the language a little better.
- `fun` (standing for function) more explicitly names what it is.
- Concise, but not quite as much (5 characters instead of 2, not counting spaces).

Cons of `fun [x y] [ x + y ]`:

- Doesn't group together the variables with the body, so that expressions such as the `filter` above are hard to read.
- More awkward with `foreach` in my opinion

**Comment by qiemem** [comment]
One consideration is how these types of tasks would be stored in variables and passed to user-defined tasks. Should the `task` keyword be required? I would definitely say no. I believe the ideal syntax for each would be:

- `let foo [ x y -> x + y ]`
- `let foo fun [x y] [ x + y ]`

**Comment by Idloj** [comment]
What about overloading `task` with 2 arguments: `(task [x y] [x + y])` ?

**Comment by mrerrormessage** [comment]
@Idloj , that's an excellent idea, unfortunately it either leads to a lot of ambiguities or requiring a complete change (including autoconversion) from the existing syntax.

**Comment by mrerrormessage** [comment]
Fixed in hexy with the addition of the `->`-anonymous procedure syntax.

**Comment by Idloj** [comment]
Just a small question (I know it's probably too late anyway), why is the `->` needed? Why can't the anonymous procedure code follow immediately after the closing bracket as it does for real procedures?

**Comment by mrerrormessage** [comment]
@Idloj , this is an important question (even though it is definitely too late to change at the moment).

We considered a number of alternative syntaxes, including "Berkeley syntax", which sounds like what you're describing. While in the normal case, the difference between "Berkeley syntax" and `->` syntax is minimal (`[ [args] code body ]` vs. `[ [args] -> code body ]`), there is a substantial difference in a few cases. Consider the case where you have an anonymous command with an empty body, then it's `[ [args] ]` vs. `[ [args] -> ]`. The arrow shows that you intended an anonymous procedure instead of a literal list (although it would be an ill-formed list, we can provide a meaningful error in this case). Even worse is the case where you have a no-argument reporter procedure which returns a list (`[ [] [] ]` vs `[ [] -> [] ]`). So the decision to add a `->` clarifies the user's intention.

In addition to the above cases, we think `->` communicates what an anonymous procedure does. It takes a list of arguments and transforms it into something else, be that a sequence of actions (for anonymous commands) or a result (for anonymous reporters). We considered a number of alternatives to `->` but found them to either be confusing or clunky.
