### ISSUE TITLE
`other` confuses error messages thrown when `with` is given a non-predicate reporter

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#789]
To reproduce:

```
observer> crt 10
turtles> show other turtles with [ color ]
```

You'll get an error like: `OTHER expected a true/false value from (turtle 0), but got 125 instead.`

The error should be: `WITH expected a true/false value from (turtle 0), but got 125 instead.`

I tested other primitives besides `other` (`any` and `one-of`) and they behaved correctly. My guess is that this has something to do with `other ... with ...` optimizations.

**Comment by SethTisue** [comment]
Your guess sounds correct to me.

**Comment by mrerrormessage** [comment]
Related: @brotatotes is doing some work on unifying the various `with` and `other`-related optimizations into a unified semi-lazy agentset abstraction. This offers an important test case.
