### ISSUE TITLE
Add alignment and snapping lines to the interface tab to allow aligning widgets with each other

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#793]
It's much more convenient if you want to place the widgets nicely.

**Comment by nicolaspayette** [comment]
Agreed. Widget placement in general could be improved. (e.g., https://github.com/NetLogo/NetLogo/pull/774). Contextual menu options like "align with each other" or "distribute evenly" would also be nice.

**Comment by SethTisue** [comment]
OmniGraffle is an example of an application with exemplary support for this.

**Comment by Idloj** [comment]
Netbeans GUI editor too

**Comment by nicolaspayette** [comment]
Also related: #343.

**Comment by SethTisue** [comment]
this is actually just a straight-up duplicate of #343, isn't it?

**Comment by nicolaspayette** [comment]
I thought @Idloj was suggesting what some programs call "alignment guides", which would be a slightly different proposal. Even then, the two issues could be consolidated.

**Comment by Idloj** [comment]
> I thought @Idloj was suggesting what some programs call "alignment guides", which would be a slightly different proposal
That's right
