### ISSUE TITLE
Make the AST available for some refactoring functions

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#794]
Many editing/refactoring will be easier to implement if the tree is available

**Comment by SethTisue** [comment]
the situation w/r/t this is way better in the NetLogo-Headless repo, however, that doesn't help you in any Swing-based context

**Comment by Idloj** [comment]
Why headless? IDEs use the AST to make their refactoring.

**Comment by SethTisue** [comment]
In a perfect world, the situation would be equally good in this repo. In practice, the work to make that happen has not been done. It's not ideal, it's just the way things are currently.

The work that was done in NetLogo-Headless to straighten this out is described at https://github.com/NetLogo/NetLogo/wiki/zOld:-Compiler-Refactoring-Notes. About 1 or 2 person-years of coding effort went into it; backporting that work to JVM NetLogo would be really hard. (The only reason the work got done at all is that NetLogo-Headless is a much smaller and easier repo to do work in.)

**Comment by Idloj** [comment]
You mean that because the GUI stuff use the old compiler, the GUI Netlogo is stuck with the old one?

**Comment by SethTisue** [comment]
Yes

**Comment by Idloj** [comment]
Forever?

**Comment by SethTisue** [comment]
5.x, probably forever. 6.x, I think @frankduncan has contemplated backporting the new compiler too, but the whole future of the 6.x line is currently very uncertain.

**Comment by Idloj** [comment]
Can't the AST be provided somehow just after the frontend phase(looking at https://github.com/NetLogo/NetLogo/wiki/Compiler-architecture)?

**Comment by SethTisue** [comment]
Yes, the resulting data structures are just difficult and unpleasant to manipulate.

For example code that does it anyway, see https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/compiler/AutoConverter2.scala

**Comment by SethTisue** [comment]
My note about 5.x vs headless was just a side note. Just because this stuff is a lot more pleasant in the new compiler doesn't mean it's impossible in the old compiler. It isn't impossible at all.

**Comment by mrerrormessage** [comment]
The stuff from headless has been ported over on the hexy branch. I'm now marking this as "closed".
