### ISSUE TITLE
Zoomed-in font size should not be saved for output widget

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#802]
- Open any model with an output box (e.g. **Profiler Example**, where the output box's font size is 12).
- Zoom in a few times. The font size is increased (e.g., to 20).
- Save the model with no other changes. The increased font size is saved.
- Reset your zoom level to "normal".
- Reload the model you just saved. You get the big font, even if zoom level is normal.

Just zooming in or out should not actually _change_ a model.

**Comment by SethTisue** [comment]
very likely a one-line fix

**Comment by Idloj** [comment]
But all the zooming stuff should be changed.
