### ISSUE TITLE
GoGo extension related error message

### ISSUE THREAD

**Issue by Shelibenmoshe** [NetLogo/NetLogo#804]
i built a model to my gogo board
and when i change something this message appears

NetLogo is unable to supply you with more details about this error. Please report the problem at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the contents of this window into your report. java.lang.InterruptedException: sleep interrupted at java.lang.Thread.sleep(Native Method) at org.nlogo.extensions.gogoserial.controller.SensorReader$class.readSensorHelper(SensorReader.scala:30) at org.nlogo.extensions.gogoserial.controller.SensorReader$class.readSensor(SensorReader.scala:11) at org.nlogo.extensions.gogoserial.controller.Controller.readSensor(Controller.scala:9) at org.nlogo.extensions.gogoserial.prim.Sensor.managedReport(Sensor.scala:11) at org.nlogo.extensions.gogoserial.prim.Sensor.managedReport(Sensor.scala:8) at org.nlogo.extensions.gogoserial.prim.ManagedReporter$$anonfun$report$1.apply(ManagedPrimitive.scala:12) at org.nlogo.extensions.gogoserial.prim.ManagedReporter$$anonfun$report$1.apply(ManagedPrimitive.scala:12) at org.nlogo.extensions.gogoserial.controller.ControllerManager$$anonfun$withController$1.apply(ControllerManager.scala:26) at org.nlogo.extensions.gogoserial.controller.ControllerManager$$anonfun$withController$1.apply(ControllerManager.scala:24) at scala.Option.flatMap(Option.scala:146) at org.nlogo.extensions.gogoserial.controller.ControllerManager.withController(ControllerManager.scala:24) at org.nlogo.extensions.gogoserial.prim.ManagedReporter.report(ManagedPrimitive.scala:11) at org.nlogo.prim._externreport.report(_externreport.java:50) at org.nlogo.prim._asm_proceduremovewithsundown_ifelse_0.perform(:2) at org.nlogo.nvm.Context.stepConcurrent(Context.java:91) at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82) at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143) at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78) at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76) at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76) at scala.util.control.Exception$Catch.apply(Exception.scala:88) at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41) at org.nlogo.job.JobThread.run(JobThread.scala:75) NetLogo 5.2.0 main: org.nlogo.app.AppFrame thread: AWT-EventQueue-0 Java HotSpot(TM) Server VM 1.6.0_45 (Sun Microsystems Inc.; 1.6.0_45-b06) operating system: Windows 7 6.1 (x86 processor) Scala version 2.9.2 JOGL: (3D View not initialized) OpenGL Graphics: (3D View not initialized) model: gogo netlogo_bottel 09:33:57.068 AddChooserConstraintEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0 09:33:57.068 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0 09:33:57.068 AddSliderConstraintEvent (org.nlogo.app.InterfacePanel$2 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0 09:33:57.068 AddBooleanConstraintEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0 09:33:57.068 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0 09:33:57.052 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0 09:33:57.052 AddJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0 09:33:57.052 RemoveJobEvent (org.nlogo.window.MonitorWidget) AWT-EventQueue-0 09:33:57.052 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0 09:33:57.037 CompiledEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0

**Comment by nicolaspayette** [comment]
Thanks for reporting, @Shelibenmoshe! I have migrated the issue to the GoGo-Serial-Extension repository: https://github.com/NetLogo/GoGo-Serial-Extension/issues/1.
