### ISSUE TITLE
All icons on the button widget should be inversed, not darkened

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#808]
Basically, forever icon and agent icon.
I don't see why active forever button is green and not white like the text, because in inactive mode they are the same color.
The agent icons can be hardly seen, and the turtles legs are gone.

**Comment by SethTisue** [comment]
not sure, but my guess is that a PR that simply removed the agent icons altogether might be accepted

**Comment by Idloj** [comment]
Why? What's wrong with them?

**Comment by SethTisue** [comment]
1) the art is poor quality
2) even if (1) were fixed, I doubt it would be obvious to users what the icons even are
3) especially since maybe 1% of NetLogo models have non-observer buttons
4) and anyway the whole feature is pretty much unofficially deprecated at this point and won't be supported in Tortoise

**Comment by Idloj** [comment]
about (2), I think it is obvious because the icon appears as soon as you change the "Agent(s)" field.

**Comment by qiemem** [comment]
I think I disagree, @SethTisue.

2) They indicate "this button does not behave like you expect!"
3) This makes them seem also more important as indicators of non-standard behavior.
4) So let's toss the ability to create them first.

**Comment by SethTisue** [comment]
Your PR may eventually be accepted, but regardless, we don't need individual tickets for minor aesthetic changes like this in the issue database. Having lots of things like this in here just makes it harder to find stuff.
