### ISSUE TITLE
Program crashing when running a library model, OSX

### ISSUE THREAD

**Issue by dportabella** [NetLogo/NetLogo#811]
Netlogo crashes when running a library model, OSX

Files -> Models Library -> Curricular Models -> Urban Suite -> Economic disparity -> Open
click "Go once"
Crashes with:
Division by zero.
error while patch -28 38 running /
  called by procedure PATCH-UTILITY-FOR-POOR
  called by procedure EVALUATE-POOR
  called by procedure LOCATE-POOR
  called by procedure GO
  called by Button 'go-once'

I've tried with other models, and it crashes also.

Netlogo 5.2 (April 3, 2015) for Mac
Mac OSX 10.10.3

**Comment by SethTisue** [comment]
You need to press "setup" first. I've opened a ticket on this general issue here: https://github.com/NetLogo/models/issues/81

**Comment by nicolaspayette** [comment]
Thanks for reporting, @dportabella! The more general issue documented by @SethTisue (NetLogo/models#81) will take a while to address, but I pushed a fix for this particular model in https://github.com/NetLogo/models/commit/2ad916b216f24a358257000ec8d03a21fa00965c.

**Comment by dportabella** [comment]
it works, thanks!
a non-related question, i would like to make a simulation about corruption in developed countries, such as spain. do you have any recommendation about how to begin? how much time do you think that i would need to learn about the software and make such a model?
and where is the best place to ask such questions?

**Comment by nicolaspayette** [comment]
> and where is the best place to ask such questions?

For general, open-ended questions like these, https://groups.yahoo.com/group/netlogo-users/ is the place. Once you're started and have more specific programming questions you can go to https://stackoverflow.com/questions/tagged/netlogo. Plenty of other NetLogo resources (including tutorials) are listed at http://ccl.northwestern.edu/netlogo/resources.shtml.
