### ISSUE TITLE
Open/Save dialog should show only .nlogo files for NetLogo and only .nlogo3d files for NetLogo 3D

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#813]

**Comment by nicolaspayette** [comment]
Agreed. Maybe this could be fixed as part of https://github.com/NetLogo/NetLogo/pull/759. (I think this may be a Linux specific bug as well.)

**Comment by Idloj** [comment]
Why would it be Linux specific, is it coded anywhere?

**Comment by nicolaspayette** [comment]
That's just a hunch. I haven't actually verified. But:
- Linux is the only platform to use `JFileChooser`;
- #720 was Linux specific;
- No one else has reported this before (Mac/Windows versions have a lot more eyeballs on them).

The guilty code is likely in https://github.com/NetLogo/NetLogo/blob/5.x/src/main/org/nlogo/swing/FileDialog.java.

If you're going to go in and change anything, I would suggest doing it from the https://github.com/NetLogo/NetLogo/pull/759/ branch.

**Comment by Idloj** [comment]
The intent to do this is actually in the comment:
>     // Incidentally, I'd like to make NetLogo properly support filename filters too...
    // But I'm guessing this late in the "ready-to-release" cycle, people might not be
    // too pleased with me hacking much and possibly introducing new bugs.  :-)
    //  So I'm just making a change that affects Linux users...
    //  ~Forrest (6/8/2009)

**Comment by mrerrormessage** [comment]
Closed in #953
