### ISSUE TITLE
Add an asterisk in front of the title to indicate if the model was modified since last saved

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#814]

**Comment by nicolaspayette** [comment]
You mean to indicate if the model was modified since last saved? (Don't hesitate to give more details when reporting issues or making suggestions. What's obvious to you may not be to the person reading your report.)

**Comment by Idloj** [comment]
Precisely

**Comment by mrerrormessage** [comment]
Closed in #860, #955 .
