### ISSUE TITLE
Widgets with ellipsis should have a tooltip with their full name

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#817]

**Comment by mrerrormessage** [comment]
It seems like it should be easy to make a very simple PR for this, and it would probably be accepted on the 5.3 branch.

**Comment by Idloj** [comment]
I have a little problem here. The tooltip is just fine... until the button is selected. If it's selected the tooltip doesn't show up.

**Comment by Idloj** [comment]
Should the tooltip for slider show also when you hover the channel/handler or just over the name?

**Comment by Idloj** [comment]
Same question goes for switcher
