### ISSUE TITLE
memory usage is increasing without doing anything

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#819]
I opened Netlogo and did nothing in it.
Then I inspected it with VisualVM and got this:

![snapshot18](https://cloud.githubusercontent.com/assets/8083458/8620464/650c7ec0-2728-11e5-9984-10ba8243b9f9.png)

**Comment by SethTisue** [comment]
what version of NetLogo, what OS, what JVM?

**Comment by SethTisue** [comment]
does the memory usage drop back down after a full GC?

**Comment by Idloj** [comment]
Netlogo 5.2, Ubuntu 15.4, JVM 1.8
It does drop after a GC, and the memory increase is probably a result of the visualvm, but I still think it goes up very fast(you can see, about 20MB in 2 minutes).

I did 2 heap dumps(which I think does a GC before dumping) and both of them show ~7MB. So maybe it's just the visualvm and Netlogo is OK. Don't know.

**Comment by Idloj** [comment]
Looking with top for some time, I don't see increasing, so I think it's just visualvm.

**Comment by SethTisue** [comment]
It might be that we're generating an excessive amount of garbage during idle and something could be done about it... but yeah, maybe not really a problem if it's not causing any trouble.

**Comment by qiemem** [comment]
Increasing heap usage during idle is totally normal for Java programs. Objects are being generated all the time for event listeners, repaints, stream listeners, etc. Remember, every single object in Java is allocated to the heap and the only time those objects are taken off the heap is during a GC. This isn't a problem with NetLogo or VisualVM (it's not a problem at all), it's just the way Java, and pretty much every other garbage collected language work.

For instance, if you take [a swing application that just opens up a window and that's it](https://gist.github.com/qiemem/eb140f0fc8f219fa1a26), you'll still see this:

![image](https://cloud.githubusercontent.com/assets/28215/8638644/276cdf6e-2887-11e5-99c9-e7e8b2bd7af4.png)

The program allocated about 5MB every minute, and this is a program that does nothing! NetLogo is a huge program with many threads constantly listening for mouse events, window events, keyboard events, and so forth, not to mention just normal thread management activity.

As @SethTisue implies, this is only really a problem if the objects are not being cleared after a GC. The other time this can be a problem is if an unnecessarily high number of objects are making it to old gen, causing very frequent full gcs. Full gcs are expensive, so this can cause performance problems.

I recommend checking out the Visual GC plugin for VisualVM. It shows the usage of each part of the heap separately so you can actually watch objects pass from eden to the survivors to old gen. Screenshot for the do-nothing program above:

![image](https://cloud.githubusercontent.com/assets/28215/8638700/19ca354e-2889-11e5-9ac1-550d075bebbd.png)

I can definitely understand your initial concern, however. It can be disconcerting to see happening. But, yeah, totally normal.

**Comment by Idloj** [comment]
I still think it's visualvm/jmx causing the problem beacause it communicates with the jvm. Try your example swing application, and look at its memory with top. I think the memory won't go high that fast or not at all.

**Comment by Idloj** [comment]
But anyway, it maybe good to set the young/old heaps in an appropriate way.

**Comment by qiemem** [comment]
Oh! That reminds me of something I was going to mention. Java programs hang on to the max heap space no matter what the heap usage actually is. By default, Java will never give memory back to the OS once taken. Thus, you won't see this fluctuation in top. The only time you'll see changes in top is when the JVM increase the max heap size, which it will do if it can't free enough space during a gc (up until it hits the `-Xmx` limit). These fluctuations are in the heap usage, not the max heap.

**Comment by SethTisue** [comment]
@qiemem ha, I would not have guessed your empty-window-only app would generate that much garbage.

**Comment by qiemem** [comment]
> I still think it's visualvm/jmx causing the problem beacause it communicates with the jvm.

This is likely influencing things as well. But calling it a "problem" doesn't make sense. Pretty much everything the JVM does generates garbage. That's just how the JVM works.
