### ISSUE TITLE
Export to NetLogo Web

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#820]
Add a way to export a model to NetLogo Web.

Proposals are welcome on how best to accomplish getting the model data currently open in NetLogo into a static page that can compile and interpret it. Some ideas we've discussed (and their drawbacks):
* Putting the model text into the page as a javascript string (kind of hacky)
* Encoding the model into the URI Fragment (potential browser compatibility issues)
* Running a single server somewhere which accepts a post request from NetLogo (operationally intensive)
* Having NetLogo serve the model into the webpage via a lightweight HTTP server ([Rube-Golberg-esque](http://blog.codinghorror.com/content/images/uploads/2005/04/6a0120a85dcdae970b0128776fae11970c-pi.png))
* Having NetLogo drop the file into LocalStorage location (difficult, and probably not cross-browser compatible).

**Comment by qiemem** [comment]
@mrerrormessage and I discussed an alternative to the first suggestion. You can put the model text straight into `<script type="text/nlogo"></script>` tags and just use normal DOM querying to get it out. If `type` is not `application/javascript` or `text/javascript`, the script tags are not interpreted as javascript. Here's an example:

https://jsfiddle.net/xwxyvwyb/

Best of all, you don't have to do any kind of encoding of newlines, strings, or anything, and formatting is preserved. You can just straight up stick the model text in there. I suppose the one forbidden string would be `</script>`.

By the way, this isn't a hack, but an intended use case of the `type` attribute. Here's an example of [embedding C in web pages using a javascript C compiler](https://developer.mozilla.org/en-US/Add-ons/Code_snippets/Rosetta).

**Comment by mrerrormessage** [comment]
Now in 5.2.1
