### ISSUE TITLE
scalajs support

### ISSUE THREAD

**Issue by antonkulaga** [NetLogo/NetLogo#821]
I may make sence to think about making some crossprojects crosscompile to scalajvm/scalajs so it will allow to run some stuff in the browser

**Comment by SethTisue** [comment]
Are you familiar with [NetLogo Web](https://github.com/NetLogo/NetLogo/wiki/NetLogo-Web)? Its engine is written in CoffeeScript, though. When the project started, we evaluated Scala.js but at the time, found it wasn't mature enough. It's possible we would make a different decision if the project were beginning today, but a lot of effort has already gone into the CoffeeScript engine and changing languages now would be difficult and time-consuming.

Note that much of the NetLogo runtime engine for the JVM is actually still written in Java, not Scala, so Scala.js is no help in getting that code running in the browser.

**Comment by antonkulaga** [comment]
@SethTisue Scalajs is already mature now and you can call javascript (or compiled coffeescript) from scalajs, so migration may be more or less smooth.

**Comment by SethTisue** [comment]
Yeah. It's unclear when or if this might ever happen, so I'm just going to close the ticket. If you want to discuss further, please use the netlogo-devel group.

**Comment by mrerrormessage** [comment]
@antonkulaga , thanks for the suggestion! As a developer who has spent time getting our two scalajs projects cross-compiling, I can say that it is *extremely* unlikely to ever happen in this repository for a few reasons:

1. High levels of GUI code, in particular, the swing event dispatch thread is critical to the operation of  code in this project but is entirely unsupported by scala.js
2. A large amount of fairly entrenched java, some of it (like the Mersenne Twister) specialized and optimized in a way that resists conversion to scala. Scala.js code, while not slow, is neither as performant as JVM code nor as performant as hand-tuned javascript, which is a problem for performance sensitive portions of the code, like the engine.
3. A fairly large amount of inertia from extensions which are built in java. These could be converted to scala, but it would take a great deal of time
4. A lot of primitives that deal with the UI and the file system, two places where scala.js pretty much hopelessly lags the JVM

Having said all that, [NetLogo-Headless](https://github.com/NetLogo/NetLogo-Headless) ports over the NetLogo parser and lexer to scala.js, where they're used by the [Tortoise Project](https://github.com/NetLogo/Tortoise) to implement a NetLogo-to-JS compiler. You might have a look, perhaps you can find something of interest in those projects.
