### ISSUE TITLE
The name of the `properties` package is misleading

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#830]
It sounds like general properties of something(maybe Netlogo) or where Netlogo saves things(like `Properties` in `RecentFilesMenu`), but in any way not "Code for editing items in the Interface tab".

**Comment by SethTisue** [comment]
Please don't open issues like this — it isn't constructive.

If you have any questions about what "like this" means, please talk to us on Gitter.

**Comment by Idloj** [comment]
OK, got it
