### ISSUE TITLE
Make auto-formatting more discoverable in the UI

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#831]

**Comment by SethTisue** [comment]
Wouldn't that just be duplicating the functionality that already exists on the Edit menu? I might be misunderstanding.

**Comment by Idloj** [comment]
What functionallity? I'm talking about a button that format your entire code automatically(like in most IDEs)

**Comment by SethTisue** [comment]
Oh, forgetful me, it's not on the Edit menu. But it's hooked up the Tab key. It already does that if you select your code and hit the Tab key.

Maybe it should be made more discoverable in the UI?

**Comment by Idloj** [comment]
agree

**Comment by Idloj** [comment]
I think providing this functionality through the Tab key is not a good choice, better be in something like Ctrl+F or whatever. I didn't see any IDE which does through Tab, and for a very good reason. The Tab is used for indenting. Not to mention the great inconsistency between automatically indentation enabled/disabled.

**Comment by mrerrormessage** [comment]
This can be done with an entry in the edit menu somewhere around comment / uncomment, indent / outdent. We already have a shortcut key for this (tab) and we could add a ctrl-tab mnemonic if that would help make it clearer.

**Comment by Idloj** [comment]
I suggest that if no text is selected it will format the entire code.

**Comment by Idloj** [comment]
Summary of current behavior:

Shift+Tab always shifts the current line (or current lines of selected text) to the left by 2 spaces.
Shift Left/Right in the edit menu always shifts the current line (or current lines of selected text) to the left/right by 1 space.

Tab key behavior:

 | Selected text | No selected text
--- | --- | ---
Auto-indent enabled | Format selected text | Nothing
Auto-indent disabled | Replace selected text by 2 spaces | Adds 2 spaces at cursor position

**Comment by Idloj** [comment]
I think it'll do much good to decide on a consistent behavior for the Tab key, regard less of auto-indentation state, to prevent [mode errors](https://en.wikipedia.org/wiki/Mode_%28computer_interface%29#Mode_errors).
My thought splits between two approaches:
 - Tab will just add 2 spaces at cursor position when no text is selected, while indenting the lines of selected text if there is some.
 - Tab will indent the current lines (or current lines of selected text), which makes Shift Left/Right redundant (or making Tab and Shift+Tab the shortcuts for Shift Left/Right).

I think I'm more inclined to the second option.

Anyway, I think Shift Left/Right should shift by 2, not 1.

**Comment by mrerrormessage** [comment]
Closed with #947 . 

@Idloj , I agree that the behavior of `tab` is strange for experienced programmers, but I don't think it's necessarily strange for programming novices and seasoned NetLogo users. While I think there are alternate ways that we could structure code auto-formatting, I don't see enough benefit over the current approach to justify the time and energy invested in making the change.

Also, have you considered applying to Google Summer of Code if you're eligible? I know you've expressed interest in improving the NetLogo IDE before and one of our project ideas this year is exactly that.

**Comment by Idloj** [comment]
I can't. Am I still permitted to do things that improve the NetLogo IDE, or this will belong to the student who chooses this project?

**Comment by mrerrormessage** [comment]
You can definitely continue to make improvements to the IDE. Summer of Code won't start for another few months. Once it starts we will want to coordinate with you, but until then please feel free to continue hacking on the IDE.

**Comment by Idloj** [comment]
Cool, thanks.
