### ISSUE TITLE
Unable to install properly on Mac OS X 10.10.5 or 10.10.2 Yosemite

### ISSUE THREAD

**Issue by ahurford** [NetLogo/NetLogo#841]
I haven't been able to install Netlogo on either of two of my macs.
1) I installed Netlogo 5.2 and the recommended Java6 program. When I click on Netlogo it just bounces on the dock and nothing opens. Also, I am unable to force quit Netlogo. I'm not sure what operating system this was for.
2) I tried upgrading my operating system to OS X 10.10.5 Yosemite. I reinstalled Java6. The same problem occurred - Netlogo bounces on the dock, then stops, but nothing opens and I can't force quit Netlogo.
3) I tried upgrading to the newest version of Java and the same problem still persists.
4) I installed Netlogo and the recommended Java6 program on my laptop which runs OX 10.10.2 Yosemite. I have the same problem.

Any help would be greatly appreciated!

**Comment by cslaviero** [comment]
Have you tried to open it with with privileges? Run the following commands on Terminal:

sudo su
<type your password>
cd /Applications/<Net Logo version>
java -jar NetLogo.jar

See if this helps. It does not solve completely your problem, but may help in finding what could be happening. I believe that even running it with no privileges will allow you to see any stacktrace which pops from running the .jar file.

**Comment by ahurford** [comment]
Thanks. There was no NetLogo.jar file, I called my computer guy, and the problem was that I took only the NetLogo 5.2.app into the Applications folder and not the entire NetLogo folder generated by the .dmg. It was a simple matter of moving over the entire folder and now everything is fixed. Thanks for your help!

**Comment by SethTisue** [comment]
it would be nice if the app gave a nicer error message in this case. it's been long enough since I looked at how the Mac app packaging works that I'm not sure if doing that would be easy or hard.
