### ISSUE TITLE
incorrect Mac/Java compatibility claim in User Manual

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#843]
docs/requirements.html says "NetLogo should work fine with whatever version of Java you already have on your Mac", but that isn't true. these days people are likeliest to have 8, but we require 6.

reported by a user at http://netlogo-users.18673.x6.nabble.com/NetLogo-and-Java-td5005751.html

**Comment by nicolaspayette** [comment]
Re-targeting for Hexy, which means (as @Idloj pointed out) that the doc will need to be updated with Hexy's new Java requirements.

**Comment by SethTisue** [comment]
I admire, yet hesitate to share, your optimism that there will be no 5.2.2 :-)

**Comment by mrerrormessage** [comment]
The hexy documentation does need updating though. I share Seth's skepticism
that hexy will be the next NetLogo release, which is why it is codenamed as
opposed to having been assigned a version number (like 5.3).

**Comment by nicolaspayette** [comment]
> I admire, yet hesitate to endorse, your optimism that there will be no 5.2.2 :-)

Haha! :-) I must admit I didn't really think about it! If a 5.2.2 was to happen, I suppose a bunch of issues would be retargeted for it anyway (though, for this particular one, it probably should be two different issues...)

**Comment by mrerrormessage** [comment]
This is fixed in 5.3
