### ISSUE TITLE
csv extension crashes reading strings with embedded double quotation marks

### ISSUE THREAD

**Issue by dougedmunds** [NetLogo/NetLogo#845]
csv version included in NetLogo 5.2

Problem: 
If the string being read contains an embedded double quotation ( \" ), csv with crash.
Noted for csv:from-row  and csv:from-string

To duplicate, 
1 ) create a text file with these two lines. Name it testtext.txt
"watching bees" 1.0 0 -1398087 true "" "plot count scouts with [task-string = some-variable]"
"watching bees" 1.0 0 -1398087 true "" "plot count scouts with [task-string = \"watching-dance\"]"

2) Create  NetLogo file with this content.  

globals [myfile mydata mydata-list]
extensions [csv]
to go
  ca
  file-close-all 
  set myfile "testtext.txt"
  file-open myfile
  ;first line does not have \", no problem
  set mydata  file-read-line 
  print mydata
  print is-string? mydata
  set mydata-list  (csv:from-row mydata " ")
  print word "item 3: " item 3 mydata-list
   
  ;second line in file has \" , and will crash below
  set mydata  file-read-line 
  print mydata
  print is-string? mydata
  ;next line will crash
  set mydata-list  (csv:from-row mydata " ")
  print word "item 3: " item 3 mydata-list
end

--------------------------------------------
Error generated:

error (RuntimeException)
 while observer running SET
  called by procedure SETUP
  called by Button 'setup'

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.RuntimeException: java.io.IOException: (line 1) invalid char between encapsulated token and delimiter
 at org.apache.commons.csv.CSVParser$1.getNextRecord(CSVParser.java:398)

**Comment by qiemem** [comment]
Thanks for reporting @dougedmunds! I've moved this bug over to NetLogo/CSV-Extension#8.
