### ISSUE TITLE
Support Markdown comments

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#846]
This will involve adding a new pre-processing step to `org.nlogo.app.InfoFormatter` (and a test to match). Should be fairly quick and simple to strip out single-line comments with a regex. I don't *think* we need multi-line comment support at this point, but if the implementer wanted to add it, it would be very welcome.

For reference, this was discussed initially on https://github.com/NetLogo/Galapagos/issues/311

**Comment by Idloj** [comment]
5.x or hexy?

**Comment by mrerrormessage** [comment]
Yes, that's exactly correct. We want the comments to show in edit mode and only in edit mode.

**Comment by SethTisue** [comment]
is there are more modern Markdown parser we could switch to, or an option we could enable in the existing parser?

**Comment by Idloj** [comment]
The current behavior is exactly what you want

**Comment by mrerrormessage** [comment]
@nicolaspayette , you authored the ticket in Galapagos, did I miss some of what the ticket was requesting? Is this about how we format the markdown when editing, or just when displaying?

**Comment by nicolaspayette** [comment]
Just displaying. The original ticket was only about hiding the "legal snippet" that's wrapped in an HTML comment when showing the Info tab in NetLogoWeb.

But if I'm not mistaken, _this_ ticket about markdown comments, not html comments. See what @TheBizzle was saying on the original ticket: https://github.com/NetLogo/Galapagos/pull/311#issuecomment-131956920

**Comment by Idloj** [comment]
I found the following Markdown comment to work:
`[anything]: # ...`

**Comment by TheBizzle** [comment]
Ah, so this a kind of interesting.  It looks like (in JVM NetLogo)

```
Test
[anything]: # (1998 2001)
[anything]: # (1998 2001)
```

displays

> Test
> [anything]: # (1998 2001)
> [anything]: # (1998 2001)

but

```
Test

[anything]: # (1998 2001)
[anything]: # (1998 2001)
```

displays only

> Test

The newline is apparently important.

**Comment by Idloj** [comment]
It seems that the comment has to be in the start of a paragraph, because it also works right under a heading.

**Comment by Akarshit** [comment]
@mrerrormessage from [here](http://stackoverflow.com/questions/4823468/comments-in-markdown/32190021#32190021) it seems like the parser is beahving as it should.
Is there anything that needs to be done here?

**Comment by mrerrormessage** [comment]
@nicolaspayette , is it acceptable to require a newline before any markdown comments? I'm happy to investigate doing more here, but I would prefer not to change parsers or add extra steps in parsing Markdown if it's easy for you to just add newlines before MD comments. Would you want something in the info tab editor that enforced newlines before MD comments?

**Comment by nicolaspayette** [comment]
> is it acceptable to require a newline before any markdown comments?

As far as I'm concerned, yes.

> Would you want something in the info tab editor that enforced newlines before MD comments?

I don't think that's necessary. Given their inconvenient syntax, I don't expect anyone to use markdown comments directly. HTML comments work fine and I don't see a need for anything else.

**Comment by mrerrormessage** [comment]
OK, so I'm closing this issue then. If info tabs have existing comments which require a newline before them, that is handled in the models library and not in NetLogo.
