### ISSUE TITLE
Javascript-compatible RNG

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#850]
At the moment, the RNG used by NetLogo can't be ported directly to Javascript. It would be a big win to have an RNG that worked in the JVM and which can be precisely reproduced in javascript.

**Comment by mrerrormessage** [comment]
@TheBizzle , did you mention a few devel meetings ago that this was no longer an issue? Do I need to port code over from NetLogo-Headless to make it so?

**Comment by TheBizzle** [comment]
The RNG in NLW is currently 100% compatible with the one in JVM NetLogo.  I would recommend closing this issue as "invalid".

**Comment by mrerrormessage** [comment]
Excellent, thank you!
