### ISSUE TITLE
Upgrade to Java 8, scala 2.11

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#855]

**Comment by SethTisue** [comment]
and re-enable Travis, of course!

**Comment by Idloj** [comment]
Wasn't this upgrade done already?

**Comment by SethTisue** [comment]
the NetLogo-Headless repo has been on Java 8 and Scala 2.11 for some time, but here we're talking about this repo — the full desktop app.

the modelruns/6.x branch has been on Java 7 and Scala 2.10 for some time, but the “Hexy Honeycomb” release is being based off the 5.x branch, not the modelruns branch. it remains unclear whether the modelruns branch will ever result in a release.

**Comment by Idloj** [comment]
But there is the 5.3 branch, which is upgraded

**Comment by SethTisue** [comment]
some of the work is done there, but not all of it.

**Comment by Idloj** [comment]
Shouldn't the work be continued from there instead of basing off 5.x?

**Comment by SethTisue** [comment]
that was certainly the original plan, several years ago. I don't have that much insight into the new situation.

**Comment by mrerrormessage** [comment]
Already done on hexy.
