### ISSUE TITLE
Cannot move agent inspection window back from second screen 

### ISSUE THREAD

**Issue by dougedmunds** [NetLogo/NetLogo#857]
My setup has two screens, set for a continuous display (left and right).  
I can move the primary NetLogo window back and forth between the screens (or halfway between).  All agent inspection windows (i.e., inspect turtle 0) open in the left screen, regardless which screen has the primary NetLogo window in it. 

I can move agent inspection windows to the right screen, but not back again. They stop at the left edge of the second monitor, and will not cross back over to the left screen.

System is Win10x64Pro on ASUS laptop with Samsung monitor as second screen

**Comment by mrerrormessage** [comment]
This looks as though it may be related to #355 (and they should certainly be tested and/or fixed together).
