### ISSUE TITLE
Palette extension link broken at http://ccl.northwestern.edu/netlogo/docs/

### ISSUE THREAD

**Issue by nicolaspayette** [NetLogo/NetLogo#864]
(Reported by Andrew Higginson.)

**Comment by bennlich** [comment]
Dunno if this is related but http://ccl.northwestern.edu/netlogo/docs/ appears to be inaccessible in general.

**Comment by vmiller** [comment]
It looks like quite a lot of links are currently broken on the site, including all of the previous version download links.

**Comment by SethTisue** [comment]
There was a server mishap. Folks at NU are working on it.

**Comment by nicolaspayette** [comment]
This was fixed with the 5.2.1 release.
