### ISSUE TITLE
Bug Hunt Disruptions bug (no pun intended)?

### ISSUE THREAD

**Issue by nholbert** [NetLogo/NetLogo#865]
Setup with default settings, press go.
Now when you press the "L-Infect Bugs" button, you get an error:

DISEASE-MARKERS breed does not own variable CURRENT-AGE
error while disease-marker 977 running CURRENT-AGE
  called by procedure UPDATE-DISEASE
  called by procedure GO
  called by Button 'go/pause'

**Comment by nicolaspayette** [comment]
Thanks for the report, Nathan! I'm closing this issue, but I have opened a new one for it in our **models** repo: https://github.com/NetLogo/models/issues/139.
