### ISSUE TITLE
Behavior Space reports incorrect size of world

### ISSUE THREAD

**Issue by barneyricca** [NetLogo/NetLogo#875]
I'm trying to use Behavior Space to report the color of each turtle in the Segregation model in the Models Library. However, it doesn't report the correct size of the world:

Reporter: [color] of turtles

With NetLogo 5.2 on OS/X (Yosemite):
Example 1: max-pxcor = 10; max-pycor = 10, with origin at (0,0) shows a 21 x 21 grid on the interface. (I counted, just to make certain.) However, it only reports 420 = 20 x 21 colors.

Example 2: max-pxcor = 25; max-pycor = 25, with origin at (0,0) shows a 51 x 51 grid on the interface. (Again, I counted, just to make certain.) However, it only reports 2450 = 49 x 50 colors.

I updated to NetLogo 5.2.1 on OS/X (Yosemite) and got similar incorrect results.

**Comment by SethTisue** [comment]
There isn't a turtle for every patch. The ratio of turtles to patches is controlled by the `density` slider. The default setting is 95, so there should be approximately 95% as many turtles as patches, and that's what your numbers show.

**Comment by barneyricca** [comment]
Ah...thanks (and d'oh!); I was actually wanting the information of all the patches, so I guess I'll get pxcor and pycor too and go from there.

Barney


Bernard Ricca, Ph.D.
Director, Graduate Program in Mathematics, Science and Technology Education
Department of Mathematical and Computing Sciences
St. John Fisher College
3690 East Avenue
Rochester, NY  14618
bricca@sjfc.edu<mailto:bricca@sjfc.edu>
585-899-3866 (Office)
585-899-3872 (Fax)

________________________________
