### ISSUE TITLE
dead gogoboard.org links in user manual

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#877]
Nicolas fixed the same thing already in the models library: https://github.com/NetLogo/models/pull/159

I'd submit a PR for this, but haven't a clue what branch I should submit it to

**Comment by SethTisue** [comment]
Robert says 5.x

**Comment by nicolaspayette** [comment]
Actually, my own changes (and yours) may have been a bit premature: it seems like http://gogoboard.org/ is back online... (the new URLs even redirect to it). Should we reverse that last commit?
