### ISSUE TITLE
nobody, no-turtles ask and agentset construction incompatability

### ISSUE THREAD

**Issue by BruceEdmonds** [NetLogo/NetLogo#880]
When one constructs an agentset, e.g. using n-of where there is a possibility of it being empty, the net-logo commands return nobody instead of no-turtles.

This is a pain since such results are often immediately used in ask commands, and nobody gives an error instead of doing no asking. This results in messy code where one has to check for nobody before doing each ask.

Please either:
1. Change agentset construction primitives so they return no-turtles when empty instead of nobody
OR
2. Change ask so it accepts nobody as an argument but then does nothing (no asking) as with no-turtles.

Thanks.

**Comment by SethTisue** [comment]
Can you give an example?

**Comment by BruceEdmonds** [comment]
ask turtles with [profit < 0] [die]

in the case where there are no turtles with profit less than 0 this gives
an error, instead of simply not asking turtles to die

so one has to do something like:

let ts turtles with [profit < 0]
if ts != nobody [
  ask ts [die]
]

Which is unnecessarily messy.


Regards.

---------------------------------------------------
Bruce Edmonds
Centre for Policy Modelling
Manchester Metropolitan University Business School,
All Saints Campus, Oxford Road, Manchester M15 6BH, UK.
Tel. +161 247 6479  Fax. +161 247 6802
http://bruce.edmonds.name

**Comment by SethTisue** [comment]
You are mistaken. Your example works fine. `with` already returns an empty agentset, not nobody.

(As for asking nobody, that's https://github.com/NetLogo/NetLogo/issues/528.)

**Comment by SethTisue** [comment]
Perhaps you are thinking of `one-of`. You can't just write `ask one-of turtles with [profit < 0] [ die ]` unless you know at least one such turtle exists. See #528 for discussion.
