### ISSUE TITLE
Missing pictures

### ISSUE THREAD

**Issue by Idloj** [NetLogo/NetLogo#883]
[Here](http://ccl.northwestern.edu/netlogo/docs/interface.html#interface), in "Chart: Interface Toolbar", some widgets are missing the picture and have text instead.

(I couldn't submit a PR for this, because I don't have a Mac so the font(size and/or shape, I don't know) is different.)

**Comment by SethTisue** [comment]
looks fine to me: <img width="172" alt="screen shot 2015-11-20 at 9 08 53 am" src="https://cloud.githubusercontent.com/assets/161079/11301589/5ca6b20e-8f66-11e5-968a-5e8f2c58547e.png">

are you seeing something different?

**Comment by Idloj** [comment]
Sorry, a glitch in the browser didn't load some images (fixed after reload).
