### ISSUE TITLE
primitive to test whether tick counter has started?

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#885]
this is a bit of a hole in the language — unless you use `carefully`, there is no other way I can see to test whether the tick counter has been reset. this occasionally makes it difficult to write code that you want to work both during setup and later.

see http://stackoverflow.com/questions/33859331/how-to-make-turtles-die-after-a-certain-tick-preferential-attachment-model/33860893?noredirect=1#comment55519697_33860893 for a sample use case

perhaps `ticks-started?` or `ticking?`

**Comment by mrerrormessage** [comment]
What's the reason that you aren't allowed to call `ticks` before `clear-all` has been called? It seems to me like the most obvious solution would just be to have `ticks` return 0 before initialization, like global variables do. I assume there are reasons this hasn't been done, but given that we're considering breaking backwards compatibility of some things in hexy, is it worth considering whether we could have `ticks` return 0 before initialization?

**Comment by SethTisue** [comment]
it used to, actually. but we changed it for 5.0, as part of the changes associated with putting plot code inside plots.

there is an element of social engineering here. we wanted people to use the new plotting style, which depends on `reset-ticks` being called, because otherwise NetLogo has no idea when the model is finished setting up, which means we don't know when to plot. we have other reasons for wanting to know when the model is done setting up: so we can update the view at the right time, and so we can record a frame in a model run (model runs were a feature we already looking forward at, even then). 

and that's just actual features — you can also imagine lots of other features in this space, like automatically recording a movie of a model, that we can't do unless we know whether the model has been set up.

if the tick counter were already 0 without `reset-ticks` being called, in practice practically nobody would call `reset-ticks`.

there is an aspect of social engineering here — I believe the current behavior steers people in the right direction, towards giving their model code the correct structure.

**Comment by SethTisue** [comment]
P.S. use cases like the SO question are actually quite rare. I don't recall it coming up even as often as once a year — almost certainly less. so (I believe) we aren't cramping users' style with this, to any significant extent.

**Comment by SethTisue** [comment]
This still comes up only rarely afaik, and I still don't think it merits an additional primitive.
