### ISSUE TITLE
Add Link to StackOverflow Q & A to "Help" menu

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#887]
* Menu entry for NetLogo Q & A on stackOverflow

**Comment by Idloj** [comment]
Isn't applet support dropped on hexy?

**Comment by Idloj** [comment]
5.x or hexy?

**Comment by mrerrormessage** [comment]
It's in the Hexy milestone, so hexy is what is planned. I would accept a PR for this on 5.x though, as it's small and unobtrusive.
