### ISSUE TITLE
bug: `runresult` does not check agent type

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#888]
this should be an error, not return an instance of `org.nlogo.agent.Observer`:

```
observer> show runresult task [self]
observer: observer
```

note that NetLogo Web gives a different, also incorrect result:

```
observer> show runresult task [self]
observer: 0
```

back in JVM NetLogo, it's easy to use this technique to make the engine actually blow up, for example:

```
observer> ask one-of patches [ show runresult task [patch-ahead 1]]
```

gives

```
java.lang.ClassCastException: org.nlogo.agent.Patch cannot be cast to org.nlogo.agent.Turtle
  at org.nlogo.prim.etc._patchahead.report(_patchahead.java:23)
  at org.nlogo.nvm.ReporterTask.report(Task.scala:53)
  at org.nlogo.prim.etc._runresult.report(_runresult.scala:52)
  ...
```

I would suggest leaving this alone in the 5.2.x series just in case someone was (intentionally or accidentally) relying on it, but fixing in Hexy

**Comment by mrerrormessage** [comment]
I assume the error here should be "This code can't be run by an observer, only a link, turtle, or patch"
