### ISSUE TITLE
`color` accepts NaN as an RGB component

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#893]
Normally, set `color` to an RGB list checks to make sure each component is between 0 and 255. However, it doesn't appear to check to make sure that they aren't NaN:

```
observer> show item 0 [ color ] of robot 43
observer: NaN
```

Unfortunately, reproducing this is going to be hard. I came across it while working with genetic programming and [the program responsible](https://gist.github.com/qiemem/18880223536e3a392f3a) is pretty hard to wrap your head around.

Anyway, NaN is not between 0 and 255 as, well, its not a number. So `color`, `pcolor`, and the rest should probably block it.

**Comment by SethTisue** [comment]
note that normally in NetLogo NaN is supposed to be caught at point of generation, not point of consumption

**Comment by qiemem** [comment]
Ah, good point. I suppose the real bug here is that it was produced at all.
