### ISSUE TITLE
NaN considered a number

### ISSUE THREAD

**Issue by qiemem** [NetLogo/NetLogo#894]
Noticed this when I encountered #893:

```
observer> show is-number? item 0 [ color ] of robot 43
observer: true
observer> show item 0 [ color ] of robot 43
observer: NaN
```

Obviously, `is-number?` is exactly what NaN isn't... so this should probably return false. Then again, NetLogo isn't exactly alone in this behavior:

```
> typeof(NaN)
"number"
```

**Comment by SethTisue** [comment]
it's arguable, but I think this is actually not a bug. `NaN` is not a legal NetLogo value in the first place, so all bets are off.

anyway NaN may be "not a number", but it isn't anything else either — it is numeric. `NaN` is a terrible naming choice that we're stuck with, but I don't think the name should drive our semantics.
