### ISSUE TITLE
Behaviorspace output slow csv save

### ISSUE THREAD

**Issue by cogijl** [NetLogo/NetLogo#897]
I've recently started using NetLogo on a new computer running Windows Server 2012 r2 (4 processors, 1TB memory). The models are running well but for some reason the output of behaviorspace experiments are exporting slowly. That is to say, the model will run for an hour or so, and will then take 8 hours to save a csv file that is about 8.5 Mb. This seems far too slow; I've run the same experiment on other computers, and although the models run slower, the file saves at a normal pace.

Has anyone else encountered this problem or have any idea what I may have done to slow this down on my end?

**Comment by SethTisue** [comment]
that seems bizarre. I don't recall us ever receiving a similar report.

is the problem limited to spreadsheet format results, or limited to table format results? if you're using spreadsheet, I would expect switching to table would help.

does increasing NetLogo's heap size ceiling help? see http://ccl.northwestern.edu/netlogo/docs/faq.html#howbig

**Comment by SethTisue** [comment]
closing for lack of information. can be reopened if we get more
