### ISSUE TITLE
Request: a primitive to return the name of the current running procedure

### ISSUE THREAD

**Issue by BruceEdmonds** [NetLogo/NetLogo#916]
I add in a variety of debugging primitives into my code, to help type-check, step and debug (written in NetLogo of course).  A primitive that returns the name of the current procedure would help (and maybe another to give the name of the procedure that called it) :-)

Thanks

**Comment by mrerrormessage** [comment]
This is possible to do through extension primitives. I've opened a PR on the [NetLogo Reflection Extension](https://github.com/NetLogo/Reflection-Extension/pull/1) which adds these features to that extension.

**Comment by mrerrormessage** [comment]
The PR I opened has been merged in. The extension is available for download [here](https://github.com/NetLogo/Reflection-Extension/releases/tag/v0.1) and the documentation is listed [in that project's README](https://github.com/NetLogo/Reflection-Extension). Thanks for the suggestion!
