### ISSUE TITLE
ArrayIndexOutOfBoundsException in time extension

### ISSUE THREAD

**Issue by kgtroitzsch** [NetLogo/NetLogo#923]
Sometimes, but not always, I observe this ArrayIndexOutOfBoundsException when I use the time extension of NetLogo. At the moment when this one occurred, the schedule has about 85 entries, see
[show-schedule.txt](https://github.com/NetLogo/NetLogo/files/110754/show-schedule.txt)

The error message produced by NetLogo follows.

error (ArrayIndexOutOfBoundsException)
 while observer running TIME:GO-UNTIL
  called by procedure GO-EVENTWISE
  called by Button 'go-eventwise'

NetLogo is unable to supply you with more details about this error.  Please report the problem
at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the
contents of this window into your report.

java.lang.ArrayIndexOutOfBoundsException
 at java.lang.System.arraycopy(Native Method)
 at TimeExtension$LogoSchedule.performScheduledTasks(TimeExtension.java:630)
 at TimeExtension$LogoSchedule.performScheduledTasks(TimeExtension.java:599)
 at TimeExtension$GoUntil.perform(TimeExtension.java:1704)
 at org.nlogo.prim._extern.perform(_extern.java:54)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:91)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.java:82)
 at org.nlogo.job.JobThread.org$nlogo$job$JobThread$$runPrimaryJobs(JobThread.scala:143)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply$mcV$sp(JobThread.scala:78)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at org.nlogo.job.JobThread$$anonfun$run$1.apply(JobThread.scala:76)
 at scala.util.control.Exception$Catch.apply(Exception.scala:88)
 at org.nlogo.util.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:75)

NetLogo 5.3
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_65 (Oracle Corporation; 1.8.0_65-b17)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.9.2
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: EONOERS 2016-01-30 10-13

11:59:05.962 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
11:59:05.946 RuntimeErrorEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:59:05.920 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:59:05.919 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:59:05.918 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:59:05.917 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:59:05.916 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:59:05.914 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:59:05.913 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
11:59:05.912 OutputEvent (org.nlogo.app.App$$anon$1 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0

**Comment by kgtroitzsch** [comment]
After had a look at the java code I suspect that this error occurs only when time:schedule-event is used with an agentset, as it does not occur when `time:schedule-event <agentset> task ...` is replaced with
`foreach sort-on [ who ] <agentset> [ time:schedule-event ? task ... ]`
But sometimes it also works with agentsets :smile:

**Comment by SethTisue** [comment]
please report this at https://github.com/colinsheppard/time/issues . (sorry, I know the error dialog sent you to this URL; that problem is https://github.com/NetLogo/NetLogo/issues/157)
