### ISSUE TITLE
Java 8, scala 2.9.3 incompatible for scala extension compilation

### ISSUE THREAD

**Issue by reyman** [NetLogo/NetLogo#932]
Hi,
As you say in extension documentation 

> If you are using Scala, you'll need to make sure you are using Scala 2.9. (2.9.1, 2.9.2, and 2.9.3 are all acceptable.) Other versions such as 2.10 or 2.11 will not work.

I'm worried that compiling extension with Scala 2.9.3 and Java 8 seems not possible, there is some  [incompatibilities](http://stackoverflow.com/questions/24517761/scala-repl-throws-error) : 

```
[ERROR] error: error while loading CharSequence, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
[INFO] (bad constant pool tag 18 at byte 10)
[ERROR] error: error while loading AnnotatedElement, class file '/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
[INFO] (bad constant pool tag 18 at byte 76)
```

Any change for an upgrade of Scala version for extension Api in the future ?

**Comment by mrerrormessage** [comment]
I can confirm that it isn't possible to compile against scala 2.9.2 with Java 8. We run against Java 8 in NetLogo 5.3, but only after we've compiled the NetLogo jar with java 6. We're currently working on the next major revision of NetLogo (you will see this referenced as "hexy" and "hexy honeycomb" here on Github, as we don't assign version numbers until release) which will build and run against java 8 and scala 2.11. We don't have a target date for this release yet, but you're welcome to use the work in progress on the `hexy` branch.

**Comment by mrerrormessage** [comment]
Now that NetLogo 6 is out, this should be resolved. Compilation for 5.3.1 extensions should continue to target Scala 2.9.3, Java 8.
