### ISSUE TITLE
Update NetLogo documentation for OS version compatibility

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#938]
The NetLogo compatibility documentation doesn't accurately reflect [Oracle's java 8 compatibility](http://java.com/en/download/help/sysreq.xml). This was a result of `javapackager` not constraining OS versions on Windows or Mac correctly. I am in the process of filing bugs with Oracle about how they need to correctly constrain the version types by default on the installers generated by `javapackager`. In the meantime, we should update our documentation (and perhaps our installer generators) to reflect that NetLogo supports:

* Windows Vista and newer
* Mac OS X 10.8.3 and newer

**Comment by SethTisue** [comment]
I've taken the liberty of assigning the 5.3.1 milestone; this seems pretty important.

**Comment by mrerrormessage** [comment]
Yep. I already have it in 5.x, so it will go in 5.3.1.

We could prevent Windows XP users from installing it at all, but we would then make it more difficult for them to run it using a batch script. I _could_ write a batch script for Windows XP users, but I'm not sure at this point whether the number of users we have justifies the effort that would be involved in creating, documenting, and maintaining such a creation. From the analytics data in NetLogo Web, it would appear that only about 2% of our users are running Windows XP, but I would think the number would be higher, maybe around 5%? We have only had one user raise the issue so far, so I'm unsure how widespread the problem is.

**Comment by mrerrormessage** [comment]
This is done on the 5.x branch.
