### ISSUE TITLE
Replace-And-Find deletes any text selected when opened

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#940]
Steps to reproduce:
- Select text in the code tab
- Open find/replace with ctrl/cmd-f
- enter anything in find
- click find & replace
- will delete all text selected

To fix we just need to deselect any text initially selected when the user opens the find/replace tool

**Comment by Idloj** [comment]
It will also be nice to use the selected text as the initial value for "Find". (This is actually pretty standard in Find/Replace)

**Comment by mrerrormessage** [comment]
Terrific idea! Let's do that.

**Comment by mrerrormessage** [comment]
Closed with #946 .
