### ISSUE TITLE
An URL for Netlogo 5.3.0 resolving using SBT ?

### ISSUE THREAD

**Issue by reyman** [NetLogo/NetLogo#944]
Hi,

Because most issues seems referenced here, i crosspost an issue about netlogo 5.3 link i opened in Sample-Scala-Extension : https://github.com/NetLogo/Sample-Scala-Extension/issues/4

Thanks,
SR.

**Comment by mrerrormessage** [comment]
A URL you can use for the time being is `https://s3.amazonaws.com/ccl-artifacts/NetLogo-5.3.0.jar`, but please expect that link to break at some point in the near-ish future when we have a proper maven setup for NetLogo jars.

**Comment by reyman** [comment]
@mrerrormessage Ok, thanks. 

I suppose we probably store a version of this Netlogo 5.3 jar on our side,  because we write a book for Netlogo 5.3 for the end of the year, and if the link is broken this can be problematic for readers.

Do you have any information i can give in advance to the readers in the book about the future url of Sbt/Maven setup ?

**Comment by mrerrormessage** [comment]
I can't give any information at this time, but I'm hoping to get the maven setup working very soon (ideally within the next week, certainly within the next month). It will almost certainly be hosted on bintray, but that's really as much information as I can give at the moment. Given that this repository may not include jars in the 5.3 series (and older), it would be nice to have a URL for downloading them. I'll attach jars to the 5.3/5.3.1 GitHub "Releases" in the next few days, which will give them a permanent home. I'll comment here with the appropriate links when that's done.

**Comment by reyman** [comment]
Yeah, great news for bintray :) 

I'm also interested by the maven link when it's done, is suppose the good issue to see any news on this is here : https://github.com/NetLogo/NetLogo/issues/256

Thanks also for the link of 5.3 / 5.3.1 :)

**Comment by mrerrormessage** [comment]
Hey, the 5.3 jars are linked to [from this page](https://github.com/NetLogo/NetLogo/releases/tag/5.3.0) and the 5.3.1 jars are linked to [from this page](https://github.com/NetLogo/NetLogo/releases/tag/5.3.1).

I'm going to close this issue for now, news on Maven will be reported on #256.

**Comment by reyman** [comment]
:+1: thx

**Comment by mrerrormessage** [comment]
@reyman , just wanted to let you know that I just put out a new version of the [NetLogo Extension Plugin](https://github.com/NetLogo/NetLogo-Extension-Plugin). The plugin itself is available from bintray, and when you give a `netLogoVersion` value in your `build.sbt` of `"5.3.1"` or `"6.0-M1"` it will require the appropriate jars from the NetLogo bintray repository for you. I think it represents a big step forward in NetLogo extension development and would appreciate any feedback you have to offer on it.

**Comment by reyman** [comment]
Great news @mrerrormessage !! Is there already an example of this new way to define build.sbt in some extension code ?
