### ISSUE TITLE
"cancel" from alert dialog when include file has changes doesn't cancel

### ISSUE THREAD

**Issue by SethTisue** [NetLogo/NetLogo#97]
the bug exists in both 4.1.3 and 5.0

reported by Ken Kahn

**Comment by mrerrormessage** [comment]
Due to changes in file load/save, this should be re-tested in 6.x.

**Comment by mrerrormessage** [comment]
This is still a bug. Just to clarify the bug can be reproduced as follows:

* Open a file with one or more `__includes`
* Edit any one of the `__includes`
* Open a new model
* Choose cancel at the "would you like to save" dialog
* The new model loads, but the include file is left open.

**Comment by Idloj** [comment]
The "offer save" functionality with external files is different now, so there is no bug with canceling. However, when opening a new model, the temporary code tabs still remain open. I have opened a PR to fix that.

**Comment by mrerrormessage** [comment]
closed in #1410
