### ISSUE TITLE
mean give overflow even for elements within range

### ISSUE THREAD

**Issue by Akarshit** [NetLogo/NetLogo#971]
like for `show mean list (2 ^ 1023) (2 ^ 1023)` the output should be 2 ^ 1023 but instead an error comes that calculated number is too large.
The problem here is with the algo. used in mean which sums all the elements of the list(cause of overflow) and then divides it by the size of list.

**Comment by mrerrormessage** [comment]
I'm closing this as you have a proposed fix in #972. In the future, if you have a bug with code to fix it, just open a PR and we'll discuss and tag appropriately on the PR. That keeps the discussion in fewer places. Issues should be opened for the following cases (and preferably only the following cases): 
1. See an issue that you would like to fix, but can't or won't right now. For example, if someone is working on a NetLogo model and discovers a bug in NetLogo, they might open an issue and come back to it when they finish working on their model.
2. Are proposing a change that requires substantial discussion before fixing. For example, if someone was to change the entire layout of NetLogo, or the model file format, or even do something like reorganizing the menu structure, I would prefer an issue first to discuss and work through the idea with the whole team before work was started and/or a PR submitted.
