### ISSUE TITLE
Add Preferences Dialog

### ISSUE THREAD

**Issue by mrerrormessage** [NetLogo/NetLogo#999]
Add a dialog where users can setup their preferences. At the moment, language is the most important. Ideally this could completely replace the `__change-language` primitive. Other settings might also be useful to include as a preference but should be considered carefully.

This enhancement should be targeted for the hexy or later - not on 5.x.

**Comment by SethTisue** [comment]
> Other settings might also be useful to include as a preference but should be considered carefully

indeed, there is a real danger of the answer to every design question becoming "add a preference". I hope this temptation can be resisted

**Comment by Idloj** [comment]
Yes, although IMO preferences can be done quite well if two things are bared in mind: a) provide good defaults, b) don't always show the full set options, have a "More" or "Advanced" button

**Comment by Idloj** [comment]
I think I'll go ahead and do this. I just want to be sure I got things right, there are going to be 3 PRs taking place in order to add a preferences dialog with a language preference and a default model preference, right? Preferences dialog, "User Interface Language" option, "Default model" option.

**Comment by Idloj** [comment]
How to deal with the different locations to put the menu-item in different OSs? (Tools > Options in Windows, Edit > Preferences in Gnome, Application menu > Preferences in Mac OS X)

**Comment by mrerrormessage** [comment]
It would be OK to put this into two PRs. The first could introduce the Preferences Dialog as well as "User Interface Language" option, the second could add "Default Model" option.

Regarding the menu location, let's put it as the top element in the "Tools" menu for now (with a divider between the new element and "Halt").  Our documentation at the moment assumes that menus are the same across platforms and I don't see a compelling reason to change that at the moment.

**Comment by Idloj** [comment]
> Our documentation at the moment assumes that menus are the same across platforms and I don't see a compelling reason to change that at the moment.

...except for the "Quit", from the Interface Guide:

> (On a Mac, this item is on the NetLogo menu instead.)

So the questions is: should I handle the Mac case (differently from Windows&Linux) using `Application menu > Preferences`. If so, How do I do it (is it with the `mac-app` project?) ?

Also, should it be `Tools > Preferences` or `Tools > Options` ?

**Comment by mrerrormessage** [comment]
I think `Tools` > `Preferences` makes the most sense. I'm OK with putting it in the same location on the Mac, but if you would prefer to put it in the Mac-native location, you can do that by adding a [`com.apple.eawt.PreferencesHandler`](http://www.coderanch.com/how-to/javadoc/appledoc/api/com/apple/eawt/PreferencesHandler.html) similar to how [`MacHandler.MyAboutHandler'](https://github.com/NetLogo/NetLogo/blob/hexy/mac-app/src/main/java/org/nlogo/app/MacHandler.java#L67-L79) is done right now. Note that all calls between the application and `mac-app` should be reflective to avoid circular dependencies and *all* references to `com.apple.eawt.*` must live in the mac-app module to make sure all critical code builds on any platform.

**Comment by Idloj** [comment]
This can be closed, can't it?
